== Chapter I.

[.chapter-synopsis]
* Birth and Parentage
* Early Religious Impressions
* Attends a Meeting of Friends for the First Time in His Fifteenth Year: Observations Thereon
* Successfully Opposes the Doctrine of Predestination
* Called Upon to Adopt the Plain Language and Plain Dress
* Received Into Membership with Friends

Having for some time believed it required to leave behind me a relation of the
dealings and tender mercies of the Lord my God with me from my young years,
for the encouragement of the sons and daughters of men who may set their faces Zionward;
and also to bear my testimony,
that the Lord will bless and favor all those who are obedient unto Him,
with the reward of peace which this world cannot give nor take away,
I commence this account.

I was born, according to records obtained, on the eighth day of the Tenth Month,
one thousand seven hundred and seventy-three, at East Greenwich,
in the State of Rhode Island.
My parents were Joseph and Rachel Healy, who were accounted honest people; and who,
when I was about a year old,
removed to the State of Connecticut into a town since called Montville;
where we lived about fourteen years.
Before I was eleven years of age, I often felt, when alone,
the judgment of the Lord upon me for my disobedience--the secret stirrings
of the grace and truth of the Lord Jesus manifested in my heart.
Which light did teach me what I should do, and what I should leave undone;
and when this judgment of God in my heart for sin and disobedience was felt,
I promised amendment of life.

My parents not yet being so much concerned for our spiritual welfare as they ought,
gave us too much liberty; so that I, with some of my older brothers,
went at times to places of diversion,
where were music and dancing.--Oh! the mournful case of
those that spend their precious time in this way.
I have since believed there is no amusement more
destructive to the precious seed sown in the heart,
than this kind of diversion.
Dear youth, remember these words.
Oh, you parents, guard your tender offspring.
Watch over their inclinations.
Much may you do towards bringing them into an early acquaintance with God,
by carefully watching the tender impressions on their minds,
and faithfully discharging your duty,
by instilling therein the great first principles of religion;
and that there is a God before whom all must give an account at the close of life.
How many children there are whose minds call for good instruction;
such as may be compared to bread to their state;
if parents are careful to give in the Lord`'s fear,
when openings may be made on their susceptible hearts,
they will not be charged with giving them a stone; but will be clear of their blood.
I have mourned for the dear children, since I have come to riper years,
in consideration of the neglect of parents and masters in not making the
training of their children in the law of the Lord their constant care;
and have remembered the inspired language, "`Hear, O Israel:
the Lord our God is one Lord: and thou shalt love the Lord with all thine heart,
and with all thy soul, and with all thy might.
And these words which I command thee this day shall be in thy heart:
and thou shalt teach them diligently unto thy children,
and shalt talk of them when thou sittest in thine house,
and when thou walkest by the way, and when thou liest down,
and when thou risest up.`"--Oh! dear parents,
leave not your tender offspring exposed to the dangers that are in the world,
lest you be cruel as the ostrich in the wilderness,
that leaves her young exposed to the foot of every passer by.

After I was twelve years old my father hired me out to work at farming by the month;
and being often alone and having many serious thoughts upon another world,
I was well convinced that, if I died in sin, I could not be happy.
And I well remember in a severe tempest accompanied with thunder and lightning,
in the night season, when I was alone in bed,
I had to examine into my state and situation by the light which did clearly shine,
to show me how the case stood between me and my God.
And finding myself not fit to leave the world, oh! how faithfully did I promise,
if the Lord would be pleased to spare me to see the light of another day,
that I would follow Him with all my heart.
Sometimes these good resolutions lasted many days;
though at other times when the morning came,
and things looked pleasant as to the outward,
I too often forgot my solemn promise made to my God.
Dear youth, be careful to keep to your covenants made at such seasons;
for the Lord is well pleased with an early sacrifice that is without reserve.

When I was between thirteen and fourteen years of age,
my parents first made profession of religion;
my father being convinced of the principles of truth--the
light of Christ shining in the heart of man--as held to,
and maintained by the people called Quakers: which people,
till then I had never remembered to have heard of But my
mother inclined towards those called the New-light Baptists;
and was zealous that way.
This last named people were numerous where we then lived;
but there were none of the Society of Friends in that part of the country.
And I, with the rest of my father`'s children, who were all older than myself,
except two brothers, very often attended the Baptist meeting.
Our father seldom went to these meetings; but I well remember many times in evenings,
after reading the Holy Scriptures and other good books, he imparted much good counsel,
which has been remembered since to my benefit.
I also recollect a valuable book which my father borrowed and brought home,
called Sewel`'s History of Friends, which he set me to reading in.
This book gave an account of Friends`' sufferings in early times,
and how patiently they gave up their lives for Christ Jesus`' sake,
their ever living Redeemer.
These affecting circumstances which I read,
made great impression on my mind in those days;
for I was convinced it was the power of God that
upheld and supported these early Friends;
and I desired to be like unto them.
And oh! that we who profess to be led by the
same holy principle of divine light and life,
may be faithful and obedient thereunto.

I very well remember, though I was then quite a child,
the day my father brought Sewel`'s History home with him.
if I was but a little fellow, yet I was quite a good reader,
and my father set me to read the book to him, whilst he sat upon his bench making shoes;
for he was by trade a shoemaker.
I recollect distinctly, as though it was but yesterday,
how much I was affected in reading some parts of that book;
especially where it told of the constancy which so many of those poor people,
both young and old, showed under suffering and cruel persecution.
I often had to stop reading, for I could not go on for weeping; and my sister Hannah,
who was older than I,
would take the book and read till I was composed enough to go on again.
My childish sympathies were indeed very much stirred up on account of these poor,
innocent sufferers of whom we read;
and I thought that if there ever were any really good people in the world,
these surely were some of them.
And I said in my heart, if the Lord should ever make me a Quaker,
like he did the people of whom we read,
and give me his testimonies to bear for the Truth,
that I also would be willing to suffer for His sake;
and that I would rather lay down my life, and die for him,
than draw back and give up my religion because of persecution.
And I now gratefully remember that the Lord did, in his own appointed time,
visit my soul; and reveal his dear Son in me; and as I was made willing to bear his yoke,
and become obedient to the word of Life, that He gave me from season to season,
as I was able to bear them, one after another of his precious doctrines to believe,
and more and more of his noble testimonies to uphold and declare before the people,
for his great name`'s sake.

And now I feel bound in gratitude to say,
that He has graciously enabled me to continue faithful to him, my good Lord and Master,
for nearly sixty years.
It will be sixty years this coming summer since I first attended a Friends`' meeting.
My brother John and I thought we would like to go to a Quaker meeting,
and as the nearest one to us we heard was at Hopkinton, Rhode Island,
we concluded one First-day morning that we would go to it.
I was not then quite fifteen years old.
So after our very long walk we went into the meeting;
and when I saw Friends sitting around me in solemn silence, I was much struck with it,
and with the very great difference there was between what I now saw,
and all that I had ever before seen in religious meetings.
In every meeting that I previously had been at, there had been no silence,
no waiting on the Lord,
and no preparation for the solemn duty of worshipping Almighty God;
but they went right away to singing, or praying, or preaching; and when they were done,
they hurried off without ceremony, and without taking any time for solemn reflection,
that they might profit by what they had heard.
But here all was changed.

When I looked over the meeting, and saw many people sitting quietly around me,
I asked myself this question:
What are these people doing? for they have not yet heard preaching,
or any good advice for them to be thinking about.
And I said,
can this be worship? are these people really worshipping their Heavenly
Father? I looked very attentively at the Friends in the gallery;
and when I saw the solid gravity with which they sat,
and especially after I had observed that tears were trickling down some of their cheeks,
although there had not been a word spoken, I said in my heart,
surely these people have something in them which I know nothing about.
And I felt an earnest desire in my heart, to know what that something was;
and where they got it from; and how it was to be obtained;
that if it were possible I might get some too, and come to know what it was,
that made the tears run down their faces,
without any of the common means having been employed to produce such
effects.--Thus the Lord began to open my spiritual eyes,
by first kindling holy desires in my heart to
know and understand the mysteries of godliness;
and blessed be his holy name, He not only raised these desires in my heart,
but by the in-shining of his Holy Spirit,
He gave me an understanding of one mystery after another, as I was able to receive it,
until I was brought,
through Divine Grace and by the revelation of his light and love and power in my soul,
to set my seal to all the doctrines and testimonies which He raised up
Friends in the beginning to uphold before the nations of the earth.
No doubt the reading of Sewel`'s History and other now forgotten incidents, prepared,
in a measure, my heart for the reception of their truth;
but on this day I was first made sensible of a true convincement;
and saw the dawn of the true gospel day arise in my soul;
and thus those principles and doctrines of life
and salvation began to be recognized by me;
and blessed be my Stay and Holy Helper who has preserved me from departing from them,
from that day to the present time.

After meeting.
Friends showed great kindness to us poor lads, and we had many invitations to dinner.
We went home with one, which would not take us out of our way,
and this Friend was indeed truly kind to us.
He told us that he would be glad to see us at
meeting when we should feel inclined to come,
and pressed us to make his house our home when we did come.
His truly friendly conduct to us made a deep and lasting impression on my mind.
This man was doctor Thomas Wilbur, the father of my dear friend John Wilbur.

The following anecdote, though not in the memoranda,
is deemed sufficiently interesting to insert here:

[quote]
____
When Christopher Healy was between thirteen and fourteen years of age,
he attended a school in New England, taught by a Presbyterian master,
who heard them ever)`' Seventh-day morning say their catechism.
This had for some time been very irksome to the lad,
the secret witness testifying against it.
In looking at the answer that fell to his lot in the lesson one day,
he found that to the question, '`What are the decrees of God?`' he must reply,
'`That God`'s decrees are the wise, free and holy acts of the counsel of his will,
whereby from all eternity, he hath, for his own glory,
unchangeably foreordained whatsoever comes to pass in time,`' etc.
This doctrine of predestination, in subversion of man`'s free agency,
was what his Bible had not taught him; and he found that he must decline these lessons;
but how to break his determination to the master was the question; yet,
as his peace consisted in it, he made the request.
In surprise,
the teacher desired to know why he wished to be excused from saying his catechism,
which he looked upon as next to the Bible, if not equally sacred.
The straitened boy could only reply, that he did not feel easy to learn it.
But,`' said the master,
'`I cannot excuse you unless you give me a reason.`' At length
Christopher had fairly to tell him he could not learn his catechism
because it was not true.--'`Not true!`' said the astonished master,
who, although he set great store by the lad,
seemed almost horror-struck at his declaration.
However, finding him firm,
he told him that if he would make his word good by proving the catechism to be false,
he would excuse him hereafter from these lessons; and a time was appointed for the proof.

A time of deep trial the little fellow had till the hour came,
to which nearly all his school-fellows staid.
But Christopher, though so young, had read his Bible with care,
and had a retentive memory;
and the good Remembrancer brought to his recollection
this passage of the prophet Jeremiah,
where, speaking in the name of the Most High,
it is said '`They have built the high places of Tophet,
which is in the valley of the son of Hinnom,
to burn their sons and their daughters in the fire, which I commanded them not,
neither came it into my heart`' Showing that these things were not preordained of God,
but were of man`'s own wickedness.
The astonished schoolmaster could only say,
he '`did not think there had been anything like it in the Bible.`' However,
he released the lad from saying his catechism any more.

Twenty-five years afterwards,
when Christopher had been recommended as a minister of
the Society of Friends about seven months,
a concern came upon his mind to visit the scenes of his childhood;
and having procured the requisite credentials from his Monthly Meeting,
he came to this very spot, and appointed a meeting, to which his old schoolmaster,
and former schoolfellows were invited and came.
In this meeting he was led to relate this anecdote, saying,
'`and ye are my witnesses,`' as he appealed to them,
and detailed some of the dealings of the Lord with him in drawing him towards Friends,
and opening one by one their testimonies to his understanding.
His old master seemed rejoiced to see him, and clung to him with affection;
and his schoolfellows received him with open arms.
____

Though but about sixteen years of age, he saw plainly the danger of living an easy,
unconcerned life in conformity with the fashions and customs of the world,
and that the surrender of the will unto Him who endured the cross,
despising the shame for us,
was called for in respect to the use of the plain language and garb.
That ancient precept seemed to be revived in his experience.
"`Put away the strange gods that are among you, and be clean, and change your garments.`"
This he was strengthened, not without trials to his incipient faith, to yield to;
and soon found a path widely different from that of the world,
and the only right one for him to walk in.
But the Lord, who had called for the sacrifice sustained therein,
and in His own good time changed the wilderness
of trial and conflict into a fruitful field;
and he was enabled to realize with the eye of faith,
that the Christian`'s home and treasure are elsewhere than here;
and in consideration thereof he faithfully practised that denial of self,
and the maintenance of the daily cross, which the Truth ever leads into,
and by which alone the peace of mind he so greatly coveted, could be secured.

His Journal continued:

But to proceed with my own experience, I had many solitary walks by night and by day,
wherein I saw my situation,
and was clearly convinced by that Divine Light within my heart,
a portion of which is given to all to profit with, that I was a daily transgressor;
and that if I continued therein,
my portion would be with the miserable at the close of life,
which I was well assured also I had no lease for.
Being earnestly concerned for my salvation,
I renewed my former promises of amendment of life; but not being deep enough,
and not having come to the true watch-tower,
I was easily led astray by the enemy of my soul,
who indeed is as a roaring lion seeking whom he may devour.
But I could not give up to live an unconcerned life;
and after renewing my covenant with my merciful Lord, I had, during these seasons,
great peace of mind.

When I had entered the sixteenth year of my age,
my father having become a member of the Society of the people called Quakers,
and my mother withdrawing from the Baptist meeting,
we removed within the compass of South Kingston Monthly Meeting of Friends,
in the State of Rhode Island.
After our removal my father hired me out to work by the month;
where I had an opportunity of going to Friends`' meetings,
which were many times held in silence.
About the end of this summer, I was very much awakened:
being sensible that I was living too much at ease,
and seeing many who I thought were running in the broad way that leads to destruction,
and fearing my part would be with them,
I again besought the Lord to look down upon me and help me;
and in this distress of mind I promised to obey him in whatsoever he required of me,
however in the cross to mine own will;
and I soon saw it was my duty to use the plain language,
and also to have my clothes made plain, and one day having been at work alone,
and coming to the house where I then resided,
and feeling it laid upon me to begin to use this new language,
and expecting to be derided on that account, it greatly humbled me.
But He who had made me sensible of my duty, strengthened me to perform the same,
blessed be His holy name forever.
And, as I expected, so it proved, for the young man who lived at the same house,
on hearing the alteration in my speech,
derided me in such a manner as to make it very trying.
But when I came to be alone,
I found great inward peace for thus giving up to use the plain Scripture language.

Moreover, having worn my hair long, as was then the fashion,
I also found it my duty to cut it off.
The next First-day morning, feeling my mind drawn towards Friends, and to their meeting,
I went home to my father`'s house, in order to attend it.
My father and mother were glad to see me with the change in my appearance.
But my sisters, who were older than myself,
said they were sorry I had spoiled my head of hair.
But they knew not the peace I felt for so doing.
I went to Friends`' meeting this day,
and found it my duty likewise to go to meetings in the middle of the week,
as well as on First-days.
I have since mourned to see such a neglect in the attendance of religious meetings,
which plainly shows that they who do so, are not enough concerned for their salvation.
Having now conformed in respect to having my clothes made plain,
and being diligent to attend meetings,
I believed it required of me to request to be taken
under Friends`' care as a member of their Society;
and they took an opportunity with me on the occasion,
and encouraged me to persevere in well doing; but waited, as I suppose,
to see what proof I made of an orderly life and conversation.
By not keeping on my guard, the enemy of my soul got some advantage over me;
but not so as to hinder me from going to meeting: nevertheless,
the sweet precious life which I before experienced, I felt greatly to decrease.
Oh! how needful it is to keep on the watchtower, the only place to grow in grace,
and to bear fruit that will be acceptable to the great Husbandman.

I continued in this situation about three years,
without much growth in religious experience.
Yet I believe the Lord had me in his remembrance, and knowing my intentions were good,
preserved me from gross evils, and mostly from running into hurtful company.
During these three years I had considerable acquaintance amongst Friends,
and being somewhat sensible of the high and holy profession
they made--that of obedience to the light of Christ within man,
God`'s gift for their salvation--and seeing many of them, as I was sensible,
take but little heed thereunto,
it was a great stumbling-block to me in such a weak state as I was in,
and sometimes almost discouraged me.
Oh that we that make so high a profession, may not offend the little ones,
or the pure principle in others;
to whom we should be as a city set on a hill that cannot be hid; that they,
beholding our good works, and strict obedience to the light of Christ,
may glorify our Father who is in heaven.
I likewise saw many worthy Friends whose good example was as lights to me;
and some whose doctrines were very precious and edifying to my mind;
which opened my eyes to see I must not feed on the failings of others,
but rather that a sense of their misconduct
should be a warning for me to be more faithful.
And I discovered that the Lord was with this people, favoring them that were obedient,
and cautioning and reproving them that were unfaithful.
Oh! may these lukewarm ones be awakened to a
sense of their situation before it be too late.

When I was about nineteen years of age,
I was again visited with the Day-spring from on high,
wherein my love to my God and my friends was renewed;
and I saw clearly it was my duty to offer myself to the care of Friends again,
acquainting my father therewith.
Friends appointed a committee to visit me on my request; and,
after the regular proceedings in such cases, I was received a member.

The death of my dear mother about this time was a great trial to me.
It occurred on the 12th day of the Eighth Month, 1792.
I was present when she departed this life;
she having been a weakly and afflicted woman more than twenty years.
