== Chapter II.

[.chapter-synopsis]
* Marriage with Alice Sheffield, and Humble Setting Out in Life
* Belief that He Would Be Called to the Ministry, and Exercises Preparatory Thereto
* Removal to the Neighborhood of Rensselaerville, N. Y.
* Removal to Middleburg, N. Y.
* Observations on His Employment as a Teacher
* Death of His Father
* Appears in the Ministry
* Remarks on the Comfort Experienced in the Attendance of Meetings for Worship

Being now received into the Society, I attended meetings diligently;
and found it my duty to observe the good order thereof,
and to take the good counsel and advice of Friends, which I prized as a great blessing;
and felt myself favored that my lot was cast among a people
whom the Lord had raised up to show forth his praise.
And I am confirmed in the belief, that if they continue to make the Lord their refuge,
no weapon formed against them shall ever prosper,
and the tongue that rises against them in judgment shall be put to silence:
for the Lord will arise for the help of his people, and his enemies shall be scattered.

When I had entered the twenty-first year of my age, I was married to Alice Sheffield,
daughter of Samuel and Elizabeth Sheffield--a
member of our Monthly Meeting of South Kingston;
it being on the 12th day of Twelfth Month, 1793.

+++[+++These dear young Friends, in their early housekeeping,
began in a very circumscribed manner.
A Friend who visited them, thus described their home: "`It consisted of but one room,
without any closet and a few shelves in one corner to hold dishes, etc.
Very few of our Friends have known the poverty that he knew; and very few,
even among the stronger-minded ones, attained to what he did, not as respects preaching,
but in the interest in his conversation and his ready answer to all that presumed
to call in question any of our fundamental doctrines and testimonies.`"]

Feeling myself more confirmed in the faith of the Society,
I believed it was my place to attend Quarterly and Yearly Meetings;
which were seasons of good instruction to me.
I often sought the Lord when alone for His counsel,
and he was graciously pleased to manifest His will to me,
which made me willing to part with all,
yes--to sell the glories of the world to purchase the
field wherein the pearl of great price lay.
And many times when alone,
I did believe if I was faithful to Divine manifestations in my own mind,
that I should be called to declare to others what the Lord had done for me.

Much of my outward employment from the time of my being married was teaching school:
and having many children.
Friends and others, placed under my care,
I found it always best to ask counsel of Him who is the great Lord and Law-giver,
that I might know how to instruct these dear children thus committed to my care,
not only in the instruction necessary to fit them for business in this life,
but also to train them in the fear of God, and in His nurture and admonition.
And when I was careful and waited on the Lord for direction,
I had great comfort in conducting my school.

When I had entered the 28th year of my age, my dear father was removed by death.
And for the loss of him my heart truly mourned;
remembering his godly concern in the latter part of his
days to instruct us in the way we should go.
Oh! that children would hearken to the good counsel given them by truly concerned parents.
I have often felt everything alive within me moved, by seeing inconsiderate,
disobedient children slight and disregard their parents`' good advice,
whose hearts have been filled with anxious care,
and no doubt many times they have strewn their tears in
consequence of their children`'s disobedience;
it may be after they have gotten out of their power to restrain them.
May these things be treasured up in the hearts of children;
and may they remember the great and ancient command, "`Honor thy father and thy mother,
that thy days may be long in the land which the Lord thy God giveth thee.`"
And also to remember, that to slight and disobey parents, is a sin of no small magnitude;
and that those who do so,
are making a bed of sorrow to lay their head upon one day or another.--But, dear youth,
the desire of my heart is, that you may shun this source of sorrow,
by obeying your parents in the Lord; so shall you be as a staff to their age,
and as balm to their declining nature.

Soon after my father`'s decease, which was on the 2nd day of Second Month, 1801,
I saw clearly that if I was faithful, I would soon be called to the work of the ministry.
And on the twenty-second of the same month, upon a First-day of the week,
at our meeting at the lower meeting-house in South Kingston,
I uttered a few words in the dread and fear of Him, the great Shepherd of Israel,
who had thus made known to me my duty at that time;
and I felt great peace as a reward for obedience.
This strengthened me;
and I was thereby encouraged to draw near oftener than
the morning to wait upon the God of my salvation,
who alone had become my guard and guide.
Thus I endeavored to be faithful and obedient,
and found that language to be verified which was spoken from the Lord by Samuel to Saul,
the first anointed king over Israel: "`To obey is better than sacrifice,
and to hearken than the fat of rams.`"
But O that none may presume to speak in the name of the Lord, without His holy influence,
and the word of command laid upon them!
Then only will such experience the answer of peace in their own bosom.
On the contrary, if they offer an offering of their own preparing,
they may expect to receive this language:
"`who hath required this at your hand to tread my courts?`"

I many times had to go down as into Jordan,
yea to the very bottom thereof Oh! none can know
the tribulated path the Christian has to tread,
but those that walk therein.
But it is the highway to holiness; the very way the blessed Savior trod;
and all His followers must become acquainted with it.
For it is through many tribulations that any one enters the kingdom.
I well remember one day being deeply tried, as to an hair`'s breadth,
so that I was just ready to conclude I was forsaken, when I put up my cries to the Lord,
and appealed to Him who knew the sincerity of my heart, for help and strength.
Upon which the language of David was presented to my mind: "`Why art thou cast down,
O my soul? and why art thou disquieted within me? Hope thou in God;
for I shall yet praise him for the help of his countenance.
O my God, my soul is cast down within me:
therefore will I remember thee from the land of Jordan.
Deep calleth unto deep at the noise of thy water-spouts;
all thy waves and thy billows are gone over me.
Yet the Lord will command his loving kindness in the day time,
and in the night his song shall be with me, and my prayer unto the God of my life.`"
And this encouragement was given me from the Fountain of all good, as I believe;
and so I felt the seas to be stilled, and the raging, foaming waves to cease;
blessed be his holy name forever.
I did not for several years find it my duty very often
to appear in public testimony in our meeting,
but often felt it my place to wait upon the Lord out of meeting, as well as in meetings;
and found as David said, that "`He inclined unto me,
and heard my cry:`" and graciously appeared for my comfort and consolation,
yea with the healing balm of life under his wings.

When I was about thirty-two years of age,
I believed it best for me to remove with my family into New York State,
within the compass of Coeyman`'s Monthly Meeting.
But I had many serious considerations about this removal,
it being a matter of great importance to me; and in the Ninth Month, 1805,
I went into that country in company with my brother-in-law Joseph Collins, to see it;
which visit was satisfactory; and in about five weeks after my return,
I removed with my family, having the unity of my friends herein.
Being favored with a prosperous journey, we got well here,
and I was truly thankful to my great Lord and Master;
and finding many sympathizing friends, I was comforted in their company.
Although I had many times to descend into Jordan, even to the depths thereof,
yet these truly baptizing seasons were times of my
greatest improvement and growth in the best things.
For the law is a light, the commandment a lamp,
and the reproofs of instruction the way of life.
And it is in the valley of humiliation that the Lord doth instruct his people.

I endeavored to abide in this Jordan spiritually with patience,
and to endure various dippings therein, until He was pleased,
by the lifting up of his holy countenance, to bring me out of these trials,
and to enable me to bring up stones of memorial to the honor of His name.
And as David praised God for his mercy, so doth my soul praise him, saying,
"`Bless the Lord, O my soul, and all that is within me bless his holy name.
Bless the Lord, O my soul, and forget not all his benefits:
who redeemeth thy life from destruction;
who crowneth thee with loving kindness and tender mercies.`"
"`Oh Lord my God, thou art very great; thou art clothed with honor and majesty:
who coverest thyself with light as with a garment;
who stretchest out the heavens like a curtain;
who layeth the beams of his chambers in the waters; who maketh the clouds his chariot;
who walketh upon the wings of the wind; who maketh his angels spirits;
his ministers a flaming fire.`"

As I was concerned to perform my duty in whatever the Lord required of me,
I found it right to visit some neighboring meetings
within the compass of our own Monthly Meeting.
Wherein, notwithstanding I had many favored seasons,
yet He who knew what was best for me,
led me again and again into the valley and shadow of death.
Oh! this is the cup our Savior spoke of, and this is Christ`'s baptism,
which all his true disciples must partake of.
Oh, dear brother and sister, whoever you are, do not think to reign with Christ in glory,
unless you are willing to partake of His bitter cups, death and sufferings.
And in order to bear these trials, so as not to forsake your dear Lord and Master,
you must pray for patience to endure the turning of His holy hand upon you.
And may you remember for your encouragement, that if you keep the word of his patience,
He will keep you in the hour of temptation.
Oh give not out, my dear exercised brother or sister, but hold on thy way.
Help is laid on One that is mighty;
and He is willing to save all those who forsake all to follow Him;
and when the time of refreshing shall come from the presence of the Lord,
all those that have patiently endured their trials, shall witness the winter to be past,
the rain to be over and gone, the flowers to appear on the earth,
the time of the singing of birds to be come,
and the voice of the turtle to be heard in their land.

When I had lived about two years within the
compass of Rensselaerville Particular Meeting,
where I first removed when I came from the State of Rhode Island,
I believed it right again to remove to a little meeting at Middleburg,
about ten miles distant, it being held under the care of the Monthly Meeting,
and but two meetings a month.
I had a desire to attend all our religious meetings,
and not knowing there would be a meeting established there,
it caused me to examine the ground of my removal.
But making them a visit, and attending one of their meetings, they felt very near to me,
and I was favored in this meeting, in a good degree, with the Heavenly Father`'s love,
and my mouth was opened in testimony to His blessed truth: and having to believe,
if the few Friends of the place remained steadfast in the Truth,
there would be a meeting established there,
after weighing the matter in a serious manner,
and advising with some of my friends of Rensselaerville,
I thought it would be safe for me to remove thither;
though I was loath to part with friends of that meeting,
as many of them expressed they were with me.
And some of their spirits I had felt very nearly united to mine in the heavenly journey.
May the Lord preserve them in His holy fear.

+++[+++Christopher Healy often experienced a being introduced again
and again into the furnace of humiliation and trial,
that so not only the dross and the tin, but the reprobate silver might be consumed,
whereby a vessel meet for the inscription of
"`Holiness unto the Lord`" should be wrought.
He was often brought into a state of mourning and lamentation.
But could as oft acknowledge with the Psalmist: "`Thou hast put off my sackcloth,
and girded me with gladness.`"
The following from his memoranda, clearly prove this:]

In the latter part of 1807 I removed to Middleburg, and when there was no meeting there,
I found it my duty to go to Rensselaerville Meeting of Friends,
they still feeling very near to me;
and I was often favored with the Lord`'s holy
presence in them to my satisfaction and comfort.
But our meeting was soon allowed, that is once a week,
which I believe was in a good degree overshadowed by the wing of Ancient goodness,
who is the life and support of all our religious meetings;
and who is the bread that cometh down from heaven.
Oh then, saith my soul, may we be concerned oftener than the morning light,
to wait upon Him, and pray for our daily bread; and He, who is rich in mercy,
will not fail to hear our prayers, and to fill our souls, in His own time,
with the soul-sustaining bread of heavenly life,
and cause us to draw water out of the well of salvation.
Then shall we experience the mountain of the Lord`'s
house to be established in the top of the mountains;
and have the pleasant prospect of all nations flowing unto it.
And feelingly can my mind unite with the Psalmist who said, "`Great is the Lord,
and greatly to be praised in the city of our God, in the mountain of his holiness.
Beautiful for situation, the joy of the whole earth, is Mount Zion,
on the sides of the north, the city of the great King.
God is known in her palaces for a refuge.
For lo, the kings were assembled, they passed by together.
They saw it, and so they marvelled; they were troubled, and hasted away.
Fear took hold upon them there, and pain.
Thou breakest the ships of Tarshish with an east wind.
As we have heard, so have we seen in the city of the Lord of hosts,
in the city of our God; God will establish it forever.
We have thought of thy loving kindness, O God, in the midst of thy temple.
According to thy name, God, so is thy praise unto the ends of the earth:
thy right hand is full of righteousness.
Let Mount Zion rejoice, let the daughters of Judah be glad, because of thy judgments.
Walk about Zion, and go round about her; tell the towers thereof.
Mark ye well her bulwarks, consider her palaces;
that ye may tell it to the generation following.
For this God is our God for ever and ever; he will be our guide even unto death.`"

On the fourth day of Second Month, 1808,
I attended our own meeting in the middle of the week,
and soon after I sat down in the meeting, I felt the Heavenly Father`'s love to spread,
and it was as a shower of celestial rain, which refreshed many of our minds;
and though our number was small, I did believe that ancient promise was verified,
that where two or three are gathered together in Christ`'s name,
there mil He be in the midst of them.

The next First-day following, at the same place, the Lord`'s mighty power was present,
and did enable me to open Truth`'s doctrine to my own comfort,
and to the encouragement of the sincere hearted,
and to the strength of the feeble-minded.
Blessed be the name of the Lord who is our strength,
and without whose presence all are poor.
O may my soul be truly humbled before the Lord, that I may learn contentment,
and also to suffer hunger, as my God sees meet.
For blessed are they that experience a true hunger and
thirst after the heavenly bread and water of life,
for they shall be filled in the Lord`'s own time.

At our next Monthly Meeting we were allowed a meeting as before hinted, twice a week;
which was an encouragement to our little number;
and we esteemed it a favor from the Good Hand,
who cares for those that cast their care on Him.
And feeling my heart to abound with thankfulness,
under a sense of the powerful word of life,
my soul was poured out in gratitude and praise to the great Author of all our blessings.

25th of Fifth Month, attended our Monthly Meeting,
where an exercise came upon me to request men and women Friends to sit together,
in order that I might clear myself of what lay upon my mind.
And having the unity of both meetings herein,
I was favored to lay before my brethren and sisters the great
difference between faithfulness to the Lord and unfaithfulness:
remembering the words of the Lord, by the mouth of his Prophet to revolting Israel,
saying: "`She did not know that I gave her corn, and wine, and oil,
and multiplied her silver and gold, which they prepared for Baal.
Therefore will I return, and take away my corn in the time thereof,
and my wine in the season thereof,
and will recover my wool and my flax given to cover her nakedness.`"
This will be the punishment of all the disobedient.
The Lord will take away the blessing and talents from them,
if they will not improve them, and withdraw His manifold favors from them,
and leave them in darkness.
But unto faithful Israel--the true church of Christ--
who live in obedience to God their Heavenly Father,
the encouraging language of Isaiah the prophet,
which also arose in my mind to communicate, may be applied:
"`For Zion`'s sake will I not hold my peace, and for Jerusalem`'s sake I will not rest,
until the righteousness thereof go forth as brightness,
and the salvation thereof as a lamp that burneth.
--And the Gentiles shall see thy righteousness,
and all kings thy glory; and thou shalt be called by a new name,
which the mouth of the Lord shall name.
Thou shalt also be a crown of glory in the hand of the Lord,
and a royal diadem in the hand of thy God.
Thou shalt no more be named forsaken; neither shall thy land any more be termed Desolate;
but thou shalt be called Hephzibah, and thy land Beulah: for the Lord delighteth in thee,
and thy land shall be married.
For as a young man marrieth a virgin, so shall thy sons marry thee;
and as the bridegroom rejoiceth over the bride, so shall thy God rejoice over thee.`"
Under these encouraging prospects my soul doth lift up its head in hope.
And the language presented: "`O Zion arise, and shake thyself from the dust of the earth,
and put on thy beautiful garment, even the white robe of righteousness, purity,
and holiness, in which thou shalt be presented to the Lord a royal priesthood,
a holy nation, a peculiar people,
zealous of good works.`"--After this time I went through many heights and depths,
sometimes feeling almost forsaken of any good;
and many times was made very sensible that the
true watch-tower was too much neglected by me;
which was the occasion of my feeling myself forsaken,
and sometimes to prove my faith and hope in God.
But blessed be his holy Name forever, it was not long before he returned,
and I felt myself comforted in His holy presence.
For He loves His poor, humble, dependent children, and will arise for their help.

Seventh Month, 1808.--Attended meeting on the First-day of the week at Stanton Hill.
The forepart of which I sat under great weakness.
But light and life arising towards the conclusion,
I was favored to clear myself of an exercise that I had been under for some time,
to the comfort of many faithful burden-bearers.
Many of the dear youth being present, my mind was largely opened to them,
in the love of our Heavenly Father; and also to the parents,
showing them the great obligations, we as parents are under,
to train up our tender offspring in the nurture and admonition of the Lord;
and that if we neglect this, and our children make themselves vile,
and wound religion through their impiety which is oftentimes chargeable on
the neglect of parents and masters while the children are under our care,
we shall stand accountable for them.
Oh dear parents, and such that have the care of children,
my mind is enlarged towards you, on account of the little lambs committed to your trust.
I fear if the children should become aliens and strangers to God,
and the commonwealth of his chosen Israel,
the blood of many of their precious souls will be chargeable to you.
While the debt contracted on your part will, I fear,
be such as you shall find it difficult to fully discharge.

This favored meeting was of the Lord, the fountain of all good.
And may no praise be given to the creature, but all the praise, glory, honor,
and renown be ascribed to our Father in heaven, who enables,
through the influence of his son Jesus Christ,
to open Truth`'s doctrine to our own admiration; and well may we say,
it is the Lord`'s doings, and marvelous in our eyes.
Oh thou ever blessed Shepherd of Israel, keep me in the low valley of humiliation;
and suffer me not to take my flight on the Sabbath day--a day of joy
and favor from the Lord to my poor soul--but lead me in thy wisdom,
and by thy right hand, so shall I be enabled, at thy command,
to teach transgressors thy ways,
and to speak a word in due season to them that are weary:
so shall the praise be given unto Thee for ever.
Amen.

+++[+++Christopher Healy, with every other child born of the Spirit,
had felt his need of the "`liberty of heart derived from heaven.`"
And no doubt experienced,
through submission to the effectual working of the Lord`'s power,
the growth into dominion of that incorruptible seed and word of God,
which liveth and abideth forever.
And also the encouraging promise,
"`In Christ Jesus neither circumcision waiteth anything, nor uncircumcision,
but a new creature.`"
And "`As many as walk according to this rule, peace be on them, and mercy,
and upon the Israel of God.`"
His diary proceeds:]

14th of Eighth Month.--This morning I felt my mind measurably
brought under the government of the Prince of Peace,
which gives the victory over our wills and inclinations:
and a fervent desire attended that others may witness the same.
Which as we dwell under the precious dominion thereof, causes our love to flow to God,
and through him to all mankind.
This Prince of Peace is thus spoken of by the Prophet:
"`There shall come forth a rod out of the stem of Jesse,
and a Branch shall grow out of his roots: and the spirit of the Lord shall rest upon him,
the spirit of wisdom and understanding, the spirit of counsel and might,
the spirit of knowledge, and of the fear of the Lord.`"
This is Christ Jesus; and if we will hearken to His counsel,
and obey His holy requirings in our own hearts,
we shall witness the wolf and lionlike nature within us to be slain and reduced to love.
Then shall we experience as the fruits of the Government of the Prince of Peace,
what the prophet declared: "`The wolf shall dwell with the lamb,
and the leopard shall lie down with the kid; and the calf, and the young lion,
and the fatling together; and a little child shall lead them.
And the cow and the bear shall feed; their young ones shall lie down together:
and the lion shall eat straw like the ox.
And the suckling child shall play on the hole of the asp,
and the weaned child shall put his hand on the cockatrice`'s den.
They shall not hurt nor destroy in all my holy mountain:
for the earth shall be full of the knowledge of the Lord, as the waters cover the sea.`"
O blessed day indeed:
and is only experienced by such as witness the new birth to be brought forth in them;
yea, of being born again of that incorruptible seed and word of God,
that liveth and abideth forever.
