== Chapter IV.

[.chapter-synopsis]
* Has a Meeting in the Dutch Settlement of Schoharie
* Experience of the Enjoyment of Divine Favor
* Remarks on the Sufferings and Resurrection of Christ

Soon after our Monthly Meeting in the First Month, 1810,
I attended a meeting at Coxsackie`'s, appointed for Samuel Carey;
and a highly favored one it proved.
The doctrine of the Gospel dropped as oil, and distilled as dew on the tender grass,
to the refreshing and comforting of many minds.
Some expressed their sense of this before they left the house.
O may all the glory be given to Him, who alone is worthy forevermore.
After this we had many large and favored meetings at Stanton Hill,
which is called Coeymans`' meeting, to the comforting of many minds,
they being owned and accompanied by the great Head of the church,
which alone makes good meetings.

Having for months felt living desires to make a visit to the people of Schoharie,
a settlement of Dutch people who were very little acquainted with Friends,
I was very much discouraged about it at times,
thinking it would not be well accepted by them;
there having never been any Friends`' meeting at that place.
This made it the harder to give up to.
But many times, when my mind was comforted in the Lord, this visit, or a meeting there,
looked pleasant.
And after weighty deliberation thereon, together with the advice of my friends,
I set out, in company with a worthy Friend from our meeting, on the 14th of Third Month,
and rode to John Drake`'s.--The next day attended Friends`' Preparative Meeting at Oakhill,
which was small.
After the meeting, John Drake joining us, we set out for Schoharie;
the distance being about fifteen miles.
It being very cold, and we riding on horseback facing the wind, it proved very tedious;
and I feeling somewhat cast down in mind,
fearing I had been too forward in making this visit,
which was also the means of drawing my friends from their homes,
the thoughts of it brought me very low.
But appealing to Him who I believed turned my mind to this place,
beseeching Him to go along with us, blessed be His holy name.
He was pleased to condescend to strengthen and comfort our minds.
We reached our friend Joseph Efners, who was the only Friend in that place, before dark.

A school-house being obtained to hold a meeting, it was held the next day accordingly.
A considerable number of the Dutch people came, though the weather was trying;
and were very civil.
And blessed be the Helper of Israel, he appeared to our comfort in this meeting.
The universality of the grace of God was fully declared to the people;
showing that a portion thereof is given to all to profit with;
and that it is His holy law that he has placed in our hearts,
even at an early period of our lives; condemning us for evil;
and that it is obedience to the same that justifies us,
and gives us the answer of peace in our own minds.
It was also showed them that the gospel was free;
and that Christ`'s ministers could not be hired to preach, but as they received freely,
so they must deliver the same to the people.
It seemed to me that the minds of the people, toward the latter part of the meeting,
were tendered with a degree of the Heavenly Father`'s love.
So that I believed, while standing on my feet amongst them,
that He who called me to go and see this people, was, in His great love and mercy,
pleased to overshadow the meeting this day,
and to tender their minds toward us and our testimonies;
and caused the meeting to end to our comfort and satisfaction.
The people spoke lovingly of us, and invited us to their houses;
and some of them felt near to me, while their countenances bespoke their satisfaction.

We rode from thence to Middleburg meeting, distant about eight miles,
and lodged at David Gurney`'s. I was glad to meet with Friends of this place.
And a meeting being appointed the next day,
our friend John Drake appeared in supplication, much to the comfort of my mind.
But it was my lot to be silent, except towards the close of the meeting,
when I informed them that solemn silence was acceptable to God,
and that I had been as clearly convinced as ever I was,
that good will for the people was not a sufficient qualification to preach the gospel.
For had that been the case, my mouth would have been largely opened amongst them.
This day we had another meeting about five miles from Middleburg, at Jonathan Mosher`'s,
in Rensselaer, several Friends accompanying us from the former place.
In which, after we took our seats, I gave up to be silent.
But unexpectedly I was drawn to declare the word of life to the comfort,
of the humble-minded, and to the stirring up of the careless.
Here we parted from Friends, and rode to Amos Mosher`'s, whose wife was a Methodist.
They inviting us to tarry all night with them, we did so.
They were young and recently married.
The young man being under a concern of mind for his best welfare,
we had a comfortable visit with them.
His wife said their house was always open to Friends.
She said she had seen it her duty to be plain in her dress and address;
and her countenance declared the sincerity of her mind.

We attended Friends`' meeting next day at Rensselaerville;
these two young people coming to the meeting.
And the Lord was pleased to comfort us together,
and I was led to declare how attentive a faithful soldier of
Christ would be to the Captain of his soul`'s salvation;
even to obey His command in all things.
As I stood on my feet in this meeting, I felt the word of life to increase;
and the true mark and badge of discipleship was clearly
brought before the view of my mind in the words of our Lord:
"`By this shall all men know that ye are my disciples, if ye have love one to another.`"
A portion of this love spread over the meeting,
and caused it to end to our humbling admiration.
After this meeting,
we had a sitting in a family wherein the humbling power of
Truth broke forth and distilled as the dew on the tender grass,
the hearts of those present being tendered and much broken.
I believe this opportunity will not soon be forgotten by them.
After this we went to Caleb Spencer`'s, and stayed that night,
and next morning returned home.
I was truly thankful to the Lord for so sympathizing a
companion as my friend proved to be in this short visit.

On the first day of Fourth Month, 1810,
I attended a meeting appointed at a sick woman`'s request, about seven miles distant.
Soon after I sat down in the meeting, I felt the presence of the Good Master near,
and I was soon raised upon my feet with these words.
"`When a man`'s ways please the Lord, he maketh even his enemies to be at peace with him.`"
Oh, the advantage and favor those receive from the Lord, that live in His holy fear,
and obey his commands.
How safe is their dwelling place.
What encouragement there is to persevere.
How these will be protected.
For "`He that dwelleth in the secret place of the Most High,
shall abide under the shadow of the Almighty.
I will say of the Lord, he is my refuge and my fortress: my God; in him will I trust.
Surely he shall deliver thee from the snare of the fowler,
and from the noisome pestilence.
He shall cover thee with his feathers, and under his wings shalt thou trust:
his truth shall be thy shield and buckler.
Thou shalt not be afraid for the terror by night, nor for the arrow that flieth by day;
nor for the pestilence that walketh in darkness,
nor for the destruction that wasteth at noonday.
A thousand shall fall at thy side, and ten thousand at thy right hand;
but it shall not come nigh thee.
Only with thine eyes shalt thou behold and see the reward of the wicked.
Because thou hast made the Lord which is my refuge, even the most High thy habitation,
there shall no evil befall thee, neither shall any plague come nigh thy dwelling.`"
I was helped from this Scripture testimony to encourage
all present to attend to the gift of God,
or seed of the kingdom in the heart.
So should we know a safe dwelling-place in the Lord.
I was much enlarged thereon to my own humbling admiration,
and to the consolation of many present.

Fourth Month, 2nd.--Returning from my school at evening,
my mind as I walked was fixed on heavenly things,
and I felt a stream of Divine love to flow into my soul,
whereby my inner man was greatly refreshed.
And my spirit breathed forth songs of praise to the Lord,
beseeching Him to preserve my soul alive, and keep me obedient to His commands.
This heavenly flow of Divine love continued with me until late in the night,
and my cup did overflow with joy at the goodness of the Lord to me.
Eye has indeed not seen, nor ear heard, neither hath it entered into the heart of man,
while in his degenerate state,
to conceive the good things the Lord hath in store for them that love, obey,
and follow Him with all their hearts.
Oh blessed Redeemer!
Thy presence is sweet; and by me is preferred before corn, wine, or oil: yea,
to the riches of the Indies.
Thou art infinitely to be preferred to gold.
For Thou canst give eternal life;
and at thy right hand are rivers of pleasures forevermore, saith my soul.

Our meetings at Stanton Hill being very large on First-days,
owing to a great number of people besides our members attending,
my soul was often prostrated before the Lord, both in and out of meeting,
craving in secret prayer His Almighty aid, and that he would keep me in a true, humble,
waiting state of mind in these gatherings,
that so I might experience my strength renewed in Him; and know Him,
the great Shepherd of Israel, to put me forth and go before.
O God! the work is thine,
and thou canst carry it on either immediately or instrumentally as pleaseth Thee.
Therefore,
may I ever wait in solemn silence before the ever blessed Savior to lift me upon my feet.
So shall I, through Thy mighty power, and gospel light and life,
teach transgressors Thy ways; and sinners, through Thy redeeming love and power,
shall be converted unto Thee.
O may I never stir up nor awake the Beloved of my soul until He please.
Then I believe He will often cause His doctrine to distill as the dew,
and as the gentle rain on the tender grass.
For when He, the God of Israel, is pleased to arise, then shall His enemies be scattered.
I well remember what our Savior said to the Scribes and Pharisees: "`My time,`" said He,
"`is not yet come; but your time is alway ready.`"
And I am well confirmed in the opinion, that all true ministers must wait His time,
before they can preach His gospel;
and must not attempt to feed on the manna of yesterday,
but know their strength renewed day by day, by the alone sustaining bread.

Fourth Month, 13th.--My mind was led to consider the beauty of holiness,
and in a particular manner what benefit the dear youth would receive,
if they would be so wise as to embrace religion in the morning of their days I What
snares and temptations of the enemy of their soul`'s happiness they might avoid,
by covenanting with, and adhering to the great Shepherd and Bishop of their souls,
before their minds become biassed by the god of this world.
O how pleasant is the morning of life when no clouds
obstruct the light of the Sun of Righteousness;
when the mind feels clear; when obedience keeps pace with knowledge;
and no condemnation covers the soul.
Such mornings may truly be said to be mornings without clouds.
Our Heavenly Father, under the law, required a lamb of the first year without blemish;
but now, under the gospel dispensation.
He calls for a broken heart and contrite spirit.
Moreover, dear youth, unto these he looks that are poor in spirit: and will,
as they continue faithful, show them His heavenly kingdom.
But all your offerings must be without blemish, even the whole heart,
without any mixture of the creaturely will.
For the feast, the heavenly feast that Christ will come unto,
must be kept with the unleavened bread of sincerity and truth.
Although some high-minded youth may look upon
the path of self-denial and the daily cross,
as too mean a road for them to walk in, especially at so early a period of their days,
falsely imagining that thereby they shall lose all their comfort in this life!
But, dear youth, let me inform you from my own experience,
that these are the suggestions of the enemy of our peace.
For never can there be found such joys and comfort in earthly things,
as those witness who can say in truth,
Thy will be done in my heart as it is done in heaven.

And may I, while writing these lines,
adopt the language of one formerly who had proved that one day
in the Lord`'s courts is worth a thousand elsewhere,
saying, "`I had rather be a door-keeper in the house of my God,
than to dwell in the tents of wickedness.`"
O how sweet is the presence of our Lord and
Savior to those who choose Him for their portion,
and obey His sweet voice.
It is as marrow to their bones, and health to all their flesh.
Safe indeed to feel preserved within the hollow of His Holy Hand.--Remember, dear youth,
that our great Lord and Master when on earth declared:
"`Whosoever shall seek to save his life shall lose it;`" that is,
to save his life of pleasure and vanity, shall lose his eternal life:
but he that is willing to lose his life of pleasure and vanity in this world,
and cleave to Christ and become His disciple through
self-denial and the daily cross to his own will,
shall not fail of preserving it, or of having a place in Christ`'s kingdom.`'

Fifth-day, 19th.--Being this day plunged into a great sea of trouble,
wherein my soul was deeply tried, my supplication to the Lord was after this manner:
O Lord, stretch forth Thy holy hand of help and deliverance; for without Thee,
as Thou knowest,
I am not able to bear up nor keep my head above the mighty waves of this tempestuous sea.
Therefore, O blessed Lord, if it be thy will, manifest thy power,
and work deliverance for thy poor servant.
Thou knowest I love thee, and thy glorious cause above my natural life;
which I refuse not to lay down if it should please thee to call for it.
I love thee above all things here below;
and long to feel a refreshing stream from thy holy fountain.
O blessed Lord of life and glory, be pleased to cause the morning dew,
and celestial rain to descend and water my poor soul as
thou hast aforetime often done to thine own honor.
O Lord,
give me patience to bear my trials until it shall
please thee to bring me safely through them.
Amen.

+++[+++After an allusion to our blessed Lord`'s query to Peter, three times repeated,
"`Lovest thou me '`?`" with the great duty of feeling
and knowing the prevalence of this love in ourselves,
first and before all to Christ, ere we can be strengthened and enabled to feed His sheep,
or speak a word in season to them that are weary; with some allusion also to the birth,
life, miracles, sufferings, death and resurrection, and despised appearance,
in the world`'s view, of Jesus Christ of Nazareth, our Savior,
Christopher Healy proceeds thus to comment upon that most satisfactory
sacrifice of the dear Son and Sent of God for man`'s salvation:]

What could be more affecting than the manner of His (the
Savior`'s) death? with the resigned situation of his soul,
conveyed in the following language: "`Oh, Father,
if it be possible let this cup pass from me: yet not my will, but thine be done.`"
This cup, this bitter cup of death and suffering he drank for us!
Oh may we so live under the power of his cross to our own wills,
as to have true fellowship with him in his sufferings;
so shall we be benefited by his death.
And when our blessed Lord arose, having conquered all the powers of darkness,
how comfortable it was to his disciples to hear the glad tidings:
Behold I go before you into Galilee, there shall ye see me.
So shall the faithful servants of Jesus,
that continue with him through suffering and death, arise with him in newness of life,
and witness the Savior`'s promise verified, that where he is,
there shall also his servants be.

8th of Tenth Month, 1810.--This day I am thirty-seven years old.
O Lord! as I grow in years may I grow in grace;
and in the knowledge of our Lord and Savior Jesus Christ, whom to know is life eternal.
Therefore, Lord, suffer me not to transgress thy holy law.
Wean my affections more and more from everything here below;
and set my heart wholly on thee.
Thou knowest the many weaknesses that surround me; but thou art my strength in weakness,
riches in poverty, and the only hope of eternal life.
O make me willing to be wholly thine, in body, soul and spirit;
and to become as passive clay in the hand of the potter.
Thou art the great Potter.
Mould and fashion me into a vessel of use in thy holy house.
O Lord, I once more resign my life and my all unto thee.
Even this evening do I resign myself to be disposed of as thou shalt see meet.
Therefore, O Lord! visit my iniquities and my transgressions, if any there be in me,
with thy rod and thy stripes; and continue thy lovingkindness, even thy Spirit of Truth,
that leads and guides into all truth;
which doth at this time enable my poor soul to give thee the praise, the honor,
the glory, to whom it is due.
Amen.
