== Chapter V.

[.chapter-synopsis]
* Remarks on the Preciousness of True Unity
* Religious Concern for the Children in His School
* Visits a Sick Woman, a Member Among the Methodists, and Attends Her Funeral

Early in the Eleventh Month of this year, I attended our Quarterly Meeting,
which was a low time with me.
The evening following, visited a sick woman, who departed this life next day;
which brought me to look closely into my own case.
The same night when I went to bed,
it pleased my Heavenly Father to visit my poor soul with the Day-spring from on high,
wherein my heart was so overcome with his lovingkindness,
that I spake of it to my friend who lodged with me; for sleep,
in this joyful state of mind, departed from my eyes.
I saw clearly that holiness became God`'s house forever;
and felt a secret prayer for further purification.
The next day, in company with my before mentioned friend, I visited a disconsolate widow,
and had a religious opportunity in the family;
wherein the Lord gave me a word of comfort to the bereaved one,
which I believe sweetened the bitter cup of her afflictions,
that she had lately drunk so large a portion of.

The next being First-day, accompanied by the same Friend, I went to Crum Elbow Meeting.
Soon after I sat down in the meeting, I felt the unity of the one Spirit,
in the bond of sweet peace to spread over us;
and in the comfort thereof I was raised upon my feet, and the Lord was unto me,
I believe I may say, mouth and wisdom.
The language of David was presented to my mind: "`Behold,
how good and how pleasant it is for brethren to dwell together in unity!
It is like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard; that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forever more.`"
Upon this subject I was lengthened and strengthened this day,
blessed be the name of the Lord; who alone can qualify to preach the gospel.
May the praise be given to him, to whom it is only due.
After this meeting, I returned home with a degree of sweet peace.

The winter following, I attended but few meetings except our own;
being in my usual employment of teaching a school.
O, saith my soul, may I so walk before the dear children committed to my care,
that I may, as way opens in the truth, administer counsel to their tender minds!
Having a large number of small children in my school,
I was often brought to consider the importance of my trust,
not only in respect to their outward education, but also to endeavor,
through Divine assistance, to turn their tender minds in the way of Truth;
teaching them that "`the fear of the Lord is the beginning of
wisdom,`" and to depart from evil is understanding.
One day having a larger number than usual, and many of their minds appearing tender,
I was led to beseech the Lord to be near them;
and in secret did put up my petition on this wise:
Lord! visit the dear lambs under my care with the Day-spring from on high.
Cause them, dearest Lord, to remember Thee, their Creator, in the days of their youth;
while their minds are tender.
And strengthen me, thy poor servant, to instruct them in thy fear;
that we may feel thy presence to be with us,
which will enable us to give thee the praise henceforth and forever more.
Amen.

Fifth Month, 1811.--Attended our Quarterly Meeting;
and the latter part of the same month our Yearly Meeting in New York,
to good satisfaction.
Many Friends from distant parts attended this annual gathering,
whose gospel labor were strengthening to my mind.

On my return home,
I was informed of the death of one of my near neighbors--a
Friend--whose departure was sudden and unexpected.
Oh how needful it is to be prepared for death;
seeing it will sooner or later arrest us all!

Eighth Month, 18th, I visited a sick woman who was near leaving the world.
She appeared in a comfortable state of mind; had her senses well;
and manifested her satisfaction with my visit,
by requesting a religious opportunity in her family.
Feeling my mind drawn thereto, I asked the people present to sit down in a quiet manner,
there being several of the Methodist persuasion present;
the sick woman being also a member of that meeting.
After a time of silence, my mouth was opened in gospel love,
and concluded in supplication to the Lord, to the tendering of most present;
and to the comfort of the sick woman, who, at our parting, signified the same.
For we parted in an affectionate manner, I not at all doubting,
if enabled to make a happy end, that I should meet her in everlasting peace.
She lived but a few hours after this interview.

The next Third-day I was at her burial.
A Methodist minister also attended, and a number more of their church.
There were likewise some Friends, and many of other denominations there.
When I took my seat in this meeting, a living desire arose in my mind,
that the Lord would be pleased to keep down forward spirits,
and instruct by his own power.
Soon after the meeting gathered, a man brought a stand with a Bible on it.
This minister and I sat side by side in a quiet manner for some time;
which no doubt appeared strange to some of them.
But I believe he felt something that forebade his proceeding in his usual formal manner.
After a while he got up; but did not take his Bible for a text,
but spoke something in allusion to the solemnity of the occasion.
He then kneeled in prayer.
After which he spoke a little,
but soon expressed that he found it right for him to leave the service of the meeting,
saying, he believed the Spirit of the Lord was at work with some present;
and so sat down.
Whereupon the meeting remained silent for some time.
My mind was truly brought to wait on the Lord, and my strength was renewed in him.
After a period of sweet silence, a man of a forward spirit,
who had been in the way of speaking in their meetings, got up and spoke;
but the power of the Lord was against him, and he pretty soon sat down.
Directly after this, I felt the power of Truth, as a live coal from the holy altar,
to touch my heart, whereby I was raised on my feet,
and my mouth opened with the declaration: Christ is the fountain of living waters,
unto which all may come and drink to the satisfying of their thirsty souls.
Enlarging thereon,
the Lord was pleased to favor with his gospel power and life-giving presence,
which only can enable any to preach the gospel;
for which divine favor my soul doth bless his holy name.
After I sat down,
the Methodist minister arose and said he was now confirmed in what he had before felt.
He expressed his satisfaction with what was said,
and desired the people to remember the counsel of our friend, as he called me, adding,
they had been faithfully warned.
He kneeled again, and then sat down.
After which we remained a time in silence.
I then offered him my hand, which he received in a loving manner,
and so the meeting concluded to the satisfaction of most present.
The minister expressed his love, and we had some agreeable conversation,
parting in a loving manner.
Oh how good it is to trust in the Lord; for I believe he gave the victory this day.

Some time after this,
I was invited to attend the burial of an aged woman--
not a member with us--living about five miles distant.
It being on First-day afternoon, and, as I was afterwards informed,
notice being given of it at their different meetings,
a large concourse of people attended.
I went to the meeting in great poverty of spirit,
and took my seat with my whole dependence on the Lord; who is strength in weakness,
riches in poverty, and a present Helper in every needful time.
But let none dare to arise to speak in his name, until he gives the word of command.
I was led to show the people the preciousness of time.
That it waited not for man, nor tarried for the sons of men.
That it was more precious,
because in time only can we prepare for a never-ending eternity.
I was led clearly to open the Apostle`'s testimony where he saith:
"`If ye live after the flesh ye shall die;
but if ye through the spirit do mortify the deeds of the body, ye shall live.`"
And also, "`To be carnally minded is death,
but to be spiritually minded is life and peace.`"
I was much enlarged thereon to my humbling
admiration.--The presence of the Lord was near,
and many were sensible thereof.
The meeting concluded with tender advice and counsel to the youth.

After this meeting, a Baptist preacher came to me,
and said he was glad to see me for the first time.
And said he felt such unity with the counsel to the youth,
that he was sorry he had not publicly declared it.
I told him I wanted no praise;
but enjoined if there was any good done to give the praise to whom it was due.
He parted with me in a loving manner; and said, "`Go on in the strength of the Lord.`"
Oh may all praise be ascribed to the Shepherd of Israel,
without whose blessed help we can do nothing.
Oh join me, reader, to give him all the praise,
and let the creature be abased as in the dust.
