== Chapter IX.

[.chapter-synopsis]
* Remarks on the Doctrines of Elias Hicks, and Efforts Used to Stop the Progress of Ani-Christian Sentiments in the Society of Friends
* Assists Friends and Others in the Southern States
* Solemn Meetings with Slaveholders and Slaves
* Letter of Nathan Hunt
* The Separation in the Society of Friends Caused by Doctrines Promulgated by Elias Hicks, and Others
* Attends New York Yearly Meeting in 1828

The journal of Christopher Healy next proceeds to
portray that disaffection and lapse in religious belief,
which in the eventful year of 1827,
culminated in the separation of so large a number from our religious Society.
Christopher Healy, in his journal, says:--

About these days (1824) there was much appearance of unsoundness among our members.
Elias Hicks had made some visits amongst us, to the grief of many,
both in city and country.
Our members began to have different sentiments
respecting the divinity of our dear Redeemer;
and this divided feeling increased very much amongst us,
so that the harmony and unity began to be lost.
And it must be so;
for in proportion as the true faith in our Lord Jesus Christ is forsaken,
the unity of the Spirit in the bond of peace, and true fellowship of the saints,
comes to be broken.
A great concern was felt by many of us,
to stop the progress of this dividing and disorganizing spirit;
for it seemed as though it would destroy all harmony and fellowship,
and comfort of love in our religious Society.
But adored be the name of Israel`'s Shepherd, who cares for his own sheep, and calls them,
and leads them as lambs in the midst of wolves; even wolves in sheep`'s clothing.
For some of these that had departed from the faith once delivered to the saints,
so as to deny that Jesus who suffered without the gates
of Jerusalem as the Savior of the world,
and yet profess a great love for us and our young people,
we could do no other than bear our testimony against.

In 1828, while attending Bridgewater Monthly Meeting, New York,
Christopher Healy felt drawn to open and support the
doctrine of the divinity of our Lord Jesus Christ,
by authority of the Holy Scriptures,
and declared it to be the doctrine always held by the Society of Friends.
These errors, which the principal leaders of the Separatists of that day propagated,
were brought into view by quotations from their printed discourses.
It was distinctly stated that, notwithstanding they professed to believe in Christ,
if they would confess their real sentiments,
it would be found they denied that He who was born of the Virgin Man,
and respecting whom it is declared, that,
"`when He bringeth the First Begotten into the world He saith,
let all the angels of God worship Him,`" is the Savior of men.
Instead of acknowledging the Son, to whom it is said, "`thy throne, O God,
is forever and ever:
a sceptre of righteousness is the sceptre of thy kingdom,`" the Separatists
declared that the Almighty could never set Jesus Christ above us,
for, if He did.
He would be partial,--thereby endeavoring to destroy the
divine and glorious character of the Son of God,--while they
pretended to believe in his light shining in the heart.

This development of the unbelief of Elias Hicks had a
very convincing effect on a number in the meeting,
who did not appear to have understood his opinions fully,
and the various shifts and glosses used to inculcate them.
This conviction was rendered still more complete, by some remarks of Hugh Judge, who had,
unhappily, in his old age, fallen in with these errors.
He observed, that he had not heard a word that had been spoken,
but felt a great weight of darkness upon his spirit.
He then endeavored to give, what he considered to be the sentiments of Friends;
making them appear very outward in their views;
and in order to exhibit the spirituality which he had attained to,
he declared that he did not believe Jesus Christ, who was born of the Virgin Mary,
to be the Savior; and near the close of his speech said:
"`My Savior never was crucified:`" thus denying Him to
be the Savior of whom the apostles declare,
"`We preach Christ crucified: to the Jews a stumbling-block,
and unto the Greeks foolishness; but unto them which are called, both Jews and Greeks,
Christ, the power of God, and the wisdom of God.`"
This effectually confirmed the observation before made by Christopher Healy,
that if they would confess their real sentiments,
it would appear they did not believe the Lord Jesus was the Savior;
and appeared to have had a settling effect on those present.

In the Twelfth Mouth of 1824,
he paid a religious visit to Friends of the Southern States;
also to slaveholders with their slaves.
He had many large and satisfactory meetings.
After one of which, he could adopt the following language:
"`In the Lord`'s presence there is life,
and at his right hand rivers of pleasure forevermore.
May my poor soul continue to be humbled in the dust before Him.`"
His own account follows:--

In Virginia I was joined by a kind friend and elder, James Stanton.
We had a large public meeting at Muffleborough, in a Methodist meeting-house.
Four Methodist and two Presbyterian ministers attended;
also a great number of slaves and slaveholders; so that the house could not hold them,
but many stood in the yard where they could hear.
A solemn stillness prevailed over the whole assembly.
It was evident the heart-melting presence of the Divine Master covered the meeting;
and ability and strength were given to declare the doctrines of the gospel,
and the righteous testimonies thereof.--Many minds, both of slaveholders and slaves,
were tendered; and my own soul did secretly praise the Lord our God.

After having many meetings in the lower part of Virginia,
we came to Piney Woods meeting of Friends in North Carolina,
where notice of our desire to have a meeting was given to slaveholders and their slaves.
A large number attended,
and the meeting was favored with the life-giving
presence of our Holy Head and heavenly Shepherd.
We passed from thence down to Elizabeth City,
having a number of large meetings on the way.--The masters and
slaves expressed their great comfort in our visit to them.
Here we saw many poor colored people, very aged, whose heads were white,
walking with staffs, and some with two, to enable them to get about.
Oh how my heart did feel for these!
When they came to shake hands with us, tears were trickling down their faces,
expressing at the same time their great thankfulness to the Lord for our visit to them,
such poor creatures.

Next morning I received a visit from a Methodist minister,
who expressed a desire that I might have another meeting with them and their slaves;
and said there would more come together than did before,
for they were all glad of the meeting.
I told him I must see my way clear, before I could make another appointment.
He said he was early convinced that slavery was wrong,
and that he had missed it exceedingly in purchasing any.
That if any way opened to free them, he would give them their liberty.
The slaveholders that I spoke with, generally acknowledged the evil of slavery.

After weighing the request of the minister, I was most easy to leave the place.
On our way up the State from Elizabeth City, we came to Rich Square,
in Northampton county, at the time of the Quarterly Meeting;
where I met with our friend William Forster, from Great Britain.
The Quarterly Meeting of business was favored.
Next day we had a public meeting.
Many of both whites and blacks could not get into the house.
The meeting was owned by the Divine Master, who was this day mouth and wisdom:
and I could adopt the language, "`In thy presence there is life,
and at thy right hand rivers of pleasure forevermore.`"
May my poor soul continue to be humbled in the dust before Him.
From thence we rode about two hundred miles up the State to New Garden,
where we had a meeting.
And one also at Deep River, which was a favored time.
Next day we had a meeting on our way to our aged friend Nathan Hunt`'s,
who was a living minister, bringing forth fruit in old age.
He kindly accompanied us, and his company and gospel labors were strengthening to my mind.
We had a number of favored meetings together,
and then came to New Garden to attend the Quarterly Meeting to be held there.
It was a favored time; blessed be the good Shepherd of the sheep,
who putteth forth his own, and goeth before them.
May they always be willing to follow Him, either in suffering or rejoicing;
so shall He be glorified in them.
After this Quarterly Meeting, except a few meetings on our way,
we came almost directly home, and found my dear wife and family all well.
Oh may my soul always remember how good it is to trust
in the Lord and never doubt his precious promises,
that he will never leave nor forsake those that trust in Him!

From letters written to Sarah Healy during her husband`'s absence on this visit,
tending to encourage her in her loneliness,
and conveying their sense of his ministerial services among them,
we select the following from the pen of Nathan Hunt:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Springfield, Guilford Co., N. C,

[.signed-section-context-open]
Third Month 11th, 1825.

[.salutation]
Dear Friend:

Thy husband came to our house last Third-day morning,
and attended our Monthly Meeting on Fourth-day;
in which his divine Master furnished him with understanding to
bring forth out of his treasures things new and old,
to the comfort, edification and encouragement of the mourners in Zion;
and to caution and counsel the lukewarm and careless professors.
I attended public meetings with him Fifth and Sixth-days,
and also on Seventh-day with a large company of people.
There were masters and some slaves in all of them.
He has shown himself to be a workman that need not be ashamed, dividing the word aright;
wielding the sword with dexterity and skill;
and applying Gilead`'s healing balm to wounded souls.
He feels particularly near to many of us, because he comes in the good old way,
and we understand him, being like face answering to face in a glass.
He is as bone of our bone, and flesh of our flesh; a brother indeed;
and we will have no other doctrine than that which he preaches.

"`If thou, dear heart, feels sometimes lonely and sorrowful,
let this thought cheer thy mind,--my dear husband is making many glad;
and they that go forth weeping and sorrowing, doubtless shall come again rejoicing,
bringing their sheaves with them.
This I believe will be the blessed experience of thy bosom friend,
and your coming together will be like the rejoicing of the righteous.
Oh how comforting the promise is,
'`The Lord will keep him in perfect peace whose mind is stayed on Him,
because he trusteth in Him.`' These become like Mount Zion, that never can be removed.
Many such gracious promises we find in the Scriptures of truth to
animate and strengthen us in the weary pilgrimage through time,
that we may keep the eye single to the Lord,
in what situation soever He may be pleased to place us in his house.
For it appears some have to go forth to battle, and some to stay by the stuff;
but all share alike in the spoil.
The beauty is, for every one to be in their allotted station.
My dear wife and myself are prepared to feel with thee and thy dear husband,
in your separation, as it has been often our lot to be separated for the work`'s sake.
But it mattereth not what may be the pathway through
the changeable scenes of this uncertain world,
be it rough or smooth,
if at the end we may but be favored to enter through the gates into the city,
where the enemy will cease to trouble, and the weary be at rest.

My dear wife unites in near and dear love to thee.
I am thy affectionate friend,

[.signed-section-signature]
Nathan Hunt

--

Here our friend again alludes to the unsound
views then being disseminated by Elias Hicks,
and some of his adherents:--

The unsound principles promulgated by E. H.,
had now increased very much within the compass of our Yearly Meeting and several others,
viz.. New York, Baltimore, and Ohio;
which broke the harmony and peace wherever those principles prevailed;
causing doubts and denials of the divinity of our Lord Jesus Christ,
and of his propitiatory sacrifice for the sins of the whole world.
Elias Hicks having travelled in several Yearly Meetings,
and books being circulated holding forth the same unchristian views,
all had the effect to make a very gloomy appearance over our Society;
and caused many of us to mourn and lament in the language of the prophet:
"`Oh that my head were waters, and mine eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of my people.`"
This awfully disorganizing and dividing spirit went on, till in the Fourth Month of 1827,
at the time of the Philadelphia Yearly Meeting,
this disaffected and unsound part of the Society drew off;
and in the Tenth Month of the same year,
established what they called a Yearly Meeting of their own.
This seemed to relieve Friends of much trouble;
and opened a way for us to testify against them in the order of Truth and discipline.
Oh! how my soul remembers the afflictions and sorrows--the wormwood and the gall--that I,
as well as many others, had to feel and taste of during this great conflict.
"`Oh my soul, come not thou into their secret; unto their assemblies, mine honor,
be not thou united.`"

Again,
after a reference to the very trying occurrences
in New York Yearly Meeting in the Fifth Month,
1828, which he attended, he writes:--

Upon the conclusion of the Yearly Meeting,
I went in company with the Yearly Meeting`'s committee as far as Bridgewater;
and a trying and proving season it was.
Oh the sorrowful state of those that deny the Lord that bought them!
The meetings mostly divided.
The unbelieving part manifesting that they went out from us, because they were not of us.
After the Monthly Meeting at Bridgewater, I returned home, taking meetings on the way.
Friends of our Yearly meeting felt near to each other
after such a load of darkness had been removed from us.
But I could not help mourning the loss of many that were
evidently carried away by the leaders of the separation,
in a dark and cloudy day.
May the Lord of the vineyard be pleased to open their understandings,
and restore them to the fold again.
And it is my heart`'s desire and prayer to the Lord our God,
that those also who have been the means of thus
dividing in Jacob and scattering in Israel,
may, if it be not too late for them to see their error,
be brought to confess that Holy Redeemer whom, as their only Savior,
they have slighted and despised.
