== Chapter X.

[.chapter-synopsis]
* Embarks on a Visit to Friends and Others in Great Britain and Ireland
* Letter to His Wife
* Letter of Ann Jones
* Letter of William Evans

Christopher Healy, as his journal states,
having for several years felt his mind drawn to visit in gospel love, Friends,
with some others not of our Society, in Great Britain and Ireland,
obtained a certificate of the unity of his Monthly, Quarterly,
and Yearly Meetings for this service.
The foil time, as he believed, having arrived, on the 2nd of the Sixth Month, 1831,
he went on board the ship Algonquin, William West, master,
and after taking an affectionate leave of his dear wife
and numerous friends who accompanied him to the ship,
he, the same day, sailed from Philadelphia; having for companions,
bound on a similar errand, Jonathan Taylor of Ohio, and Stephen Grellet, from Burlington,
New Jersey.
They had several meetings, both morning and evening,
with opportunities also for reading portions of the Holy Scriptures; the captain,
who was very kind and courteous to them, sitting with them;
and many of the passengers and sailors likewise giving them their company.
They had an unusually smooth and pleasant passage,
and on the 29th of the same month cast anchor before the city of Liverpool.
Next morning they went on shore, and it being Friends' usual meeting day,
they attended it.
Christopher Healy writes: "`It was a comfortable meeting,
and I can say my soul felt humbled as in the dust for the blessing
and favor of Heaven in bringing us safely over the mighty deep.`"
"`He that made the heavens and the earth,`" he continues, "`the sea,
and the fountains of waters, can control them at His pleasure.`"
They visited a number of Friends' families in and about Liverpool,
with some of the sick and the aged.
On First-day morning they also together attended the same meeting,
and on the following Fourth-day morning Stephen Grellet left for London,
and Jonathan Taylor for Manchester;
Christopher again attending Liverpool Meeting on Fifth-day.
He says it was a precious meeting,
and very confirming to him that he was in his right place.
He adds, "`May my soul wait for right direction.
And may the Shepherd of Israel keep and preserve my dear wife and children,
to whose care I have resigned them.`"

He held some more meetings in and about Liverpool, of one of which he records,
that "`the blessed Redeemer was pleased to overshadow the assembly,
and to crown with his living presence.
May He alone have the praise.`"

Taking coach from here, he and his companion came, amongst other places, to Nantwich,
where a Monthly Meeting was held.
Here he says, "`We met with our dear friends George and Ann Jones,
who had not long since been in America on a religious visit.
We were truly glad to see each other;
and could thank our divine Master and take fresh courage.`"
At Colebrookdale, on a First-day, he had a public meeting,
which was large.--Christopher was opened both in doctrine and counsel.--He adds:
"`May it be remembered;
and may I never forget the loving kindness of the great Minister of ministers,
who alone can rightly teach what to declare among the people, and when to be silent.`"

At Sidcot, he thus writes: "`A considerable number of Friends belong to this meeting,
who have a school under their care; of which a large proportion attended the meeting.
It was a very good time.
Counsel flowed freely to parents and teachers,
that they should instruct the children in the fear of the Lord.
Advice was given likewise to the dear children; many of whom were much tendered.
May it be long remembered.
Had a meeting at the same place in the evening, to the joy and rejoicing of many;
which was acknowledged by those not of our Society in a feeling manner.
May the Lord have all the praise, to whom it is due.`"

At Chatham he writes: "`A large public meeting in the evening.
A precious quiet spread over us; and it proved a solemn, favored time.
May such seasons not be forgotten.
It is the Lord's doings, and marvelous in mine eyes.`"

At London,
he attended the Quarterly Meeting of Ministers and Elders for London and Middlesex.
Here he met with his friend and fellow passenger and countryman, Stephen Grellet,
and his aged friend Thomas Shillitoe, of that land;
who had been in America on a religious visit.
This meeting was to their comfort, being truly glad to see each other.
Next day, Christopher Healy attended the general Quarterly Meeting, which was large.
He was silent; but Sarah (Lynes) Grubb was largely engaged in the ministry;
as was Thomas Shillitoe.

About this time he wrote to his wife; from which the following is extracted:--

[.signed-section-context-open]
Stoke Newington, Tenth Month, 10th, 1831.

[.salutation]
My Dear Sarah,

I have just finished visiting all the meetings in London and Middlesex Quarterly Meeting,
and am this morning going to attend the Morning
Meeting of Ministers and Elders in London.
Then I expect to take meetings through the different counties towards Scotland.
Yesterday was at Tottenham meeting, which is about six miles from London.
Here our dear friend Thomas Shillitoe lives.
I drank tea with him and his dear wife, who is eighty-six years old;
seven years older than her husband.
They both attended meeting with me--a large meeting of Friends.
I had a public meeting at four o'clock for others, which was large, and solemnly quiet.
Soon after I took my seat in meeting,
the testimony of the apostle was presented to my mind:
"`There is therefore now no condemnation to them which are in Christ Jesus,
who walk not after the flesh but after the Spirit.
For the law of the spirit of life in Christ Jesus hath
made me free from the law of sin and death;
"`on which important subject my mind was clearly opened to explain to the
people the necessity of attending to this law of the Spirit of life.

Dear Thomas Shillitoe says he remembers thee perfectly well,
and also his being at our house.
He desires to be affectionately remembered to thee.
Thomas preaches the gospel in his old age, in life and power.
Oh how encouraging it is to see such dear Friends,
and to believe they are planted in the house of the Lord,
and to see them flourish in the courts of our God; bringing forth fruit in old age.

My mind is abundantly engaged in public meetings,
and the minds of the people are very much opened to
hear the truth of the gospel as it is in Jesus,
through the teaching of his grace and Holy Spirit in their heart..--Oh! saith my soul,
may they be willing to obey.
Then will they have a sure foundation to build upon, even Christ Jesus,
who was the foundation of old,
and remains to be the everlasting Rock against which no storm nor tempest can prevail.
My heart is full of gospel love while I am writing to thee, my dear companion,
believing thou canst read and understand the feelings of my heart.

+++[+++After the expression of tender regard and counsel for his dear children,
whom he respectively named, he thus concludes:]

Give my dear love to father and mother, and all our dear friends.
May they be favored to know the sweet presence of the
Lord Jesus in their religious meetings.--And now,
in dear and tender love, never to be quenched by many waters, nor distance, nor time,
I take my leave, and bid thee farewell in the Lord.

[.signed-section-signature]
Christopher Healy

At Uxbridge he attended a meeting of Friends;
which he writes was "`a trying time;`" and then adds,
"`as it has often been with me since being in this land.
I often go mourning on my way.
Oh the unfaithfulness that prevails!`" "`At Luton,`" he says:
"`I was led to speak in a very plain manner,
and felt that the service was owned by the great Head of the Church,
and that it was to the edification of the people.`"
At the house of his kind friend John Smith, of Thirsk,
he was taken dangerously ill of bilious colic.
By this he was confined three weeks.
He thus alludes to the kind care of this family towards him:--

It could not be possible for more care and sympathy to
have been bestowed than was by these kind friends,
together with my dear companion, Joseph Hopkins,
whose attentions seemed to be to every want of mine.
May the Lord bless each and all of these for such
sympathy and kindness to a stranger in a strange land.
Just as I was recovering,
news came of the death of my dear and much beloved friend Jonathan Taylor;
who departed this life at the house of Mary Lecky, at Kilnock, in Ireland.
He came to England in the same ship that I did; and for the loss of him I did truly mourn.
Yet from the account I had of his departure,
I have no doubt but that he made a happy close.

The following letter from his friend Ann Jones, alludes to this illness,
and also to the death of Jonathan Taylor;
and on other accounts is well worthy an attentive perusal:--

[.signed-section-context-open]
Stockport, Eleventh Month 23rd, 1831.

[.salutation]
My dear friend Cristopher Healy,

I can very truly tell thee that it has not been for want of fellow feeling,
in near sisterly sympathy with thee,
that I have not sooner given thee a written proof of my remembrance,
but for want of health and ability for the employ.
My mind has followed thee and our other transatlantic brethren,
with feelings of more than common interest:
and that not only as one who knows 'the heart of a stranger' in a land of strangers,
but also as one who knows a little of the bonds and afflictions which
abide those who go forth as advocates of the doctrine of the cross,
and of the gospel of Christ Jesus our Lord, in a day, when, because iniquity abounds,
the love of many waxes cold.
I think the apostle says,
'we count them happy which endure' and blessed indeed are they who endure to the end:
who strive through the faith of the gospel to persevere in patience
in the path of duty till He who hath called to the service,
and apportions to each his share or measure of suffering and of labor,
shall see meet to say, 'It is enough.'

I heard some days ago of thy serious indisposition at Thirsk:
but having no direct or very recent account,
am at a loss to know where to address a letter to thee.
Nevertheless I am disposed to try,
not only to give thee an assurance of our near sympathy with thee, but also to say,
that if thy state of health and religious feelings and
engagements will allow of thy coming to rest awhile with us,
we do most freely and gladly offer thee a home with us,
till thou art so far recruited as to allow of thy travelling safely in our damp climate.
By no means questioning the kindness or want of hospitality of Friends where
thy lot is cast--I trust and believe thou wilt not lack either--but as one
who knows the great difference between this climate and that of America,
and how little English people in general are aware of
the need which Americans have of more warmth,
from fire, clothing, etc., than is necessary for the English constitution;
neither would I by any proposal of mine, like the old prophet formerly,
be the means of turning or drawing a fellow-servant out of the right way,
and yet if thou couldst see thy way to rest awhile with us,
and not go to Scotland or Ireland, till the winter has at least partly passed away,
I should be glad.
I know not where our friend John Wilbur is,
but on hearing of your prospect of going together into
Scotland at this season of the year,
I could but desire that if you did go,
it might be with the assurance that it was the best you could do.

I do not forget that He whom we desire to serve,
is all-sufficient to carry His servants through
all the perils and difficulties they meet with,
in the discharge of their duty to Him:
but 'wisdom dwells with prudence,' and it is requisite for us to try whether
we may not safely keep on the side of (shall I say) human prudence,
where two ways are before us.
Thou wilt perceive I only propose;
with an assurance of a hearty welcome to thee if thou canst find thy way hither where,
and in the neighborhood, there is no lack of people who have souls to save or to lose.

I shall hope to hear from thee on the receipt of this.
If thou canst not suitably write thyself,
request some friend where thou art to write in reply.

As there is no doubt thou wilt hear of the removal from works,
(undoubtedly) to blessed and glorious rewards, of our dear friend Jonathan Taylor,
at Kilnock, in Ireland,
I think I must give thee a few particulars
relating to dear Jonathan Taylor's latter days,
his illness and close.
He was at meeting at Dublin, and had good service.
His concern was principally to the young people.
He and his companion Jacob Green, had visited all the meetings in Ireland except three;
and attended the three Quarterly Meetings.
Jonathan Taylor appeared to be low, and not quite well, and on H. S., Jr.,
asking him when he expected to go to England, he replied he did not know,
he could not tell when he should leave Ireland;
but wished to go to Mary Lecky's at Kilnock, to rest awhile.
He was at Dublin fleeting on First-day morning, and Kingstown in the afternoon:
had an appointed meeting at Wicklow on Second-day:
returned to Dublin where he was at meeting on Third-day--silent.
After meeting complained of being unwell;
and spent the time in Dublin and the neighborhood until Sixth-day.
He said he had taken cold.
Friends observed a remarkable sweetness in his countenance.
Sixth-day, the 28th, went to Kilnock very unwell; worse when he arrived;
went to bed immediately; and was not up afterwards.
Inflammation of the lungs came on: his mind much abstracted from outward things:
he expressed that he felt resigned.
Dr. Harvey went from Dublin on the first instant to see him:
bled him which afforded some relief,
but the doctor found him too weak to bear the
depletion necessary' to remove the inflammation:
continued gradually sinking, and was frequently heard supplicating to be released.
On First-day the 6th of Eleventh Month, this dear disciple fell asleep in Jesus,
on whom he firmly believed; and for whose Name's sake he had patiently suffered.
This will be a heavy stroke to his wife and daughter.
And whilst we mourn their and the church's loss, are bound to unite in the language,
'Blessed are the dead which die in the Lord,' etc.

I have written more than I expected when I began; and am reminded it is time to close.
My husband is well.
He unites with me in the above invitation, and in the salutation of love and sympathy.

[.signed-section-closing]
Thy friend,

[.signed-section-signature]
Ann Jones

The following are extracts from a letter of our late beloved friend William Evans,
to Christopher Healy while in England:

[.signed-section-context-open]
Philadelphia, Twelfth Month, 22nd, 1831.

[.salutation]
My Dear Friend,

Thy very acceptable communication, written at Hartford, 7th of Tenth Month last,
was duly received,
and tended to quicken our feelings in that
fellowship we have long enjoyed with each other,
and which has not been diminished by the temporary
separation we are subjected to for the work's sake.
Thou art often the subject of our thoughts and conversation,
and it has been pleasant to hear by letters from
some of our English Friends of thy movements,
which, though we have had no very particular accounts, are satisfactory.
If we are the servants of Christ, it is not probable we shall please all men;
for there are those who with all their profession of his religion,
are nevertheless in heart enemies of the cross;
they cannot bear the foolishness of his gospel,
and it is not proper that such should be fed with food
that gratifies their vain and superficial minds.
But the unity of the true Seed, those who are acquainted with the afflictions of Joseph,
is truly desirable and this, I doubt not, thou wilt be favored with.

It is very difficult to form a correct judgment of the
state of the church in England without being there;
but from what we hear, and from what we know of the visitors to this country,
it is evident there is a difference in the tribes.
A class who profess much head knowledge with some experience,
and another who are less concerned about that which is
gathered by the wisdom and talents of man,
and more deeply engaged to descend into Jordan, where they may, from season to season,
witness the washings of regeneration and the renewings of the Holy Spirit,
by which they are made quick of understanding in the Lord's fear,
and prepared to receive and communicate the language of the Spirit unto the churches.
To meet with such as these,
and to mingle with them in the fellowship of the Gospel of Christ,
which is often the fellowship of suffering, is truly strengthening, and indeed,
though seemingly paradoxical, it is cheering.
Those who know much and whose time seems always ready for doing,
have a strong aversion to the doctrine of suffering--they do
not like to look on what is called the gloomy side,
but are in danger of compassing themselves with sparks of their own kindling,
the end of which will be sorrow.
To the traveller in the Lord's cause, it is however a consoling reflection,
that help is laid on one that is mighty; who can preserve in heights,
and sustain in depths, and mercifully furnishes, as he is waited upon,
with wisdom and strength from his sanctuary,
to enable him to steer through the various difficulties which surround him,
and to set up stones of memorial that hitherto the Lord hath helped him.

Fellow-pilgrims, particularly those employed in the same work,
cannot but desire for each other,
that they may in all their goings forth be thus favored,
that the Great Name may be honored and exalted,
and the answer of sweet peace be poured into their bosoms,
when the allotted labor is accomplished.
That this may be thy experience is our affectionate trust and desire,
as we doubt not it would be thy prayer for us under similar circumstances.

According to thy request, I wrote to thy wife informing her of thy letter to us,
thy health and comfortable getting along;
and held up to her view the standing ordinance in Israel,
that those that remain with the stuff, faithful in their allotment,
were to participate in the spoils, equally with them who went to the battle.
After visiting the meetings of Burlington and Shrewsbury and Rahway Quarter,
I went into Bucks in the Ninth Month last, and was at the Falls Meeting, where I saw her.
She appeared to be in good health,
and told me she had then recently had letters from thee.

I was at all the meetings in your Quarter,
which being attended by few others than the members, were small, except the Falls.
In all of them are to be found some exercised Friends, who are the salt, which,
through divine mercy, preserves the body; otherwise,
the external appearance furnishes but little to cheer with the
hope of a succession in the church in some parts.
Upon these the weight of exercise on account of others and the cause at large must fall,
and there seems no safe alternative but to give themselves up cheerfully to
spend and be spent for the sake of our poor shattered Society.

Our meetings are held in quiet, for which we have cause to be thankful;
but the great want of religious fervor makes them at times very trying.
Ease and prosperity seem to be the bane of religion.
One to his farm, another to his merchandise,
and others to their worldly comforts and delights,
lessens the number of laborers for the springing up of the water of life,
and throws an undue weight upon others,
who often feel greatly discouraged with the little evidence of
fruits proportionate to the labor bestowed upon such,
and the trials we have just emerged from.
We endeavor to keep hold of the hope that brighter days are ahead, but how far,
seems often wrapt in much uncertainty.
Times and seasons are in the Lord's hand,
and he can cause light to break forth from obscurity,
and darkness to become as the noon-day.
For the cause sake, and for the children, and those who may be looking towards Zion,
one cannot but desire that the brightness of the everlasting light
might shine forth more conspicuously and availingly amongst us.

My wife desires me to present her love and say thou hast her wishes for thy
preservation and safe return.--We shall be glad to hear from thee again.

[.signed-section-closing]
From thy affectionate friend,

[.signed-section-signature]
William Evans
