== Chapter XIII.

[.chapter-synopsis]
* Attends Abington and Haddonfield Quarterly Meetings, and Baltimore Yearly Meeting
* Visits the Families of Friends in Bucks and Abington Quarterly Meetings
* Holds Meetings with the Inmates of the County Poor-Houses in New Jersey; Remarks Thereon
* Visits Friends and Others in the Northern and Western Parts of New York Yearly Meeting, and in Ohio
* Letter from B. W. Ladd
* Religious Engagements at and Near Home
* Incident Connected with a Visit of Christopher Healy to the Yearly Meeting of Women Friends in New York
* Letter of Joseph Edgerton

In the Tenth Month of this year, 1838,
Christopher Healy attended the Quarterly Meetings of Abington and Haddonfield;
and the Yearly Meeting of Baltimore; of which last he notes,
that owing to unsoundness in the faith and doctrines of
our Society in some individuals present,
it was a trying meeting.
He attended some meetings going and returning, and got home with the penny of peace.
The diary resumed:--

In the Twelfth Month of the same year,
I felt my mind drawn to make a visit to the families of
Friends belonging to Bucks and Abington Quarterly Meetings.
I was favored to perform this arduous service to the peace of my own mind;
and from what appeared, to the comfort of the visited.
May the Lord have the glory and praise of his own works!
After returning home,
my mind was brought into deep sympathy and tender feeling with the poor.
And as I dwelt under this humbling exercise of mind,
it opened in the Truth that it would be my duty to make a religious visit to the
stewards and inmates of the county poor-houses in the State of New Jersey.
With my kind friend and elder James Moon, of our Monthly Meeting, in Sixth Month, 1839,
I performed the same to satisfaction.
I am not able to express to the full the feelings which I had in this visit.
The spectacle presented at some of these houses was, I think,
more reaching than the greatest sermon that I ever heard;
and my soul was humbled before the Lord.
I often said in my heart, how many there are who do not rightly prize their blessings,
and perhaps could not until deprived of them!
Some of these poor afflicted ones had no doubt been the means of their own distress,
but who now could not help themselves.
How my heart mourned for them.
There were some whose hearts were made glad while sitting in these meetings.
With these we rejoiced together.
The language of such at heart seemed to be,
keep me from murmuring on account of my afflictions.
Oh!
I did remember many times in these meetings, the language of David:
"`Before I was afflicted, I went astray: but now, +++[+++through afflictions],
have I kept thy word.`"

Our dear friend seems not to have been allowed to remain long at home.
He could no doubt adopt the language, in his measure, of the dear Master:
"`My meat is to do the will of Him that sent me.`"
Feeling his mind drawn in gospel love,
to visit Friends and those not of our religious Society in the
northern and western parts of New York Yearly Meeting,
and in the State of Ohio, he, in the Sixth Month, 1840, took leave of his family,
having for companion his dear friend William Hilles, of Frankford;
and got the first day to the house of his friend Joseph Shotwell, at Rahway.
The next day, being the first of the week, and general notice being given,
many not of our Society came together.
Christopher Healy writes: "`It was a large and good meeting.`"

There does not seem to be much to extract from the account left of this visit,
save the following memorandum:--

The man that I discoursed with,^
footnote:[See previous visit to New York and Canada.]
when here on a former visit, came to two of our meetings.
He had left the Society, taking a number of followers with him.
It appears by his going to and fro, as though he knew not what to do, nor where to stay.
Such wandering stars must feel themselves left in darkness.
May the Lord have mercy on them, and bring them into the Garden enclosed,
if consistent with his blessed will.
May they thus know Him as their Shepherd, to lead and feed them,
before they are called from works to rewards.

While Christopher Healy was out on this visit, the following letter from B. W. Ladd,
was received by his wife:--

[.signed-section-context-open]
Smithfield, Ohio, Eighth Month, 26th, 1840.

[.salutation]
Dear Friend,

We have had with us several days and nights,
the acceptable company of thy dear Christopher, and his agreeable companion,
William Hilles.
They left here yesterday in good health for Stillwater Quarterly Meeting,
which occurs about a week hence; taking meetings in their way.
After that meeting, they have one day only to travel to Mount Pleasant,
until our Yearly Meeting commences.
From appearances we are to have with us an unusually large
number of ministering Friends from other Yearly Meetings,
some of whom have already arrived.
But it is not numbers we want so much, as those of the right kind.

It has been a satisfaction and comfort to me,
and I doubt not to many other Friends hereaway,
to find that thy husband and his companion belong to the old school.
I mean,
are those who are content with the doctrines of the gospel as they were unfolded by
the Light of Truth to our worthy predecessors in religious profession.
Well would it have been for us, if we as a Society had endeavored,
in the obedience of faith, to mind the same thing and to speak the same language.
For want of this,
there has of latter years been much shaking and unsettlement within our borders;
and some bright instruments, not keeping upon the watch,
and relying singly upon Him who declared to his immediate followers, '`without me,
ye can do nothing,`' have quite fallen from the good condition
which they once happily enjoyed in the church of Christ;
and others by listening to the tempter, have come to great loss.
Our trials in this way have been very great, and I much fear they are not yet over.
Possibly thy dear husband may be instrumental in the Lord`'s hand,
in helping some who once were as bone of our bone, out of their present crippled state.
The way to the kingdom was declared by our blessed Lord to be narrow.
Our dear forefathers in the truth found it so, when they renounced the ways, worships,
customs, and fashions of the world; and the true Quaker, I believe,
will ever find it safest to follow their footsteps--in other words to
follow them as they in faithfulness and much dedication,
endeavored to follow Christ.
But this must be in the way of the cross--the only way to the crown.

It has fallen to my lot to be at several meetings with thy dear husband,
and was pleased to find, after an interval of twenty-two years,
that his bow abides in strength--his ministry being in
demonstration of the Spirit and of power.
I consider it a precious privilege to feel with
our brethren and sisters the unity of the Spirit;
it is indeed like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard, that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion:
for there the Lord commanded the blessing, even life for evermore.

[.signed-section-closing]
In affectionate love to thee and thine,

[.signed-section-signature]
Benj. W. Ladd

P+++.+++ S. I might have said something to thee in regard to the great sacrifice which at this,
as well as at many other times,
thou hast made in yielding up thy dear husband to the Master`'s service.
But thou well knowest, dear friend, where to look for thy reward.
I trust in due season, and perhaps before very long,
he will be restored to thee with the reward of peace,
in which thou wilt be made a rich partaker.

[.signed-section-signature]
B+++.+++ W. L.

Returning from Ohio, Christopher Healy says: "`I remained at and about home,
except attending many of the meetings within the limits of our Yearly Meeting,
as well as many appointed ones for those not of our Society;
much to the relief of my mind.`"

The following interesting circumstance was related by Christopher Healy,
upon one of his visits to Philadelphia, to a Friend of that city.
There may be too much preaching as well as too little;
and it is only as the Urim and Thummim of those called to minister in holy things,
is with the Holy One, and they, through the obedience which is of faith,
are made quick of understanding in His holy fear,
that it can be expected they will accept and carry out in consistent practice,
the precept of the Psalmist: "`Open thou my lips,
and my mouth shall show forth thy praise.`"
For ever true, and ever to be heeded by the anointed minister,
are the Savior`'s gracious words: "`It is not ye that speak,
but the Spirit of your Father, which speaketh in you.`"
The service of Christopher Healy in means and end was, to say the least, striking;
and is as follows:--

Upon one of his visits to New York Yearly Meeting,
Cliristopher laid a concern before the Men`'s Meeting to visit that of the Women`'s,
when Willett Hicks and some others, did not approve of it.
But though his prospect was at first opposed by those persons,
the meeting finally united with it, and James Mott was appointed to accompany him,
and they went.
After being in the women`'s apartment about fifteen minutes,
James Mott said '`Time is precious.`' Christopher sat perhaps five minutes longer,
and then rose, saying that a concern had attended his mind to visit this meeting,
without having anything given him; and now he had nothing in charge for them.
As soon as he sat down, that mother in Israel, Willits,
expressed her great satisfaction with his faithfulness
in attending to the intimation of duty,
and being circumscribed by it.
Some other valuable Friends expressed their
unity with him for keeping within holy limits,
till Christopher said he was afraid they would spoil it all.
Next day Willett Hicks said to him, '`Before thou went in, the women Friends say,
they could do no business for the quantity of preaching that was going on,
but thou knocked them stone dead,
and the meeting afterwards got on comfortably,`' or words to this effect.
Christopher added, that he was never better paid for a visit than he was for that.
What an instructive lesson, to attend to manifested duty, in simple obedience,
and leave results.`"

The subjoined letter from his friend J. Edgerton,
was received by Christopher Healy in the year 1841:

[.signed-section-context-open]
Near Barnesville, Belmont Co., Ohio,

[.signed-section-context-open]
Fourth Month 4th, 1841.

[.salutation]
Dear Friend Christopher Healy,

In near and dear affection I address thee,
and may acknowledge the receipt of thy very acceptable letter of the Twelfth Month last,
which was instructive; and I can heartily respond to what thou writes,
that the members of the spiritual house rejoice
to hear of each other`'s walking in the Truth;
for however widely they may be scattered over the earth,
they are brought nigh in the covenant of life,
and partake together not only of the afflictions of the gospel,
which the living members of the body of Christ have to experience,
but also those consolations which are at his right hand.
I doubt not that the living,
faithful followers of the Lamb in every part of the heritage,
travail for the welfare of Zion, and the enlargement of her borders; and,
notwithstanding many discouragements at times appear,
as they keep inward and fervent in spirit,
these will be favored to know what their place and duty are,
whether in silent exercise and prayer,
or to be more actively engaged in this great cause.
And we have the best authority for believing
that such a state of mental breathing unto Him,
who is Head over all things unto His church, will not fail of a due regard.

I feel much for my dear friends in various parts, who are deeply tried,
and at times may be ready to cry out, The Lord hath forsaken me,
and my Lord hath forgotten me.`' The subsequent language may,
through divine mercy be sweetly applied: '`Can a woman forget her suckling child,
that she should not have compassion on her son? yea, they may forget,
yet will I not forget thee.
Behold, I have graven thee upon the palms of my hands;
thy walls are continually before me.`' My faith is at
this time unshaken in the Arm of Israel`'s God,
that was so wonderfully manifest in the gathering together of this people: as well as,
from age to age, to raise up and preserve a remnant upon the same eternal Foundation.
And having brought us thus far.
He will not leave nor forsake.
For the mountains shall depart, and the hills be removed;
but my kindness shall not depart from thee,
neither shall the covenant of my peace be removed,
saith the Lord that hath mercy on thee.`'

I conclude; my dear wife uniting with me in love to thee, and thy dear wife and children;
and remain, in the fellowship of the Gospel, thy friend,

[.signed-section-signature]
Joseph Edgerton
