== Chapter XVI.

[.chapter-synopsis]
* Appoints Public Meetings in Several of the New England States

At a Monthly Meeting, held Fifth Month, 1850, Christopher Healy expressed a concern,
and received its full concurrence and encouragement to appoint some public meetings
with those not of our religious Society in several of the New England States.

This concluding engagement seemed like the evening sacrifice.
In the course of it he had forty-seven meetings,
many of them being held in places for worship belonging to Methodists,
Baptists and other denominations;
and his gospel labors were said to have been remarkably owned by his gracious Master.
These visits are all represented as being to the satisfaction
and peace of his own mind.--And divers testimonials were also
given him of the sweet unity and fellowship,
and encouragement of Friends, where his lot had been cast.

In the performance of this visit, Christopher was accompanied by his wife Sarah M. Healy,
an elder, and also by George W. Brown, a Friend of his own neighborhood.
from whose memoranda the following account has been taken; both had certificates,
suitable to the occasion, from the Monthly Meeting of which they were members.

In the progress of this religious visit, Christopher attended forty-seven meetings,
to all of which public invitation had been extended.
He also had considerable service in a more private way, in companies, in families,
with individuals, in conversations;
and received much kindness and favor from the
people generally amongst whom his lot was cast.

They left home on the morning of the 20th of Sixth Month, 1850,
and were received at New York City by one of Christopher`'s nephews,
who conducted them to his own dwelling, where Christopher met with two of his children,
a son and daughter by his former marriage.

At five o`'clock in the afternoon, went aboard a steamer bound for Stonington,
a hundred and fifteen miles distant.
The evening was spent in one of the spacious rooms of the steamer;
and it proved to be an interesting season.
Christopher entered into a conversation with a man from Boston, and as they proceeded,
others gathered around them,
until the number amounted to a large proportion of the numerous passengers.
About five at times took part in the subjects introduced,
and our dear friend was favored to answer their inquiries and suggestions discreetly,
and to address suitable counsel and admonition to the company collectively.
The feelings of the people were evidently enlisted,
and expressions of satisfaction and approbation were heard from several individuals.
This Opportunity lasted about two hours,
and was a further evidence of the religious solicitude which Christopher had
so long manifested for the best welfare of those not of our Society,
of the peculiar grasp which he secured upon the minds of many of these,
and of his extraordinary faculty for interesting their thoughts and feelings.

Sixth Month, 21st.--Took passage by railway for Westerly,
and found kind friends and hospitable entertainment there.
At this place Christopher met with John Wilbur, one of his ancient and life-long friends.
The greeting between the two aged patriarchs was cordial.
They had been friends in early life,
and that friendship had been cemented by long years of gospel labor and fellowship,
and both were now tottering over the grave.
A meeting at Christopher`'s request was appointed
to be held the next afternoon at four o`'clock.

Sixth Month, 22nd.--The appointed meeting proved to be a favored time,
being largely attended.

Sixth Month, 23rd.--First-day; attended meeting at Hopkinton; the morning was wet,
and the meeting perhaps smaller in consequence; but a considerable number attended.
A meeting had been appointed to be held in a school-house, one and a-half miles distant,
in the State of Connecticut, at five o`'clock in the afternoon.
This building stands on the opposite side of the road
from the site of the old one (now demolished),
where Christopher received school instruction in his youthful days,
and had taught school for several years.
His company arrived before the conclusion of the meeting of Seventh-Day Baptists,
there assembled,
and remained on the outside of the house until the breaking up of the congregation,
when, after a short respite, the people again took their seats,
and several others coming in, a large meeting assembled.
A solemnity soon spread over them,
and Christopher was moved to administer word and doctrine, exhortation and reproof,
in the demonstration of the Spirit and with power.
He stood at least one and three quarter hours,
and taking into consideration the length of time most of the audience
had been sitting previous to the commencement of our meeting,
it was admirable to see the quiet and order that prevailed.
The interest and solemnity continued throughout, and the opportunity closed comfortably.
Several of Christopher`'s scholars and old acquaintances came around him after meeting,
and gave him the hand of friendship, as did also the two Baptist ministers in attendance.

Sixth Month,
24th.--Arrangements had been perfected to hold an appointed
meeting in the vestry of a Calvin Baptist meetinghouse,
and information was spread accordingly through the factories and schools.
This place of worship is located at Bushville, between two manufacturing villages,
each half a mile distant.
Thither the company repaired at the hour appointed, accompanied by some of their friends,
but not a solitary individual had arrived, and the door of the house was locked.
At length the key was produced,
and information that way did not open to suspend
operations in the factories until the usual time,
which was after sunset; but that the people would convene as soon as possible afterwards.
The door was unlocked, and about half-past eight o`'clock a large company assembled,
entering the room in an orderly manner, and sitting very quietly.
A solemnity soon spread over them,
and Christopher was drawn forth in testimony and counsel,
which continued about one and a-half hours.
It was not so much a doctrinal sermon as a persuasive exhortation,
and particularly adapted to those young in years.
This opportunity was manifestly owned by Israel`'s Shepherd,
gospel love and power distilled as the dew, and as the gentle rain upon the tender plant,
and was apparently received and relished with much cordiality.
The meeting was appointed to be held at seven, and it closed about ten o`'clock.
One of the company proposed paying for the lights, but the answer was, "`No,
you have nothing to pay; we are thankful for the meeting.`"
Doubtless,
there were hearts clothed with reverent gratitude for
the peculiar favors vouchsafed this day.

Several appointed meetings were held to satisfaction in
the neighborhood of East Greenwich,
Rhode Island, where Christopher Healy was well known to the inhabitants.

One of these, held Sixth Month 30th, was at a Baptist place of worship,
where Christopher had formerly held several favored meetings,
and to which he appeared to feel an unusual drawing at this time.
The gathering proved large.
Quiet prevailed, and a solemnity soon spread as a canopy over them;
under which precious covering Christopher arose and handed forth doctrine, reproof,
instruction in righteousness and encouragement.
The hearts of the people were contrited and solemnized together,
and somewhat of the baptism of the Spirit was felt amongst them.

A meeting was appointed Seventh Month, 2nd, to be held at the Methodist place of worship,
in Fiskville, at three o`'clock in the afternoon.
After the meeting they stopped at the house of an aged physician,
an old acquaintance of Christopher`'s. He was feeble, chiefly confined to his bed,
and appeared to be drawing near the close of life.
He was sensible of his situation, and looked forward to his dissolution with composure,
testifying that the Lord was gracious to him.
As the company sat by his bedside,
he asked that they might have a religious opportunity together,
and those present gathered into stillness.
After a time of silent waiting,
Christopher was drawn forth in exercise of soul on his account, which, doubtless,
was comforting to the aged sufferer.
It proved a heart tendering season,
and the baptizing influence of heavenly love and power was felt amongst them.

On their northward journey they passed, near Providence,
the residence of the late venerable Moses Brown,
a Friend of great possessions and large benevolence,
yet his dwelling was neither large nor ostentatious.
They also passed the plantation where that eminent minister,
Job Scott resided, previous to his embarkation for England; and reached Fall River,
Massachusetts, on the 5th of Seventh Month.
Here, on First-day morning.
Seventh Month 7th, they attended Friends`' meeting.
An invitation to the public had been extensively spread, many attended,
and through the condescending goodness of the Head of the Church,
who promised to be with those gathered together in his name,
it proved a solemnizing season--something like
the baptism of the one spirit into the one body.
Words flowed freely, accompanied with gospel life and power, and he that sowed,
and some that reaped, rejoiced together.
The afternoon meeting at three o`'clock, was larger than that in the morning.
In it Christopher labored in the authority of truth.
It was a memorable season, and one not soon to be forgotten by some present.

Seventh Month 10th.--At North Berwick, Maine,
attended a meeting appointed to be held in the Baptist meetinghouse;
it proved large and favored.
Christopher labored honestly, and some plain truths were spoken,
especially in reference to forms and ceremonies, and qualification for the ministry.
A part of his testimony was somewhat sharp; but apparently it was well received,
and many expressed satisfaction with the meeting.

Seventh Month 11th.--Attended Friends`' meeting at North Berwick,
and Christopher had considerable service by way of exhortation and counsel.
Toward the conclusion he again arose, and, in sympathy with this little company,
who had passed through many tribulations and anxieties in
endeavoring to guard the ancient faith of the Society,
and in sustaining its order and discipline;
extended comfort and encouragement to those who truly mourn in Zion.

Seventh Month 12th.--Left North Berwick this morning,
rode thirteen miles over a pleasant, undulating country to the village of Kennebunk,
and received kind entertainment in a family of Friends.
A meeting had been appointed to be held at their dwelling,
at three o clock in the afternoon, and the usual invitation had been spread.
At the time appointed a considerable number of the neighboring people assembled.
Christopher was led to distribute doctrine, reproof and instruction in righteousness,
and as his testimony was continued,
an increasing solemnity spread over the company--oil was poured into wounds,
the sincere-hearted encouraged,
and the meeting ended under the solemnizing and cementing influence of heavenly love.
In the evening, several beside their own little company being present,
Christopher was very interesting in conversation;
and as the hour of parting for the night drew on,
he testified that he then realized some of the prospects which
had attended his mind before he left his own home.
The Friends assembled were tenderly affected,
and somewhat of that unity of spirit and bond of peace, which is not of man,
nor of the will of man, but by Divine grace and power, was felt,
binding the hearts of some of the company together in a
measure of that life in which those of true and living faith
are sometimes permitted to know and greet each other.
Doubtless,
some were present who were enabled to thank their Heavenly helper for his many favors,
and to take courage.

After some further labor in Maine, the travellers journeyed southward,
holding several meetings,
and having acceptable religious service in the families they visited.
It was with much interest they noted at Boston,
the spot where William Leddra and others of our early Friends laid down
their lives for their faithful obedience to their Lord and Savior,
departing from this world with the glorious assurance of a happy immortality.
As they passed the meetinghouse where Comfort Collins attended meeting many years ago,
the remembrance of this faithful minister was brought freshly before them,
as an instructive instance of the efficacy of Divine grace.
She had been faithful in her day and generation, and lived to a great age.
Her mental faculties became so far impaired that she
did not even recollect that she ever had a husband,
but was still mercifully permitted to retain the savor of spiritual life,
and even when near the end of her lengthened pilgrimage upon earth,
was qualified to speak of her many mercies, and to exhort her friends in living,
impressive and instructive testimony.

Seventh Month 21st.--First-day.
Attended Friends`' meeting at Nantucket, where a large assemblage collected;
under a precious covering Christopher arose,
and delivered that which was given him for the people,
and it is trusted that many minds were instructed, and many hearts comforted.
The afternoon meeting was held at five o`'clock,
and it was estimated that over six hundred were in attendance.
Stillness soon prevailed throughout this large assembly,
and it was believed that many were truly gathered into the silence of all flesh,
and felt the precious influence of the Heavenly Father`'s love to extend to them,
solemnizing their feelings and increasing their faith.
Our dear friend was raised upon his feet,
and delivered a large testimony in gospel life and authority;
the mourners in Zion were comforted; the fearful in heart were encouraged;
the unfaithful were warned; the lukewarm were aroused;
and the wanderers were invited to return.
His testimony was somewhat close against those who take up carnal weapons,
and against those who preach for hire and divine for money;
but the power of truth reigned over all opposition,
and the meeting closed under the prevalence of solemn and contrited feelings,
to the praise of the great Master of assemblies,
who evidently had owned it and magnified himself therein.

After leaving Nantucket, Christopher Healy held a number of meetings in New Bedford,
Fall River, Newport and other places in that section of country.
In these his testimony was often close and plain,
clearly pointing out their withered condition to
those who wandered from the fold of Christ;
yet being delivered in the authority and with the love of the gospel,
and mingled with encouragement for those whose faces were turned Zionwards,
they were generally acceptable.
At one of these meetings, held in a Methodist meetinghouse,
where Christopher had been led to criticize some of the
practices of other professors of Christianity,
the minister who usually officiated at the place remarked,
that he would be glad if their house could often be occupied in that way.
Near the conclusion of his account of this visit, his companion observed,
after alluding to the Christian boldness which
had marked the public labors of our friend,
"`Apparently his gospel labors have been very generally, and perhaps universally,
well received, much satisfaction there with has been expressed,
and we do not find that he offended any.
He has been divinely assisted in his goings forth, and we, his companions,
have been comforted in bearing him company.`"

The last of the meetings held on this journey was held at Westerly, Rhode Island,
Eighth Month 18th. The house was crowded, but the audience was quiet and attentive,
Christopher was again clothed with gospel life and power,
and handed forth that which was given him to distribute in right authority.
Several ministers of other denominations were present,
and although some plain and close testimony respecting hireling ministry,
and to the call to the ministry, went forth to all those whom it might concern,
yet it apparently was well received, and may, in the cool of the day,
have been remembered,
to the instruction in righteousness of some who were present on the interesting occasion.

Eighth Month 20th.--They arrived safely at their own homes.
Two months had been occupied in the performance of the visit,
and thirteen hundred miles had been traversed.
Christopher Healy brought home with him several certificates
of the unity of Friends with his labors during this visit.

After Christopher Healy returned from his religious visit to New England,
the last distant field of his gospel labors, bringing sheaves of peace with him,
and appreciating the favor of a safe return to his comfortable home,
he continued diligent in the attendance of the religious
meetings for worship and discipline of which he was a member.
He visited a neighboring Quarterly Meeting,
received his friends cordially at his own dwelling, and made several social visits.

Christopher Healy, as these minutes, with the whole of his memoranda, show,
was called to labor extensively in the cause of his dear Master,
whom he ever delighted to honor:
his meat and his drink being--in the expressive language of
conduct--to follow in the obedience which is of faith,
the undeceiving Light of Life.
And for others, the great desire of his heart appeared to be,
to bring them to Christ Jesus,--the ever-living and redeeming power--the
inexhaustible fountain of eternal excellency--the foundation of many generations.

In his ministry,
and in his conversation--in principle and practice--he
was engaged to uphold with faithfulness,
simplicity and zeal, the primitive doctrines of our beloved Society,
which he had early espoused for their purity,
and because of his love to their divine original.
He often dwelt upon our fallen and lost condition as children of the first Adam,
with the gradual and severe,
yet indispensable cleansing operation of that baptism which is
declared to be with the Holy Ghost and with fire;
as being that alone which can purify the soul from every defilement,
and restore it to a state of reconciliation and peace with God.
This inward work--the leavening and thoroughly changing power
of Christ`'s Holy Spirit received and cooperated with in the
heart--was much the theme of his exhortations and ministry.
So that truly may it be said of him,
that in his gospel labors both in public and in the more private circle,
he preached not himself, but Christ Jesus the Lord.
Thus Sarah (Lynes) Grubb, in one of her letters "`to a young Friend,`" writes:
"`Just now I recall to mind that Christopher Healy, from America,
told us in the Select Yearly Meeting (London), in a very impressive manner,
to '`let nothing move us from our steadfastness in Christ Jesus.`'`"

An outline of another discourse of his follows, as reported by a Friend in attendance,
at an appointed meeting at Germantown, Seventh Month, 12th, 1846. He arose,
with expressing his thankfulness that he knew and valued the Holy Scriptures,
which were "`profitable for doctrine, for reproof, for correction,
for instruction in righteousness: that the man of God may be perfect,
thoroughly furnished unto all good works;`" but adverted to the great
necessity there was that we should read them aright and understandingly.
He said he had the account of the transfiguration of the
blessed Savior brought to his remembrance this afternoon;
and he repeated the interesting incidents of the
account as given by the apostle:--when Peter said,
"`It is good for us to be here,`" and "`let us build three tabernacles,`" etc.
Christopher thought he was influenced by the Holy Spirit,
but he did not himself know why he thus spoke; saying,
"`Oh! how beautiful the instruction conveyed.`"
On the different portions of the account he very interestingly commented,
in his peculiar and striking manner: Moses, representing the Law; Elias,
whom our Savior himself declared to be John the Baptist, the forerunner,
typifying the preparatory dispensation with the elementary baptism;
and Christ the Promise--were here together on the Mount,
and a bright cloud overshadowed them.
The voice was heard from the cloud; not, hear them--Moses and Elias--but,
"`This is my beloved Son, hear ye him.`"
When the disciples heard it, they fell on their faces and were sore afraid.
And when they lifted up their eyes, they saw no man save Jesus only.
The representatives of the preceding dispensations were gone,
with their rituals and observances; and Christ only remained.
The purer dispensation to which the others led, was brought in.

He showed how, under the Law, it was said, "`Thou shalt love thy neighbor,
and hate thine enemy:`" but Christ declared, "`I say unto you, love your enemies.`"--See,
friends, what a change!
The very root of wars and fightings was to be destroyed.
Here Christopher briefly showed the incompatibility of war with Christianity,
either offensive or defensive.
Some might say, why if you don`'t fight, the enemy might come and overpower us.
The Jews opposed the spread of right things upon the same ground, saying:
"`If we let this man alone, all men will believe on him,
and the Romans will come and take away both our place and nation.`"

He commented upon the offices of John the Baptist,
"`the voice of one crying in the wilderness,`" and his elementary baptism.
He said he thought some people did not rightly understand the Savior`'s words,
where he said, "`Among them that are born of women,
there hath not arisen a greater than John the Baptist; notwithstanding,
he that is least in the kingdom of heaven is greater than he.`"
He did not mean to shut him out as a saint from the kingdom.
His work is accomplished, and he has entered into rest.
But the least child in the kingdom was greater than he.
John saw the fading of the legal dispensation, and warned the Jews no more to say,
"`We have Abraham to our father`" and he saw Christ`'s office and proclaimed,
"`Behold the Lamb of God.`"
"`I indeed baptize you with water, but there standeth one among you, whom ye know not;
He shall baptize you with the Holy Ghost and fire.`"
Ah! they did not know Christ; they would not receive him!
How many are there now in the same case!
Christopher then said he did not know that there were any here
who thought water baptism necessary to salvation.
But what was given him, he had to speak.

He proceeded to show the insufficiency of putting away the filth of the flesh,
and to testify concerning the baptism of the Holy Ghost and its purifying,
heart-changing effects, which were necessary to conversion and salvation.
Here he quoted the language, "`He that believeth and is baptized shall be saved.`"
This was not an historical belief--a mere confession of
the name of Christ--but an operative one,
having the answer of a good conscience.--The text did not say,
has believed and has been baptized, but it is in the present tense,
"`believeth and is baptized.`"
They might have known better, and then fallen away.--He knew there were many,
up and down, who held, "`once in grace,
always in grace,`" but this was totally at variance with our blessed Savior`'s
parable of the vine and the branches "`As the branch cannot bear fruit of itself,
except it abide in the vine, no more can ye, except ye abide in me.
I am the Vine, ye are the branches; he that abideth in me, and I in him,
the same bringeth forth much fruit; for without me ye can do nothing.
If a man abide not in me, he is east forth as a branch, and is withered;
and men gather them, and cast them into the fire, and they are burned!`"
Now mark, friends, they had been engrafted into the vine, Christ Jesus,
and drew nourishment from it--had been in grace--but they had become withered,
fallen away, and fruitless--lost their state of grace.
The same effect follows unfaithfulness now.
When those who have known something of the Truth, fall away from it,
the men of this world gather them unto its associations, and its mixtures,
and confusions, and sad is their condition--even that of the unfruitful branches.
A feeling address was here briefly made to some who had known better days;
upon whom dryness and withering had crept;
that they might endeavor to know the holy circulation of the sap of life renewed.

He referred to the so-called "`ordinances`" the bread and wine, etc.,
and quoted the passages, "`The bread of God is He which cometh down from heaven,
and giveth life unto the world.`"
"`I am the bread of life,`" etc., and showed that this was no outward bread,
and that down to this very day his true disciples feed on him; He was their meat,
their sustenance; and He was also their drink, their refreshment.
You remember, most of you, what he said to the woman of Samaria, at Jacob`'s well.
Have not most of you read the account? (Though I do fear you don`'t read the
Scriptures as much as you ought to.) And He is still in his faithful followers,
a well of water springing up into everlasting life.

He addressed parents, particularly those in younger life,
with many little children around them, desiring them to come to Christ themselves,
that they might have something to give their dear children.
He giveth liberally and upbraideth not.
