== Chapter XVII.

[.chapter-synopsis]
* Notice of Some of His Religious Communications, and Incidents Related by Him

The following short extracts of communications by Christopher Healy,
at his own meeting at several different times, were taken by a Friend present,
who informs that they were all delivered either in or subsequent to the year 1842.

The first communication by our friend, recorded here, was in supplication.
His sister in the truth, and with whom he had doubtless often taken sweet counsel,
Elizabeth Pitfield, was also present; who,
after exhorting those young in years not to trifle with
Omnipotence in rejecting his offers of grace and mercy,
but to be faithful to all of his requirings;
reminding them of the many prayers and tears that had
been offered for the children of godly parents,
was followed by Christopher Healy on the bended knee;
who supplicated on behalf of the same class, as too ready to take wing and fly away;
being loath to give up the ways of the world.
He interceded that the hearts of these might be opened,
and that all might turn unto the Lord, that so they who sow, and they who reap,
might rejoice together.

The discourses to which allusion has been more particularly made, follow:--

"`In our meeting to-day,
our beloved friend Christopher Healy was led to hold forth persuasive counsel,
reciting the words of the Psalmist: 'Oh, my soul, look thou unto the Lord,
for my expectation is from Him!' He brought to view the
necessity of this being the prevailing tendency of our desires;
and without which we shall never know the excellency of silent waiting.
That there is a vast difference between those who feel poor, and weak, and unworthy,
and whose expectation is from the Lord;
and those who endeavor to worship him in their own will and wisdom,
and whose expectation is much from the poor instrument.
It is only the humble, dependent, waiting ones,
that will come to know the excellency of silent waiting.

"`In the meeting for business, our dear friend extended encouragement to us,
especially to those young Friends who came a good way to meeting.
He thought that they would never repent the sacrifices they
make for the sake of attending our religious gatherings;
and the more they give up thereto, the more they would love to attend.
Stating it as his belief,
that whether poverty or sweet peace be their portion when assembled,
they would find it good for them that they had been there.`"

"`To-day our dear friend preached a very impressive sermon,
and among much instructive testimony, said, 'The righteous shall have tribulations,
but the Lord will deliver out of them all.' Holding up to view
the necessity of having living faith in the Divine promises,
and then tribulations would be borne patiently,
and our faith will increase with our trials.
There is, he said, but one sure foundation;
but one foundation that will stand when all things else fail.
And unless we build rightly thereon we cannot be saved.
He spoke of the necessity of having faith in that Almighty Power,
which a servant of old described in this language: 'The sea saw it and fled.
Jordan was driven back.
The mountains skipped like rams, and the little hills like lambs.
What ailed thee, O thou sea, that thou fleddest? thou Jordan,
that thou wast driven back? ye mountains, that ye skipped like rams? and ye little hills,
like lambs?' This was the power that gathered our Society from
the maxims and customs of the world--from the forms and
ceremonies of a lifeless profession--from all will-worship,
and from an hireling priesthood.
And though many may fall on the right hand and on the left,
yet the faithful will be preserved;
and he believed that if all our members walked answerable to our high profession,
there would be an hundred come unto us, to where there is one now;
and we should indeed be as a city set upon a hill, that could not be hid.
Our conduct would then speak louder than words; and many would be invited by our example,
to come look upon Zion; and to behold Jerusalem a quiet habitation,
with none of its stakes broken, nor cords loosed.`"

"`Our meeting just held was an interesting season.
Our beloved friend Christopher Healy was favored to hand forth an instructive testimony,
in demonstration of the Spirit and of power; quoting the language:
'Remember now thy Creator in the days of thy youth, while the evil days come not,
nor the years draw nigh, when thou shalt say,
I have no pleasure in them,' and bringing to view the
blessed effects of obedience to the Divine will,
and the danger of putting off the day of visitation.
That we all have need of a mightier power than our own
to guide us safely to the realms of peace.
He believed that some whose faces had been turned Zionward,
felt a little discouraged because their troubles were greater now,
than when more careless about spiritual things; but he told us this was nothing new.
For while we are pursuing self-gratification,
and walking in the way that Satan would have us to go, he troubles us not,
but endeavors to make the way smooth and easy.
But when we take a stand against him, and turn our faces toward Zion,
'tis then he is aroused to vigorous action, with his assaults,
temptations and insinuations,
in order to hinder and to turn us from the way that leads to salvation.
This keeps us in a state of continual warfare against our soul's enemy.
But it is good for us.
The watch and the warfare must be maintained, and with weapons that are not carnal,
but mighty through God to the pulling down of the
strongholds--the strongholds of sin and Satan.
He had stood by the bedside of one who acknowledged
that he had despised the counsel of the Lord,
and had served Satan in almost every respect;
and he thought it was the most awful sight he had ever beheld!
The soul struggling under the just judgments of the Lord,
seemed to be in torment while yet in the body.
The poor victim had no hope of pardon and redemption,
and ended his days much in this awful condition.
Our beloved friend seemed much affected in the contemplation
of this lamentable state of human existence;
and held it up to view as a solemn warning to us.
He upheld the necessity of seeking the Lord while He may be found,
and making preparation for the solemn close before the
evil days come or the years draw nigh when we shall say,
we have no pleasure in them.
The Lord will not say to the sincere wrestling seed of Jacob,
'Seek ye my face in vain.' Oh do not any of you despise counsel.
He also intimated that there was danger of some
falling away who had made a good beginning,
and would, unless they were obedient to Divine requirings.
Our dear friend also spoke of his own experience, how he had been assailed by the enemy,
and had fled to the Lord Jesus for refuge; who pointed him to the strait and narrow way;
and as he endeavored to walk therein, had raised him up out of the miry clay,
and set his feet upon that rock, which he could declare was the Rock of Ages,
even Christ Jesus.`"

"`After a time of solemn silence, our valued friend Christopher Healy arose and stated,
that his mind had been exercised almost from his first sitting down in the meeting,
in a way comparable to our Savior's answer to those who spake of the Temple,
how it was adorned with goodly stones and gifts.
The reply was: As for these things which ye behold, the days will come,
in the which there shall not be left one stone upon another,
that shall not be thrown down.' Now, Friends,
these things must be fulfilled spiritually in us,
as much as they were fulfilled outwardly:
the glory of this world must be stained in our view; our delight in the riches,
the fashions, the customs, and whatever is worldly must be thrown down.

"`There is too much of a disposition in us to shun the cross.
We want to come to the Savior, and at the same time hold fast to the things of the world.
We are convinced that there is no better profession,
than the profession of the Society of Friends;
and we would love to become religious members,
and walk answerably to our high profession; but the cross is in the way.
We are not willing to suffer for the Savior's sake,
who himself was a man of sorrows and acquainted with grief.
He had met with many while travelling up and down through the land,
who were willing to acknowledge that Daniel's God was the only true God;
that there is no better profession than ours; and yet they would not live up thereto.

"`When the light of the Divine countenance shines upon us,
we are almost or quite persuaded to be Christians,
and resolve to live in obedience to the Divine mil;
but when the light is a little obscured, we stumble at the cross and turn away.
He queried of some present what was the cause of these things? The cross must be borne,
though it may lead us into singularity,
and to be despised and rejected by the worldly wise.
He did not mean to insinuate that we should make
ourselves disagreeable in the eves of the world,
further than to live in obedience to Divine requirings.
He had felt it, as plain as he had ever felt any thing outwardly with his hands,
that there were those present who had sustained great loss by going on from year to year,
and not sufficiently confessing their Savior before men;
and if there had been more faithfulness to their Divine Master's will,
there would have been more fathers and mothers in our Israel raised up amongst us,
to encourage others to come look upon Zion, the city of our solemnities,
not one of its stakes broken, nor cords loosed;
and they would have found Him indeed to be their Counsellor; the mighty God;
the everlasting Father; the Prince of Peace.

"`In allusion to the unalterable necessity of self-denial and the daily cross, he said,
he should not marvel so much that so few are disposed to take up the cross,
and follow the Captain of their salvation,
if their real enjoyments were abridged thereby.
But on the contrary the way of the cross is the only way to lasting peace,
and the only way in which true enjoyment is to be found even here.`"

Christopher Healy paid a visit to Friends in the neighborhood of Gwynedd,
in the summer of 1847. A family sitting during
that visit is thus described by Hannah Williams,
late of Plymouth, Pennsylvania, to Jacob and Phebe Roberts, Seventh Month 17th, 1847:--

"`He commenced with supposing we all believed that every good gift was from God;
that we had nothing but what we had received; that we were entirely dependent;
we could save neither 'body nor soul;' that faith was His gift;
if we believed there was a way to be saved, it was His gift.
So He stripped us of all things,
and we saw ourselves standing naked and alone before the great all-seeing Eye.
Here he brought in the omniscience of our great Care-taker.
His compassion for our helplessness, as we with sincere hearts looked toward him;
and when we fell short and did evil, and repented and humbled ourselves, how,
oh how He would make the dry ground of the heart springs of water;
that instead of the 'thorn' should come up the 'fir tree,' and instead of the '
briar' shall come up the 'myrtle tree:' and it shall be to the Lord for a name,
for an everlasting sign that shall not be cut off!'

"`The diligent and right attendance of all our religious meetings he encouraged;
said that though we might sometimes feel poor and low,
yet He would not send empty away those who waited for him in singleness of heart.
On the subject of unfaithfulness he said, a little unfaithfulness, and very little too,
how quickly it weighs down the scale against the little good we might have done;
concluding with, 'Oh Friends, be encouraged!
Be faithful!'`"

During the same visit in another opportunity in the same family,
Christopher Healy spoke of faith which he seemed
to think we had found to be as an anchor,
staying the mind in seasons of trials.
He then proceeded to describe a ship anchored firmly with the watch on board in a storm;
that the watch needed, in an especial manner, to mind the cable,
which was fastened to the ship and to the anchor, and held all safe.
If that parted,
the poor ship would be driven hither and thither at the mercy of the winds and the waves.
He dwelt on the importance of the watch having an eye to the cable,
to see that it did not part.
Christ Jesus was He in whom our anchor, faith, was firmly stayed.
The other part of the figure it was easy to apply;
the ship would ride out all the storms of time safely,
only let the 'watch' mind the 'cable.'

Allusion has heretofore been made in these sketches,
to Christopher Healy's conversational talent.
This, when with his friends in the private circle,
he often exercised to their entertainment and instruction.
It is said, Richard Jordan, that wise Israelite, who was also remarkable for this talent,
has stated that he felt himself as much under the Divine anointing
when pressing religious truths in a conversational or anecdotal way,
as when engaged in his public ministrations from the gallery.
Christopher Healy also often pressed close home in a lively manner,
solid and pertinent truths in his familiar and easy method of communication.
He seemed in this as well as other things,
to let his "`light shine`" by giving diligent heed to the precept of the Apostle:
"`Whether ye eat or drink, or whatsoever ye do, do all to the glory of God.`"

The following incidents, related by him at different times in companies where he was,
are inserted here, viz:--

"`Upon Christopher's visit to the Southern States, in the year 1824,
he found that Elias Hicks had commenced disseminating his unsound views,
and that a few in those parts had imbibed them.
At one place our friend attended a small Select Meeting.
There were not more than about ten present.
Christopher said something came over him that he could not get rid of,
and so he quoted the expression of the prophet: 'Shut the door,
and hold him fast at the door;
is not the sound of his master's feet behind him.
' When any one believes that there is no devil,
no evil spirit other than the natural inclinations of the human heart,
whether he is a Friend, or belongs to another denomination,
he is ready to deny the divinity of our Savior.
Christ was tempted of the devil, and he could not have been tempted by his own nature,
it must have been by an evil spirit.
Through this door +++[+++of denying the existence of a devil]
all infidel principles can come in, even till a man comes, with the fool,
to say in his heart, there is no God.'

"`After the meeting had dispersed,
his companion told him that he had heard one of the
Friends present state his opinion in these very words,
that there was no devil other than the natural inclinations of the heart.
Nothing had been said to Christopher about it, and at the time he felt the impression,
he was not aware that any present held such views.`"

"`Fourth Month 15th, 1849.--At the house of a friend, Christopher said,
'I suppose that there are few members of our religious Society now living,
who have passed through sorer trials of their faith,
or have been plunged into deeper baptisms of suffering than I have been; but,' he added,
'I can now see that it has all been for the best, and that they have been permitted,
or perhaps I may say appointed, to purify me more effectually from defilement,
and to wean me from the perishing things of this world,
and to induce me to seek for consolation where alone it can be truly found.
And lastly, that I may sympathize with, and comfort those who are under suffering,
with a little of that comfort wherewith I myself have been comforted of God.
And I do believe that it is not only my privilege, but my duty also,
to do what I can to comfort and encourage my
Friends who are under trials and afflictions,
by telling them how good Master has been to me,
not only in sustaining and supporting me under
my many und varied provings and besetments,
but in bringing me out from under them in His own appointed time;
and when He has seen that it was enough,
permitting me and enabling me to sing His praises on the banks of deliverance.
Glory be to his ever worthy name therefor!

"`I just now remember a time when I was plunged
into as deep distress as perhaps I was ever in;
and I am willing to tell thee of it,
(addressing an individual present) for thy consolation and encouragement.
I had been speaking a little in meetings from time to time, as thou hast been,
and not without doubts and reasonings from within, and opposing spirits from without,
as I suppose thou hast had to encounter.
But the cause of my then great trouble was on account
of some debts which I had left behind me unpaid,
in Rhode Island.
I knew that they ought to have been paid long before, but I had never been able to do it,
though I had worked early and late,
and denied myself almost the necessaries of life in order to do so;
yet I had not been able to procure the means.
The consideration of these things troubled me very much,
for I feared that my creditors would believe that I was dishonest,
and that I intended to cheat them out of their just dues, by refusing to pay what I owed.
Indeed, I was so much troubled about it, and got so worked up in my mind,
that I felt almost confident that a complaint
would be sent to our Monthly Meeting against me,
and I was really afraid to go to Monthly Meeting lest I should
there hear myself charged with being a dishonest man.

"`One evening in particular I was brought very low in my mind.
I seemed to have got to the very lowest spot that a poor mortal could be plunged into.
My wife had gone to bed, and was asleep, but I was afraid to go to bed, and there I sat,
or walked about, reduced almost to despair.
After a while I thought I would get my Bible,
and see if I could not find some comfort in it;
or at least if I could not divert my mind from its very distressing thoughts,
by reading in that good book.
The first passage I read did but increase my distress.
I have forgotten what it was, but it plunged me still deeper into misery;
and the further I read on, the worse I got,
so that I thought I would go distracted if I did not shut up the book.
It was then after midnight.
I put my Bible away, and concluded to go to bed,
expecting nothing else than I would toss and tumble about without sleep till morning.
But I think I was not in bed five minutes before I fell asleep;
and I seemed to awake as suddenly.
I stared around me, and it was broad day, and the sun was shining full in my face.

"`We lived then in a log cabin,
at the east end of which there was a window of six lights,
through which the sun was shining bright and clear as I ever beheld it.
I looked round the room.
There lay my wife sleeping sweetly by my side, and I could see every thing in the room,
looking as natural and in its place as usual.
I looked out of the window, and everything there seemed bright and beautiful:
the glorious sun seemed to be half way up the sky, shining with its accustomed splendor;
and there I lay in bed debating with myself whether it was really day,
with the sun half way up to the meridian,
or whether it was a vision of light that encompassed me.
But whilst I was considering this question, the light faded from my view,
and I found myself lying in my bed with the darkness of midnight around me.
I then knew that it was either a dream,
or else a vision of light from the Lord to comfort my heart,
and to bring me out of my sore distress.
And blessed be His holy name, who thus did comfort me,
and gave me at once faith to believe that He would make bare His holy Arm for my help,
and bring me out of my great and sore troubles.
Yea, the Sun of righteousness did already shine into my heart,
as the sun of this vision of light shone into my face, and lighted up the flame of hope,
giving me to believe that He would enlighten my path,
and enable me to see of the travail of my soul, and be satisfied therewith.
Being thus refreshed and comforted, I fell asleep and slept soundly till morning.

"`Next day I wrote to a Friend in Rhode Island,
and told him how distressed I had been about my debts,
assuring him that I was desirous and anxious to pay them,
but that hitherto I had been unable to do so; and I requested him to inform my creditors,
that I was striving to earn the means of paying them,
and I would send it to them as soon as I could get it, which I hoped to do before long.
I soon after received an answer, saying that I might make myself easy about my debts,
as all my creditors knew that I was an honest man,
and they were willing to wait for the money,
until I was able to pay it without distressing myself.
Times soon changed for the better with me.
I had a pretty good crop of wheat, which I sold, and I parted with some other things:
so that I collected a pretty considerable sum of money for me,
though not quite enough to pay all I owed; but I sent it to my friend C,
desiring him to divide it among my creditors.
I soon after received a letter from him, enclosing receipts in full from all my creditors.

"`So the Lord helped me out of that difficulty,
as I trust He will help thee out of thine;
for I know that He will help all his poor distressed children
and servants out of their difficulties and trials,
if they will but trust in Him, and not cast themselves down as I did,
and as the devil tried to tempt the blessed Jesus to do,
when the old deceiver quoted Scripture to accomplish his wicked purposes.
It is wrong to cast ourselves down,
and it is nearly as bad to stay down in the cellar a moment longer than we can help it.
A cellar is a cold, damp, and sickly place,
and it is equally unwholesome for body or mind.
Come up out of it as soon as thou canst, and hold fast the shield of faith;
don't cast it away, as though it had never been anointed with oil; for if thou hold on,
the Master will bring thee up out of the horrible pit, and out of the miry clay,
and set thy feet upon a rock, and establish thy goings; yea,
He will put a new song into thy mouth, even praises to our God: yea.
He will enable thee to sing a song of deliverance, even one of the holy songs of Zion,
to his praise.`"

"`A missionary among the Stockbridge Indians was
sadly given to the practice of using compliments.
Upon a certain occasion, when Christopher was surrounded by a good many Indians,
the missionary indulged himself even more than usual with him, in this way.
As Christopher felt his mind drawn to administer a little reproof, he quietly asked him,
'what he would think of a Bible,
if he should buy one that had in it Mr. Paul and Mr. Peter,
instead of simply Peter or Paul, as our common Bibles call them? Wouldst thou not say,
away with it; this is a cheat and a counterfeit: I'll have none of it,
because it is not genuine;
for I know the Holy Ghost never taught men to write so? Now if holy
men of God spake as they were moved by the Holy Ghost in old time,
as the Apostle Peter says they did,
does the same holy and heavenly Teacher lead thee and
others to speak a different language now? '

"`The missionary seemed to be very much disconcerted, but made no reply;
and the Indians nodded from one to another an assent to
the justice of the rebuke which had been administered.`"

"`After the Second Month Quarterly Meeting (Bucks),
Christopher Healy visited his ancient friend Ruth Ely.
At the time of parting he took her hand, and said, 'Farewell:
Perhaps we may meet again in mutability,
and perhaps we may not.' 'It seems lively with me,' said Ruth,
'to say to thee what two valuable Friends said at parting: one said,
'We may see each other again;' to which the other replied: 'No:
when thou comest this way again, I shall be in heaven.' Ruth added,
'I believe I am waiting.
I had thought I must go out again; but I believe I am waiting.' Christopher said,
after a pause,
'I must tell thee what I once heard a good old
Presbyterian say to one who thought he was waiting:
'There is no waiting state until the work is done!' 'Then,' said Ruth,
with great solemnity, 'I must see what remains for me to do yet.
This has been a very pleasant visit to me.
The unity that has always been between us, is not to be broken;
neither heights nor depths, nor anything in this world can separate us.'

"`After this interview, Ruth Ely paid several visits that were upon her mind,
to her own comfort, as well as to that of the visited.
She also got out once more to meeting.
When, the work being done and the waiting state attained,
she was suddenly called home to the joy of her Lord, on the 18th of Third Month, 1851,
in the eighty-third year of her age.

"`The next time Christopher went that way was to attend her funeral,
at which time he intimated he should soon follow her; and about three weeks after,
he was taken sick.`"

+++[+++The following two letters of Christopher Healy,
addressed to his lifelong friend John Wilbur,
were written at a time when unsound doctrines were
making great headway in the Society of Friends,
and many ancient principles of Quakerism were being abandoned in favor of
doctrines more suited to the wisdom and ability of the natural man.]

[.letter-heading]
From Christopher Healy To J. W.

[.signed-section-context-open]
Bucks County, Pennsylvania, 2nd of 6th mo., 1847.

[.salutation]
My very dear and much beloved friend, John Wilbur,

I received thy salutation of unfeigned love, a little while after our Yearly Meeting.
It miscarried and got to Doylestown, and lay there a long time,
but when I did receive it I was comforted, and rejoiced in spirit.
May thou, my dear brother in the Truth, be comforted, and filled with joyful hope,
for greater is He that is in thee, than he that is in the world;
this thou hast clearly proved, by thy great suffering,
for thy divine Master's and the church's sake.
May he be pleased to make bare his holy arm of power, for thy health,
both in spirituals and temporals.
I have often thought of thy dear bosom friend, how she must be tried as well as thee,
in that long and sore warfare.
May our blessed Helper be very near to strengthen you to bear up, now in your old age.
I have divers times read thy "`Narrative`" as well as some other accounts,
and I thought nothing short of Divine power
could have carried thee so remarkably through.
Thou hast heard by this time, I suppose, that our Yearly Meeting this year,
condemned the unsound writings of Joseph John Gurney, and also of Edward Ash,
and the document after our next Meeting for Sufferings, will be published.

I was taken sick last 8th month, and have not yet recovered,
so as to be able to write but very poorly; my nervous system being so affected.
This is the first writing since my sickness, but my health is middling good otherwise,
and that of my family.

Oh! my dear brother, this is a sifting time to the members of our Society.
I have believed our poor Society will yet be sifted as wheat is sifted in a sieve,
for it is declared, "`I will overturn, overturn, overturn, saith the Lord,
until he shall come whose right it is to rule and reign.`"
Our Israel is too much mixed among the people of the world.
The language of my soul is: "`come out from among them, and be ye separate,
and touch not the unclean thing, and I will save you.`"
Now my dear brother in the gospel of the dear Son of God,
be not discouraged at these trying times,
for Zion cannot come forth out of the wilderness of this world, clear as the sun,
fair as the moon, and terrible as an army with banners, leaning also on her Beloved,
until she shall arise and shake herself from the dust of the earth,
and put on her beautiful garments,
then she will arise with Him who is the Resurrection and the Life,
and because he is the bread of life, our souls shall live also.
Oh! that this blessed day might come to the church,
then will judges be restored as at the first, and counsellors as at the beginning.
I do believe this time will come, though a great falling away may take place first;
but my dear friend, a people,
a favored remnant will be preserved of the true principle and name of Quakers.

I know when I consider all the circumstances connected with the case,
that thou mayest sometimes in thy poor soul say, Israel has almost forsaken the Lord,
but my dear friend, remember the answer of the Lord was to him in the still small voice,
I have reserved seven thousand who have not bowed the knee to Baal, nor kissed his image.
I believe thou hast said many times under thy deep troubles,
as Jacob of old said concerning his dear son Joseph, "`Joseph is a fruitful bough,
even a fruitful bough by a well, whose branches run over the wall;
the archers have sorely grieved him, and shot at him, and hated him;
but his bow abode in strength, and the arms of his hands were made strong,
by the hands of the mighty God of Jacob; from thence is the shepherd,
the stone of Israel.`"
These things thou hast largely experienced,
and they will be sanctified to thee for thy salvation,
and if thou shouldst not see the desires of thy soul in this world,
if thou keepest the word of his patience, through this tribulated scene,
thou wilt witness being kept in the hour of temptation, and, by and by,
when thou art gathered among the just of all generations,
to shine forth as the sun in the kingdom of our heavenly Father,
then wilt thou receive thy blessed reward, and thy joy will be full,
and no man will take thy crown, because thou hast labored and not fainted.

So now, my dear brother, farewell, in the love of the gospel of our Lord Jesus Christ.
My dear wife sends her love to thee, and thy dear wife and family.
James and Jane Moon also send their love to thee, and so would many more,
did they know of this freedom.
In the great satisfaction and love which for many years we have had together,
and for each other, the remembrance of which now rejoices my heart, I take my leave,
and remain thy affectionate friend,

[.signed-section-signature]
Christopher Healy

[.letter-heading]
From Christopher Healy To J. W.

[.signed-section-context-open]
Lower Makefield, Bucks County, Pa., 3rd mo., 22nd, 1850.

[.salutation]
My dear friend John Wilbur,

In the love of the gospel I write unto thee to inform thee that I received
thy very acceptable letter yesterday which we read with great satisfaction,
and were comforted in feeling thee so firm in
the ancient faith once delivered to the saints.
May He who has been thy bow, and covered thy head in the day of battle,
continue with thee and renew thy strength in him whose arm is everlasting strength.
I know of no one in these latter days of trouble in our Society that
has had so deep baptisms to pass through as thou hast.
But my dear friend,
may thy soul be filled with thanksgiving and living
praises to the great Captain of our salvation,
who was never foiled in the field nor overcome in the day of battle.
Nothing but his help could have sustained thee and thy
dear friends in such times of sore conflict;
and my heart's desire and prayer to the living God is that you may hold on your way,
for I do believe the victory will be obtained if your faith fail not.
Remember the blessed declaration that the mountains flowed down at his presence.
When this scourge has sifted our poor Society enough,
he will take the work into his own hands and
show who are his friends and who are his enemies,
as he has in some measure began to do already.

Oh, my dear friend, as thou art so thoroughly converted, strengthen thy brethren;
yea speak often to them and one unto another,
and the Lord who has been your helper will hearken,
and a book of remembrance will be written before him.
Thou with myself art of the number that have stood firm for that blessed
cause which is dignified with immortality and crowned with eternal life;
hold fast the beginning of thy confidence steadfast unto the end,
that so the crown may be sure.
The time is approaching when thou as well as myself must be offered up,
and may we through watchfulness and holy help,
be enabled to adopt the language of that faithful apostle Paul:
that we have fought a good fight, have kept the faith and finished our course,
and that henceforth there is a crown laid up for us,
which the Lord the righteous Judge shall give to us at that day,
and not to us only but to all those that love his appearing.
Oh, if our poor Society had loved his appearing there never would
have been such a leaving of the ancient stepping-stones.
But my beloved friend, let us not be too much discouraged;
our heavenly Shepherd can raise up sons and daughters from the highways and hedges,
bring them into the church and qualify them for his work and service.
My mind is enlarged, but my hand fails by reason of the weakness of my nervous system.
I have not written so much as a line since I wrote to thee, until now,
so thou will excuse my short letter.
I am middling well except my nervousness; my family are also well.
Give my love to thy dear wife and to all inquiring friends.

Please to write soon that I may know how thou feels concerning that better part,
as well as how thou art in bodily health.
So I conclude in that love which shall abide,
thy brother in the gospel of the dear Son of God,

[.signed-section-signature]
Christopher Healy
