[#supplement, short="The Last Year"]
== Supplement: The Last Year of the Life of Christopher Healy

[.blurb]
=== by George Williams Brown

At the beginning of summer in the year 1850,
Christopher Healy was dwelling at his pleasant
residence in the southern part of Bucks County,
Pennsylvania.
His earthly pilgrimage had been extended to near four score years,
and the outward man was feeble; but age sat serenely upon his countenance,
and he was lively in spirit.
Surrounded by temporal comforts, and diffusing a generous hospitality,
his friends were warmly welcomed at his dwelling,
and edified by his interesting and instructive conversation.
The most of his coevals, with whom he had taken sweet counsel and walked in company,
had passed away, but his faithful wife was still spared to him.
The Monthly and Quarterly Meetings of which he was a member, had granted credentials,
leaving him at liberty to perform a religious visit to his native New England,
and appoint public meetings there as truth might open the way;
and he looked forward to the accomplishment of
this service as a probable evening sacrifice.
In the performance of this visit Christopher was accompanied by his wife S. M. H.,
an Elder, and also by Gr. W. B., a Friend, of his own neighborhood,
from whose memoranda the following account has been taken; both had certificates,
suitable to the occasion, from the monthly meeting of which they were members.

In the progress of this religious visit, Christopher attended forty-seven meetings,
to all of which public invitation had been extended.
He also had considerable service in a more private way, in companies, in families,
with individuals, in conversations;
and received much kindness and favor from the
people generally amongst whom his lot was cast.

Our little company left home on the morning of the 20th of 6th month, 1850,
and was received at New York city by one of Christopher's nephews,
who conducted us to his own dwelling, where Christopher met with two of his children,
a son and daughter by former marriage.
They manifested affectionate attachment to their father,
and he appeared to be gratified with their company;
but the son being a prominent minister amongst those
who separated from Friends in the year 1827,
was evidently a drawback upon the gratification,
as it obstructed the flow of gospel fellowship which, added to natural affection,
doubly endears children to their piously concerned parents.

At 5 o'clock in the afternoon, went aboard the steamer bound for Stonington,
115 miles distant.
Leaving this noted metropolis, the great resort and mart of the western continent,
"`checkered with all complexions of mankind, and spotted with all crimes,`" yet,
doubtless, possessing many inhabitants who are bright examples of Christian virtue,
and for the sake of such as are worthy,
the great city may be spared in the hours of peril.
Passed several benevolent institutions located upon
islands surrounded by the waters of the East River;
one of these was the accommodations for the poor of the city:
whatever appertains to suffering humanity and the welfare of souls,
appears to be interesting to Christopher,
and his observations thereon are often very instructive.
Nor were the works of the Creator's hand, the demonstrations of his power,
and the extension of his favors, passed by entirely unnoticed;
the wild and turbulent Hurlgate, the bold and picturesque banks,
the variegated and pleasing landscapes, the important and attractive water way;
the coming storm, the rushing winds, the agitated waters, the torrents of rain,
the thunder and the lightning; the lifting clouds, the radiant sunset, the beautiful sky,
the purified atmosphere, the surrounding calm, the slowly waning twilight;
and although scenes such as these,
most likely would attract but little attention from travelers generally,
yet in company with our beloved friend Christopher,
whose contemplative mind is so well qualified to draw lessons of instruction,
even from wayside and familiar objects,
and to impart them in their fulness and freshness to others,
the situation becomes interesting,
and there is evidence that he occupies a peculiar gift,
much of the value thereof becoming utilized through the
current conversations of every-day life.

The evening was spent in one of the spacious and
extravagantly furnished rooms of the Steamer,
and it proved to be an interesting season.
Christopher entered into conversation with a man from Boston, and as they proceeded,
others gathered around them,
until the number amounted to a large proportion of the numerous passengers.
About five at times took part in the subjects introduced,
and it was thought that our dear friend was favored to
answer their inquiries and suggestions discretely,
and to address suitable counsel and admonition to the company collectively.
The feelings of the people were evidently enlisted,
and expressions of satisfaction and approbation were heard from several individuals.
This opportunity lasted about two hours,
and is further evidence of the religious solicitude which Christopher has so
long manifested for the best welfare of those not of our society,
of the peculiar grasp which he secures upon the minds of many of these,
and of his extraordinary faculty for interesting their thoughts and feelings.
Arrived at Stonington about midnight,
where most of the passengers immediately left for Boston;
but we remained quietly in our floating lodgings until morning.

6th month, 21st. Took passage by railway for Westerly,
and found kind friends and hospitable entertainment there.
At this place Christopher met with John Wilbur, one of his ancient and life long friends.
The greeting between the two aged patriarchs was cordial.
They had been friends in early life,
and that friendship had been cemented by long years of gospel labor and fellowship,
and both were now tottering o'er the grave.
A meeting at Christopher's request is appointed to be
held at Westerly to-morrow afternoon at 4 o'clock.

6th month, 22nd. The appointed meeting proved to be quite a large assemblage,
and it was thought that Christopher was favored to declare some of
the truths of the gospel in a good degree of right authority.
Westerly contains many manufacturing establishments,
and judging from the numerous houses for public worship,
there are various religious sects in the place.
Rode nine miles to Hopkinton, and met with kind entertainment there.

6th month, 23rd. First day, attended meeting at Hopkinton; the morning was wet,
and the meeting perhaps smaller in consequence, but a considerable number attended,
and Christopher was thought lively in his testimony.
A meeting had been appointed to be held in a schoolhouse, one and a half miles distant,
in the State of Connecticut, at 5 o'clock in the afternoon.
This building stands on the opposite side of the road from the site of the old one
(now demolished) where Christopher received school instruction in his youthful days,
and had taught school for several years.
Thither we pursued our way at the time appointed,
and arrived before the conclusion of the meeting of seventh day Baptists there assembled.
Their minister was exhorting with energy,
but we remained on the outside of the house until the breaking up of the congregation;
when, after a short respite, the people again took their seats,
and several others coming in, a large meeting assembled.
A solemnity soon spread over us,
and Christopher was soon moved to administer word and doctrine, exhortation and reproof;
which was thought to be with demonstration of the Spirit and with power.
He stood at least one and three quarter hours,
and taking into consideration the length of time most of the audience
had been sitting previous to the commencement of our meeting,
it was admirable to see the quiet and order that prevailed.
A manifestation of interest and solemnity continued through out,
and the opportunity closed comfortably.
Several of Christopher's scholars and old acquaintances came round him after meeting,
and apparently gave him the hand of cordial friendship,
as did also the two Baptist ministers in attendance.
It was remarked respecting the congregation that frequents this house,
that their minister had produced much agitation amongst them,
but that which may be compared to the whirlwind and the earthquake being past,
they were then in a condition to hear the "`still small voice.`"
The distant views are pleasing, but most of the ground being excessively stony,
although it appears to possess a good degree of fertility,
renders the near prospect less interesting.

6th month, 24th. Those of our own little company, and some others,
walked a short distance to visit the burial-ground and
site of the old Hopkinton MeetingHouse.
There are many interesting associations connected with this place.
It was here that Christopher attended meeting in early life;
it was here that he came forward in the ministry; it was here that he first married;
and in these grounds the remains of his mother are laid.
Here, too, appear the graves of others of his deceased friends,
and also those of the worthies of earlier generations.
There was observable two solitary mounds beneath a spreading oak; these,
said one of the company, are the graves of my precious daughters,
one died at the time of my absence in England, and the other shortly after my return.
Recognizing the solemnity of these cherished associations,
and mingling our better feelings with those of our beloved friend, Christopher,
it was manifest that we all felt the impressiveness of the situation;
and as the pilgrimage drew to a close,
left the interesting premises with hearts tendered,
and feeling that it was good for us to have been there.

In the afternoon, moved forward in order to attend an appointed meeting.
Arrangements had been perfected to hold it in
the vestry of a Calvin Baptist meeting-house,
and information was spread accordingly through the factories and schools.
This place of worship is located at Bushville, between two manufacturing villages,
each half a mile distant.
Thither we repaired at the hour appointed, accompanied by some of our friends,
but not a solitary individual had arrived, and the door of the house was locked.
We abode in the patience for half an hour,
but still no other signs of a gathering appeared.
At length one man came, and he informed us that the key was kept at the lower village.
Soon after a boy driving some cows drew near,
and being a friendly disposed little fellow,
he was asked if he would procure the key for us, to which he readily assented.
The aforesaid man sat for a few minutes on the steps, and then went away,
and we were again left to ourselves until the return of the little boy,
who informed that owing to the absence of the custodian of the key,
at was then at the upper village.
One of our company volunteered to go for it,
and we again found ourselves solitary until a little girl came and stood near us.

At this time the prospect of holding a meeting looked really discouraging,
and serious thoughts were entertained of giving it up;
but at length the key was produced,
and information that way did not open to suspend
operations in the factories until the usual time,
which was after sunset, but that the people would convene as soon as possible afterwards.
The door was unlocked, and we took our seats in the house,
and about half-past eight o'clock a large company assembled,
entering the room in an orderly manner, and sitting very quietly.
A solemnity evidently soon spread over us,
and Christopher was soon drawn forth in testimony and counsel,
which continued about one and a half hours.
It was not so much a doctrinal sermon as a persuasive exhortation,
and particularly adapted to those young in years.
This opportunity was manifestly owned by Israel's Shepherd,
Gospel love and power distilled as the dew, and as the gentle rain upon the tender plant,
and, was apparently received and relished with much cordiality.
The meeting was appointed to be held at seven, and it closed about ten o'clock.
One of our company proposed paying for the lights, but the answer was "`No,
you have nothing to pay; we are thankful for the meeting.`"
Doubtless,
there were hearts clothed with reverent gratitude for
the peculiar favors vouchsafed this day.

6th month, 25th. Moved forward towards South Kingston, fifteen miles distant;
crossed the Wood river at the manufacturing village of Hope Valley,
and wending our way for a few miles through a not very fertile district of country,
called at the residence of the widow of one of Christopher's brothers;
the long separated relations met, and parted affectionately, and we moved onward.
The country continued to present the same rugged and not very attractive aspect,
but we passed through a thriving manufacturing village.
These tokens of enterprise, skill and thrift,
sometimes contrast strangely with the surroundings.
We also passed through a reservation belonging to a remnant of the Narragansett Indians.
They are, now much reduced in number, and are considerably mixed with African blood;
we met one woman bearing strongly the marks of pure aboriginal descent,
and one man evidently of the amalgamated race.
Christopher had upon former occasions held religious meetings amongst them,
and he had been looking forward to a similar attainment at this time;
but it was ascertained that many of them are absent
from the reservation at this season of the year,
and it is not likely that any considerable number can be collected.
They also have degenerated into more dissolute habits, have now no settled minister,
and their meetings for worship are suspended.
Alas! for the poor Indians.--A remnant of the Penobscot
tribe recently passing through this part of the country,
pitched their tents in this neighborhood, where they were attacked by a disease,
which soon swept fourteen of them from the face of the earth.' Christopher has long
manifested a Christian sympathy and earnest desire for the welfare of the Indian,
and I believe that it is unabated now,
but it does not appear that a satisfactory visit can be made amongst them at this time;
it is therefore left for the present.
Continued our travel through a part of the country much of the way uninhabited,
until we approached the flat land bordering on the Atlantic.
From the brow of the hill which skirts this land scape,
more attractive scenery presented; the flat land is thickly settled and quite productive,
and with the sea view beyond presented a pleasing picture.
We found entertainment at the hospitable dwelling of kind friends,
who not only were diligent in their demonstrations to make us comfortable,
but were instrumental in procuring the appointment of a meeting to be held in a
Baptist meeting-house (not far distant) to-morrow afternoon at 3 o'clock,
and in endeavoring to gather the people thereto.

6th month, 26th. Took a walk after break fast to an eminence called Green Hill,
which is an extensive pasturage;
from this elevation was presented a beautiful view of the Atlantic Ocean,
and we saw numerous beds of oyster shells on the highland,
where the poor Indians were wont to regale themselves
in days that have long since passed away.

At the appointed hour we proceeded to attend the appointed meeting; it proved large,
and through the condescending goodness of Israel's Shepherd,
who was evidently mouth and wisdom, tongue and utterance, to our dear aged,
but still earnest friend, it proved a tendering and doubtless a profitable season;
many expressions of satisfaction therewith were afterwards heard.
Rode about two miles to the abode of one who is not a member,
but her three daughters had recently been admitted into
the fold on the ground of convincement;
the family were all kind, and we spent an agreeable evening with them and others,
and tarried at their dwelling until morning.
The view seaward is beautiful, and the sea breezes refreshing.

6th month, 27th. Left our comfortable quarters this morning, and riding about five miles,
stopped at the habitation of the widow of another of Christopher's brothers;
their greeting was affectionate, and she blessed the Lord for the visit.
She is about eighty years of age, and retains her mental faculties scarcely impaired,
and also her retentive memory;
her son and daughter appeared gratified with their uncle's company.
After dining with the family we proceeded another five miles onward,
to a manufacturing village called Kenyon's Mills,
and stopped at the abode of a widow not a member of any religious sect;
but her house and heart were open to receive us, and we were kindly cared for by herself,
her sister, her son and four intelligent daughters; and when a meeting was proposed,
she freely offered their large house for that purpose.
The offer was accepted, and the meeting appointed to be held at 8 o'clock in the evening;
but Christopher had not much service therein.

6th month, 28th. Still moving onward and passing through several manufacturing villages,
we entered a railway car,
and proceeding twenty miles were kindly received at the attractive residence of a friend,
located on a fertile farm lying at the outskirts of »East Greenwich.
A meeting is appointed to be held at the Methodist
meeting-house to morrow afternoon at 4 o'clock.
East Greenwich is the place of Christopher's nativity.

In the southern section of the State of Rhode Island, where we have visited,
the best of building stone is very abundant,
yet the dwellings are constructed very generally of wood;
a considerable proportion of them are one-story houses,
but they are spread out and contain more internal space
than might be supposed from external appearances,
and the apartments are ingeniously and conveniently arranged; of,
course there are many costly and attractive dwellings.
The agricultural produce is largely pasturage and hay,
which are said to be rich and nutritious.
The products of the dairy are excellent, and also the beef and pork;
corn and rye are raised to moderate extent,
and bread made from a combination of these articles is
extensively preferred to that manufactured from wheat flower.
The soil or climate does not appear well adapted to the growth of wheat,
and but very little of that grain is cultivated.
In traveling some of the public roads, we pass through a considerable number of gates,
located at the dividing lines of the different farms
through which the unfenced or unwalled road passes.
Ornamental trees and shrubbery surrounding the dwellings do not
appear to meet with very general favor--of course there are many
exceptions--and although much of the ground is excessively stony,
and not remarkable for fertility,
yet the inhabitants appear to thrive and live well upon their unkindly soil,
and perhaps generally desire no better location.
But in manufacturing enterprise they excel,
and the land produce of the locality not being
sufficient for the sustenance of the population,
they draw a portion of their supplies from distant places.

6th month, 29th. Attended the appointed meeting; invitation had been spread extensively,
but the gathering was not large,
and Christopher was not largely engaged in testimony therein;
but another is appointed to be held at the same place at 5 o'clock to-morrow afternoon.
People not of our religious society do not often freely leave
their business to attend religious meetings on week-days.

6th month, 30th--First day.
Rode about six miles to a Baptist place of worship,
where a meeting had been appointed to be held at 10 o'clock in the forenoon.
Christopher had formerly held several favored meetings at this house,
and he appeared to feel an unusual drawing thither at this time.
The gathering proved large.
Quiet and good order prevailed, and a solemnity soon spread as a canopy over us;
under which precious covering Christopher arose and handed forth doctrine, reproof,
instruction in righteousness and encouragement.
He stood at least one and a half hours,
and it was thought that our hearts were contrited and solemnized together;
and although most of the audience were Baptists,
and perhaps relied confidently upon the efficacy of the outward element,
yet somewhat of the baptism of the Spirit was surely felt amongst us.
At 5 o'clock in the afternoon we attended the meeting
appointed at the Methodist place of worship in East Greenwich.
It was supposed that the gathering would be large,
and a considerable number did assemble;
but a funeral taking place at the same hour at the Baptist meeting-house,
a large concourse of people assembled there.
It is usual in this part of the world among the religious sects generally,
to carry the remains to the place of worship where the assemblage of those interested,
and such ceremonial proceedings as are deemed suitable take place previous to interment.
Our meeting was doubtless smaller in consequence of the funeral;
nevertheless it proved a good meeting;
quietude and good order prevailed among the attentive audience,
and it is reasonable to suppose that minds were instructed and
hearts benefited under the solemnizing power of truth.

7th month, 1st. Left our hospitable accommodations this morning,
proceeded about five miles westward,
and met with kind entertainment in a Friend's family.
A meeting had been appointed to be held in a Methodist meeting-house at Centerville,
at 7 o'clock in the evening, and thereunto we proceeded at the appointed hour,
and settled into stillness about early candle-light.
The wing of Divine Goodness was evidently spread over us; a marked quietude prevailed,
and apparently many hearts were solemnized together.
Our dear friend Christopher was clothed with Gospel life and power,
and ministered to an attentive audience in the authority of truth.
This sea son of favor closed about half-past nine o'clock.

7th month, 2nd. This forenoon we rode to the dwelling of Christopher's half brother,
where we dined.
The family were all kind, and some of them accompanied us to our appointed meeting,
held at the Methodist place of worship in Fiskville, at 3 o'clock in the afternoon.
The gathering was not large,
and Gospel life and power did not appear to arise into
dominion as much as at some other times.
After the meeting we stopped at the house of an aged physician.
He is not now a member of any society,
but is an old acquaintance of Christopher's. The doctor is feeble,
chiefly confined to his bed, and appears to be drawing near the close of life.
He is sensible of his situation, and looks forward to his dissolution with composure,
testifying that the Lord is gracious to him.
As our company sat by his bedside,
he asked that we might have a religious opportunity together,
and those present gathered into stillness.
After a time of silent waiting,
Christopher was drawn forth in exercise of soul on his account, which, doubtless,
was comforting to the aged sufferer.
It proved a heart tendering season,
and it was thought that the baptizing influence
of heavenly love and power was felt amongst us.
Rode several miles along the valley of the Pautuxent River,
where the number and extent of the manufacturing establishments is really surprising.
The scenery is picturesque, the beauties of nature blended with the works of art,
and the evidence of intelligence and thrift,
combined with the attractive aspect of the various factories, places of worship,
and dwellings neat in appearance and pleasant in location,
can scarcely fail to interest the eye and the mind of the traveler.

7th month,
3rd. The district of country which has been presented
to our observation within the last few days,
is attractive.
The farms generally appear to be productive and well cultivated; the buildings thereon,
of liberal extent and rarely dilapidated, and the manufactories are a marvel.
The general appearance portrays a high grade of temporal prosperity.

7th month,
4th. Proceeded to the railway station at East Greenwich about 8 o'clock this morning.
This being the anniversary of the signing of the Declaration,
an abundance of people were in motion, and our feelings not being in unison with theirs,
traveling under such circumstances was not very agreeable.
We waited half an hour in the crowd,
when the very long train of cars arrived laden with a vast number of passengers;
there was some confusion,
but we finally succeeded in obtaining comfortable accommodations,
and rode about twenty miles to the city of Providence, where a kind Friend met us,
and conducted us in his own conveyance about four miles further to Pautucket meeting.
We gathered with quite a large number of other attenders,
and I can not doubt but that it was a profitable season throughout,
although a portion thereof seemed laborious,
and not very relieving to Christopher's exercised mind.

Near Providence, we passed Providence Boarding School;
it is a spacious and hand some structure, its location high,
and its situation and grounds adjacent pleasing.
We also passed the residence of the late venerable Moses Brown;
he was a Friend of great pos sessions and of very large benevolence,
yet his dwelling was neither large nor ostentatious.
Also passed by the plantation where Job Scott
resided previous to his embarkation for England;
it is one of the best in the neighborhood, and still in possession of his descendants,
but they have no connection with Friends.
We likewise traveled upon a wide, solid, smooth,
and beautifully finished road extending several miles northward from Providence,
and bordered on each side by stately New England Elms.

7th month,
5th. Visited the large cotton factories belonging to
some of our kind friends and entertainers,
and passed through the pleas ant promenade on the banks of the Blackstone River,
which their private generosity have devoted to the public benefit;
and in the after noon proceeded to Providence,
and took passage in the steamboat bound for Fall River.
Passed Bristol, which it is said was formerly an extensive slave market;
but that degrading traffic is no longer known in New England;
its paralyzing effects upon human energy is not now felt here;
the pursuit of honest industry has free scope and flourishes marvelously.
After a pleasant passage of two hours' duration, arrived at Fall River,
twenty-five miles distant from Providence,
and were kindly conducted to the hospitable dwelling of a Friend,
a little beyond the skirts of the city.

7th month, 7th--First day.
Attended Friend's Meeting at Fall River, at half-past ten o'clock.
The usual invitation to the public had been extensively spread, many attended,
and through the condescending goodness of the Head of the Church,
who promised to be with those gathered together in his name,
it proved a solemnizing season--something like
the baptism of the one spirit into the one body.
Words flowed freely, accompanied with Gospel life and power,
and he that sowed and some that reaped rejoiced together.
We attended the afternoon meeting at 3 o'clock.
It was larger than that in the morning.
As we assembled and sat in stillness,
and I trust many of us truly gathered into the silence of all flesh,
presenting our bodies a living sacrifice accept able unto the Lord,
He did manifest his Divine presence unto us,
and permit us to partake a little of that stream
which does refresh and make glad his heritage.
Christopher arose, and in the authority of truth, handed forth doctrine and reproof,
counsel and encouragement which, doubtless, fastened upon many minds.
It felt to me that these opportunities were memorable seasons,
and will not soon be forgotten by some.

7th month, 8th. Left Fall River about 6 o'clock this morning,
and set our faces toward North Berwick in the State of Maine,
one hundred and twenty-eight miles distant.
Traveling by rail way, and passing through various cities and villages,
and through a country presenting a variety of aspects, and many interesting features,
arrived at the place of our destination in the evening,
and were cordially received at the abode of valued friends.

7th month, 9th. Rode over a pleasant district of country, and called at several dwellings.
In the afternoon were visited by numbers of the neighboring people.
A meeting is appointed to be held in the Baptist
meeting-house at North Berwick to-morrow afternoon.

7th month, 10th. Attended the appointed meeting; it proved large and favored.
Christopher labored honestly, and some plain truths were spoken,
especially in reference to forms and ceremonies, and qualification for the ministry.
A part of his testimony was somewhat sharp; but it apparently was well received,
and many expressed satisfaction with the meeting.
In the evening,
our minds were painfully affected upon hearing the sad news from Philadelphia,
a locality endeared to us by many interesting associations.
A devouring fire, of unprecedented extensiveness, has swept over a portion of that city;
the destruction of property is great, the loss of life considerable;
many homes are desolated, and formidable distress abounds.
These dispensations convey lessons of instruction, arouse thoughtful solicitude,
and may be designed to awaken our understandings to a renewed
sense of the uncertainty of terrestial enjoyments,
and of the uncertainty of life;
and to invite us to lay up treasure which nothing earthly can destroy.

7th month, 11th. Attended Friends' Meeting at North Berwick,
and Christopher had considerable service by way of exhortation and counsel.
Toward the conclusion he again arose, and in beautiful language,
handed forth sympathy to this little company,
who had passed through many tribulations and anxieties in
endeavoring to guard the ancient faith of the Society,
and in sustaining its order and discipline;
comfort and encouragement was extended to those who truly mourn in Zion.

7th month, 12th. Left North Berwick this morning, rode thirteen miles over a pleasant,
undulating country to the village of Kenebunk,
and received kind entertainment in a family of Friends.
A meeting had been appointed to be held at their dwelling, at 3 o'clock in the afternoon,
and the usual invitation had been spread.
At the time appointed,
we took our seats in one of the apartments which opened into others,
and a considerable number of the neighboring people assembled with us.
Christopher was led to distribute doctrine, reproof, and instruction in righteousness,
and as his testimony was continued,
an increasing solemnity apparently spread over us--oil was poured into wounds,
the sincere-hearted encouraged,
and it was thought that the meeting ended under the
solemnizing and cementing influence of heavenly love.
We passed an instructive evening together,
several beside our own little company being present.
Christopher was very interesting in conversation,
and as the hour of parting for the night drew on,
he testified that he then realized some of the prospects which
had attended his mind before he left his own home.
Our hearts were tenderly affected,
and somewhat of that unity of spirit and bond of peace, which is not of man,
nor of the will of man, but by Divine grace and power, was surely felt amongst us,
apparently binding the hearts of some of the company together
in a measure of that life in which those of true and living
faith are some times permitted to know and greet each other.
Doubtless,
some were present who were enabled to thank our Heavenly helper for his many favors,
and to take courage.

7th month, 13th. Made preparation to leave our comfortable quarters this morning;
but before our departure, a parting opportunity was proposed,
and we seated ourselves together and gathered into silent waiting,
and I cannot doubt that the cementing influence of heavenly love was felt amongst us,
or that the oil of the kingdom did circulate as from vessel to vessel,
drawing us near to one another in fellowship of spirit, into sympathetic feeling,
and mutual desires for each other's preservation through all
the temptations and trials of life's probationary scene.

7th month, 14th--First day.
Again attended meeting at North Berwick; and although we met with some annoyance,
yet Christopher had acceptable service,--the meeting was interesting,
and the situation instructive.
In the afternoon, rode eight miles to the manufacturing village of Great Falls,
in the State of New Hampshire,
where a meeting had been appointed to be held in a spacious Methodist place of worship,
at 5 o'clock.
A large number of people assembled, and we took our seats amongst them,
I trust under a solemn sense of the seriousness
and of the responsibility of the occasion.
Christopher ministered at considerable length;
his exercise seemed somewhat laborious for a time, but as he proceeded,
life and power continued to arise into dominion,
and it was thought that we had a good meeting;
several expressed their satisfaction therewith,
but some plain truths were uttered which may not have
settled altogether pleasantly upon some minds.
Returned to North Berwick to lodge.

7th month, 15th. Made a few visits in the neighborhood, and on our way returning,
called at the dwelling of an ancient female Friend; a widowed daughter resides with her.
After a little time of conversation we settled into stillness,
and the wing of Divine goodness was evidently spread over us;
under which precious covering Christopher was drawn forth to address our
aged sister in the endearing language of tenderness and encouragement,
and the word of counsel and sympathetic feeling flowed freely towards the daughter.

7th month, 16th. Prepared to leave North Berwick this morning,
and as the time arrived to bid farewell to those who
had entertained us with much kindness and hospitality,
and had been so diligent and efficient in making way
for the appointment and attendance of public meetings,
there was evidence that we all felt the separation,
and entertained mutual desires for each other's best welfare.
Leaving the railway station we proceeded on our way toward Salem,
passing Portsmouth in the State of New Hampshire,
and Ipswich in the State of Massachusetts.
I glanced at the last-named town with a considerable degree of interest;
not that it possessed remarkable beauty, or great importance,
but as a place where a witch court formerly existed,
and where many persecuted fellow mortals (seventy in one year) were
condemned to destruction under a most fallacious and unaccountable delusion.
It is really marvelous that that dark superstition was so
long suffered to cloud the minds of an intelligent people.

7th month, 17th. Proceeded five miles to Lynn in order to attend meeting there;
the usual invitation had been extended, but the gathering was small.
Christopher was exercised in the ministry, and his service appeared to be acceptable.
The manufacture of shoes is carried on to great extent at Lynn;
the place has an agreeable aspect, a fine view of the Atlantic spreads out before it,
and refreshing sea breezes often fan the inhabitants.

7th month, 18th. Attended meeting at Salem at 11 o'clock in the forenoon,
the usual time of gathering; the meeting was not large,
but Christopher was engaged in testimony,
and his company and religious labors appeared to be satisfactory.

We felt a peculiar interest in one residing in this locality,
who has been several times in our company.
he is about forty years of age, and was educated among the Baptists,
has officiated as a minister for them, and is master of many languages;
but more than sixteen years since his mind was brought
under exercise for the attainment of a more perfect way,
and as he hungered for that bread which nourishes up the soul,
and thirsted for the waters of life, his mind was gradually drawn from outward forms,
and centered upon the everlasting substance;
he appears to have been first awakened to see the beauty and perfection of
our principles through the instrumentality of Barclay's Apology,
which accidentally fell into his hands.
The way of primitive and vital christianity there described,
answered the Divine witness in his own soul,
and he sought out and attached himself to a people making so high a profession.
There is much evidence that he was not afterwards a mere nominal Christian,
but submitting to the powerful heart-changing operations of Divine Grace,
he became himself a changed man, firmly rooted and grounded in the truths of the Gospel,
enabled to stem the torrent of ridicule and
abuse which he encountered from his own family,
and from those with whom he had formerly walked in fellowship,
and has given abundant evidence that he has bought the truth and will not sell it.

In the afternoon we were conducted to the attractive residence of a Friend,
located upon a valuable farm, in a pleasant district of country,
about three miles distant from Salem:
it is part of a tract of five hundred acres formerly belonging to Governor Endicott,
that most rigid Puritan persecutor,
who wielded the affairs of the infant government of Massachusetts,
and passed sentence of death upon several of our worthy Friends.
The site of his mansion is near by,
and thither he repaired from Boston to spend the summer months.
Near by stands an aged pear tree which it is said the Governor
planted with his own hands two hundred and ten years ago;
it was loaded with fruit, but it did not look vigorous.
Endicott possessed houses, and lands, and popularity,
and was called one of the pious pilgrim fathers,
but we may well suppose that that unrelenting
persecutor did not enjoy a peaceful serenity of mind.

7th month, 19th. The day was rainy, but we proceeded to Salem,
and having received much attentive kindness in these localities,
moved forward toward Boston; rode through that attractive city,
and in so doing passed an ex tensive and beautiful enclosure called Boston Common.
A solemn feeling covered my spirit as I gazed upon it:
the remembrance of departed worth and faithful martyrdom came up before me;
it was upon this common that several pious sufferers
for the testimony of their Lord and Savior,
laid down their lives.
William Leddra, Marmaduke Stephenson, Mary Dyer, and one other worthy were executed here,
and here they gave ample evidence of faithfulness to the sacred cause they had espoused,
departing hence with the glorious assurance of a happy immortality,
and doubt less entered upon that eternal rest which
their extreme persecutors may have longed for in vain.
After leaving Boston,
continued our travel about sixty miles through a
not very productive country to New Bedford.

We somewhere passed the meeting-house where
Comfort Collins attended meeting many years ago.
The remembrance of this faithful minister and interesting example of
departed worth being thus brought prominently before us,
our dear Friend Christopher manifested a lively interest therein,
as it portrayed an instructive instance of the efficacy of Divine grace,
and of the compassionate regard and favor of a loving Savior.
She had been faithful in her day and generation, and lived to great age.
Her mental faculties became so far impaired that she
did not even recollect that she ever had a husband,
but was still mercifully permitted to retain the savor of spiritual life,
and even when near the end of her lengthened pilgrimage upon earth,
was qualified to speak of her many mercies, and to exhort her friends in living,
impressive and instructive testimony.

7th month,
20th. Went on board of the steamer which plies between
New Bedford and Nantucket seventy miles distant,
and moving forward, touched at a promontory of Massachusetts,
and also at Martha's Vineyard,
arriving at the place of our destination after a voyage of about six hours' duration.
The earlier part of the passage was not strikingly unpleasant,
but arriving at unsheltered situations where the
winds had a fair sweep across the waters,
we were much tossed upon the agitated surface of the deep.
On the previous day there had been a storm of unusual violence, uprooting trees,
and otherwise damaging, and the wind continued to blow fresh.
The forcible undulating waves beat heavily against our unstable bark,
causing it to sway and rock,
and the effect of this uncomfortable motion was soon apparent among the
passengers,--yet to me the passage was interesting and instructive;
I could sit and gaze with an untiring eye upon the solemn
grandeur of the scene which spread in wide expanse around us,
occasionally glancing at the distressed condition of our passengers,
and reflect upon the sacrifices and sufferings which
some of our worthy ministers endured for weeks together,
while crossing the wide ocean to promulgate the Gospel in distant lands.

7th month, 21st--First day.
Attended Friends' Meeting at Nantucket;
the usual kind of invitation had been spread extensively,
and a large assemblage collected.
It felt to me that the wing of ancient goodness which had been spread over
the assemblies of our people in primitive times was also spread over us,
pre paring our hearts to receive the heavenly dew and the gospel rain;
under which precious covering Christopher arose, and in demonstration of the spirit,
and with power, handed forth that which was given him to distribute;
and I trust that many minds were instructed, and many hearts comforted.

The afternoon meeting was held at 5 o'clock,
and at the time appointed we proceeded to attend it,
and found that a large number of people had collected and were continuing to collect;
the house is spacious, seventy feet square,
and it was estimated that over six hundred were in attendance.
Stillness and good order soon prevailed throughout this large assembly,
and I trust that many were truly gathered into the silence of all flesh,
and felt the precious influence of the Heavenly Father's love to extend to them,
solemnizing their feelings and increasing their faith.
Our dear friend Christopher was raised upon his feet,
and delivered a large testimony in Gospel life and authority;
the mourners in Zion were com forted; the fearful in heart were encouraged;
the unfaithful were warned; the lukewarm were aroused;
and the wanderers were invited to return.
His testimony was somewhat sharp against those who take up carnal weapons,
and against those who preach for hire and divine for money;
but it seemed to me that the power of truth reigned over all opposition,
and it was thought that the meeting closed under
the prevalence of solemn and contrited feelings,
to the praise of the great Master of assemblies,
who evidently had owned it and magnified himself therein.

7th month,
22nd. Those resident upon the Island are mostly located in the City of Nantucket,
which contains about eight thousand inhabitants,
and covers about a square mile of ground.
It has a line harbor, which was formerly frequented by abundance of shipping,
but as a commercial whaling centre the place has declined in population and importance.
The whale fishery itself has of late years diminished in value,
and much of its remaining greatness has been absorbed by New Bedford.
Much of the soil is stony, but it produces much pasturage,
and the products of the dairy are excellent.
Sea fish are plentiful; the atmosphere is notably salubrious,
and the people appear to be much attached to their sea-girt island.

It was in this locality that John Richardson held a remarkable
meeting in days that have long since passed away,
in which that gifted, prominent and dignified woman, Mary Starbuck,
could not resist the power which attended his ministry,
although she strove long and resolutely against it;
but she and the audience generally were overcome
by its heart searching and baptizing operations,
in a most extra ordinary manner, demonstrated by abundance of tears.
Many of the Nantucket people are her descendants.

7th month, 23rd. Partly owing to the perils appertaining to the afar-off whale fishery,
widows are numerous on this Island: we made visits to several of these,
and memorably to one prominent and far advanced in life,
the shadows of the evening are lengthening around her,
and the end of her earthly pilgrimage is in view; evidently,
there was no cause for mourning on her account, and after silent waiting,
Christopher was moved to hand forth encouragement,
in beautiful and affectionate language.

7th month, 24th. Several of our friends called to bid us farewell this morning.
They had been very kind to us,
had done much to forward Christopher's concern as set forth in his certificate,
and without their support,
it is probable that his religious opportunities with
the public would have been greatly circumscribed.
Parting affectionately with them, and turning our backs upon Nantucket,
moved onward across the briny waters; the return passage was pleasant,
and after dining with kind friends in New Bedford,
proceeded twenty miles by railway to Fall River.

7th month, 25th. In the afternoon, rode seventeen miles to Little Compton,
in view of attending meeting at that place to-morrow morning.
Our route was principally along the margin of Narragansett Bay; the road was good,
the weather was pleasant, the scenery picturesque; and being in good company,
the ride was enjoyed with peaceful tranquility of mind,
but not without an occasional thought of a far-distant home and family.

7th month, 26th. Attended the contemplated meeting at 10 o'clock;
the house was quaint and antiquated, but in good repair and comfortable,
and erected upon an eminence com mantling a beautiful view of sea and land.
A considerable number gathered with us, and truly it was a favored season.
Our dear friend Christopher was manifestly clothed with Divine authority and power,
and it was thought that the tabernacles of some were shaken.
After an interesting and instructive parting opportunity with the family,
who had entertained us so kindly at their hospitable dwelling,
we left Little Compton in the afternoon, and wended our way back to Fall River.

7th month, 27th. Left Fall River about 10 o'clock this forenoon,
on board of the steam boat bound for Newport, twenty miles distant;
the passage was pleasant, and the views diversified with land and water, hill and dale.
Not far from Fall River, we passed an eminence called Mount Hope,
which had been a great resort for Indian warriors,
and is famous in the history of that distinguished Indian Chief, King Philip,
who so long and so successfully withstood the encroachments of the white man,
and was finally shot near this place.
Arrived at the place of our destination,
and received kind entertainment in a Friend's family.

7th month, 28th--First day.
Attended meeting at Newport at 11 o'clock;
the usual invitation had been spread at Christopher's request,
and a considerable number of those not of our Society, gathered with us.
Our dear friend had large service in this meeting,
and his testimony was evidently delivered in the authority of Truth,
somewhat sharp against those who had wandered from the fold,
and had become as withered branches, but comforting to the mourners in Zion,
and to those who had turned their faces thitherward.
Several children were present,
and to them he was drawn forth in affectionate and encouraging exhortation.
A meeting had been appointed to be held at 5 o'clock in the afternoon,
about six miles' from Newport, among a sect called Christian Baptists,
and to the place of gathering we pursued our way.
The ride thither was pleasant, the roads good,
the country beautiful and highly cultivated.
The attendance was quite large; many Gospel truths were uttered,
and some close observations.

7th month, 29th. Before parting with our friends this morning,
at whose dwelling we had been kindly and hospitably entertained,
one of the company read from a manuscript containing an
instructive account of an interesting daughter;
her health gave way at the age of sixteen,
and after passing through nine years of severe bodily affliction,
approached the borders of the grave, with the triumphant hope of a bright immortality.
Humble faith and trust in a compassionate Savior, the refining process,
the sustaining grace, patience, resignation, a deepening in religious experience,
and Christian love,
appear to have been characteristic marks of her life
through the period of her protracted sufferings.

Newport has a fine harbor; a portion of the town looks somewhat antiquated,
but many of the more modern improvements are attractive;
the high reputation of the place as a sea-side resort is proverbial.
Wind-mills for grinding grain, and other purposes, are numerous on the Island.
Proceeded to New Bedford by way of Fall River, arriving in the evening.

7th month, 30th. Left New Bedford this afternoon, and proceeded on our way to Padan Aram,
three miles distant.
At this place a meeting had been appointed to be
held in a Baptist meeting-house at 5 o'clock;
a consider able number gathered with us.
Christopher was largely engaged in testimony, and clothed with right authority,
doubtless, to the instruction and edification of many minds;
and although some close observations respecting man made minis try and water baptism,
went forth to all those whom it might concern, yet none appeared to be offended.
The ride from New Bedford to this place was pleasant, and as we journeyed,
at least one mind was instructively carried back in
retrospect to the youthful days of the Patriarch Jacob,
and to the covenant which he made with his Maker
when on his way to Padan Aram of that day:
that covenant was never broken, and Jacob was preserved green in old age,
and laid down his head in peace.

7th month, 31st. Wended our way to meeting at South Dartmouth, at 11 o'clock;
but as we approached the place,
it was evident that the people could not be
comfortably accommodated by present arrangement;
a number were seated in their carriages near by,
and others collected about the door and windows;
this position of affairs not being satisfactory,
and a large dwelling-house being located near by,
the occupants thereof cheerfully offered a portion of it for our accommodation;
the offer was accepted, and we were soon comfortably seated therein.
A quiet solemnity soon spread over the assembly thus gathered,
and Christopher was drawn forth to impart much exhortation and counsel;
some by way of encouragement, and some by way of reproof.
And although some of his testimony might not have been altogether savory to some minds,
yet the truths thereof were self-evident,
and it is to be hoped that it was a season of profit to all.

8th month, 1st. Attended meeting at North Dartmouth;
the usual invitation to the public had been extended,
and a considerable company gathered there.
Christopher was led to declare some Gospel truths in plain and searching testimony,
and some close doctrine was handed forth.
It has been intimated in several in stances that he has spoken
remarkably to the states of meetings and of individuals;
many of his testimonies have been delivered with Christian boldness,
disquieting to the unfaithful, and to the lukewarm; gently leading to the trembling ones,
and to the honest hearted; awakening to the rebellious,
but comforting to those who truly mourn in Zion.

The residence of the late Sarah Tucker,
who had traveled in the ministry in our part of the land, and died several years since,
was near our hospitable accommodations.
I looked upon the earthly abode of that mother in our Israel,
not with superstitious reverence, nevertheless with a degree of lively interest,
as the remembrance of departed worth seemed to be
brought more vividly into view while gazing upon it.
Her memoranda are fraught with abundance of instruction,
giving evidence that she lived near to the fountain of living waters,
and she has left a sweet memorial behind her.

8th month, 2nd. Morning rainy.
In the after noon,
moved forward to attend a meeting to be held in a Baptist meeting-house,
in the village of Westport, about five miles distant;
stopped by the way to visit an ancient couple,
the sands of whose life are fast running out;
but they appear to accept the situation with cheerful trustfulness.
The meeting was quite well at tended, and after a time of silent waiting,
Christopher rose up to declare some of the truths of the everlasting Gospel;
he was favored to hand forth a powerful testimony,
and although he did not prophesy smooth things to all, yet it was hoped that his home,
testimony fastened as a nail in a sure place upon some minds
that in the cool of the day will profitably remember it.

8th month, 3rd. In the forenoon, visited an aged friend eighty-seven years old;
he is quite active, his intellect unclouded, has a remark ably retentive memory,
and can write without spectacles.
He has lately buried an interesting daughter who had been confined to her bed for years;
she is represented as having been an able defender of her faith,
and as a bright example of Christian virtue.
Left Westport,' and proceeded about five miles
further to another Baptist place of worship,
where a meeting had been appointed to be held at 2 o'clock in the afternoon.
The gathering was quite large, and much instructive counsel was handed forth,
especially to those who have the training of children:
the people sat quiet and attentive, which has been the case, perhaps without exception,
in all the meetings which we have attended in New England.

8th month, 4th--First day.
Attended meeting at New Bedford, at 10 o'clock.
The morning was rainy, but a considerable number gathered with us,
and the meeting proved solid and comfortable.
Christopher was engaged in testimony not largely, but impressively.
The afternoon meeting was held at 5 o'clock,
and a large number of people assembled and gathered into stillness;
much instructive doc trine and counsel were handed forth; the fall of man,
and his restoration and salvation were largely treated upon,
and many unprofitable things and hurtful practices were spoken against.

8th month, 5th. In the afternoon,
Christopher had something like a parting opportunity with a number of
those who had been interested in our visit to this place and vicinity;
he had received much kindness at their hands,
and they had been largely instrumental in for
warding and supporting his religious concern,
in the appointment of public meetings, and in promoting the attendance.
He addressed them in sympathetic and affectionate language,
and there was manifestation of much interested feeling,
when we finally bid each other farewell.

New Bedford has many vessels engaged in the whale fishery,--
appears to be a place of considerable commerce,
contains seventeen thousand inhabitants, is an attractive city, regularly laid out,
and beautifully shaded with trees.
Much of the country adjacent is only of moderate fertility.

8th month, 6th. Left New Bedford this morning, and proceeded by railway to Fall River.
A sorrowful circumstance occurred in this locality on first day afternoon,
by the upsetting of a sail-boat containing five young men,
and in connection therewith two of them (members of the Society of Friends) were drowned.
Their funerals took place at Fall River to-day--but way did not open to attend them-.

8th month, 7th. Attended meeting at Fall River;
the usual kind of invitation had been extended at Christopher's request,
and a considerable assemblage collected; he was much favored in testimony,
and had a relieving time amongst us; some close observations were handed forth,
but his testimony was delivered in the authority of truth,
doubtless to the comfort of many minds, and the instruction of others:
this meeting was evidently owned by the Master of assemblies,
and was very satisfactory to Christopher himself, as it was also to others.

8th month, 8th. Crossed the Taunton River by steam ferry-boat,
and proceeded about two miles to the residence of an ancient female Friend;
she is eighty-nine years of age, and very feeble in body,
the lamp of life is evidently fast going out, but through the decay of nature,
her spirit appears to be kept alive by living water from Shiloh's fountain,
and she looks forward with holy confidence,
that there will be a mansion prepared for her where the wicked cease from troubling,
and the weary are at rest, when time to her shall be no longer.
In the afternoon, proceeded to a Methodist Meeting-House,
where a meeting had been appointed to be held at 3 o'clock,
and it proved large and satisfactory.
Christopher was raised up to declare some of the truths
of the Gospel in demonstration of the spirit,
and with power;
a plain testimony was borne against some of the
peculiarities of other professors of Christianity,
but in convincing and unoffending language.
The minister who officiates at this place remarked after the conclusion of the meeting,
that he would be glad if their house could often be occupied in that way.
The appearance of this part of the country is pleasing.

8th month, 9th. We, with a number of those who had been interested in our proceeding,
met in the meeting-house at Fall River;
this gathering together seemed somewhat comparable to a parting opportunity.
Christopher felt under many obligations to them;
they had been cordial and diligent in gathering the public to his meetings,
and in upholding his hands through abundant labors, by their sympathy and fellowship;
and he was moved largely to address them.
The wing of Divine Goodness seemed to be spread over us,
and it proved a baptizing season,
something like the baptism of the one spirit into the one body:
much counsel was extended, encouragement flowed freely,
and the word of caution was not withheld.

Fall River contains about twelve thousand inhabitants;
the number of buildings designed for public worship are
evidence that the people are divided into many sects:
numerous manufacturing establishments evince their general pursuit,
and on every hand there is evidence of their enterprise.

8th month, 10th. Left Fall River,
and after a pleasant ride of twenty-two miles through a part of the country,
pleasing in appearance,
found kindness and hospitable accommodations at the dwelling of a Friend at Norton.
8th month, 11th--First day.
Two meetings are appointed to be held at the house of our kind entertainers to-day,
one at 10 o'clock in the forenoon, the other at 5 o'clock P. M.,
and several of the apartments were seated for the purpose.
At the first-named hour, we took our seats, and many gathered with us.
Christopher was clothed with Gospel life and power,
and ministered to an attentive people in the authority of truth; words flowed freely,
and although smooth things were not prophesied to all,
yet all appeared to be satisfied and much interested.
In the afternoon, a large meeting assembled; this too was favored.
Christopher was largely engaged in testimony,
and was led impressively to declare many Gospel truths,
apparently to general satisfaction.
There appears to be great openness in the minds of many
in this neighborhood to attend Friends' Meetings.

8th month, 12th. Before leaving our hospitable friends this morning,
Christopher was led to distribute counsel and encouragement in
a solid parting opportunity with the family and others present;
we then moved onward and rode fourteen miles to North Providence.
Our route still continued to lie through a section of country pleasing in appearance;
the roads were good, the comfortable looking farm-houses and surroundings drew attention,
and the fine New England Elms were an at tractive feature in the landscape.
Crossed the Blackstone River at the village of Seaconk; it was here that Roger Williams,
when he fled from Massachusetts' intolerance,
essayed to establish a government that would
afford an asylum to the persecuted and oppressed,
and promote civil and religious liberty;
but finding himself still within the jurisdiction of that colony,
he removed and founded the town of Providence.
Near the bridge which crosses the river to Pautucket,
stands the first factory established in Rhode Island; it is yet a good building,
its date quite modern, and since its origin,
factories have multiplied in that state to a marvelous extent.
Christopher had a parting opportunity with some of those who had been kind,
hospitable and serviceable to us, and we moved forward to the railway at Providence,
passing the fatal spot where the dwelling of A. J. and
her daughter had recently been destroyed by fire.
Proceeded forty-three miles to Westerly, and were again kindly entertained there.

8th month, 13th. We had looked forward toward setting our faces homeward this evening,
but a prospect of further religious service arising with weight and clearness,
Christopher has concluded to pass into Hopkinton to-morrow,
and more meetings have been appointed; some of us may have looked longingly homeward,
but we do not wish him to relinquish the service until
the work required at his hands is fully accomplished.

8th month, 14, Left Westerly this morning,
and moved forward toward a Methodist place of worship,
where a meeting had been appointed to be held at 3 o'clock in
the after noon,--passing many places familiar to Christopher,
and traveling twelve miles.
The meeting was well attended, and after a time of silent waiting,
Christopher delivered much instructive counsel; words flowed freely,
accompanied with an evidence of Divine anointing,
and with the authority of truth the meeting closed comfortably,
and much satisfaction therewith was expressed.

8th month, 15th. Attended meeting at Hopkinton at 11 o'clock.
On the way, stopped at the farm where Christopher's father died,
and on which the remains are buried; we all visited the grave,
and the scene was solemn and impressive.
The day was rainy, and although the usual invitation had been extended,
the meeting was not large; but Christopher had good service,
including an interesting parting opportunity,
and we were again kindly and hospitably entertained in this neighborhood.

8th month,
16th. Parted with several of this vicinity who had been cordial and hospitable to us,
had done much to open the way for Christopher's religious opportunities,
and to uphold his hands.
Of this number was J. W.; the frosts of age have settled upon him, but he is yet active,
his intellect unclouded, his discernment keen, his judgment forcible,
and his conversation edifying; but according to the course of nature,
his days are fast numbering toward a close, and we bid him thoughtfully farewell,
not thinking it likely that some of our little
company would ever meet him again in mutability.

8th month, 17th. It is concluded to appoint two meetings at Westerly to-morrow,
and our departure homeward is delayed.
We spent the day agreeably with kind friends,
and as the sun was sinking below the horizon, the western sky was beautiful,
the golden and azure tints were reflected from the placid bosom of the waters,
the steamboat Water Lily glided swiftly by,
the undulating waves gently rocked the smaller craft,
and a boat load of light-hearted boys appeared to enjoy it much;
we should be careful that our minds are not too much engrossed in earthly objects,
yet it may be allowable to entertain a passing interest in scenes like these.
It was a calm and lovely evening, a fitting hour for contemplation,
and far distant homes and families were brought into affectionate re membranes.
Before parting for the night, our circle gathered into silence,
and Christopher was moved to distribute impressive counsel.

8th month, 18th--First day.
It had been arranged to hold a public meeting at
a private dwelling at 10 o'clock this forenoon,
and at the time appointed a moderate number of attenders sat with us in the large parlor,
and gathered into silent waiting.
Christopher was led to impart much counsel, and some searching testimony.
The afternoon meeting was appointed to be held in a public meeting-house in Westerly,
at 5 o'clock: at the appointed hour we found a large number of people collected,
and still continuing to collect; the house was crowded,
but the audience was quiet and attentive.
Christopher was again clothed with Gospel life and power,
and handed forth that which was given him to distribute in right authority.
Several ministers of other denominations were present,
and although some plain and close testimony respecting hireling ministry,
and the call to the ministry, went forth to all those whom it might concern,
yet it apparently was well received, and may, in the cool of the day be reflected upon,
to the instruction in righteousness of some who
were present upon the interesting occasion.
This meeting is the last which Christopher expects to appoint in New England;
it was evidently owned by Israel's Shepherd,
and was a comfortable conclusion to Christopher'
s religious services in this part of the land.

8th month, 19th. We expect to set our faces homeward this evening.
I rambled from the village,
and took a seat under the shadow of a rock on one of the rugged hills of New England;
a distant view of the ocean, the windings of the Pawcatuck River,
and a pleasing landscape scene were spread out before me.
I did not look upon these beauties of nature with an indifferent eye,
but a retrospective view of the proceedings of
our little company for the last two months,
more definitely arrested my attention at this time.
Our sojourn in New England localities, apparently, is nearly brought to a close,
and although in looking over my poor services,
feelings similar to those of the unprofitable servant are mine,
yet I could rejoice in the abundant favors which have
been vouchsafed to the aged servant of the Lord,
whom it has been my privilege to accompany in his visit in the love of the Gospel,
to habitants of the land which we have lately traversed.
The Gospel message has often distilled as the dew,
and as the gentle rain upon the tender grass,
and he that sowed arid those that reaped have at times rejoiced together.

Christopher's testimony has at times been somewhat
sharp against the rebellious and evildoers;
the peculiarities of other religious societies have at
times been handled with Christian boldness,
and the unfaithful of our own religious profession have not always been spared;
but apparently his Gospel labors have been very generally, and perhaps universally,
well received--much satisfaction therewith has been expressed,
and we do not find that he offends any.
He has been Divinely assisted in his goings forth, and we, his companions,
have been comforted in bearing him company.

Took leave of our kind friends at Westerly, and wending our way to Stonington,
in the dusk of the evening, transferred ourselves and baggage to the Steamer Vanderbilt,
and later in the evening were pursuing our watery way homeward bound.

8th month.
20th. Reached New York City this morning, but immediately left for Pennsylvania,
arriving safely at our own homes, and finding our families well.
Two months had been occupied in the performance of the visit,
and thirteen hundred miles had been traversed.
The preservation of ourselves and families was cause for gratitude,
and surely we were not unmindful of it.

On one occasion while still pursuing our New England
visit on board of a steamer on eastern waters,
Christopher Healy became somewhat involved in conversation and controversy
with a prominent and zealous sup porter of the slave interest;
it was a time of considerable agitation upon the slavery question,
and much uncharitable feeling and severe criticism were frequently indulged in;
and it was manifest that this champion of the rights and wrongs of
the persecuted slave-holders had no partiality for Friends,
and the position they had assumed.
Christopher brought into view a specimen of severe
intolerance lately practised upon a northern man,
yes, (retorted the other,) and if you were to go there,
they would serve you in the same way.
Christopher mildly expostulated with him,
and informed him that he had several times visited the South,
and had not found the people unfriendly; but being in the line of his religious duty,
and going forth in a Christian spirit,
way was made for him with apparent cordiality to hold
numerous religious meetings with the slave-holders,
and with their slaves.
And although he did not always speak smooth things to those in power,
yet he received much kindness and hospitality at their hands.
Our opponent seemed softened, and we heard no more annoying language from him.

Our beloved friend Christopher Healy occupied a precious gift in the ministry,
and his religious communications were sometimes accompanied
with an extraordinary degree of Gospel life and power.
Several specimens of portions of his sermons are hereunto appended;
and though we cannot in the reading of such notes,
expect to feel in full the living energy and holy anointing that often
accompanies the ministry which is of the Lord's preparing,`" and although
the incidents described in these notes and the two succeeding memoranda,
did not occur within the last year of his life,
yet they convey an interesting idea of his ministry;
of his earnest solicitude for the prosperity of our Zion,
of his religious con cern for the best welfare of his friends,
and of present help in the needful time:
these and kindred manifestations of qualification and favor continued to attend him,
and were still bright and prominent in the last year of his earthly pilgrimage.

1842+++.+++ In our meeting for worship at Falls, our beloved friend, Christopher Healy,
spoke impressively, saying: "`The righteous shall have tribulation,
but the Lord will deliver them all,`" holding up to view the
necessity of having living faith in the Divine promises,
and then tribulations will be borne patiently,
and our faith will increase with our trials.
There is but one sure foundation;
but one foundation that will stand when all things else fail,
and unless we build rightly thereon, we cannot be saved.

The Divine will revealed in us is always in accordance with the scriptures;
he had never found it different.
He spoke of having faith in that Almighty power which a
servant of old described in this language:
"`The sea saw it, and fled; Jordan was driven back; the mountains skipped like rams,
and the little hills, like lambs.
What ailed thee, O sea, that thou fleddest, thou Jordan that thou wast driven back,
ye mountains that ye skipped like rams, and ye little hills,
like lambs?`" This was the power that gathered our
society from the maxims and customs of the world,
from the forms and ceremonies of a lifeless profession, from all will worship,
and from a hireling priesthood;
and though many may fall on the right hand and on the left,
yet the faithful will be pre served.

He believed that if our members walked answerably to our high profession,
there would be a hundred come unto us to where there is one now;
and we would be as a city set upon a hill that could not be hid;
our conduct would then speak louder than words;
and many would be invited by our example to come look upon Zion,
and behold Jerusalem a quiet habitation, with none of its stakes broken,
nor cords loosed.

1842+++.+++ Attended meeting.
Our beloved friend Christopher Healy,
bore a short but impressive testimony to the excellency of silent waiting,
and warned us against suffering our silent sit ting together to become a mere formality;
that if our practice is merely to come and sit down in meeting, and abstain from words,
without endeavoring to have our thoughts gathered to the Master of assemblies,
we shall never know the excellency of silent waiting,
and perhaps never experience that state of mind which
will afford us a lively hope beyond the grave;
but if we maintain the warfare, and struggle for the blessing,
the Lord may condescend to favor us as He did a faithful servant of old,
that man after God's own heart; "`The Lord inclined unto me and heard my cry,
and He raised me up out of a horrible pit, and out of the miry clay;
and set my feet upon a rock.`"
How encouraging! "`And He established my goings, and put a new song into my mouth,
even praises to our God.`"

1842--11th month.
Our meeting was much favored; our beloved friend Christopher Healy,
amongst much instructive testimony, was led to set forth in its true light,
the necessity of preparation for another state of existence,
and that sufficient grace is bestowed upon every
man to make his calling and election sure;
and if this grace is rightly heeded, death would not find us unprepared:
repeating these solemn warnings: "`As the tree falls, so it lies; as death leaves us,
so judgment will find us;`" "`there is no repentance in the grave,
nor par don offered to the dead.`"
He also brought to view as a warning to the lukewarm,
the condition of the church that was neither hot nor cold,
and the judgment denounced upon-it;
a state of lukewarmness being so offensive in the Divine sight.
And in our meeting for worship,
occurring shortly after a fatal accident in the neighborhood,
he was evidently moved to speak in reference thereto;
holding up to view the necessity of making our calling and
election sure while time and opportunity is afforded:
"`Be ye also ready, for in such an hour as ye think not, the Son of Man cometh.`"
There are gifts dispensed to every one of us, by which, if we properly profit,
death will not find us unprepared, though it come upon us as a thief in the night.
No soul is lost that has not had the opportunity of being saved;
but if we are not careful for the improvement of these gifts,
we cannot expect to grow in grace,
for it is only as we are faithful in the little that we shall be made rulers over more.

And in another meeting for worship, occur ring about the same period,
our dear friend distributed instructive testimony:
"`If any man love me he will keep my words, and my Father will love him,
and he will come unto him, and make our abode with him.`"
We are the children of Abraham if we do the works of Abraham,
and it is an evidence that we love our Savior if we keep his words;
holding up to view the precious reward of coming unto Him who is the way,
the truth and the life; the necessity of having faith in God;
and that the reason some of us do not grow in grace is for the want of faith.
We make a partial sacrifice, and do not give up the whole heart.
If we had faith as a grain of mustard seed, mountains of opposition would be removed,
and a way made where no way is seen by the art of man.
He expressed a desire that we should love one another,
and that our Church might be a church of love.
He also brought into view the preciousness of
the example of those who have served the Lord,
and their generation in their day, and have been gathered to their rest.
Their usefulness does not always die with them, but they being dead,
yet speak by the pious examples and precepts they have left behind them,
and who finally had nothing to do but to die,
and join the general assembly and Church of the First-born,
whose names are written in heaven.

In a meeting for worship, about this time,
he was again led to distribute persuasive counsel "`Oh, my soul! look thou unto the Lord,
for my expectation is from Him.`"
Bringing into view the necessity of this being the prevailing inclination of our desires,
and without which we shall never know the excellency of silent waiting;
and that there is a vast difference between those who feel poor, weak, and unworthy,
and whose expectation is from the Lord;
and those who endeavor to worship Him in their own will and wisdom,
and whose expectation is from the poor instrument.
It is only the humble, dependent waiting ones,
that will come to know the excellency of silent worship.

In another meeting for worship,
he was instructively led to describe that rest which remains for the people of God;
and told us that the Lord would not forsake us, unless we first forsake him.

1842--12th month, 25th. In our meeting to-day, our beloved friend, Christopher Healy,
handed forth an instructive testimony, setting forth that his mind had been exercised,
almost from his first sitting down in the meeting,
in a way comparable to our Savior's answer to those who spake of the Temple,
how it was adorned with goodly stones and gifts: "`As for these things ye behold,
the days will come in which there will not be left one
stone upon another that shall not be thrown down.`"
And these things must be fulfilled spiritually
in us as much as they were fulfilled outwardly.
The glory of this world must be stained in our view: our delight in the riches,
the fashions, the customs, and whatever is worldly must be thrown down.

There is too much of a disposition in us to shun the cross.
We want to come to the Savior, and at the same time hold fast to the things of the world.
We are convinced that there is no better profession than the profession of Friends,
and we would love to become religious members,
and walk answerably to our high profession; but the cross is in the way;
we are not willing to suffer for the Savior's sake, who was a man of sorrows,
and acquainted with grief.

He had met with many, while traveling up and down through the land,
who are willing to acknowledge that Daniel's God is the only true God;
that there is no better profession than ours; and yet they would not live thereto.
And when the light of the Divine countenance shines upon us,
we are almost or quite persuaded to be Christians,
and resolve to live in obedience to the Divine will;
but when the light is a little obscured, we stumble at the cross, and turn away.
The question he put to those whom it is for: "`What is the cause of these things?`"

The cross must be borne though it may lead into singularity,
and cause us to be despised and rejected of the worldly wise.
He did not mean to insinuate that we should make
our selves disagreeable in the eyes of the world,
further than to live in obedience to the Divine requirings.
He had felt it as plain as he had ever felt anything outwardly with his hands,
that there were those present that had sustained
great loss by going on from year to year,
and not sufficiently confessing their Savior be fore men.
If there had been more faithfulness to the Divine Master's will,
there would have been more fathers and mothers in our Israel raised up amongst us,
to encourage others to come look upon Zion, the city of our solemnities,
not one of its stakes broken,
or cords loosed,--and they would have found Him in deed to be their counselor,
the mighty God, the everlasting Father, the Prince of peace.

1843--1st month.
Our meeting to-day was a favored season.
Our dear friend, Christopher Healy, was raised up to publish a testimony,
evidently in demonstration of the spirit, and with power:
"`Remember now thy Creator in the days of thy youth, before the evil days come,
when thou shalt say,
I have no pleasure in them:`" bringing into view the
blessed effects of early submission to the Divine will,
and the danger of putting off submission to the
Lord's visitation until a more convenient season;
and that we all have need of a mightier power than our
own to guide us safely to the realms of peace.
He believed that some felt a little discouraged because their trials
are greater now than when more careless about spiritual things;
but he was acquainted with these things, for while we are pursuing self gratification,
and walking in the way that Satan would have us to go, he troubles us not,
but endeavors to make the way smooth and easy; but when we take a stand against him,
and turn our faces toward Zion,
'tis then he is aroused to vigorous action with his assaults,
temptations and insinuations,
in order to turn us away from the way that leads to salvation.
This keeps us in a state of continual warfare against our soul's enemy,
but the watch and the warfare must be maintained; and with weapons that are not carnal,
but mighty through God to the pulling down of the strongholds of sin and Satan.
He had stood by the bedside of one who acknowledged
that he had despised the counsel of the Lord,
and had served Satan in almost every respect,
and he thought it was the most awful sight he ever beheld;
the soul struggling under the just judgments of the Lord,
and it seemed to be in torments while yet in the body.
The poor victim had no hope of pardon and redemption,
and ended his days much in this awful condition.
Our beloved friend seemed to be deeply affected
with this revolting state of human existence,
and held it to view as a solemn warning to us;
pressing upon us the necessity of seeking the Lord while He may be found,
and making preparation for the solemn close before the evil days come.
The Lord will not say to the sincere wrestling soul: "`Seek ye my face in vain.`"
Do not despise counsel.
He also intimated that there was danger of some
falling away who had made a good beginning.
They would fall unless they were more obedient to Divine requirings;
and he spoke of his own experience; how he had been assailed by the enemy,
and had fled to the Lord Jesus for refuge;
who pointed him to the straight and narrow way, and raised him up out of the miry clay,
and set his feet upon that rock which he could declare was the rock of ages,
even Christ Jesus.

Accompanied our beloved friend, Christopher Healy,
on a religious visit to friends and others in
the northern part of Bucks Quarterly Meeting,
esteeming it a precious privilege to accompany a deeply experienced
and dedicated servant of the Lord upon a Gospel errand.
The difficulties of the way, occasioned by heavy snow-drifts, were very considerable,
but we were favored to escape accident,
and reach each place of destination in seasonable time.
We attended several meetings, part of them by special appointment,
and some in Friend's MeetingHouses, to all of which the public were invited.
In addition to other instructive counsel,
Christopher was conspicuously led to invite out ward and carnal
worshippers to turn away from an undue depending on man,
to an unreserved dependence upon the power and
promises of our Lord and Savior Jesus Christ,
and by obedience to His Divine will to know Him to rule and reign in their hearts,
that they might through Him partake of the bread and
water which nourishes up the soul unto everlasting life.

We had lodged at a friend's house in Plumbstead,
and early in the morning were preparing to proceed to Buckingham Meeting,
six miles distant; there had been a heavy snow storm, commencing early in the morning,
and continuing throughout the previous day; in the evening it ceased,
but a high north-west wind continued through the night,
and in the morning the abundant snow was alarmingly drifted.
Our friends endeavored to discourage us from attempting
to travel until the roads were rendered passable,
and some of their neighbors thought it folly to attempt it;
but our dear friend Christopher wavered not in his faith and trust,
but intimated that we must make the effort, that we must do our part,
and hoped that we would be helped.
The undertaking appeared really formidable, but after many startings and stoppings,
treading down and removing snow, and long, patient perseverance,
we arrived at the place of our destination in due time.
It felt to me that our success was not altogether attributable to human skill and power.
Our meeting was a much favored season.

Made a short visit to our beloved friend, Christopher Healy,
and experienced edification from his kindness and instructive company.
I believe that he has near sympathy with such young
friends as he thinks are religiously dis posed,
and seems very desirous that our doc trines and testimonies should be supported,
which he intimated must ere long be by those who are
now young in years if they are sup ported at all,
as the aged standard bearers, those who have long borne the burthen and heat of the day,
must soon be called hence,
and their places in the church militant will know them no more.
It is sometimes very encouraging as well as profitable, to the trembling ones,
to such as are endeavoring to set their faces toward Zion,
to be kindly noticed by those who are deeply experienced in the ways of the Lord;
who have themselves trod the slippery paths of youth and of early man hood,
and are qualified to speak understandingly of the quicksands, the snares,
and other hidden dangers with which an unwearied adversary is ever ready to deceive,
and to allure from the pathway leading to a happier state of existence.

After Christopher Healy returned from his religious visit to New England,
the last distant field of his Gospel labors, bringing sheaves of peace with him,
and appreciating the favor of a safe return to his comfortable home,
he continued diligent in the attendance of the religious
meetings for worship and discipline of which he was a member,
visited a neighboring Quarterly Meeting,
received his friends cordially at his own dwelling, and made several social visits.
One of these visits was of a peculiarly interesting character;
it took place at the hospitable abode of that dignified mother in our Israel, Ruth Ely,
after the conclusion of Bucks Quarterly Meeting, held at Buckingham,
in the year 1851. These prominent and earnest workers in their Master's vineyard had,
for many years,
been colaborers for the promotion of the welfare of the Society of Friends,
and of Bucks Quarterly Meeting in particular,
and had diffused abundant services in their more immediate surroundings;
they had taken much counsel together, uniting in harmonious labor for truth's honor,
rejoicing in the aboundings of the Gospel, and harmoniously suffering in its afflictions.
The evidence of Christian friendship which had so long been
mutually cherished by these worthy representatives of Friends,
continued prominent through life; the beautiful simplicity of their quiet lives,
their edifying conversation, the valuable instructiveness of their pious precepts,
the manifest weight of their spirits,
and the aboundings of hospitality accompanied by guarded cheer fulness.
These and kindred demonstrations portraying instructive lessons of well spent lives,
were now about to terminate with their mortal existence,
and both appeared to feel that this interview would be their last upon earth;
they spoke to the states of each other in prophetic
language which was after wards apparently realized.
It was under these interesting circumstances they bid each other a final farewell,
and Christopher returned to his own quiet habitation;
and although in much feebleness of body,
was clothed with sufficient ability to attend the
funeral of his beloved friend shortly afterwards.
But the wasting energies of his manhood continued to decline,
the shadows of the evening more and more lengthened around him,
and as life's setting sun steadily approached the horizon,
the good man calmly and peacefully approached the borders of the grave.

4th month, 8th, 1851. Our beloved friend, Christopher Healy, was taken alarmingly ill,
and upon being conducted to his chamber, he calmly surveyed his condition,
and felt very apprehensive that this sickness would be his last;
and under the solemnity of the dispensation,
and with the prospect of eternity before him,
wished his friends to understand that he felt no condemnation;
but now felt that pas sage of Scripture verified: "`There is, there fore,
now no condemnation to them that are in Christ Jesus, who walk not after the flesh,
but after the spirit.`"

4th month, 11th. He said: "`I feel very poorly, but tell all my friends that if I now go,
I go well.`"

The physician calling to see him, Christopher manifested solicitude on his account,
and exhorted him to be careful that he did not get into
the spirit of the world as some had done.
Although he seemed willing to try the remedies offered,
yet intimated that he felt entire resignation to the Divine will.
He appreciated the comforts with which he was surrounded,
and contrasted them with the destitution of many of his fellow mortals,
repeating the language:
"`While some poor creatures scarce can tell where they may lay their heads.`"

He said that the accumulation of wealth might have been a snare to him;
he had not sought great things, but what he had asked for had been abundantly granted.
His mind seemed clothed with contentment and gratitude.

4th month, 16th. Some of his friends calling to see him, he imparted counsel,
and desired that his love might be given to some distant ones.
In the afternoon his articulation be came much obstructed,
so that but little that was handed forth from his exercised mind could be gathered;
but the following expressions were distinctly understood: "`All is peace; all is peace.`"
"`The righteous shall have living comfort.`"
"`The living praise the Lord, the dead cannot praise Him;
they may praise Him in the letter, but they cannot praise Him in the spirit.`"
"`Where the wicked cease from troubling, and the weary are at rest.`"
"`They that live in the spirit must walk in the spirit.`"
"`I have a hope, an everlasting hope.`"
"`My secret help, my hope and my salvation.`"

4th month, 20th. His wife coming to his bedside, he said:
"`We have lived together many years in great harmony and good unity,
and I believe that the time is drawing near when we shall have to part,
and I hope we shall be favored to meet in a better country.`"

4th month, 22nd. This forenoon,
he poured forth his feelings in the following pathetic language:
"`Oh! if I can have patience, and pass away, how glad I shall be;
I do not think that I see anything in my way, all seems well;
what a favor to be an inhabitant of that City, that needeth not the light of the sun,
nor of the moon to shine in it, for the glory of the Lord doth lighten it,
and the Lamb is the light thereof.
Oh! if I could now quietly pass away to that blessed inheritance, how glad I should be.
I hope there is nothing in my way; my soul thirsteth for God, for the living God;
when shall I come and appear before Him? 'As the heart panteth after the water brooks,
so panteth my soul after Thee, O God.'`"

About noon to-day,
he became nearly strangled by the accumulation of phlegm in the throat,
and his friends were apprehensive that he was about to depart; in his struggles for life,
he said: "`I cannot stand it, I must go.
Oh, be honest! oh, be faithful! joy forevermore appears great.`"

4th month, 24th. He said: "`Christ knoweth His own sheep, and His sheep hear His voice;
and He leadeth them out, and goeth before them; and a stranger they will not follow,
for they know not the voice of strangers.`"

"`Poor and unworthy as I am, I see nothing in my way,
and hope I shall be patient until it shall please my
Divine Master to cut short the thread of my life;
to cut short the work in righteousness.`"

A beloved friend sitting by his bedside, he said: "`We love each other in the Lord;
we have both known the Truth, and the Truth has made us free;
and if Christ has made us free, then we are free indeed.`"

He received messages of love from several distant friends,
which seemed very precious to his feelings, and said, he believed that many,
in different places, felt united with him in spirit, and his dear love was to them.

4th month, 25th. One of his daughters coming to see him he expressed gladness,
and said he hoped that his children would be
willing to follow the footsteps of their father,
who had been made willing to take up the cross in young life,
which had preserved him from many snares and temptations.

At times he appeared to be much exercised on account of the afflictions of the Gospel,
but there were times when he appeared to be looking forward to a brighter day;
in one of these seasons of encouragement, he quoted the Scripture language:
"`Therefore I will allure her, and bring her into the wilderness,
and speak comfortably unto her; and I will give her vineyards from thence,
and the valley of Achor for a door of hope;
and she shall sing there as in the days of her youth,
as in the day when she came up out of the land of Egypt.`"
"`Oh! if I could now settle away and go to sleep in the arms of my beloved Savior,
how glad I would be; but it is not time yet, His time is the best time,
and the right time.
He has brought me through all my trials and temptations,
and landed me safe in a well-grounded hope of a happy eternity.`"

"`What a consolation it is to me,
and how glad I am that I can say at such a time as this, that I feel no condemnation;
everything looks bright and pleasant; yes, as clear and as bright as the light.
I have that hope which is as an anchor to the soul, both sure and steadfast,
and enters into that within the veil whither our forerunner has gone.'`"

"`I have no wish to pass the morning; I am ready to leave this troublesome world;
to pass the valley and shadow of death,
to that City whose inhabitants shall not hunger--hunger any more;
neither thirst--thirst any more;
for the Lamb which is in the midst of the throne shall feed them,
and lead them into living fountains of waters,
and God shall wipe away all tears from their eyes.`"

"`As, saith the Apostle, 'we have not followed cunningly devised fables,
when we made known unto you the coming of our Lord Jesus Christ.'`"

"`I have this to comfort me, that I have always believed the truths of the Gospel,
that the true Gospel is the power of God unto salvation, to all them that believe.
The angel flew through the midst of heaven, having the everlasting Gospel to preach;
that everlasting Gospel was not a book, it was the power of God unto salvation;
the angel had no book, but he said, with a loud voice, fear God, and give glory to Him,
for the hour of His judgment is come, and worship Him who made heaven and earth,
the sea and the fountains of waters.
Ah! that is the point.
First, fear God, and then give glory to Him, and worship Him who made heaven and earth,
the sea and the fountains of waters.`"

"`I now say as I have often said, friends speak often, one to another,
and if we speak right, the Lord will hearken and hear;
I do not mean we should speak often one to another in common conversation,
or about the things of the world, but about heavenly things; encourage one another,
and endeavor to get into that pure state of mind in which we will say no evil,
and think no evil; and the Lord will hearken and hear,
and a book of remembrance will be written for them that fear Him,
and think upon His great and glorious name.`"

While wrestling in spirit for the welfare of the Church, he said:
"`How shall we sing the Lord's song in a strange land; 'if I forget thee, O Jerusalem,
let my right hand forget its cunning; if I do not remember thee,
let my tongue cleave to the roof of my mouth,
if I prefer not Jerusalem to my chief joy.'`" He placed a high value upon
that unity which subsists among brethren baptized by the one spirit,
into the one body, and in reference to such unity repeated the 133rd Psalm:
"`Behold how good and how pleasant it is for brethren to dwell together in unity;
it is like the precious ointment upon the head, that ran down upon the beard,
even Aaron's beard, that went down to the skirts of his garment, as the dew of Hermon,
and as the dew that descended upon the mountains of Zion,
for there the Lord commanded the blessing, even life forevermore.`"
A friend making him a visit, he said: "`I am glad thee has come to see me;
we are poor things of ourselves,
but how precious if we can only feel that we have no condemnation,
that we are in Christ Jesus, the only safe abiding place.
Oh, that our Divine Master would bow the heavens and come down,
and make way for His wrestling seed.`"

4th month, 27th. "`What a pleasant morning: it is a morning without clouds;
is it so out of doors? Being answered that it was a bright morning, he said:
"`All seems bright and pleasant with me,
and if I could now pass away how glad I should be.`"

Upon taking some water, he said: "`It is but little more water that I shall need here,
but believe that I will be permitted to partake freely of the waters of life.`"

"`He maketh me to lie down in green pastures.
He leadeth me beside still waters;
though I walk through the valley of the shadow of death, I will fear no evil,
for thou art with me; thy rod and thy staff they com fort me;
thou anointest my head with oil; my cup runneth over.`"

He desired that his dear love should be re membered to some of his absent children,
and "`the dear little ones, they feel very near to my best life;
I hope they will be willing to walk in the footsteps of their poor old grandfather.`"

In contemplating the approaching termination of life,
he made inquiry respecting some who had watched by his bedside,
and being informed that they were absent,
he hoped that some careful friend would be present at
the time of his departure to close his eyes,
and also desired that his children might be present.

His little grandchildren approaching, he manifested much interest in their coming years,
saying that he loved them dearly,
and believed that they would remember him when he had gone to his long home.

"`I am going, I am going to my peaceful home,
but hope to await quietly my appointed time.`"

He said to a beloved Friend from a distant Yearly Meeting,
that his labors were nearly closed, and that his peace was made.
The Friend responded, "`I have no doubt of that,
and if I had never seen thee again in mutability,
I should have had the assurance in my own breast,
that thou hadst landed safely where the soul would forever be at rest;
and since sitting by thy bedside, I have been renewedly confirmed in that assurance.`"

Being under great bodily suffering, he exclaimed: "`O Lord,
be pleased to give me patience to endure unto the end,--my pain is very great;
"`but even while passing through this excruciating affliction of body,
his thoughts and feelings clustered around his loved ones,
with pious solicitude for their best welfare, and continuing his intercession, said,
"`and be Thou pleased to bless my dear wife and children.`"
He afterwards added: "`your loss will be my gain, and I hope you feel it so.`"
"`My Lord was a man of sorrows, and acquainted with grief.
You will all have to pass through this last dispensation, and oh, be prepared!`"

5th month, 3rd. Some friends from a distance calling to see him, he said:
"`I was much comforted, and had sweet peace, in visiting your part of the vineyard,
believing, that many there were preferring Jerusalem to their chief joy,
and may that number increase.
Ah! dear friends speak often one to another of the good things to come;
keep in the unity, and a blessing will attend you.
Give my love to friends in your part of the land.`"
"`The Lord will bless Zion, when He pleases; He will fortify her walls;
He will set up her gates.`"
"`O Lord, the mighty one of Israel, I feel Thy comfort,
and rejoice and sing Thy name and Thy praises in the land of the living.`"
"`Unto you that fear my name,
shall the sun of righteousness arise with healing in his wings.`"

"`Bless the simple-hearted, and all those who love the Lord Jesus in sincerity.
For Zion's sake I cannot hold my peace,
and for Jerusalem's sake I cannot rest,`" (and as if looking with an eye of faith
to the future prosperity of the church,) "`Gentiles shall see Thy righteousness,
and kings thy glory; thou shalt also be a crown of glory in the hand of the Lord,
and a royal diadem in the hand of our God.
Thou shalt no more be termed forsaken, neither shall thy land be desolate;
as the bride groom rejoiceth over the bride, so shall thy God rejoice over thee.
I have set watchmen over thy walls that shall not hold their peace, day nor night.`"

"`What will become of the poor little precious flock and family;
may their heads be a little anointed with oil; He will anoint their heads with oil.`"

"`Inquire after the good old ways, and the ancient paths,
and shun the paths that lead to evil.`"

Being in great pain, he passed a tedious and suffering night,
and had obtained but little alleviation the next morning;
but through his protracted sufferings, his mind seemed to be centered on heavenly things,
and clothed with devotion.
He spent much of the night in earnest intercessions at the throne of grace;
his mind was unusually exercised; he prayed fervently for the best welfare of his wife,
his children, his friends, and for the Church of Christ; and pending the decay of nature,
was remarkably supplied with bodily endurance and spiritual support,
manifesting abundant evidence that faithful ones are remembered in the hour of extremity,
when vain is the help of man; and are sometimes even enabled to rejoice in tribulation,
singing praises to their Creator in the midst of abundant suffering.
His pious confidence and well grounded hope in
the attainment of an inheritance incorruptible,
that fadeth not away, was apparently unchangeable; and his heavenly faith, and hope,
and trust, appeared as a light, shining more and more,
until his unshackeled and redeemed spirit would be absorbed in immortality.

His mind seemed to be carried back to the days of his youth,
and he expressed his gladness that he had come out from
the forms and ceremonies of a lifeless profession,
and had been brought into the attainment of a more spiritual way.
He spoke of the importance of bearing a faithful
testimony to the faith once delivered to the saints,
to the faith delivered to and appreciated by our forefathers;
and of the necessity of great watchfulness,
lest hurtful things should take root amongst us,
and weaken our faith in the precious doctrines and
testimonies that had been confided to our care;
for, said he, "`it was while men slept that the enemy sowed tares;
"` and he seemed much impressed with the importance of
endeavoring to preserve the seed clean,
and its growth uncontaminated.

He wrestled much in spirit for the welfare of Zion.
The welfare of our Society, mingled abundantly with his best feelings,
and his intercessions at times arose to the Father of mercies,
that He would spare His people, and give not His heritage to reproach.

It was but seldom that feelings of distress has
been permitted to cloud his triumphant spirit,
and they have soon passed away,
and left his mind calm and peaceful as a morning without clouds,
in the enjoyment of renewed faith, and holy hope and confidence.

5th month, 6th. He intimated that his day's work was done, that his peace was made,
that he was ready to depart;
but manifested no impatience on account of the
protracted period of his earthly pilgrimage.

There is a beautiful feature sometimes apparent
in the experience of the devoted Christian,
which seems to be the fulfillment of the commandment,
"`Thou shalt love thy neighbor as thyself.`"
This feature presents to our observation a disinterested love
and living desire for the preservation of all souls;
and it is believed has seldom been more prominent in
the experience of any of Zion's children,
than in that of our departing friend; when health and liberty permitted,
his labors in the line of religious duty flowed
abundantly beyond the pale of our Society;
and as the energies of the outward man became prostrated,
and the termination of his earthly existence apparently drew near,
still that universal love of souls came up before him,
and he supplicated fervently for this generation.

5th month, 12th. A friend calling to see him, he said: "`I love to meet my friends;
it generally brings tenderness with it.`"

He spent much of the night in supplication and exercise of soul,
but owing to great exhaustion and feebleness of articulation,
but little could be gathered, except the frequent naming of his Maker,
and a few detached sentences, such as,
"`How good;`" "`How comfortable;`" "`How sweet;`" "`His
glorious good presence;`" "`I love my friends.`"

"`Every one that will not bow in mercy, must bow in judgment.`"
"`Dear friends, fear God and keep His commandments, for this is the whole duty of man;
for God will bring every work into judgment, with every secret thing, whether it be good,
or whether it be evil.`"

He was often exercised on account of the low state of our once much favored Society;
but said it was his unshaken belief,
that the doctrines and testimonies given our forefathers to bear,
would not be suffered to fall to the ground;
but that there would be standard bearers raised up to proclaim the day of the Lord,
as said the prophet: "`I will turn my hand upon thee, and purge away thy dross;
and I will restore thy judges as at the first, and thy counselors as at the beginning;
afterward thou shalt be called the city of righteousness; "`then the song will be: "`Lo,
the winter is past, the rain is over and gone, the flowers appear upon the earth,
the time of the singing of birds is come,
and the voice of the turtle is heard in our land.`"

5th month, I6th, 1851. This day about 11 o'clock, our beloved friend, Christopher Healy,
departed this life; an easy passage from the conflicts of time was mercifully granted;
his close was calm and peaceful, his last words, peace, peace.

A concern had long rested on his mind to have his remains
enclosed in a coffin of very plain and simple appearance;
and at times during his illness,
and especially as the solemn period of his departure drew near,
the subject revived with increasing weight,
and he earnestly enjoined the faithful performance of
his wishes in this respect upon his friends.
He said: "`have my coffin made of white pine boards, without stain or coloring,
brass hinges or lining; have it flat on top,
and let it be laid in the grave without an outside coffin.`"
These requests were faithfully complied with;
and although the fulfillment of the conditions of this concern
might present the aspect of needless singularity to some minds,
yet it unmistakeably felt to our dear friend to be a matter of very grave importance,
which he felt conscientiously bound to sustain.
And be it remembered,
that a corresponding rigid simplicity of burial
prevailed among Friends of his native New England,
among whom his lot was cast in his early years,
and for a considerable portion of his life;
and it is most likely that he still felt attached to what he
then valued as an appropriate and commendable custom.
But aside from these considerations,
he had long mourned over what he was apprehensive might be an
increasing propensity to exhibit a display at funerals,
and which he feared was gradually leading us away from
the becoming simplicity of our forefathers,
and introducing us into a worldly spirit;
and he felt religiously anxious that his precepts or
example might never tend to promote such departure.
He also was apprehensive that it might not be entirely
consistent with the will of an all-wise Creator,
that there should be decoration and adorning about the remains of perishing mortality,
which he had decreed +should return to dust, and lose all their beauty and comeliness;
but that strict simplicity was more befitting the solemn occasion,
and more accordant with the committing of dust to dust.
Our dear friend undoubtedly felt that there was a necessity laid upon
him to bear a faith ful testimony against all appearance of pride or
ostentation in the preparation of the poor body for the grave.

5th month, 19th, 1851. To-day the remains of our beloved friend, Christopher Healy,
were interred in Friends' burial-ground at Fallsington,
attended by a very large company of Friends and others;
after which a solid meeting was held,
and much testimony was borne to the Christian virtues of the deceased;
to the faithful occupancy of the precious gifts that had been committed to his care;
and to the undoubted assurance that his soul had been
gathered into the fold of everlasting rest and peace.

1883+++.+++ In Friends' modern burial-ground at Fallsington,
in near proximity to many other inhabitants of this city of the dead,
and also adjacent to the MeetingHouse,
the scene of abundant labors of faithful ones now gathered to their everlasting rest,
there is observable a family row of four lowly graves, lying side by side.
No letters engraved on sculptured marble proclaim the names and virtues of the departed;
such testimonials of worldly display would be sadly out of place here,
and widely at variance with the pious precepts and examples set forth in the
circumspect lives of those whose remains repose beneath these humble mounds.
The green grass has for many summers taken root in the
mother earth which marks these dwellings of the dead;
and the snows of winter, the sunshine and the rain, and innocent birds,
and appreciative friends, have all been visitors here; but the disembodied spirits,
we humbly trust, are now surrounding the everlasting throne,
with all tears wiped away from their eyes.
The first grave, that by the south wall,
is occupied with all that is mortal of our dear friend John Miller,
long a substantial and much esteemed Elder, and father-in-law to Christopher Healy.
Shortly after his decease, in the year 1850,
the appended notice thereof appeared in "`The Friend.`"

[verse]
____
The good man's setting sun
Hath a most holy radiance; and its beams
Linger the longest on the earth-weaned minds,
Whose thoughts are nearest heaven!
We mourn thy absence venerable sage,
Though well persuaded that we should not mourn,
That having trod thy pilgrimage below,
Thy Father's house received thee! Thou hast well
Fulfilled thy mission in a world of sin,
And entered to thy rest--that holy rest
That still remaineth for the child of God!
Dearly beloved and venerated Friend,
Thy upright bearing through a lengthened life
Shone so conspicuous in thy daily walk,
That as a light to others was thy path,
Showing the road that Christian pilgrims tread;
And by example calling to the youth,
"`Follow ye me as I am following Christ!`"
Born in a foreign land he crossed the waves,
While yet a boy, and reached our favored shores,
Finding a refuge and protecting friend,--
Beneath a roof where virtue loved to dwell.
The Christian care that compassed him in youth,--
The pious precepts of his Quaker friend,--
The drawing cords of a Redeemer's love,--
Performed their office on his honest heart,
And drew him to the truth his Friends professed.
That truth that Fox in early days had taught,
That truth that Barclay could so well defend,
That truth that breathed on Penington's pure page.
The bud, the blossom, and the ripened fruit,
In his experience knew their seasons come,
Till he was found a Father in the Truth,
A pillar in the temple of our church.
With native strength of mind, with judgment clear,
With zeal for Truth and with discernment keen,
From left hand errors and from right hand free,
He had the wisdom of the truly wise.
As outward substance gathered round his home
To snare his feet, Humility came in
With guardian wings, and shielded him from harm;
Thrust ostentation from his calm abode,
And made religion an abiding guest.
His vacant seat
Reminds us of our loss,--the church's loss!
But also of his everlasting gain.
In life's decline deep suffering was his lot,
Wearisome days and tedious nights were his--
Yet, heaven-sustained, no murmuring thoughts went forth
But he looked calmly toward the narrow house,
And joyfully beyond. At length the sound,
"`It is enough,`" from the great Judge went forth,
And the gate opened to the world of bliss,
Where songs of praise eternally ascend
From ransomed saints around the Father's throne.
____

The next grave contains the remains of our beloved friend, Christopher Healy;
and those of his faithful and beloved wife, Sarah M. Healy, are deposited by his side.
In the fourth grave the remains of Mark Healy are buried, the goodly and dutiful son,
whose untimely death by accident,
created such wide spread sympathetic feeling at the period of its occurrence.
Lovely were they in their lives, and in their deaths not long divided.
