== Chapter III.

[.chapter-synopsis]
* Engages in a Religious Visit in Coeyman`'s Preparative Meeting, N. Y.
* Remarks on the Evils of the Use of, and Traffic in, Spirituous Liquors
* Warns a Neighbor on Account of Having a Man Who Pretended to Be a Soothsayer in His House
* Strengthened In a Time of Deep Trial by the Unity of His Friends
* Visits a Man and Warns Him Against Preaching for Hire
* Removes Within the Compass of Coeyman`'s Preparative Meeting

I informed my friends at our Monthly Meeting,
that it was on my mind to visit a few Friends`' families
in the compass of Coeyman`'s Preparative Meeting.
And the meeting uniting with me therein, it left me at liberty to perform the same,
in company with an elder and sympathizing brother belonging to that meeting.
I went to the said Friend`'s house on Seventh-day, the third of Ninth Month, 1808,
preparatory to the visit.
The next morning before meeting, we went to see one of the families;
and a favored time it proved;
wherein my heart was truly humbled under a sense
of the importance of so great an undertaking;
it being the first visit that I had ever made in this way of going from house to house.
After this we went to meeting at Stanton Hill; wherein I was favored, I believed,
with the word of life to my Own humbling admiration.
O may I give Him all the glory to whom it is due.
Who alone can appoint, anoint, and qualify for His great work and service.
Many of my dear brothers and sisters were brought very near to me in this meeting;
and the Word of comfort and consolation flowed freely.

The nursing fathers and mothers were encouraged to persevere.
The lukewarm were warmed; and the dear youth invited.
After meeting we performed the rest of our visit to a good degree of satisfaction.
Returning next morning, we went to see one of my companion`'s neighbors,
a woman that appeared to be near her end.
I found a concern to lay before her the necessity of a preparation for death;
also that some were received at the eleventh hour.
She expressed great satisfaction with the visit.
The same day attended a meeting appointed at Henry Post`'s, which proved a trying one,
though it ended to some satisfaction.
After this meeting, returned home to my family.

O Lord! when I remember your lovingkindness to me, a poor worm of the dust,
my spirit is humbled under a sense of your condescending love.
O may I ever dwell in the low valley, where you are pleased to visit, and feed your flock.
Yes, by the side of still water, and in the midst of green pastures,
where such shall rest under the banner of your love.

21st of Ninth Month.--Attended our Monthly Meeting at Coeyman`'s;
where we were favored with the company of several Friends,
who were appointed by the Yearly Meeting to attend the
subordinate meetings with a minute of advice,
containing a living concern and travail of the Yearly Meeting, for a reformation herein.
The company and gospel labors of these,
were truly strengthening and edifying to many of our exercised minds; and, I believe,
had a powerful tendency to reach the witness in many of the lukewarm among us.
There was also a word of invitation, in the love of the gospel, to the dear youth.
One part of the Yearly Meeting`'s advice, together with that of its committee,
proved relieving to my mind, namely,
that of the evil connected with using spirituous
liquors any otherwise than as a medicine.
For I had believed for some time, that no person while under the influence of good,
could, when in health, partake of an article so destructive as this to the human race.
I also believe,
if professed Christians of all denominations were to live
under the circumscribing power of the Spirit of Jesus Christ,
that a lesser quantity would serve them as a medicine.
O may all professing the Christian name consider these things!
And may such as are in the unnecessary use of this destructive article--destructive
to both soul and body--and which is affecting the peace of so many families,
and especially those who are buying and selling,
and making themselves rich by the profit thereof,
consider whether they are not of that number our Lord
said offended his little ones that believe in Him!
In love to your souls,
I leave these lines to be read when I am in another state of existence.

On the First-day of First Month, 1809,
I felt my mind relieved from a close trial that had been resting on it for some months,
and at times so heavily that had not the Lord in His
lovingkindness reached forth His helping hand,
I must have been utterly discouraged.
But now, under a renewed sense of His goodness to me this day,
I am brought to renew my covenant with Him whom I feel to be my only Lord and Lawgiver.
The prayer of my soul is,
that I may be preserved so watchful and careful as with His holy help,
never to depart from my covenant with Him.
Oh what a comfort those feel who are engaged to
live near to the great Fountain of all good,
from which does flow the sweet refreshing stream that waters the soul.
These are they that can praise Him in truth in the land of the living.
Oh blessed Redeemer remember those in every quarter of the world,
whom you have given largely to partake of afflictions.
Reach forth Your mighty Hand of power, and place it underneath, that they may not sink.
Endow with patience to bear all trials that you permit to come upon us;
for you alone can enable to persevere into obedience unto holiness.
Unto You, O Lord, belongs all the praise forevermore.
Amen.

On the 9th of Fourth month I felt my mind drawn to go and see one of my neighbors
who had a man residing with him who pretended to have a familiar spirit,
whereby he could tell what had or what would come to pass, taking pay therefor.
Feeling the indignation of the Lord against such conduct,
I found it laid upon me to go the next day, which I did;
and told my neighbor if he allowed this man thus to proceed in his house,
he would be partaker with him in the plagues with which
he would be visited as a reward for his iniquity:
for it is an abomination in the sight of the Lord.
This neighbor said he was obliged to me for my visit;
and appeared to be affected with what I had to say to him;
and said he had felt uneasy about it himself;
and further expressed that he believed my message was of the Truth.
In a few days after I was informed that he had put a stop to such conduct at his house.
For this act of obedience I felt great inward peace.
Oh may I continue in humiliation before the Most High.
After this time I had several highly favored meetings,
wherein we were truly comforted together m the name and with the presence of the Lord.

+++[+++Perhaps there are but few who have been called to the work of the ministry,
that have not at times known the accuser of the brethren,
who is ever watching to hinder the work of the Lord,
and if possible utterly to discourage and to destroy, to introduce his subtle reasonings,
which if listened to, and heeded, tend only to bewilder and to blind.
Christopher Healy did not escape this "`slough of
despond;`" but through the help of the ever-present,
ever effectual Helper, and that of his friends, he got safely out of it.

His allusion to worthy elders, among whom his lot was now cast,
who sympathized with him in his great poverty of spirit,
and who were alike willing and able to go down with him into baptism and death,
must have proved particularly helpful to him in comforting his drooping spirit.
Being able also to speak a word in season to his weary and ofttimes heavy laden soul:
which "`fitly spoken`" word,
Solomon in his Proverbs beautifully compares to "`apples of gold in pictures of silver.`"
May the Lord in his never failing mercy continue such Aarons and Hurs to His church,
who as faithful burden and standard bearers, keeping the word of His patience,
and watching unto prayer with all perseverance,
may thus be instrumental in upholding the hands that hang down through weakness,
and in effectually turning the battle to the gate.]

At our Monthly Meeting in the Third Month,
I found it laid upon me to put Friends in mind of the
awfulness and solemnity of worshipping the great God;
and that no offering, except of His own preparing, will be accepted by Him.
For the Lord knows in whose hearts it is to serve Him.
I had likewise a word of comfort to the mourners in Zion.
After the meeting of business came on, the enemy of my poor soul,
who is always ready to destroy,
made me believe that I had disturbed the silence of the meeting for worship,
and thereby offended the Lord, and burdened my friends.
The which brought my soul into mourning, and I sat as with sackcloth on my loins,
and my head in the dust.
And almost despairing I put up my prayers, cries, and tears to my God,
to whom I could appeal in sincerity of heart.
But O, my spirit was bowed to an extent I never remember to have witnessed,
but blessed be the Holy Helper, when I was just ready to sink.
He put forth His Holy Hand for my help.
After meeting, such were my feelings,
I thought it best to desire the ministers and elders to stop,
that I might have an opportunity with them: that so they might correct or advise me.
And when we met, the Lord met with us,
and gave me strength to inform them how it had
fared with me through the meeting for business.
When, instead of correction from my brethren,
I had their unity and near sympathy with me in my deep baptism;
which fully healed up all the wounds that my poor soul had experienced this day.

O may all that are concerned to appear in the ministry,
be careful to know the word of command from the Holy One,
and not let a good desire for the people be sufficient to raise them up in the ministry.
But remember, O exercised brother or sister, who are called to the work of the ministry,
that in order that your offerings be acceptable to God, or beneficial to the people,
you must feel with the apostle the necessity of the woe.
Yes, woe be unto you if you preach not the gospel.
Then if the enemy of your soul seeks to discourage you, and to destroy your faith,
and you be thereby brought to fasting,
you shall witness the Holy Hand to be underneath your head to keep you from sinking;
and when the time of fasting is over,
you shall witness the company of holy angels to administer to your hungry soul,
and your heart shall rejoice with songs of praise to
your Heavenly Father through Jesus Christ.
Which, blessed be the Lord,
was my happy experience on my way home after this Monthly Meeting.

The neighbor before alluded to,
whom I was constrained to go and see on account of having the soothsayer,
as he professed to be, in his house, in a short time being convinced of our principles,
requested and became a member of our Monthly Meeting.

In this year, 1809, it came livingly in my mind to go and see a hireling priest.
But weighing the concern, not being willing to go too fast,
and desiring the Lord to direct me aright in what I believed was from Him,
after a time of waiting and proving the fleece both wet and dry,
I felt renewed and strengthened from the great Minister of ministers.
And one morning believing the time had come to make the priest this visit, I went,
beseeching the Lord to go with me, well knowing that without His help,
I was unable to perform it according to His will.
And blessed be His Holy Name, He was pleased to be my companion and helper.
For when I came to his house, the Lord renewed my strength,
and opened my way to have an opportunity with him.
Feeling my mind clothed with the love of our Heavenly Father, I, in a solemn manner,
said to him,
I have come in the spirit of restoring love to tell you that the Lord God of
heaven and earth is not well pleased with your preaching for hire.
And if you continue so to do,
the things that belong to your peace will be hid from your eyes.
But if you will refrain, and live under the power of the cross of Jesus Christ,
you shall become acquainted inwardly and experimentally
with Him whom to know is life eternal.
He was tender and loving, and invited me to stay.
But feeling myself clear, I acknowledged his kindness,
gave him my hand and bid him farewell.
He said he wished me well.
I told him I wished him well.
And so in love we parted;
and I went on my way with a humble heart rendering the praise to my Heavenly Father,
who is a present help in the needful time.

The latter part of Eleventh month, 1809,
I removed with my family within the compass of Coeymans`' Preparative meeting,
where I opened a school.
Soon after my removal I was brought into great poverty of spirit,
but I found many sympathizing friends there.
Among them,
dear brethren and sisters who were willing to go down into Jordan with ministers.
Such elders are indeed worthy of double honor;
and some of those worthy Friends were made instrumental in comforting my drooping spirit,
by speaking a word in due season to my weary mind;
which about this time was plunged into deep baptisms.
This language of encouragement from my friends proved as words fitly spoken,
which were to my soul as apples of gold in pictures of silver:
being sanctified by the Lord.
