== Chapter VI.

[.chapter-synopsis]
* Visits Meetings and Families Near Renssalaerville, N. Y.
* Visits Rhode Island Quarterly Meeting, and Some Meetings in Connecticut
* Letter of Dorcas Brown.
* Letter of Lydia Weeks
* Leaves Home to Visit Friends and Others in Easton and Ferrisburg Quarterly Meetings
* Death of His Wife
* Letters of Mary Varney
* Letter Of John Wilbur

+++[+++In the Second Month of 1812,
Christopher Healy informed his Monthly Meeting of a prospect of
religious service in some neighboring meetings with their families.
It granting him the requisite liberty, he set out the 27th of the same month,
accompanied by a Friend of his own meeting.
In some of these opportunities he writes of his way being much closed up; but at others,
enlargement through Holy Help, was experienced.]

His diary thus continues:

Berne meeting was crowded, and the Lord was pleased to favor with His holy presence.
Truth`'s doctrine dropped as the dew, and as the gentle rain, to the comfort of many minds.
This afternoon was at an appointed meeting about four miles from Berne,
held at the widow Coles`'. I was led to open to the people the
mystery of Ezekiel`'s vision concerning the dry bones;
showing them that there are many at the present day,
who are as dry and lifeless as those the Prophet beheld in the valley.
Oh may the Lord by His mighty powerful voice,
shake the dry and barren minds of the children of men,
and cause them to behold their situation; that so they may cry for help,
and that the Lord may be pleased to breathe the breath of life into them,
that they may stand up and become an army for the Lord, to fight in his glorious cause:
the weapons thereof being not carnal,
but mighty through God to the pulling down of the strongholds of sin.

+++[+++After attending a few more meetings, he returned home, with, as he states,
a thankful heart to the Lord; and found his family well.

On the 13th of Ninth Month of the same year,
his friends of the Monthly and Quarterly Meetings respectively of which he was a member,
having granted the needful certificates,
he started on a religious visit to Rhode Island Quarterly Meeting,
and some meetings in the State of Connecticut.
He speaks of the parting from his dear wife and family as trying,
this being the farthest from home he had yet been;
but of her giving him up as cheerfully as he could expect.
With his friends Nathan and Ruth Spencer he proceeded pretty directly to Canaan,
in Connecticut, where he writes:]

We found a few Friends.
Had a meeting to good satisfaction;
and afterwards an opportunity with the members by themselves;
which proved strengthening to our minds as well as theirs.
There appeared to be a few among them that were engaged in the blessed cause,
and who were good examples to others.
From there we went to Hartford, and had a meeting with Friends.
It was somewhat trying in the early part, but towards the conclusion more favored.
I was led to declare the necessity of a living engagement in the Truth,
that we might become as lights to the world; and my friend Ruth Spencer,
in sounding an alarm.
We found some well engaged Friends at this place, though the number was small.
From others we parted with almost aching hearts, beholding their lack of spiritual life;
which ever causes the true mourners in Zion to weep.

+++[+++After going to and from several meetings, with but little remark in reference to them,
he came on the next First-day week to Hopkinton, where he writes:]

Many attended, not of our Society.
It was a highly favored meeting.
Many of the dear youth having been received by
convincement in this meeting within a few years,
their company and countenances refreshed my spirit:
feeling the living engagement of their minds and fellowship in the truth.
Had a meeting this afternoon about four miles from Friends`' regular
meeting-place at the house I removed from when I went into New York State.
Many of my former neighbors attended and were glad to see me.
Though this meeting was trying in the forepart, it ended to good satisfaction.
Next day had a meeting at Rickmonton, at Friends`' meeting-house,
where it appeared that there was lack of attention to
the direction of the great Physician of value,
by which means some of them remained sick and wounded,
causing us to leave the meeting with heavy hearts.

The next Fifth-day attended the meeting at the lower meeting-house in South Kingston.
Information that we intended to be at this meeting having spread,
many not of our Society attended.
The Great Master was pleased to crown it with His heavenly light,
and the doctrine of the gospel dropped as the dew and
as the gentle rain to the watering many minds.
This is the place that I first publicly espoused
that cause which is dignified with immortality,
and crowned with eternal life.
This afternoon had a meeting at the court-house on Little Rest Hill,
and many people attended.
Here I was led to declare Christ Jesus to be the only way of life and salvation.
That he was the stone that was set at naught by the builders of old, but was then,
and is still, the head of the corner.
I was favored to set before them the blessed effects of
obedience to the spirit of Truth in the heart,
to the consolation of many minds present.
This meeting concluded in fervent supplication to the only preserver of men.

Sixth-day had a meeting at Wickford, wherein I was silent;
but our friend Ruth Spencer had a few words by way of testimony.
In the afternoon,
attended a meeting appointed for us at a Baptist
meeting-house about three miles from Wickford,
which was owned and crowned by the good Master.
Several that were there, after the meeting concluded, expressed their satisfaction,
and that their minds had been sweetly comforted.
First-day attended Friends`' meeting at Greenwich.
In the afternoon, one appointed for us at a Baptist meeting-house,
about seven miles from Greenwich, near to the cotton factories of that place.
A blessed meeting it was.
Many of the people attended.
The principles of truth were clearly opened, and seemed to have place in many minds.

Second-day had a meeting at Foster, which was small but to our comfort.
After meeting, dined at B. Collins`'. In a religious opportunity in his family,
the children were very tender; and parted with us in a sweet frame of mind.
From there we rode to Rowland Green`'s;
who was gone on a religious visit in the Southern States.
His wife and children received us very affectionately.
Next day had a meeting at Scituate; very few Friends belong to this meeting,
but general notice being spread, many others came;
and the great Shepherd was pleased to make himself livingly known amongst us,
who is the crown and diadem of all our meetings.
Some expressed their satisfaction in this meeting in a very
moving manner.--Fourth-day had a meeting at Cranston,
to good satisfaction.
Dined at Sylvester Weeks`'. He and his wife,
Lydia--she being a worthy minister--are as a father and mother in Israel.
In the afternoon rode to Providence,
accompanied by our kind and loving friend Dorcas Brown; and by William Jenkins,
a young man that came out to meet us at this meeting.
Lodged this night at Daniel Anthony`'s, who is the parent of our friend Ruth Spencer,
and father-in-law to Job Scott.
They received us gladly.

Fifth-day, 8th of Tenth Month, which was my birthday,
had a meeting at Providence Sat the meeting through in suffering silence.
Sixth-day visited families at Pautucket.
Found great lack of a living engagement among them.
Seventh-day, had a meeting at Cumberland; where light and life gave the victory.
Several Friends came where we dined, and we had a comfortable opportunity together,
which proved consolatory.
First-day attended Friends`' meeting at Smithfield lower meetinghouse.
Here, through our blessed Helper, judgment was laid to the line,
and justice to the plumb-line; and we were mutually comforted together.
Daniel Anthony and daughter accompanied us to several of these meetings.
First-day afternoon,
attended a meeting appointed for us at Friends`' meeting-house in the town of Providence;
which was large; some few colored people being among them.
I was largely opened to speak on Daniel of old.
Oh, says my soul, may we of the present day have that holy zeal and faith that Daniel had!
I also had a word of encouragement to the colored people,
to the tendering of some of their minds.
One of them followed us to the house where we stopped,
and in a very tender manner expressed the satisfaction and love he felt.

Second-day, rode to Swansea; and at one o`'clock attended a burial,
where the friends of the deceased had requested a Friends`' meeting, and many attended.
It was a favored time.
At three o`'clock this afternoon,
attended a meeting appointed for us in Friends`' meetinghouse at Swansea,
which was large and greatly favored.
Third-day, in the forenoon, we were at Freetown.
It was an exercising time in the fore part, but ended to a good degree of satisfaction.
It the afternoon had a meeting at a small village about two miles from Freetown.
This was small,
occasioned by the young men of that place being
called upon that day to perform military duty.
My mind not feeling clear, I desired another meeting in the evening,
which was much united with; particularly by their minister,
who not only gave his attendance in the afternoon, but expressed his satisfaction.
The evening meeting was large, amounting it was thought to as many as four hundred people.
The captain of the training company, when he dismissed them,
requested their attendance at the meeting.
It proved a precious season.
The peaceable kingdom of Christ was clearly held up to their view.
After meeting, the minister invited us home with him, and treated us very kindly.
Oh may we never forget the tender mercies of our
God! who is the great Minister of ministers;
and only can give ability to preach the gospel;
and also to send it home to the hearts of the people, and seal it on their minds.

Fifth-day, attended their meeting at Providence.
And after it, the meeting of Ministers and Elders, to good satisfaction.
At six o`'clock in the evening had a meeting appointed for the colored people of the town.
It was thought there were more than four hundred of these attended,
with two hundred white people or more.
It was SI solemn meeting.
The doctrine of the gospel flowed freely.
It was clearly opened to the people, that God had no respect of persons,
but in every nation, he that fears Him and works righteousness, shall be accepted of him.
And as the rivers of old that went out of the garden of the Lord,
parted and became into four heads, and one part watered the land of Ethiopia,
so does the grace of God and stream of gospel love, flow to the people of color.
It was a season not to be forgotten by many.
Some of these poor people were heard to say, Oh what a good meeting we have had!
How I wish, said one, that some of my acquaintance had been here!
One of them towards the close of the meeting, in a solemn manner,
testified to the goodness of the Lord, saying, "`Had I the riches of the Indies,
I would willingly part with it all, for the love I now feel.`"
May the praise be given to the Lord who was evidently near this evening,
and whose presence alone makes good meetings.
Blessed be his holy name forever.

After this he had or attended meetings at Newport, Portsmouth, Tivertown,
Conanicut Island, Boston Neck, Tower Hill, Hopkinton, Providence, Bristol, Greenwich,
Wickford, North Kingston, Cranston, Swansea, and at Warwick.
The last meeting, he writes, "`was a precious one,
wherein the people were shown that the travels of the children of Israel of old,
were a type of the Christian travel towards the heavenly Jerusalem, the holy Mount Zion,
the city of the living God, whose walls are salvation, and whose gates are praise.`"
He appointed a few more meetings at factories, and some among other religious societies,
where he was treated with much kindness and respect; and then, parting with his friends,
set out for home, which he was enabled to reach safely,
and was joyfully received by his dear wife and family:
being truly thankful to the Lord for his preserving hand, that, as he writes, "`kept me,
and brought me safely home to my family and friends with the reward of peace.`"
He was absent on this journey about ten weeks, attended more than sixty meetings,
and rode upwards of one thousand miles.

While on this religious errand, the following letters were written.
They show the esteem, in some wise, which Friends there had for him,
with their appreciation of his gospel labors.
They are thus endorsed by Christopher Healy:--
"`Some letters received by my wife while I was in Rhode Island.`"

[.signed-section-context-open]
Providence, 31st of Tenth Month, 1812.

[.salutation]
Dear Friend

Though personally unknown to me, I take the liberty of thus addressing you.
Having been some days in company with your beloved husband in attending meetings,
it has tended to create a near sympathy with him,
and also for you in his absence from you.
Your care is great in superintending so large a family of little ones.
But, my dear friend, I would have you to remember,
that formerly there was a reward for those that tarried at home.
Yes, we read that they divided the spoil.
And I have no doubt but this will be your enriching experience;
and that you also will share largely of the Father`'s love,
by thus resigning the precious partner of your life,
to the disposal and service of his blessed Master.
The Lord has indeed anointed and appointed him to perform the service
in which he has been engaged since he has been in our parts,
strengthening him to fervently and affectionately labor for the good of souls;
and to the exalting of that grace by which the Apostle said, "`I am what I am.`"
And,! says my soul, may he continue on the right foundation,
keeping a single eye to his Holy Head and Leader, Christ Jesus, the Rock of ages;
that he may more extensively labor, if required,
to the awakening of thousands to the knowledge of the truth;
which I have no doubt will be the case,
as he keeps humble and reverently dependent upon the
alone putting forth of the Shepherd of Israel,
the only safe Leader and Guide, who has already led him about and instructed him,
and opened to his understanding the treasures of wisdom and knowledge,
and revealed the mysteries of the kingdom to him.
May he therefore continue faithfully ministering in the ability which God gives.

I have been with him at fifteen meetings; in most of which he was greatly favored;
some of them being particularly heart-tendering seasons,
I hope long to be remembered by many to their lasting improvement.
I said in my heart, it is the Lord`'s doings and marvelous in my eyes.
And oh! what might this power effect for many more if submitted to?
There is nothing that dignifies and exalts like the truth;
and none are so happy as the followers of it.
Although it leads in a straight and narrow path, it leads to peace;
even that peace that the world can neither give nor take away;
while how desirous are those that enjoy the possession of it,
that all mankind may live in the same.
For this they labor,
and are willing to spend and to be spent if it
may be to the gathering of but one precious soul.

Your husband is nearly through the meetings that he expected to take, and will probably,
after attending our Quarterly Meeting, look toward home.

[.signed-section-context-close]
Yours affectionately,

[.signed-section-signature]
Dorcas Brown

[.asterism]
'''

[.signed-section-context-open]
Swansea, 5th of Eleventh Month, 1812.

[.salutation]
Beloved Friend

I thought I felt a precious liberty to salute you in endeared affection,
having not only to feel with your dear husband since his lot has been cast in this land,
but with you in your present tried situation.
It is often consoling to my mind to believe,
that the law that was made for the benefit of
those that stay by the stuff is in full force,
having never been repealed.
And I am comforted in a fresh belief, that as you abide in the faith and in the patience,
you will be favored to partake,
not only with your precious Christopher in his sufferings,
but also in his cup of heavenly consolation: which, if I have any sense and feeling,
he has had at times to overflow.
I have been at several meetings with him,
in which he has been wonderfully favored to divide the word aright,
to the strengthening and encouraging many who were almost ready to say,
Who shall show us any good? That I have said in my heart, It is the Lord`'s doings,
and marvelous in my eyes!
Oh! says my soul, may He have the praise of his own works; that so whatever we do,
may be to the honor of his great and excellent name.

Your dear husband has had many meetings among those not of our Society;
for which I think him eminently qualified.
I have travailed with him, in my feeble capacity,
fervently breathing for his preservation on the right ground;
and that he may be favored to see the right time of returning to you,
and to reap the rich reward of entire dedication.
As his visit seems drawing to a close, I hope and have no doubt in my mind,
that as he keeps an eye single to his great and good Master,
that He will graciously condescend to be with him in returning to his outward habitation,
giving the enjoyment of that sweet peace that is only purchased by obedience,
and is more to be preferred than corn, wine, or oil; which peace I have had to believe,
you would be a sharer in.
As you keep near to the Fountain of all good.
He will not only be a father to your children, and a tender husband unto you,
but will keep you in the hour of temptation,
and when you are separated from your richest earthly
comfort.--And as dear Christopher keeps his place,
he will find, if I am not very much mistaken, that though he has tender ties,
he must turn his back upon them, and do whatever his Divine Master bids him to do.

My dear husband wishes to be affectionately remembered to you;
and says he feels a near unity with Christopher.
We are at Swansea, where we have come to attend our Quarterly Meeting.
It is near the hour of gathering, so I bid you farewell.

[.signed-section-signature]
Lydia Weeks

At the next Monthly Meeting succeeding his return from this journey,
he again laid before it an exercise which had for some time attended his mind,
to make a religious visit to Friends and others within
the compass of Easton and Ferrisburg Quarterly Meetings.
His friends uniting with him herein, he was set at liberty to pursue his prospect.
This journey, requiring him to leave home so soon again,
is alluded to as a close trial to both him and his dear wife, who, as will be seen,
departed this life, in the mysterious providence of our Father in heaven,
leaving ten children, the oldest not seventeen years of age,
before his return again to the afflicted remnant of his family.
He left home on the 1st of First Month, 1813, and rode to Jacob Gurney`'s,
a worthy Friend who had given up to be his companion; saying,
he believed it to be his duty to accompany him in this journey.

They attended meetings pretty steadily within the limits mentioned.
But as little is said in reference thereto, except the fact of doing so,
it might seem more tedious than otherwise to the reader to insert them all here.
The diary states that on "`First-day we attended Friends`' meeting at Queensbury,
which was large.
Notice being given of our intention of being there,
and a funeral also occurring at the same time,
caused most of the people within some distance to be collected together.
The uncertainty of time, and that all flesh is as grass,
was clearly held up to their view; and,
that the dispensation which we of the present day live under, is the gospel dispensation,
whereof Jesus Christ is the great Minister:
who declared his kingdom was not of this world.
I may say, under a humbling sense of Holy Help,
that He was unto me this day mouth and wisdom;
and many were reached with the incomes of the Father`'s love.
May all praise be given to the great King,
who holds the treasures of wisdom and knowledge.
The meeting concluded in solemn supplication.
Thus we parted in that love, which enables to drink into one cup,
and closely binds together.`"

After an appointed meeting at Lake George,
he alludes to being introduced to a young man about twenty-one years of age,
who had received a gift in the ministry.
He says, "`May he be preserved!
What good examples such are to those that are young,
as well as to some that are more advanced.
My dear young friends, how does my heart, while writing these lines,
flow with tender solicitude for you,
that you may closely attend to the law of the Spirit of life,
the light of Christ in the heart,
which ever has and ever will prove to be a fountain of
life to preserve from the snares of death.`"

It was while he himself was an invalid at Troy, on this labor of love,
that he first heard of his dear wife`'s illness; and very soon after of her death;
with that also of his mother-in-law.
How true is the language of the poet:--"`Woes cluster: rare are solitary woes.`"
This seemed to be an unexpected and very heavy stroke to him.
He says:

I was weighed down with trouble.
Think, dear reader, of the bitterness of my spirit on my own,
and my dear children`'s account!
But I hope I did not exceed right bounds.
Though my heart did ache with sorrow, so that I seemed like sinking under it,
I craved of the Lord to be resigned to His will, and He, the tender Shepherd of Israel,
regarded my cry, and consoled me by His precious presence.
I carefully searched the ground of my leaving my family,
and could appeal to my God that my intention was to obey him, and follow his requirings;
and I dare not think that I had done wrong in leaving them.
Thus I tried to resign all to His blessed will, and to renew my covenant with Him,
promising the great Lord of all, the remainder of my days.

He returned to his lonely home on Fifth-day, the 11th of Third Month, 1813,
having been absent about two months, attended seventy-three meetings,
and travelled more than a thousand miles.

His wife died, as already referred to, the 6th of Third Month, 1813,
as if going into a sweet sleep.
She much lamented the bereaved condition her children would be left in,
and greatly desired her husband`'s and their welfare.
The last words she was heard to utter were:
"`Come, and let us go to the house of the Lord.`"

His journal further states, that--

Through the blessing of the great Caretaker,
who opened the hearts of sympathizing friends,
I was favored to place my children to my satisfaction;
and then removed myself to my much beloved friends Benjamin and Martha Gurney`'s,
where I met with a very cordial reception.
Oh, may the blessing of heaven rest upon them,
and upon those that have the care of my dear children,
who I desire may be trained in the fear of the Lord.
I am well satisfied with my home.
Greater care could not be taken, than is taken by those kind friends with whom I live;
and if they that give only a cup of cold water in the
name of a disciple were not to lose their reward,
how much more shall the blessing descend on those, who, out of a sense of duty,
do so much for one left as I am.
We live together in that love and true Christian
fellowship that enables to drink into one cup.
Behold how good and how pleasant it is!
May the Great Shepherd guard and keep us thus united together in the ever blessed truth.

During Christopher Healy`'s absence from home on this visit,
several letters of encouragement and sympathy were written either to his wife,
or to himself, near the time of, and after her decease.
From these we select the following.
To the former, dated Charlotte, 2nd Mo. 10th, 1818,
there is this endorsement by Christopher Healy "`A letter from Mary Varney to my wife.`"

[.salutation]
My Dear Friend:

Though personally a stranger to you,
yet having been favored to attend several meetings appointed by your endeared companion,
I felt something to arise in my mind after this manner:
What a blessing it is to be favored with such a husband,
who prefers the welfare of his fellow-creatures to every outward tie!
Oh, my endeared friend, mourn not too much for the loss of his company;
for how has he been strengthened, through Holy Help,
not only to sound an alarm to the ungodly, and to invite the wanderers home,
but also to speak a word in due season to comfort them that mourn in Zion!
Oh, how has he indeed been made an instrument in the hand of our God, to encourage these,
and take them by the hand, as it were, in their solitary and depressed situations.
I have great cause to number this among the favors with
which the great Preserver has blessed me,
at a time when I was ready to say in my heart,
'`who shall show me any good,`' or can I much longer endure
under the weight of discouragements which I feel? Oh,
that I might walk worthy of all the favors conferred on me by His Almighty Hand,
who has wrought wonders indeed.
May you, dear sister, be strengthened to give your dear husband up,
though he may be called to lands unknown, and to places far distant from hence.
If this should be, He that has called him to leave all that is near and dear in life,
will be a husband to you in his absence,
and a father and caretaker to your beloved children.
I have felt a sympathy with you not to be described fully by words,
nor conveyed by ink and pen.
Thus with a salutation of love unfeigned, I affectionately bid you farewell,

[.signed-section-signature]
Mary Varney

The next letter, addressed to Christopher Healy,
seems almost prophetical of that forthcoming chastening,
which suddenly and forever severed his dear companion from him.--

[.signed-section-context-open]
Charlotte, Third Month 4th, 1813.

[.salutation]
My endeared Friend,

That regard which I believe Truth itself raised in my mind for you,
is by no means impaired; but often, very often, since we parted has it been revived,
with fervent desires, I trust, for your prosperity as well as my own.
In seasons of greatest retirement, my spirit has craved His holy aid for you,
my endeared friend, believing many trials are allotted you,
on account of the testimony He has given you to
bear for His name and truth before the people.
It has frequently occurred to my mind,
while viewing the favors conferred on you while with us,
whether the enemy will not be allowed to buffet and to try you still more!
But may your faith fail not, my endeared brother.
He that has been with you in six troubles, will not leave you in the seventh,
as you abide steadfast.
I remember, my endeared friend, to whom I am writing;
and it is not with a view to teach you, but as things simply arise in my mind,
so I drop them in that freedom which I trust true friendship confers.

I have felt myself much alone since I saw you; and it frequently revives on my mind,
'`I am like a pelican in the wilderness;`' and there
seems but One to whom I dare to make my moan;
and I have found him all sufficient.
Indeed he has not only enlarged my heart towards my fellow creatures,
but given me that confidence in his Almighty power that enables to
testify that He will give ability to answer His requirings,
even to be mouth and wisdom, yes all in all, to those who trust in Him alone.
May my soul bow in humble reverence before him at all times,
in remembrance of his mercies and great condescension to me, a poor unworthy child.
I have felt like one relieved from a great weight of distress since you were at Lincoln;
for which relief, may gratitude fill my mind to His adorable name.
But you know, my dear friend, the unwearied enemy is ever present on every hand,
and when he cannot prevail to sink the poor tried one below all hope,
he will endeavor to creep in, in some other way--perhaps to exalt the mind,
and to make it appear somewhat in its own view.
May your prayers be for me, that my faith fail not in the trying hour;
but that I may be sustained and supported to the praise of His ever worthy name.

[.signed-section-signature]
Mary Varney.

The following, from the same,
holds out the cordial of tender sympathy to his bereaved and afflicted mind.--

[.signed-section-context-open]
Granville, Fifth Month 4th, 1813.

[.salutation]
My endeared Friend Christopher Healy,

I have had frequently to remember you in your lonesome situation.
But I trust the great Caretaker will care for you,
and sustain and bear up your mind under the many
trials which in his wisdom he may permit.
We read that many are the afflictions of the righteous,
yet the Lord delivers out of them all.
I should esteem it a great favor to see you once more;
but whether this will ever be is very uncertain.
Oh that we may dwell where we may be as living epistles written in each other`'s hearts!
I believe that while I remain in time, and am favored to live in the truth,
I shall not forget you, my beloved friend, who was made an instrument for my help.
I have thought many times since,
that I seemed to myself in a new world where a free air circulated.
Truly I have cause to praise His great Name that works wonders.
May I dwell in humility all the days of my life;
and give the honor and praise to whom jt is due.
If you feel a freedom to write a few lines to me at any time,
they will be very acceptable.
After hearing of your great loss, and as I was musing on your case,
it seemed to arise in my mind to write.
I am your friend, I trust, though I feel at times as the least in the flock,
desiring your sympathy.

[.signed-section-signature]
Mary Varney

John Wilbur also thus writes to him on this sorrow stirring occasion:--

[.signed-section-context-open]
Hopkinton, Fifth Month 23rd, 1813.

[.salutation]
Dear Friend Christopher Healy,

We received your kind salutation of Twelfth Month last,--which was very acceptable.
I had written a few lines previous thereto, in order to send you,
but finding that you were from home, I omitted forwarding them.
But as they were penned under some sensibility and
anticipation of an afflictive dispensation to be meted you,
I think it may not be altogether improper to enclose and forward them at this time.
I can tell you, Christopher, that I ever desire, while here,
to be in such a situation of mind, as to be able to sympathize with the afflicted,
and to be willing to take my share in whatever sufferings are
permitted to assail any of my near and dear friends;
knowing, from a little experience, that the commiseration of a friend,
when I have been afflicted, has been as a precious cordial to my mind.
And now my desire is that you might be enabled
to bear up in your present bereaved situation,
leaning on that Beloved which I hope you are not bereaved of.
Notwithstanding the desire of your eye and of your heart is taken away as with a stroke,
yet I trust there is One, who, although invisible to your outward eye,
you are favored to behold, and your heart to be fixed upon; who is altogether lovely;
yes, far surpassing all earthly ties or outward possessions,
on which the mind may rest and have hope.
All earthly enjoyments are subject to change; but this,
the Beloved of souls and Father of all, is the same yesterday, today, and forever.
He will never wholly forsake those that love Him, and rely on his supporting power;
but he will bear them up as on eagle`'s wings, and often bring them into quiet places,
and speak comfortably unto them; giving them, as it were, vineyards of precious fruit,
and the valley of Achor for a door of hope;
making them sometimes to sing his praise as in the vigor of youth.

When I take a view of your late service, I am ready to say,
that I think you have cause to be thankful that you gave up thereto.
For hud there been a holding back therein,
peradventure it might have added greatly to your affliction when otherways deeply tried.
But now I think you may be comforted in reflecting that you have endeavored to
fulfill the several services pointed out as time and ability were afforded.
May you therefore be enabled to say that this dispensation is from the Lord;
and to adopt the language of Job, that tried servant formerly, '`The Lord gave,
and the Lord has taken away; blessed be the name of the Lord.`'

My wife has been afflicted with sickness for about a month; but is rather on the mend.
She desires to be remembered to you,
and expresses much feeling and sympathy for you under your late loss and afflictions.
Similar feelings are also mentioned by many of your friends hereaway.
I remain affectionately your friend,

[.signed-section-signature]
John Wilbur
