== Chapter VII.

[.chapter-synopsis]
* Attends the Yearly Meeting in New York
* Visits Meetings in Easton Quarterly Meeting
* Religious Engagements at Home
* Visits Friends and Others in the Eastern and Southern Parts of New York, and in Philadelphia Yearly Meeting
* Incident Related of His Entering a Ball-Room

The diary is resumed:--

The latter part of the Fifth Month of this year (1813),
I attended our Yearly Meeting at New York.
The several sittings thereof were favored with the presence of our Holy Head,
who is the life and crown of all our religious meetings.
There I met with some of my dear brethren and sisters from the northward,
where I had made my late visit;
and in remembrance of the sweet unity and fellowship we had one with another,
we were glad and rejoiced to meet again,
believing that the love of Jesus had bound us together.
After my return, I attended some burials,
and had a number of meetings within the compass of our own Monthly Meeting;
most of which were favored.
When at home, particularly, I was exceedingly lonely,
and my feelings not to be described;
visiting my children brought sad and sorrowful recollections,
especially to hear some of them express the loss of their dear mother.
But many times, in the midst of these seasons,
the great Caretaker was not lacking with the comfort of His Holy presence.
Oh may He continue to be my companion!
And I have no doubt He will, if I can but be preserved His devoted servant.

On the 2nd of Ninth Month, I left home in order to visit my sister, Sarah Main;
and to have some meetings within the compass of Easton Quarterly Meeting;
having the concurrence of my friends herein.
Was at Easton on First-day, and was glad to see and sit with Friends of this meeting,
as well as many that were not members; being favored to participate in that love,
that has no bounds.
Afternoon at Cambridge,
where the precious water from under the threshold of the door of the sanctuary,
did flow and become a river to swim in; and we rejoiced in the Lord`'s presence.
Many Friends and others that attended when I was here before, were at this meeting.

The Fifth-day following, I attended Friends`' week-day meeting at Queensbury.
This meeting being composed mostly of Friends,
I desired no notice to be given except to such.
Here I had to set before my brethren and sisters the purity of our profession,
and the Rock from which we were hewn.
Also how our ancient Friends not only suffered for the cause of Truth,
but obtained the victory through Christ Jesus their Leader.
He was made perfect through suffering;
and how highly it behooves us--as professors of
the same holy faith--to be willing to suffer;
and through and over all to stand for the cause and the testimony; that it may not,
through our unwatchfulness, or any other means, fall in the streets.
I did believe, while standing in this meeting,
that if Friends keep to their peaceable testimonies and practice, as well as profession,
that no weapon formed against them shall ever prosper.
For, as it is written, "`When a man`'s ways please the Lord,
he makes even his enemies to be at peace with him.`"

I visited some Friends`' families in this place; and on Sixth-day came to my sister`'s,
in the town of Greenwich; and we were rejoiced to meet again.
Seventh-day had a meeting in the neighborhood, which the Master was pleased to own.
In the afternoon held one at Whipple City, which was small; and I not feeling clear,
requested another in the evening, which was readily granted; and a large meeting it was.
Here the glorious gospel dispensation was clearly set forth,
with the benefit those receive who live under the peaceable government of Christ;
and how inconsistent all outward wars and fightings were with
such a dispensation which was ushered in with the anthem;
"`Glory to God in the highest, and on earth peace,
good will toward men,`" which all such as profess Christianity claim to live under.
This meeting continued near three hours, and was a heart-melting season.
The people appeared reluctant to leave their seats when the meeting was over.
Here I parted with my dear sister; and a heavy parting it was to us both.
May she be favored to live in the truth, and to have the company of Him,
who comforts those that mourn in Zion.

Shortly after this he returned home.
In another short visit he writes of being at a meeting at Othniel Phelps`'; who,
with his wife, had been convinced of Friends`' principles.
"`May they continue,`" writes Christopher Healy,
"`in what is made known to them to be their duty;
so shall their endeavors be crowned with success in the holy warfare,
the weapons whereof are no more carnal,
but mighty through God to the pulling down of strongholds.`"

On First-day, the 20th of Ninth Month,
Christopher Healy attended his own meeting at Stanton Hill, "`wherein,`" he writes,
"`the doctrine of the gospel was clearly opened.
Many people, not of our Society, attended, and a refreshing time it was.
May the praise be given to our gracious Helper.
At the close of this meeting the epistle from the Yearly Meeting in London was read.
The hearing of which brought a sweet covering over the meeting;
and it broke up in a solid manner.
On the Fourth-day following, attended our week-day meeting.
Almost as soon as I had taken my seat, these words came into my mind:
'`Without faith it is impossible to please God.`' On which I enlarged,
showing to my beloved friends,
that the faith which pleases Him works by love and purifies the heart.
I was greatly engaged thereon, to the reaching the blessed witness in the hearts of many.
This meeting concluded in solemn supplication to the King of heaven;
and I believe will not soon be forgotten.`"

Obtaining certificates from his respective meetings, he, on the 6th of Twelfth Month,
1813, left his home, to perform a religious visit to Friends,
and those not of the Society in the eastern and southern parts of his own Yearly Meeting;
and to the same class within the limits of the Yearly Meeting of Philadelphia.
His journal states,
that after taking a solemn leave of the family where he made his home,
it being a precious season, he pursued his journey cheerfully;
having commended his dear children to the protection of the guardian Shepherd of Israel.
After attending a few meetings, he writes of tarrying one night at Zopher Green`'s;
whom he represents as a worthy father in Israel,
his counsel and advice being precious to him.
He alludes to their dear children also as those that were walking in the Truth;
and then adds, "`Oh how helpful young Friends may be to one another,
by being good examples; and this not only to each other, but to the world at large.
What a comfort, too, such are to their religiously concerned parents!`"

This worthy Friend accompanied him to the next meeting.
Notice being given, it was large and much favored; proving to many a watering season.
After meeting, he visited a Friend`'s family in the neighborhood; "`wherein,`" he says,
"`the Great Master favored with that counsel which is bread to the soul.
A heart-tendering season it was to the dear youth present,
may it remain with them as a nail fastened in a sure place,
and the praise be given to Him who alone is worthy.`"

After visiting several meetings and families, with but little comment thereon, he,
with his companion, Samuel Seaman, passed into Pennsylvania, and attended Stroudsburg,
Easton, Plumstead, and Abington meetings, and from there on Third-day,
to Thomas Scattergood`'s, in Philadelphia,
who kindly accompanied them to the three Monthly Meetings in the city.
The memoranda continue:--

These were mostly favored meetings; and Friends of Philadelphia showed us much kindness.
Sixth-day, accompanied by Thomas Scattergood and Thomas Norton,
we attended a meeting appointed for us at Germantown.
In this meeting I was led to speak of the glorious gospel dispensation,
contrasting it with that of the Law.
That the outward wars, under the dispensation of the Law, are to be spiritualized;
and it is thus that they convey divine instruction to us of the present day.
For the day prophesied of by Jacob of old,
has come to pass that "`The sceptre shall not depart from Judah,
nor a lawgiver from between his feet, until Shiloh come;
and unto Him shall the gathering of the people be.`"
This Shiloh, which is Christ Jesus, is come to teach his people Himself;
and happy are those who are taught of the Lord: for great will be their peace.
I was very much enlarged on this subject, to my own comfort and satisfaction,
and to the tendering of many minds.
Near the close of the meeting, Thomas Scattergood stood up and said,
that the gospel dispensation had been clearly pointed out,
and spoken to in a lively manner;
and his heart was made glad that these things were so cleared up.

First-day, was at Horeham meeting.
Many Friends and others attended.
It was a time of favor.
The manner in which our Savior was born;
the way in which he was preserved from the wrath of Herod; his life and doctrine;
and the benefit and blessed effects of his spirit on the mind, were clearly spoken to;
and I believe it was a profitable season to many present.
One aged Friend, after meeting, greeted me kindly;
and told me I had labored faithfully among them; and said,
"`you will have your reward.`"
Second-day was at Buckingham Monthly Meeting,
where I had to remind them of our great and holy profession.
They were exhorted to live consistently therewith, that they might be lights in the world.
Third-day attended Monthly Meeting at Solebury;
and that evening had an appointed meeting at Buckingham, which was large.
Fourth-day at Wrightstown Monthly Meeting;
and in the evening attended a meeting appointed for our Friend T. H., from New York:
a favored time.
This meeting was at a village called Newtown.
Fifth-day was at Middletown Monthly Meeting; and had a public meeting in the evening.
Sixth-day at Falls; and a public meeting in the evening.

All of these meetings were owned by the Shepherd of Israel.
Friends were mutually comforted,
and my soul had to rejoice in deep humiliation before the Lord,
from whom all our strength does flow.
Seventh-day had a meeting at Makefield, where many hearts were tendered;
and it was evident that the good Shepherd watered and fed his flock;
and opened their minds to see his glorious rest,
that he had prepared for those that follow him.
That evening had a sitting in a family, to satisfaction.

First-day morning, my dear companion, Samuel Seaman, parted with me, and returned home.
We parted in that love that had enabled us, while together, to drink into one cup.
I came that day to Bristol meeting.
Here the Lord caused his baptizing power to descend, which made my cup to overflow;
and many hearts felt living praises to ascend to our Heavenly Father.
Oh Lord!
You who are strength in weakness,
and whose living stream does water your poor depending children,
I have great cause to be humbled before you,
for you have never failed to help in the needful time, as my faith has been unshaken,
and my eye and expectation has been unto you.
Oh! may I be preserved in a holy dedication of soul unto you,
for truly I have found there is none like unto you, who have the words of eternal life.
Under a realizing sense of your great power and merciful hand
extended to me in this remoteness from my own abode,
do I bless your great Name.
It is your love that has opened the hearts of Friends in this land,
as well as the hearts of the different denominations of professing Christians,
to hear the blessed words of truth.
How often has your word, O Lord, been as a fire and as a hammer,
to the melting and breaking everything that opposes your glorious reign.
Be pleased.
Oh blessed Father, in and through your beloved Son,
who alone can preserve under the operation of your truth,
to keep those whom you have reached unto in your lovingkindness; that they,
with my poor soul, may be strengthened to ascribe all honor and glory, might and power,
unto you, and to your dear Son, forevermore.
Amen.

Second-day attended a meeting appointed for me at Byberry.
I felt great weakness to attend my mind in the morning,
which continued until I sat down in the meeting;
but as I endeavored to keep my eye to Him who is strength,
He did prove to be strength in my weakness; and truth reigned over all.
Many not of our Society attended, and among them were some colored people.
The great Master descended and did break and hand the bread of life to the multitude,
to the rejoicing of the dear children of the heavenly family.
Third-day, at a village called Smithfield, had a very crowded meeting.
Fourth-day, attended Friends`' meeting at Byberry; a very large meeting.
Afternoon we were at Bustleton.
Fifth-day at Holmesburg; they were large,
and favored by the overshadowing of Divine love, that caused many hearts to rejoice.
Sixth-day had a meeting at a place called Goosetown.
Seventh-day, at a village called Milford;
a more crowded meeting I have not been at in this land.
The Great Master made known his lovingkindness, and many rejoiced in his presence.

First-day, crossed the Delaware to Trenton, and was at Friends`' meeting there,
which was small.
Stayed that night at Joshua Newbold`'s--a precious family.
There met me here a kind Friend by the name of Simon Gillam, a minister.
Had a meeting appointed next day at Trenton.
Third-day, at Stonybrook.
Fourth-day, at Bordeutown.
Fifth-day at Crosswicks.
Sixth-day, at Lower Mansfield; and in the evening at Bordentown.
Seventh-day at Upper Mansfield; mostly favored meetings.
At the last meeting came two kind Friends, Robert Pitfield and Elizabeth Allinson,
from Burlington, to meet us.

First-day attended meetings at Burlington, both fore and afternoon;
where we had the company of our beloved friend Henry Hull.
General notice being given, the meetings were large,
and Owned by the Master of our assemblies.
Here belong our aged friends, John Hoskins, George Dillwyn, and John Cox.
In the evening, made three religious visits in the town, namely, at John Hoskins`',
William Allinson`'s, and Nathaniel Coleman`'s. These were precious seasons;
the families being alive in the Truth.
This when accompanied by the Shepherd of Israel, which was our happy experience,
makes such seasons refreshing.
This evening returned to Robert Pitfield`'s; whose wife is a living member,
which causes her conversation to be refreshing to a weary mind.
She is but twenty-five years of age.
Here we parted with our kind, friend Joseph Satterthwaite,
who had been with us for several days.
Next day Robert Pitfield took us in his carriage to a meeting at Westfield.
Third-day to one at Rancocas.
After meeting we went home with our friend Samuel Wills,
where we were sweetly refreshed both in body and mind,
feeling the Great Master was there.
Fourth-day attended a meeting at Mount Holly.
Fifth-day, one at Moorestown.
Sixth-day at Newtown.
That evening we crossed the Delaware to Philadelphia: and Seventh-day rested.
First-day morning was at meeting at the Northern district.

He then attended in succession the Monthly Meetings of Chester, Darby, Goshen, Concord,
and Wilmington, together with the Almshouse of Chester County,
during one of the evenings; and on the next, which was Seventh-day,
he attended the select Quarterly Meeting in Philadelphia.
Resuming the journal--

First-day morning, I attended the meeting at Arch Street; wherein I was silent.
Afternoon, at Pine Street; where I was again silent.
Second-day, attended the general Quarterly Meeting at Arch Street.
Our friend Henry Hull was favored in testimony.
Towards the close of the meeting for worship, I had a few words to offer.
Third-day, had a meeting at Frankford; which was to satisfaction.
Fourth-day, at the select Quarterly Meeting of Abington, wherein I was favored.
Fifth-day, the Quarterly Meeting.
The business of Society was transacted with brotherly love and condescension,
and concluded to the encouragement of each other.
Sixth-day attended a meeting appointed for us at Merion.
Rode that night to Edward Garrigues`'. Seventh-day, rode to Darby;
and rested at Thomas Garrett`'s, who are loving and kind friends.

First-day, at Darby meeting, which was large,
being composed of Friends and those not of our Society.
It ended to mutual satisfaction.
That evening rode to Concord.
Second-day, attended the meeting of Ministers and Elders.
Third-day, that for discipline; wherein, through Divine help,
I was favored to relieve my mind, to my comfort, and the satisfaction of many.
After meeting, rode to Philip Price`'s, who, with his wife,
went with us to Cain Quarterly Meeting.
I had many stripping and baptizing seasons, about this time,
but was favored to abide in the patience.
At this Quarterly Meeting I was helped, towards its conclusion, to relieve my mind.
Stayed that night at J. K.`'s. Next day attended a meeting by appointment at Westchester;
wherein I was silent, being resigned to the will of my Divine Master.
That afternoon rode to Thomas Garrett`'s, at Upper Darby,
where our dear friends were glad to see us.
Seventh-day, reached the neighborhood of Byberry.
Next day attended meeting there,
where were a great number of people of different professions.
It was a precious meeting by and through the help of Israel`'s King,
who does anoint afresh for his work and service, as he is waited for in humble patience.
Oh! blessed and adored be the name of the great Minister of
the sanctuary who still remains to be mouth and wisdom to
those that stir not up nor awake him until He please.

This afternoon rode to Isaac Parry`'s,
attended by a young Friend by the name of James Thornton,
grandson of that eminent minister James Thornton, of Byberry.
Second-day had a meeting at the almshouse of Bucks County, with the sick and afflicted.
This is the second of this description that I have found it my duty
to visit since I have been within the limits of this Yearly Meeting.
Oh, what lessons of deep instruction these have been to my mind.
My pen is not able to represent to the full, my sympathy with these poor creatures.
Some have lost their reason, so as to be quite distracted.
Some are cripples.
Some groaning with severe pains,
who expressed that they did not expect to live many days; exclaiming,
"`O! if I could but be happy, it is all I ask.`"
How thankful they were, that we thought so much of them as to have a meeting with them.
It seems to me that pure religion, under the immediate,
quickening power of the great Opener, leads to visit these.
Oh, may I never forget these seasons; and may you, that read these lines,
be favored to feel as I now feel.
If so, it will humble the mind as in the dust, and raise living intercessions,
that the Lord would bless these poor creatures; and although they receive, as it were,
their evil things in this life, that they may be prepared for endless rest at last.

Second-day afternoon, had a meeting at Doylestown,
which ended to a good degree of satisfaction.
Third-day, made a visit to a settlement of Germans called Mennonists.
They are a plain people; both young and old being exemplary in this respect.
They have also a testimony against war.
The meeting was a satisfactory one;
and they expressed their thankfulness for our visit to them.
That afternoon rode to John Watson`'s. Next day attended
Bucks Quarterly Meeting of ministers and elders,
held at Wrightstown.
In the afternoon had an appointed meeting about six miles distant, at a public house.
Fifth-day was at the Quarterly Meeting, to good satisfaction.
Sixth-day had a public meeting at Wrightstown, appointed at nine o`'clock in the morning.
It was a large and favored meeting.
Another at Yardleyville in the afternoon.
That evening came to our friend John Miller`'s, who with his family are choice Friends.
Here I was joined by William Taylor, a dear and truly sympathizing friend and help-mate.
He has also a precious gift in the ministry, though not so large as some.

After visiting a few more meetings, with some families in and about Bristol,
and crossing the river into the neighborhood of Burlington, he went to Vincentown,
where he had a meeting on First-day, the 6th of the month.
He thus again writes:--

It was attended mostly by those not of our Society.
Here we were Sweetly refreshed together.
In the evening had a meeting with the few Friends by themselves;
wherein the Truth was held up; and our principles, with our high and holy profession,
opened in primitive purity; and they were exhorted to cleave thereto.
This was a precious little meeting;
and notwithstanding there appeared a great slackness in some,
yet I believe they felt renewedly concerned to double their diligence.
We parted in great love; our minds being drawn near to each other.
Oh, how precious is the love of Truth!
How it unites together.

Second-day, had a meeting at Lumberton, in a Methodist meetinghouse,
to good satisfaction.
From here I went home with my dear friend Josiah Reeve.
Next day had an appointed meeting at Upper Evesham.
Fourth-day at Easlon.
Fifth-day attended the Monthly Meeting at Moorestown.
Here the honest-hearted were comforted; the lukewarm were warned;
and the dear youth invited.
Sixth-day at Evesham Monthly Meeting.
Seventh-day, Monthly Meeting at Upper Evesham.
Here the Divine Master enabled to lay justice to the line, and judgment to the plumb-line.
The meeting concluded to the comfort of many.

First-day was at Cropwell, a branch of Upper Evesham Monthly Meeting;
a large and satisfactory meeting.
Second-day at Haddonfield Monthly Meeting.
Silent, except a few words in the meeting for discipline.
This meeting was hurt by the youth going out at the close of the meeting for worship;
some of them tarrying a considerable time.
Oh that all Friends, old and young,
might be careful how they disturb the quiet of meetings by coming late,
or going in or out unnecessarily.
Remembering that both meetings for worship and discipline,
ought to be held in the authority of truth.
Then they will prove edifying and strengthening.

The next Fourth-day attended the select Quarterly Meeting at Haddonfield;
wherein our friend Richard Jordan was greatly favored.
That evening rode to Benjamin Swett`'s, distant about four miles.
He and his wife are worthy ministers.
Fifth-day was at the Quarterly Meeting of Haddonfield.
It was an open time, the glorious truth being in dominion;
of which many present were sensible.
Richard Jordan, a father in our Israel,
concluded the first meeting in solemn supplication;
and under the precious covering granted,
Friends`' minds were prepared to transact the weighty concerns of the church.
That evening rode to Benjamin Cooper`'s. He and his family are good examples,
and prefer Jerusalem`'s welfare to their chiefest joy.
Although they have considerable of this world`'s goods,
yet they have the blessed cause at heart.
This tends to keep the worldly disposition in subjection to the power of Truth;
whereby if they continue to live in the same, they will be enabled to be good stewards.
May this consideration have place in the minds of those who have large possessions.

Christopher Healy attended some more meetings,
principally within the limits of the Southern and Western Quarterly Meetings;
also the almshouse of the State of Delaware,
a service for which his sympathizing mind with the afflicted,
seemed particularly to draw him.
He then went to Westtown School, to which he thus alludes:
"`Had a meeting with the scholars, which was a precious season.
Oh, the innocent sweetness that was felt among them!`"
Not long after this he rode to Philadelphia, preparatory to the Yearly Meeting.
The diary resumed:--

Seventh-day attended the select Yearly Meeting, which was divinely favored.
First-day, five meetinghouses were opened for worship.
Second-day, the 18th of the Fourth Month, 1814,
the business of the Yearly Meeting commenced; which through the several sittings thereof,
was owned by the Great Shepherd, and conducted in brotherly love and condescension.
It concluded on Sixth-day, the 22nd of the month.
Our beloved friend, Thomas Scattergood, left this yearly meeting on Fourth-day,
being unwell: which illness increased, and proved to be the prevailing fever.
On First-day evening he resigned his soul to Him that gave it.
Though his family and the church have met with a great loss,
yet for him they have no cause to mourn.
He has left a sweet savor behind him, and his memory will be pronounced blessed.
He has been as a father to me.
May we that are left behind, follow him as he followed Christ.

Our friend had some religious service on his way, but except this,
he proceeded pretty directly from Philadelphia Yearly Meeting to that of New York.
The memoranda continue:--

Seventh-day, the 21st of Fifth Month, attended the Yearly Meeting of Ministers and Elders.
And on Second-day that for business came on.
Through the several sittings of this Yearly Meeting,
the Divine Master was pleased to favor us.
We had the company of William Flanner, from Ohio, Micajah Collins from New England,
and many other strangers.
The meeting concluded on Fifth-day, the 26th.

After the conclusion of the Yearly Meeting, he turned his face homeward;
taking some meetings on his way.
One with the Methodists, which, he writes,
he had had a prospect of for nearly three years, proved to the relief of his mind.
He reached home on the 10th of Sixth Month, 1814. To which, in his journal,
allusion is thus made:--

Rode home to my dear friend Benjamin Gurney`'s, where I was kindly received;
and can say I feel a thankful heart to the Lord, who,
by His divine voice called me forth,
and by his divine power preserved and strengthened me to perform what he required,
to the praise of his own eternal Name.
I was out on this journey six months and ten days;
attended two hundred and seven meetings, and travelled by computation two thousand miles.

The following circumstance,
which it is believed took place while he was a resident in the State of New York,
is not in Christopher Healy`'s journal;
but its authenticity being substantiated by a Friend who heard it from his own lips,
we have thought good to present it here.
It tends to show not only the respect which was paid him by citizens of his neighborhood,
but also the power of the Spirit,
which wrought in and through him to the conviction of many minds.

"`We had been speaking,`" says the writer of this,
"`of the trials and faithfulness of Sarah (Lynes) Grubb, and Christopher remarked,
that other Friends were sometimes brought into close trials of faith.
In confirmation of this, he said he was once travelling on the 4th of the Seventh Month,
and the time had fully come for feeding his horse.
It was a few miles from Albany;
and he stopped at a tavern kept by two brothers whom he knew very well,
and put his horse under the shed.
The hostler came and gave the horse his oats.
Presently the sound of a fiddle was heard in the house,
and Christopher knew there must be a dance going forward.
He became a good deal disturbed,
under the thought of what people would say if he should be found on such a day,
at a tavern where a dance was going on.
It would bring discredit, he thought, on his profession.
He quickly decided to proceed; and was about mounting his horse,
when he heard the language,
You must go into the dance room!`' This he thought was out of the question,
and a delusion, and he`'d do no such thing.
So he rode off slowly, but with a heavy mind.
Feeling so uncomfortable riding, he dismounted and tried walking; but it was no better;
the exercise continued.
Again he heard the voice, and again strove to put it away as a delusion.
The third time the admonition was '`Perhaps you will never have another
opportunity to warn these people.`' '`If it comes to that,`' said Christopher,
'`I must go back.`'

"`Mounting his horse, he returned to the tavern,
put it under the shed to finish the oats, and proceeded into the house.
The senior of the young men who kept the house, he found in the bar-room,
and inquired of him if he might go into the dancers`' room? Though doubtless astonished,
the landlord said, '`You may, Mr. Healy, if you desire it.`' On being requested to do so,
he also went with Christopher upstairs and opened the ballroom door.

The floor was occupied by the dancers, and the fiddler was engaged in his vocation,
when the unexpected appearance of the plain Quaker burst upon their astonished vision.
Instantly the tones of the fiddle ceased,
and the dancers retired to the seats placed around the room.
The junior landlord came forward instantly, seeing his gain was likely to be disturbed,
and said, '`Oh, Mr. Healy, you can`'t preach here? '`But,`' said Christopher,
'`only let me ask the young people a question.
Would you be willing to get into the quiet a little
time?`' The company very generally gave assent;
but the young landlord interposed, and said, '`Any other time, Mr. Healy,
we shall be glad to hear you, but positively not now.`' '`Well,`' continued our friend,
'`If you will not allow it, I shall be clear, and must leave it on you.`' He then departed,
and went with a light and cheerful heart on his road.

"`Some time after, Christopher met with the young landlord,
who told him that he had felt very much troubled whenever he
had thought of having stopped him from speaking to the dancers;
and desired him to have a meeting appointed in that dance-room,
and he would take care to have all the company that were then present invited.
The proposal took hold of Christopher`'s mind,
and after consulting with the select members of his Monthly Meeting,
he felt easy to appoint a meeting in this large room of the tavern.
Very special care was taken by the young landlord to
have all the company of the Fourth present,
and Christopher added, '`That he never remembered to have had a more satisfactory meeting;
the floor being a good deal wet with the tears
of his auditors.`' After the meeting was over,
the young landlord told Christopher,
that his object in going into the room at the first was so far accomplished,
that there was not another sound of the fiddle,
or a single dance after he went into the room that day;
but that they all departed to their respective homes as
though they had been at a Quaker meeting.`"
