== Chapter VIII.

[.chapter-synopsis]
* Marriage to Sarah Miller, of Bucks Co., Pa.
* Pays a Religious Visit to Some Parts of the New England States
* Pays a Social Visit, with His Wife, In Pennsylvania
* Holds Meetings in Connecticut, Massachusetts and Rhode Island
* Visits the Western Part of New York State, and Some of the Indian Tribes There
* Visits the Southern and Western States
* Again Visits Some Parts of the Southern and Western States
* Interview with Four Men Under Sentence of Death at Goshen, New York
* Removes to Bucks Co., Pa., and Opens a School
* Visits Friends and Others in the Northern and Eastern States
* Visits Friends and Others in New York and Upper Canada
* Letter to His Wife
* Remarks after Holding Meetings with Indians

On the 12th of Tenth Month, 1814, Christopher Healy was married to Sarah Miller,
daughter of John and Sarah Miller, of Bucks County, Pennsylvania.
She being one that he believed would make him a helpmate in the Truth.

After his marriage, he did not go much abroad, until on the 24th of Tenth Month, 1815,
with the unity of his Friends,
he left home to pay a religious visit to some parts of the New England States.
While on this visit,
after a favorable allusion to the parents and children
of a family in which he was much interested,
he thus concludes: "`May all parents consider the importance of their trust,
which is nothing less than being guardians over them for the Lord.`"
He also alludes to a satisfactory meeting he had at Bath,
upon which he makes the following remarks: "`I often say in my heart, good is your word,
O Lord!
Worthy are you to be waited upon and obeyed.
May I never move without your anointing being renewed upon my spirit.
So shall I be enabled, through Your power, to teach transgressors your ways,
that sinners may be converted unto You.`"

After this, again resuming the diary, he says:--

I was at Durham meeting, which was very large; many not of our Society being at it.
My mind was deeply humbled before the living God;
and herein my soul was brought truly to wait upon Him,
and in Him was my strength renewed.
I was afterwards enlarged in the doctrines of Truth.
May my soul be kept humble,
and may such seasons be sanctified to the people for
their improvement in the way of life and salvation.
From here I wrote the third letter to my dear wife.
When I contemplate our separation for the Truth's sake, my soul is thankful to the Lord;
who is able to strengthen to bear this and every other cross, and will,
if we continue faithful in all to Him, enable us through mercy,
finally to wear the crown.
The following intercession also arose in my heart at this time on her behalf: May You,
dearest Father, be to her precious mind as a husband;
and so strengthen her that she may not repine.
Fill her soul, if it be your good pleasure, with your good things;
that so she may joy in the Lord, and rejoice in the God of her salvation.

May we, though far separated from each other, yet be sweetly united in your Holy Spirit;
and at all times give You the honor and the glory,
who can and will make hard things easy, and bitter things sweet.

This journey throughout appears to have been to
the satisfaction of Friends where he travelled,
and to his own peace.
One little extract from the record he has left of it, shows who was his sufficiency;
and where and how his strength was sought and found: "`Oh, dearest Lord,
keep me sufficiently humbled under a sense of my own inability
to do anything that will advance Your glorious cause!`"

Upon reaching home,--we quote again from the journal:--

My dear wife and family received me with joyful hearts.
We felt thankful to the great Preserver of men, that he had not only led forth,
but brought again in peace.
Blessed be the name of the Lord.
I was absent on this journey eleven weeks; travelled one thousand one hundred miles;
and attended over sixty meetings.

About three weeks after my return home my wife and I
went to Pennsylvania to visit our relations;
and had a number of satisfactory meetings thereabouts.
In attending Bucks Quarterly Meeting,
my heart was brought into mourning to see in so many of the
young people a departure from our testimony in relation to
plainness.--Counsel was given suitable to their states.
May it be sanctified to the dear youth.
The meeting ended well.
We found our relations well, and returned home in about seven weeks.

Christopher Healy did not at any time long rest from religious service abroad.
In the Sixth Mouth of the year now reached (1816),
not feeling his mind clear of the New England States, he again went forth,
and held some meetings in Connecticut, Massachusetts, and Rhode Island,
and attended the Yearly Meeting there.
He returned home in about five weeks,
with the reward of peace.--"`Blessed,`" he hereupon writes,
"`be the great Shepherd, who, when he puts forth, goes before.`"

His next concern was a visit to the western part of the State of New York;
and to have some meetings with the Indian tribes there.
Obtaining the unity of his Friends, he left home on the 5th of First Month, 1817.
He had a number of meetings, both among Friends and others, including the Indians;
of which he states, particularly in allusion to the latter,
that they were to great satisfaction.
He was from home about six weeks.

On the 12th of Eighth Month, 1817, Christopher Healy writes:
"`I took an affectionate leave of my dear wife and tender children,
and being joined by my kind friend Robert Nelson,
proceeded on a visit to the Southern and Western States.`"
Of this journey our dear friend has left but little,
except an account of the meetings he attended, and the places at which he tarried.
After getting home, he thus records his gratitude:
"`May the Lord be praised forever--the great Minister of ministers--
who has brought me again to my precious family in peace.
My soul is humbled under a consideration of these favors.`"
And shortly after, his pen thus dwells upon the Lord's mercies,
and sets forth his praise:--

What shall I render, O Lord,
unto You for all your benefits? You that redeems from destruction!
You that crown with loving kindness and tender mercies!--May
you continue to preserve from temptation,
and deliver from evil; and strengthen me, O Lord, to perform your requirings.
It is You, Blessed One, that can bend my mind, and enable me to say, Your kingdom come:
Your will be done in my heart, as it is done in Heaven.
So shall my poor soul praise You, who alone are worthy.
Amen.

Feeling his mind again drawn in gospel love to visit
some parts of the Southern and Western States,
he left home therefor, with the unity and sympathy of his Friends,
on the 19th of Eleventh Month, 1818, accompanied by his friend and former companion,
Robert Nelson.
On his way southward, he attended Bucks Quarterly Meeting;
and had an appointed meeting at Trenton, which he writes was large and much favored.
At Germantown he records being exercised strongly against the love of the world.
Arriving at Baltimore, he says, "`I received a truly sympathizing letter from my wife,
which cheered up my mind.`"
In this city he attended the Monthly Meeting for the Eastern District, which, he writes,
was "`to some satisfaction.`"
The Western District "`somewhat trying.`"
A public meeting being appointed in the evening, it was large.
He says,--

I went to it under great poverty of spirit.
After a time of reverential silence, feeling the power of supplication poured forth,
my poor soul addressed the Throne of Grace.
Then was the way open to minister from these words,
"`If any man have not the Spirit of Christ, he is none of his.`"
Showing from there the necessity of being in Christ, that so our salvation may be sure.
This meeting ended to our great comfort.

Next morning visited two sick Friends;
one of them being near her end with a cancer in her breast.
Oh the sweetness of her spirit!
Her cup was made to overflow with Divine love.
She was patiently waiting and quietly hoping;
and it was evident she was borne up of Him who is everlasting strength.
May the Lord continue to be her support to the end.

Passing into Ohio, under date of the 5th of First Month, 1819, he thus writes:--

Was at Flushing; a crowded meeting.
The doctrine of the peaceable kingdom of the Messiah was held up to view,
which lays waste the kingdom of Antichrist.
Oh! may this be the happy experience of all mankind.
At Zanesville, on First-day, attended a small meeting of Friends.
Had hard labor, but was favored to relieve my mind.
Oh the love of money! which, while men covet after, they err from the faith,
and pierce themselves, and those that are concerned for their welfare, with many sorrows.

At Waynesville, Springborough, Lebanon Court House, he held meetings;
and in the evening one at the same place, for the Methodists.
These, he writes, were large and favored.
"`The minds of the people were opened to receive the truth,
and many hearts were comforted.
My own soul could say, great is the Lord,
and greatly to be praised in the city of our God, in the mountain of His holiness.`"

Next day he attended Friends' meeting at Cincinnati; and in the evening appointed one,
which was held in a Methodist meeting-house.
"`A very large number attended; and a favored time it proved.
Blessed be the name of Him who is the Helper of his people.
Next day visited some that were sick,
including one at the poorhouse--a young man who went from New
York to this western country in search of his father;
but did not find him.
Meanwhile he was taken sick, and being out of money was conveyed to the almshouse.`"
When Christopher Healy went in to see him, he perceived he was dying,
and he lived but about seven hours afterwards.
The case of this poor stranger excited much
tender feeling in the mind of Christopher Healy.
The same evening he had a meeting for the people of color, to their mutual comfort.
"`How true it is,`" exclaims Christopher Healy,
"`that the Ethiopians shall stretch out their hands to God.`"

He got to John Miller's, his father-in-law,
where he left his family on the 27th of Second Month;
and states that he found his dear wife and family all well;
and were greatly rejoiced to meet again in the Truth.
That the reward of sweet peace was granted them,
in resigning each other for the sake of that cause which is dignified with immortality,
and crowned with eternal life.
From here, on their way home, he attended some meetings;
and being at the house of one of his friends,
he was informed that there were four men in Goshen jail,
about twenty miles from where he was, under sentence of death; having committed murder.
His memoranda thus gives the affecting relation:--

Feeling my mind drawn to make them a visit, in company with two of my friends, I went.
The jailor seemed kind, and was willing we should make the poor criminals a visit.
He also, in a respectful manner, waited upon us to the different apartments of the prison.
Oh what a shocking sight were these poor creatures!
In a religious opportunity, some of them were much affected,
and wrung their hands with grief.
My soul was deeply stirred while I sat with them.
All but one were sensible of their wicked deed.
That one appeared hard-hearted.
One, a colored man, honestly confessed the deed, and said he was hired for money.
He said keeping bad company had brought him there.
I asked him if he had found forgiveness? He said not;
but he meant to beg to Jesus as long as he lived.
I felt to say to the poor man, that if he continued in that humble, begging state,
I believed he would find pardon.
I felt very desirous that these poor objects of
pity would be enabled to obtain forgiveness.
I thought this sad scene was as great a sermon as ever I heard.
Oh may these lines prove a warning to those that read them.

On Fifth-day, the 18th of Third Month, 1819,
they reached home with thankful hearts to the Preserver of mankind.
He adds, "`Blessed be his holy Name forever.`"

The following summer and autumn he attended Nine Partners,
and Stanford Quarterly Meetings;
and had a number of meetings with those not of our Society; which yielded peace.

In the Ninth Month of 1820,
he visited the meetings in the western part of the State of New York.
Was absent from home about three weeks,
and returned with the incomes of his Master's approbation.
This year (1820), he removed with his family to Bucks county, Pennsylvania.
He thus alludes to it in his journal, which is, for a time, resumed:--

Having for some time believed it would be right to remove with my family to Bucks county,
and having settled my outward concerns, and my children being willing to part with us,
we took a solemn leave of children and friends in the Eleventh Month of 1820,
and came here.
My family consisting of myself and wife, with four small children.
we settled within two miles of the Falls fleeting,
and were comforted in being among our friends.
we had also many precious meetings together,
which were owned by the good Master's presence.
Soon after settling here, I opened a school near our home, many children attending.
This is an employment which always suited me,
when I felt released from travelling on Truth's account.
I continued my school, only attending meetings at home, with some neighboring ones,
until in the spring of 1822 I opened a concern that had rested with weight on my mind,
to pay a visit in gospel love to Friends and others not in membership with us,
in some parts of the Northern and Eastern States.
Obtaining the unity of the Monthly and Quarterly Meetings,
I left home in the Fifth Month, accompanied by my dear Friend Moses Comfort,
an elder of the same Monthly Meeting.
We appointed some meetings on the way, which we attended to satisfaction.
Getting to New England Yearly Meeting, held in the Sixth Month,
we met with our dear friend George Withy, from old England.

After this, upon coming to Nantucket, he says:--

We had some very large meetings on this island;
the inhabitants seeming ready at the notice given.
We were here one week.
Were at both their Monthly Meetings; and parted in much tenderness and love.
From here we went into the State of Maine,
and travelled as far eastward as the Kennebec river.
Then returned through New Hampshire and Vermont to New York;
and had many precious meetings.
From there to Long Island.
Here we found some Friends very uneasy concerning sentiments held by Elias Hicks;
who lived at Jerico, on this Island.
Some of us had been doubtful for several years of his soundness in the true
faith of our Lord Jesus Christ.--After our visit on Long Island,
we returned to New York.
Hence by Shrewsbury and Rahway, on home; and found my dear wife and family well.

His journal continues: "`Staid at and about home, visiting meetings,
and attending to such concerns as Truth required of me, until in the Twelfth Month, 1823,
having previously opened a concern to perform a visit, in gospel love,
to Friends and those not in membership with us, to some parts of New York State,
and Upper Canada, I set out with my brother-in-law, John Miller, Jr., as companion.
We went by New York, up the North river,
and had many favored meetings with Friends and others.`"

While out on this visit, he thus wrote to his wife:--

[.signed-section-context-open]
Queensbury, 12th of First Month, 1824.

[.salutation]
My dear and loving Wife,

I embrace the opportunity this morning to inform you of my health.
I received your letter, which made me to rejoice.
I am comforted in finding you are so thoughtful concerning the
great work that your dear husband believes himself called to.
May the Holy Hand bear you up in your lonely seasons, and may you, my dear bosom friend,
pray for me, that my faith fail not.
So shall I be resigned to our Divine Master's will,
and also cheered by the hope that we will meet again in that love in which we parted.
I may tell you, that the Good Hand that called me to go forth has been near,
and we have had many favored meetings with Friends and those not of our Society.
Yesterday we were at Queensbury, where the Good Master's presence was our crown.
May He have the praise, who alone is worthy.
Our present prospect is next to go towards Black river.
I have found Friends, so far, in this northern country, generally sound in the faith.
O, may the Lord preserve this people, whom he has raised up to show forth his praise,
in the true faith of our Lord and Savior, Jesus Christ.

And now, dearly beloved,
we sympathize together.--Though far separated from each other in body,
we are present in spirit, serving the Lord.
May we be enabled to have our faith strengthened by the blessed
promise to those that love the Lord more than wife or children,
houses or lands--They "`shall receive a hundred-fold,
and shall inherit everlasting life.`"
In this belief we were joined together;
being well assured we should have to resign each other to our Divine Master's disposal.
Farewell in the everlasting Truth.

[.signed-section-closing]
Your loving husband,

[.signed-section-signature]
Christopher Healy

Wishing to get to the HalfYear's Meeting in Upper Canada,
they crossed the river St. Lawrence.
This was attended with much difficulty;
owing to the ice on the river being too thin to bear their horses,
and yet so thick as to prevent the use of boats.
After much risk and toil they finally got safely over; when they all for a time sat down,
and felt their hearts bowed in thankfulness to the Great
Preserver of men for His merciful help and protection.
Before parting with the ferryman and his helpers (a large
number having assisted in getting them over the river),
they asked for the fare across.
The ferryman said:

"`I consider we have risked our lives for the
sake of helping you on in the line of your duty,
and I cannot take money for it.`"
And the rest all agreed therewith; saying,
we were perfectly welcome to all they had done;
and that they were thankful in being able to help us on our way.
We were favored to get to the Half-Year's Meeting at West Lake in good season;
and had a comfortable time with Friends there.
Also visited most of the meetings belonging to the Half-Year's Meeting,
and had some meetings among different tribes of Indians: I trust to their,
as it was to our comfort.

Oh these poor children of the wilderness, how my heart feels for them!
When I contrast our favored situation with their sufferings, I am humbled as in the dust.
I have believed when sitting in meetings with them, that every thoughtful mind,
if made acquainted with their situation, must feel sympathy and tenderness for these,
our poor afflicted brethren and sisters in the creation of an Almighty Father;
they being also equal objects of redeeming grace.
My desire is while writing these lines,
that it may sink deep in the minds of all the white people, especially our rulers,
to consider their case; and remember our Blessed Savior's saying,
"`As you would that men should do to you, do you also to them likewise.`"
I fear that many who profess to be the follower of Christ,
fall short of living up to this rule that our dear Lord has laid down.
Oh may it not only be remembered in the case of the poor Indian,
but in that of the afflicted sons and daughters of Africa, yes, likewise,
in all our dealings one with another.
For true Christian principles will surely lead
to the faithful observance of this blessed rule.

After feeling my mind clear of Upper Canada,
we crossed the Niagara river a little below Buffalo, and came into the United States.
After which, we had a meeting with the Buffalo Indians.
This tribe is a part of the Six Nations.
Red Jacket and Cornphinter, with another Indian chief,
and a large collection of other Indians, both male and female, came to this meeting.
They sat remarkably solid; much becoming such an occasion.
I spoke by an interpreter that Red Jacket brought with him.
It was a favored time.
From there we travelled homeward through the States of New York and New Jersey,
taking meetings on our way.
Upon reaching home I found my family well.
O, may my soul give the glory to Him, who is glorious in holiness,
and ever worthy of all praise.
