== Chapter XI

[.chapter-synopsis]
* Visits Ireland
* Returns to England
* Letter of Mary J. Lecky
* Letter of Samuel Reynolds
* Letter of Joseph Thorp
* Extracts from Letters of Christopher Healy to His Wife
* Letter Respecting the Character of Christopher Healy`'s Religious Exercises in England
* Remark of John Barclay on His Christian Fearlessness
* Extracts from Letters of Thomas Christy Wakefield and Jacob Green
* Returns to America
* Notice of an Interview with a Young Man in England on the Danger to Friends of Joining with Persons of Other Religious Denominations on Benevolent Associations

Going to Ireland, Christopher Healy visited Belfast, Lisburn, Lurgan, Moyallen, Grange,
Richhill, Dublin, Ballitore, Carlow, Waterford, Youghall, and Cork.
"`The meeting at Cork,`" he says, "`was a laborious time at the beginning; but,
through hard labor, way opened and strength increased, until Truth reigned over all.
Blessed be the name of the Great Head of the Church,
who alone can give strength for his work and service.`"
From there he went to Clonmel, Limerick, Roscrea, Mountrath, Mountmellick;
and returning to Dublin, took steamer for Liverpool.

Extract from a letter written by Mary J. Lecky, dated Second Month, 12th,
1832,--and addressed to Sarah Healy:--

In the City of Cork he had a meeting with Friends; a remarkable season.
He wrote me that it was a very open time,
but J. Hopkins told us more fully that he thought it would be
almost worth coming from America for such a meeting.
From Munster he took a few meetings of Leinster Province in his way to Dublin,
where he arrived the 6th of last month.
He left for Liverpool on the 10th, leaving a sweet savor on the minds of his friends,
I believe, where he visited them in this land.
In Dublin, which is a very large particular meeting,
he had much service with Friends on First-day forenoon,
and with those of other professions in the afternoon; favored seasons.
It was sweet to sit under his ministry.

After returning from Ireland to England, he held many public meetings,
the most of which he records were to good satisfaction.
He thus alludes to one of them:--

The doctrines of Truth being opened, a hireling ministry, with the subject of war,
as being inconsistent with the gospel, and contrary to the command of Jesus,
was closely spoken to.
The necessity of taking up the cross of our holy
Redeemer before we can become his followers,
was also dwelt upon.
It being only as we do this, through obedience to the teaching of his grace,
that we can have our fruit unto holiness, and in the end everlasting life.

The following letter from Samuel Reynolds, of Dover,
was written to Christopher Healy some time in the year 1831:--

[.salutation]
Beloved Friend,

An opportunity offering of sending you a few lines,
I felt unwilling to let it pass by without expressing my deep
regret in not being favored with your company at Dover;
the more when I reflect that I might have availed myself of the more
full expression of our mutual feelings on those things to which there
appears too much reason to apply the words:
'`That which now restrains will restrain,
until it be taken out of the way.`' You have done what you could,
I believe may truly be said; and in that your feet were turned another way,
the burden must rest upon those unto whom they were first directed; but unto such,
who although in a far inferior degree have become
companions in travail for the suffering seed,
there is brought an increase of exercise and sympathy
with those who wish well unto our favored Society.
The language of my spirit at times is,
when viewing the ravages that have been made within our
borders by a conformity to the spirit of the world:
Surely we shall one day fall by the hand of the enemy.

With the salutation of dear love, in which my wife unites,
I desire very sincerely that your portion may be a rich reward of
heavenly peace and comfort as you pass along in the Master`'s service,
and when you have completed this, your work of labor and love,
you may be favored largely to partake of the joy of
your Lord.

[.signed-section-closing]
I remain your truly affectionate friend,

[.signed-section-signature]
Samuel Reynolds

The following letter, received by Christopher Healy about this time, from Joseph Thorp,
who had for a time been his companion,
alludes to his instructive and entertaining conversation,--a
talent for which our dear friend was remarkable;
and which is so well remembered by those who had
the pleasure of listening to its animating flow.
Perhaps, too, there were no subjects dearer to his heart,
or upon which he was more likely to enlarge,
than the doctrines and testimonies of Friends, of which mention is made in the letter.
We well remember hearing him say, with much emphasis of manner,
"`These (Quaker) principles are the dearest principles on the face of the earth.`"
May none of us, professors of the same precious truths,
be either lukewarm in their support or be
ashamed of their faithful maintenance among men;
remembering the dear Savior`'s own words:
"`Whosoever shall be ashamed of me and of my words,
of him shall the Son of man be ashamed when he shall come in his own glory,
and in his Father`'s, and of the holy angels.`"

[.signed-section-context-open]
Halifax, Second Month 27th, 1832.

[.salutation]
My dear Friend Christopher Healy,

As I fear I shall hardly be able to meet you during your stay at Stockport,
as I rather had hoped to do,
I thought I would at any rate drop you a line if it were only
to assure you that we do bear you in affectionate remembrance.

I was truly reluctant to surrender my privileged office when I did,
but the ties of the dearest attachment,
the fear that I should be needed in the business at home,
and the little indisposition of which I spoke to you,
and which rather increased for a few days afterwards,
seemed to make it prudent to return.
And though I parted from you, yet in mind I have gone with you.
I have thus had you my companion often every day.
I have marked your progress; have felt interested in it;
and while my heart has breathed fervently for your preservation,
and that you may be favored to return in peace to the bosom of your family,
I have felt answered in the belief that He will keep, who has called you;
and that He wall preserve you in the work whereunto he has called`' you.

I have much pleasure in calling to remembrance the
subjects upon which you touched in your conversation;
and I hope the valuable instruction contained in it, will not be quite lost to me.
Your remarks on our principles and peculiarities too,
have raised and confirmed them in my esteem;
and though your plain and powerful speaking may almost startle
us who have perhaps been too much used to smoother things,
yet we cannot but acknowledge that these are indeed the Society`'s first principles,
from which we have too much glided away, and that to ourselves almost imperceptibly.

[.signed-section-closing]
I remain your assured friend,

[.signed-section-signature]
Joseph Thorp

Christopher Healy went to London on Seventh-day, the 12th of Fifth Month, 1832,
in time to attend the Yearly Meeting.
His journal states that up to that time,
he had travelled thirty-seven hundred and fourteen miles,
and attended two hundred and eighty-five meetings.
In London he stopped at the house of his friend John Sanderson "`Here,`" he writes,
"`I received a consoling letter from my dear wife.`"
At Northampton and at Bardfield respectively, he sent letters to her.
From these the following extracts are taken.
They set forth some of the exercises which were his portion while on that foreign shore:--

Northampton, Third Month 20th, 1832.

I have had much close labor in this land,
and as much as some could bear who were superficial Quakers;
and whose adorning was not that of a meek and quiet spirit,
which is in the sight of God of great price.
Therefore the simplicity of the truth as it is in Jesus is too strait for them.
A desire too much prevails to be called by Christ`'s name,
while they want to eat their own bread and wear their own apparel.
Such, wherever they are in meetings, make hard work.
But blessed be the great Name of the good Shepherd,
He has abundantly appeared and given the victory May my poor soul be humbled before him.

Bardfield, Essex, Fourth Month 4th, 1832.

I feel as though I had plenty of time to get through with all
that I have in prospect before the Yearly Meeting in London,
without hurrying; and it is a great favor to have, once in a while,
a day of rest for my poor body and mind.
The exercises of the latter are sometimes almost more than the poor body is able to bear.
Yet, blessed be the Lord`'s holy name,
I have been marvelously supported beyond what human reason could suppose.
May He forever have the praise, who alone is worthy.

I still continue the prospect of returning in the same
vessel in which we came to England--the Algonquin:
which will sail, according to advertisement, the 8th of Sixth Month,
from Liverpool to Philadelphia.
But my dear, all this pleasant prospect must be in submission to the Divine disposal.
May our eye be kept single to the Holy Redeemer;
looking to Him from whom alone come all our blessings.
You know how He has blessed us every way;
and has not allowed us to be tried beyond what he has given strength to endure;
which has abundantly, I hope,
strengthened our faith and confidence in his all-sustaining power.
Oh! then may we, my precious one, continue to keep the word of his patience,
and no doubt He will keep us in the hour of temptation,
which may be permitted to try us yet again.
I have been favored since I last wrote, with many large and comfortable meetings.
May He alone who is the crown of meetings, have the praise.
I have close exercising times amongst my dear friends,
yet it is a comfort to me that they very generally receive what I have to communicate,
and appear well satisfied.
But a great reformation is needed in some.
May He that raised up our worthy forefathers in
this land to bear such precious testimonies,
open their eyes to see how they are departing from them.
Notwithstanding I have many painful and distressing
feelings about some not in the lowest rank,
yet my mind is at times comforted that there are some among the youth of both sexes,
who do see the danger; as well as many among the elder ones, who are, with my own soul,
saying, Lord arise for our help;
even you who did so clearly manifest your will to our worthy forefathers,
and separated them from a dependence on forms without life;
and in a remarkable manner brought them forth to preach
in the demonstration of the Spirit and with power,
whereby many were added to the church.
May such days be known among us again, if it please You, our Holy Helper.

The following letter addressed not to Christopher Healy,
but to other persons concerning him,
gives some insight into the nature of the testimony borne by our friend in England:--

[.salutation]
My Dear Friends,

As we have each had an opportunity of reflecting upon the subjects of
discussion with our highly valued friend Christopher Healy,
myself for having been the means of their being introduced,
and you for the little reprimand which you thought me entitled to for so doing:
I feel inclined to cast before you,
in the pure freedom and precious feeling of love and unity,
some of my thoughts in meditating thereupon.
As to myself, considering how we are circumstanced,
I count it a privilege to have been made acquainted with his views on the subjects.
Perhaps to say that they correspond very much with some of my own original views,
may be almost too presuming.
His are so clear,
so apostolic and so truly consonant with the practice and usage of our early Friends,
that I cannot but admire them,
as well as delight in the hope that they are in the way of being revived amongst us,
the nation through.
Perhaps there may be many, who with you do not admire,
nor hardly know how to bear his plain dealing with us on the subject, but `'tis,
I verily believe, in the way of his gift;
which I find is exercised among Friends in a conversational, not a ministerial way,
out of meetings.
And does not the precious feeling of life and power frequently, yes for the most part,
accompany these his communications.
My impression is that it does, at least wherever I have been in his company,
which has been as much as six or seven times, or more, both in and out of meetings.
Fast days, the holding the office of special constable,
and attendance of missionary meetings, etc., I have heard him equally plain upon,
and equally convincing to me;
though at the same time condemning some of my own practices.
But what then!
We must not rest there.
If our judgment has been warped by the example of others,
or even that we have erred in our own--for the deceiver,
as some of us know by long and very dear-bought experience,
has many ways of transforming himself--even under the most upright intentions,
and in the truest sincerity of desire,
to be dedicated to the service of Him whom to know (from the deceit) is life eternal.`'

Therefore, methinks,
that all this very plain dealing of our beloved and honored friend and elder
in the Truth (of which surely he is one among the valiants in our day) will
not hurt or hinder the growth of the precious lowly plant of renown in us,
no not in any of us old or young.
No, has it not already been to some of us like a digging about,
in order to clear the spurious growth from the root? Which I desire may be the case;
and that the root may be watered with the refreshing streams from Zion`'s hill,
so that we may grow and bring forth abundant fruit to the praise of the good Husbandman,
etc.

[.signed-section-closing]
Your affectionate friend,

[.signed-section-signature]
J+++.+++ W.

Third Month, 1832.

Alexander Dirkin related that when he was in England,
and conversing with the late John Barclay about Christopher Healy, John remarked,
"`that Christopher was the right kind of a man to come there on a religious visit,
for he was not afraid to challenge a Peter or a Paul, and to say, '`You are the man.`'`"

The following are extracts from letters which were addressed to Christopher Healy,
before he left England, according to their respective dates:--

[.signed-section-context-open]
Moyallen, 5th of First Month, 1832

We indeed stand in need of help and support in this place of trial and discouragement.
Indeed it abounds every way,
and at times appears as if the flood would not only overflow the banks,
but carry away the ramparts, and leave little behind.
My dear children, intend to add a little to this letter,
so must bid you farewell in the love of the gospel, and am with dear love to you,
and your companion, your affectionate friend,

[.signed-section-signature]
Thos. Christy Wakefield.

[.asterism]
'''

[.signed-section-context-open]
Trumery, Fifth Month 4th, 1832

[.salutation]
Dear Friend:

I received your acceptable letter, which satisfied my desire,
for before I got it I was very anxious to know when you
intended to return to your native country,
believing it would be the time for me, if liberated by my Yearly Meeting,
to proceed on my prospect of visiting your land; and the way seems now open for me,
and I trust I can be ready, if all is well, to meet you in Liverpool,
the 8th of Sixth Month, as you propose.
It is a great comfort to me and my family the prospect
of having your company across the great deep.
When you were in our parts I felt nearly united to you.
I hope you have got comfortably through your important mission in Europe,
and feels the reward of peace.
I hope you may have as agreeable a Yearly Meeting as we had in Dublin.
I believe it might be said in measure, as formerly, the Lord`'s power was over all,
which is the crown of all religious assemblies.
I trust this may be your experience--that all
crowns may be cast down at his sacred footstool,
that He only and alone may be exalted.
There felt to me, when I was in London last year,
a great deal of the worldly wisdom and head knowledge amongst the members of our Society,
that I was afraid they were not taught in Christ`'s self-denying school.
I hope you may not see nor feel this among you this year.
It was very painful to me, and would be I am sure to you.
With earnest desires for our preservation in every good word and work,
I conclude with dear love to you, in which my dear wife and children unite;
and am your affectionate friend,

[.signed-section-signature]
Jacob Green

Several letters are preserved among Christopher Healy`'s papers, from different Friends,
expressive of their interest in his labors in Great Britain,
and of unity with the plain dealing he was drawn into during his visit among them.
At a Monthly Meeting where he was present,
he spoke pretty fully on the dangers which attended Friends joining with persons of
other religious denominations in associations for promoting benevolent objects;
using such texts as, "`Strangers have devoured his strength, and he knows it not.`"
The clerk of the Monthly Meeting was a youngish man of great natural abilities.
After meeting, he requested an interview with Christopher, saying,
their views were not alike on some points.
At this interview he proceeded at some length,
and with much eloquence to set forth the public benefits and
the opportunities of disseminating Friends`' doctrines,
etc., that would arise from the course some were pursuing.

When he had finished, Christopher asked him a few questions:
"`Are the views and practices of the Episcopalians the same now as they were
in the days of George Fox and our early Friends?`" "`They are.`"

"`Do you believe that George Fox and our early Friends were
led out from these things by the Spirit of Truth?`" "`Yes, I do.`"

"`Do you believe the same Spirit of Truth would lead us into that, now,
out of which it formerly led us?`"

The man`'s head drooped, and he sat without answering.

They parted pleasantly, and after Christopher Healy`'s return to this country,
he received a letter from the clerk,
stating that the few words uttered by him at that
interview were the first thing that had opened his eyes,
and led to a change in his views.

Diary resumed:--

First-day morning, Fifth Month, 13th.--Attended Grace-Church Street meeting.
Afternoon, that of Devonshire house.
Second-day, the Yearly Meeting of Ministers and Elders.
I informed this meeting that I believed my labors and
services were near a close in this land;
and that my prospect was, if my way continued to remain open,
and with the blessing of heaven,
to return to my family and friends soon after the Yearly Meeting.
The meeting thereupon appointed a committee to produce a certificate for that purpose;
which was done.
At this Yearly Meeting, Stephen Grellet, John Wilbur, Charles Osborne,
and myself were in attendance from America.
The meeting was favored, particularly at the conclusion;
and Friends parted in the love of the great Head of the Church.
On the Seventh day of the week, went to Tottenham.
First-day morning attended Friends`' meeting there.
In the afternoon rode to Hitchin, twentyseven miles from London.
Second-day pursued our way towards Liverpool, the place proposed to embark.
Third-day took stage to Manchester, and from there to Liverpool.
Fourth-day rested.
Here I met with my dear friend Jacob Green, from Ireland,
who was going to America on a religious visit.
The thought of having each other`'s company over the sea was mutually pleasant.
Fifth-day attended meeting at Liverpool.
This parting opportunity was refreshing to many of our minds.
The Great Shepherd had cemented many of our hearts together;
and though we now had to part, yet the remembrance of each other in the Lord, I trust,
will not soon be forgotten by us.

On the morning of the 8th of Sixth Month, 1832, being the Sixth of the week,
we went on board the ship Algonquin, bound for Philadelphia, Thomas Cropper, master.

Christopher Healy and his friend Jacob Green were the only cabin passengers.
They held meetings through the course of the voyage,
to which many of the steerage passengers came.
While on the passage homeward he thus writes:--

My mind is comforted in looking over my visit to England and Ireland;
and the prospect is pleasant also in looking towards home, to my dear wife and children,
as well as many of my dear friends.
Oh may I be humbled in thanksgiving and praise to Him,
who rules the winds and on the ocean rides; the only preserver of men.

(Again):--

First-day, the ship rolled so, that we could not have a meeting.
But I humbly trust my mind was preserved in submission to the Divine will.
How true is that Holy Scripture testimony, "`You will keep him in perfect peace,
whose mind is staid on you, because he trusts in you.`"
Oh may this be my happy case!
Then will all things work together for good, and the Lord will have the praise,
who alone is worthy.

And again, Sixth Month, 25th:--

The wind increased and the sea rose, tossing the ship very much.
26th.--The wind strong, and the sea very high.
Oh the awfulness of the great deep!
The sea continuing to increase, a part of the vessel and rigging was carried away.
Never did my eyes behold greater wonders on the rolling, foaming deep, than this day.
We got but very little sleep.
My trust was in the Lord alone;
who could command the winds and the mighty sea that so greatly raged and roared.

Again, Seventh Month, 16th:--

We are now about one hundred and fifty miles from the capes.
The weather warm and pleasant.
May we be thankful to the Lord for his many favors.
Some of our steerage passengers having a longer voyage than they expected,
are getting scant of provisions; which must be proving to them.
But a hope is entertained that a fair wind will soon spring up, which,
with the favor of heaven, may soon bring us to our desired port.
But of ourselves we can do nothing.
May we, under a humbling sense thereof, look to Him who created the winds and the seas,
and rules them at his pleasure.

Our dear friend finally reached his home on the 21st of Seventh Month, 1832,
and found his wife and family well, "`which,`" as he records,
"`was cause of humble thankfulness of soul before the Lord,
who had been pleased to put forth, to go before, and to bring again in peace.
Taking a retrospective view of my late visit, I feel great peace of mind;
though mourning and lamentation were my portion very
often while travelling in those foreign lands.`"
