== Chapter XII.

[.chapter-synopsis]
* Visits Meetings in Bucks Quarterly Meeting, Pennsylvania; and in New Jersey
* Visits Friends and Others in New York and New England
* Extract from a Letter to His Wife
* Remarks on Divine Judgments to be Apprehended for the Treatment by the Whites of the Indian and African Races
* Visits Meetings Composing Abington and Haddonfield Quarterly Meetings: also, Shrewsbury and Rahway Quarterly Meeting, N. J.
* Visits Friends and Others in Several Quarterly Meetings in Pennsylvania
* Holds Meetings in New Jersey, Where No Friends Were Settled
* Visits Some of the Tribes of Indians on the West and Northwest; and Friends and Others in Michigan
* Extracts from Letters to His Wife
* Testimony to Christ Inwardly Revealed as the Foundation of the Faith and Practice of Friends

After his return to America, Christopher Healy`'s first religious service from home,
was a visit to the meetings composing his own Quarterly Meeting,
and subsequently the families of the same; and also many of the meetings in New Jersey;
in which, as he writes,
he had to rejoice in the goodness of the Great Shepherd of Israel.
In the visit to the families of Bucks Quarterly Meeting,
he had the company of Abraham Harding, an Elder of his own Monthly Meeting,
and John Comfort, of Solebury.
Their company, he writes, was pleasant to him,
and this labor of love satisfactorily accomplished.

His journal again states,
that having felt drawn in gospel love to perform a visit to Friends,
and those not of our Society,
within the limits of New York and New England Yearly Meetings,
the concurrence of the Monthly and Quarterly Meetings was duly granted;
and taking leave of his dear wife and family, he proceeded thereon in Tenth Month, 1833,
accompanied by Benjamin Cadwallader.
The memoranda of this and the few following journeys, are concise.
A few extracts therefrom are as follow:

[.small-break]
'''

First-day, again attended Coeymans`' meeting.
A very large gathering.
It seemed as if almost all the neighborhood came together,
except those that had separated from Friends.
A more precious season I do not often remember.
Blessed be Jehovah`'s glorious Name.
Had a very favored meeting at Brothertown with a small tribe of Indians.
The Indian minister, with some of the most thoughtful of his tribe,
came to Thomas Dean`'s, who was the government agent, and where we put up,
and dined with us.
They expressed much thankfulness to the Great Spirit for this favored opportunity.
How true it is, that Christ is given for a light to the Gentiles;
that He may be God`'s salvation to the ends of the earth.

[.offset]
At Madison, Christopher Healy writes:

I met with some of my former acquaintance, particularly two men and their wives,
who had for years been associating with the separatists;
but hearing at the meeting this afternoon the true
faith of our Lord Jesus Christ opened in a clear manner,
they were instructed and comforted;
and in the evening came both the men with their wives to our lodgings,
and we had a favored time together.
In a short time they returned to Friends, acknowledging they had been misled.
And I have no doubt there are many more such among them.
May the Good Shepherd be near to help these sincere ones, whoever and wherever they are.

[.offset]
While on this visit, he addressed a letter to his wife,
from which the following is extracted:--

[.embedded-content-document.letter]
--

And now, my dearly beloved wife, be of good cheer; and be filled with joyful hope.
I believe if you continue to cast all your care on Him who cares for us,
and has been our Preserver and Comforter, He will be your comforter still,
in your husband`'s absence.
I may say without boasting, the Lord is my Shepherd,
in whom I trust day and night--this blessed Shepherd of Israel,
who was pleased to unite our hearts together,
and enables us to resign each other for his blessed cause and
testimony. Neither do I see but that we may be favored to
meet again in the sweet embraces of Heavenly love.
Benjamin travels cheerfully, and makes a pleasant and very agreeable companion.
Give my dear love to his wife.
Tell her I hope she may feel the sweet reward of
peace for resigning the partner of her joy.
He expresses good satisfaction in the journey thus far.

Farewell, my dear wife.
Give much love to all the children.
Tell them to be good children, and love their dear mother.
I hope this may find you all well.
From your faithful and loving husband,

[.signed-section-signature]
Christopher Healy

--

At Hamburg he had a large meeting.
Many of those who attended had gone off from Friends.
He writes:

Here I was led to show the great difference between those who do not
believe that our Lord Jesus Christ was anything more than a good man,
and we, who as a Society,
have always believed as the Savior himself declared of
himself in his intercession to his Father,
"`And now, O Father, glorify me with together with yourself,
with the glory which I had with you before the world was.`"--Again,
"`I and my Father are one.`"--And again, to Philip,
"`He that has seen me has seen the Father, and how do you say, then,
Show us the Father?`" When our dear Redeemer said to the unbelieving Jews,
"`I and my Father are one,`" it is written they took stones to stone him.
Jesus said unto them, "`Many good works have I shown you from my Father:
For which of those works do you stone me?`" The Jews answered him, saying:
"`For a good work we stone you not: but for blasphemy; and because that you being a man,
make yourself God.`"--what is the difference between
those of this day who call our Holy Redeemer but a man,
and those unbelieving Jews that called him a blasphemer because he said "`I
and my Father are one?`" Oh how mournful is this same spirit of unbelief!
May their eyes be opened to see the great delusion by
which the grand deceiver has ensnared them.

[.offset]
Upon their return home, he thus writes:--

What added much to the comfort of the journey,
my dear companion was a truly uniting and sympathizing friend.
He travelled cheerfully, though it was a laborious one as to the flesh.
But He who is strength in weakness, riches in poverty,
and a present help in time of need, was pleased to make bare His Arm for us.
Oh may we ever trust in Him, who never said to the seed of Jacob, seek my face in vain.

[.small-break]
'''

Benjamin Cadwallader, in returning his certificate in the Third Month, 1834,
said that Christopher Healy and himself had visited the
greater part of the meetings of New York Yearly Meeting.

Resuming this religious visit, Christopher Healy, with Robert Alexander for companion,
in the Fifth Month, 1834, attended New York Yearly Meeting;
making their home at his kind friend John Wood`'s, who, he writes,
is "`a precious minister.`"
The memoranda continue:--

Though some seasons during this Yearly Meeting were trying,
there were many deeply exercised minds present,
and some favored testimonies were borne in the life and power of the gospel;
and I trust the meeting closed under thankful acknowledgments
to that Good Hand that first raised us up to be a people.

He visited during this journey a small tribe of Indians,
with whom he previously had had several meetings.
He writes:--

[.small-break]
'''

How thankful they always are;
I am scarcely able to find words to convey my sympathy for these poor afflicted people.
It seems to me the language to us is at the present day, "`Open your mouth for the dumb,
in the cause of all such as are appointed to destruction!
Open your mouth, judge righteously, and plead the cause of the poor and needy.`"
It seems as though the wrath of man has counted them
not fit to live and enjoy themselves in this world.
May we not expect that the Lord will visit for these things done to this people,
and also to the African race.
Will not his soul be avenged on such a nation as we are, unless we repent,
and submit to that holy and just rule of the dear Son of God:
"`As you would that men should do to you, do you even so to them.`"

Coming to North Kingston, he says:--

My mind has been drawn to this place several times before;
and finding great openness in the people`'s minds, a precious season it proved.
May the Lord sanctify it for good to all present.

He went from there to Greenwich; and next to Providence, where, his journal states,--

I had a very trying meeting in the forepart, but got some relief.
After meeting we went home with our dear aged friend Moses Brown,
living about a mile from Providence.
His conversation was sweet and savory, and the exercise of his spirit helpful.
This could be felt as we sat by him.
He was then in the ninety-fifth year of his age.
He truly seemed like one planted in the house of the Lord,
and flourishing in the courts of our God; being green in old age.
How edifying and instructive is the company of this dear father in Israel!
Oh, says my soul, may the Lord raise up more such judges and counsellors in his church.

Soon after this, they returned home; and, as he says, "`found all well;
and we rejoiced in Him of whom I could say, '`The Lord is my Shepherd; I shall not want.
He makes me to lie down in green pastures;
he leads me beside the still waters.`' Oh glory to his holy Name forever!`"
Their certificates were returned in the Eighth Month, 1834.

His next visit was to Abington and Haddonfield Quarterly Meetings,
and the meetings composing them; with that also of Shrewsbury and Rahway,
though not the meetings constituting it.
As his manner was, in all these he held meetings with those not of our Society.
He was favored to accomplish the same to the peace of his own mind.
He adds, "`Blessed be the Lord who can send help from his sanctuary,
and strengthen us out of Zion.`"

Early in 1836 he was liberated by his Monthly
Meeting to pay a religious visit to Friends,
and those not in membership with us, within the limits of Philadelphia, Concord, Cain,
and Western Quarterly Meetings.
Attending the Northern District Monthly Meeting, he writes:
"`Our friend J. W. kindly offering to bear me company, it was united with,
and he set at liberty.
We had many public meetings, as well as attended those of Friends,
to the strength and encouragement of our minds.`"
Here occurs the following memorandum:--

How clear I am that the profession of the faith and doctrines
of our religious Society is a good and holy profession.
Oh that all would live up to them! then would righteousness indeed cover the earth,
as the waters cover the sea; and light and life would reign over death and darkness.

In the latter part of the same year (1836),
he obtained the unity of his Friends to hold meetings in some towns and villages,
particularly in New Jersey, where no Friends were settled, as Best Wisdom might direct.
He writes:--

Being joined by my kind friend Benjamin Cooper, of Newtown, an elder, we visited Newtown,
Woodbury, Woodstown, Salem, Bridgeton, Port Elizabeth, and from there down to Egg Harbor;
together with many more in that part of Jersey.
These meetings were largely attended by those not of our Society.
My dear companion, Benjamin Cooper, was a very suitable Friend for such a visit,
and very helpful to me herein.
Returning towards Evesham, we had a very precious meeting at the Glass-works;
and another at Evesham, also greatly favored.
May the good Shepherd of the sheep have the glory;
for to none other does any glory belong.
Returned home with a peaceful mind.

Not having completed my prospect in this visit,
towards the spring of the following year (1837) I again
set out with my dear friend Benjamin Cadwallader,
to the eastern parts of New Jersey.
Had meetings at Plainfield, Rahway, Mount Holly, and Rancocas, with some public meetings.
In these we felt thankful hearts for favors received from Him,
who is the crown of all heavenly meetings.
Being enabled to perform this visit, as I believe, in the love of,
and I humbly hope in a measure of the life of the gospel of Christ Jesus,
it brought peace to my own soul, and to the living members of the church.

The memoranda continue:--

Having felt drawings in my mind for several years to visit, in gospel love,
some of the tribes of Indians in the western and north-western parts of this continent;
with Friends and those not of our Society in the State of Michigan;
and also to have meetings going and returning; on the 2nd of Fifth Month, 1838,
after taking a solemn leave of my dear wife and family,
I set out in company with Thomas Wistar, Jr., of Abington; a young,
but kind and pleasing companion.
We proceeded, having many public meetings on the way,
to a small tribe of Indians at Brothertown, in the western part of the State of New York.
While I was sitting with these poor afflicted people, my mind,
from the sweet consolation I felt,
was strengthened in believing that my concern originated from the living truth;
and I felt assured that not only the meetings among the Indian tribes,
but many of those appointed where there were no Indians, were favored in a measure,
to feel that the drawing cords of the Heavenly
Father`'s love were round about us to gather us.
May it continue and increase with them, says my soul.
We had meetings with five tribes of Indians in the western part of New York State,
as well as many more public meetings, to our great comfort.

Whilst on this journey, Christopher Healy addressed two letters to his wife,
from which the following extracts are taken:--

[.embedded-content-document.letter]
--

Skeneateles, New York, 20th of Fifth Month, 1838. On leaving Brookfield,
we were invited to stop at one of their neighbors, who they thought was dying.
We went in and sat down, and in about half an hour the poor man breathed his last.
Oh what a solemn time it was!
After a precious silence, and a few words of comfort to the family,
we proceeded to Brothertown, where the first tribe of Indians on our route reside.
On Fifth-day, at three o`'clock p. m., the Indians came together, and some white people.
The meeting was a good one.
They understood our language.
Sixth-day came to Oneida, where were about five hundred Indians.
Their missionary was a Methodist minister, who was glad to see us.
After showing him our certificates, he desired we might have a meeting with them.
The Indians being met in Council near by at the time, we went to the Council House,
and conferred with a number of their chiefs.
These took it on them to give information of the meeting,
to be held at three o`'clock in the afternoon.
The Council House was nearly full.
Our guide, the Methodist minister and wife, with ourselves,
were all the white people in the meeting.
Oh! in looking over this assembly of Indians,
it seemed to call up just such feelings in my heart,
as I had witnessed years before towards these poor people.
Under these precious feelings I stood up; and a remarkable season we had together.
I thought if I had no other joy in the journey,
this would have rewarded for all my privations consequent upon leaving home,
with all that is near and dear in this world.
Therefore, my dear wife, be not discouraged, but be filled with joyful hope.
I believe I am in the line of my duty to our dear Master and Lord,
who has called me to this service;
and that the same Good Hand that brought the concern on my mind,
will make the way for us.
Blessed be his name forever.

Read this letter to our friends who want to hear from us, particularly to Ruth Ely.
She loves the poor Indian.
She will see what a good meeting we had at Oneida, where her dear father visited them.
Give my dear love to her, and all enquiring friends.
Farewell.

[.signed-section-closing]
I remain your loving husband in the unchangeable truth.

[.signed-section-signature]
Christopher Healy

--

[.embedded-content-document.letter]
--

Hamburg, 3rd of Sixth Month, 1838.

Sixth-day had a meeting with the Cattaraugus Indians, to good satisfaction:
though it is hard to speak by an interpreter.
Our certificates were read by a young Indian, and interpreted to them.
One of their chiefs spoke some time after I had got through,
expressing great thankfulness for our visit to them,
believing it was from the Great Spirit.
They seemed exceedingly glad to hear our certificates in their own language.
We parted in a sweet friendship with them.
Second-day, attended a meeting of the Buffalo Indians, at their Council House,
seven miles from Buffalo.
The house was nearly full.
One of the young Indian chiefs that I saw in Philadelphia, was my interpreter.
It was a good meeting to the poor Indians, and to the relief of our minds.

The Indians, when we sit in meetings with them, seem just as I used to see them by faith,
when my prospect was clear,
and you and I used to talk about these poor children of the wilderness.
Yes, my dear, their hearts were made glad:
as many of their chiefs and warriors expressed by the interpreters.

Hitherto we have parted in abundance of love and friendship.
Oh may you be comforted; for He who is mighty has done great things for us,
and holy is his name.

To my comfort, I received here a good letter from you,
which gave an account of John`'s narrow escape.
Oh may he never forget it!
But may he, as well as all the rest of our dear children,
remember their father`'s and their mother`'s God, now in the days of their youth;
before the evil days come, or the years draw nigh, wherein they will say,
we have no pleasure in them.

Farewell in the love of the Good Shepherd that made us acquainted with each other,
and joined us together in love.

[.signed-section-signature]
Christopher Healy

--

Continuing the diary, Christopher Healy writes:--

We then left our horses at Lockport, and taking passage in the steamboat up Lake Erie,
came to Toledo; then to Adrian, a settlement of Friends.
We wished to reach there in time to attend their Monthly Meeting,
but did not arrive until near its close.
But we had a precious opportunity together before the meeting separated.
May our Divine Master have the praise forever.

Seventh-day,
made some enquiry concerning the situation of the Indian tribes in this State,
but found to our sorrow the poor creatures much unsettled;
the government having made a treaty with them some time before to give up their homes,
and go far west into a more wilderness land;
the agents of the United States had just arrived to
bring the Indians word to prepare for removing.
Finding many of them had left their homes in
order to get something to make them comfortable,
the prospect of having meetings with these poor children of
the wilderness seemed altogether discouraging.
Having to relinquish this prospect,
we proceeded on our visit to the white people as far as Lake Michigan.
Had a public meeting at Saint Josephs, which was a favored time.
We had meetings also at all the meeting places of Friends in the State,
as well as in the houses of those of other societies,
to my own comfort and I trust to the edification of many minds.
A Methodist minister was at a meeting of Friends,
and very kindly offered their house to have a meeting in;
an offer I felt quite willing to accept.
He took great care to spread information, and attended himself.
It proved to be a good meeting.

Soon after coming into this State, I met at a Friend`'s house with a plain looking man,
who, in the course of conversation, asked me some questions, which I answered.
After dinner,
a paragraph of our early Friends`' views on the spirituality of
the gospel dispensation having been read,
this man also read the 19th and 20th verses, chapter ii.
of the Epistle of Paul to the Ephesians.
I asked him if he read that Scripture in reply to the paragraph? He said he did.
I asked him if he thought they clashed? He said he believed that Scripture;
and asked me if I did not? I told him, yes; I verily did believe that declaration.
I told him that we (Friends) had always held that true believers in Christ were built,
as the apostle testifies, on the foundation of the apostles and prophets,
Jesus Christ himself being the chief cornerstone.
And, our ancient Friend, George Fox, concerning faith in Christ, declared:
that we believe in that same Jesus that was crucified without the gates of Jerusalem,
the same that was the foundation of all the holy prophets and apostles,
and that He is our foundation; and another can no man lay,
than that which is already laid; even He who tasted death for every man;
shed his blood for all men; and is a propitiation for our sins,
and those also of the whole world.
The more I conversed, the more uneasy I grew, as he appeared to be a man of talents.
I told him he was a stranger to me;
and asked him if he was a member of our Society? He replied shortly,
and with a quick tone of voice, I am; and a minister in good esteem.
I told him he must excuse me,
but it was his views of Scripture that caused me
to ask if he was a member of our Society.
I thought I plainly saw that he believed the Scripture
to be the primary rule of faith and practice.
I having another visit to make that afternoon, we parted.
A Friend in the ministry being with me,
who was acquainted with him towards whom I had felt this uneasiness,
said he was glad he had not mentioned the circumstance to me,
and that I had so clearly discovered his unsoundness.

Next day, which was First-day,
notice having been given of our intention of being there at meeting,
a very large company got together.
After a solemn silence, I believed it to be required of me to declare to the meeting,
what foundation true believers have to build upon.
That beloved and experienced Apostle, Paul, did not say,
we are built on the prophets and apostles;
but that we are built upon the foundation of the prophets and apostles.
Here we may see that that holy Apostle did not mean to call
himself the foundation of the prophets and apostles,
by no means.
But that the foundation they built upon, was and is Christ; the eternal rock of every age.
It was He who inspired prophets and apostles of old, as we read holy men were,
to write and to speak as they were moved by the Holy Spirit.
And we may likewise see how the same Apostle gives the honor and glory to God,
in and through Christ Jesus, where he says, "`By the grace of God, I am what I am:
and his grace which was bestowed upon me was not in vain;
but I labored more abundantly than they all; yet not I,
but the grace of God which was with me.`"
And our blessed Lord, in speaking of the Holy Scriptures, says, "`Search the Scriptures;
for in them you think you have eternal life; and they are they which testify of me.
And you will not come to me, that you might have life.`"
Oh how many there are in the present day,
who think that in the Scriptures they have all the knowledge of eternal life.
And thus stopping short, settle down in a false rest;
and become of those of whom Christ declared,
"`you will not come to me that you might have life.`"
The testimony of Christ in the Scriptures, and that of those he influenced to write them,
is good and precious, if we receive Christ, by his Holy Spirit in our hearts,
and yield to his holy teaching.
It is then we build on the foundation that the prophets and apostles built on.
Then shall Christ Jesus be our Rock and sure Foundation,
against which the gates of hell cannot prevail.

Returning home to his family, he found them all well;
and acknowledges that the Good Shepherd who had been with him,
had also kept and preserved them.
