== Chapter XIV.

[.chapter-synopsis]
* Anecdotes on the Happy Effects of Faithfulness Experienced by Christopher Healy in the Maintenance of the Testimonies of Truth to Plainness of Address, Etc.
* Anecdote of His Humility in Condemning a Fault
* Opposes the Doctrine of Predestination in an Interview with Paul Todd

Christopher Healy, though not a member of our Society by birth,
seems to have been scrupulously careful to maintain, from his early introduction into it,
what are called the minor testimonies of the Society of Friends.

Our dear friend believed the testimony of plainness of
speech to be no cunningly devised fable;
and hence was engaged to keep it in the meekness of wisdom;
and the Lord--who looks on the heart,
and who in speaking of "`the weightier matters`" in
connection with the smaller "`tithes`" of our obedience,
says, "`These ought you to have done,
and not to have left the other undone,`"--honored him in the eyes of all,
even the great of the earth.

This is substantiated by the following narrative:
--"`At the Quarterly Meeting of Haddonfield,
Christopher Healy said, in substance, that he did not know why it was,
but a circumstance that had occurred many years ago had been brought to his remembrance,
perhaps for the benefit of some one present.
There was a man in the neighborhood where he then resided, high in civil station,
whom even some members of our Society addressed with titles of honor.
With this man, Christopher said,
his brother had some business to transact connected with his high station,
and desired an introduction from Christopher to him.
As they proceeded towards the residence of this great man,
a deep concern came upon our Friend`'s spirit that he might not
be found shrinking from the testimonies of Truth,
and the language powerfully arose in his mind, '`Whosoever shall deny me before men,
him will I also deny before my Father which is in heaven.`' And
when he entered the presence of the visited,
the salutation which he uttered was on this wise, '`Elias,
how are you?`' (for his name was Elias Potter.) They
were kindly received and the business attended to.
Some time after, this man of note told Christopher`'s brother,
'`Some of your people balk their testimonies by giving titles of honor,
but your brother Christopher is not one of these.`' In process of time,
Christopher continued, I had a meeting appointed there,
and Elias Potter did what he could to further it, and came to it,
and behaved very solidly.
Christopher Healy then added some pertinent observations upon Friends in
their associations with others standing plumb and upright for the Truth.
'`His lively way of narrating the circumstance,`' writes
the Friend to whom he afterwards communicated it,
'`made it deeply interesting;
and doubtless it entered somewhere between the joints and the marrow
of those in the Quarterly Meeting for whom it was designed.`'`"

The following allusion of Christopher Healy to incidents in his early life,
may well cause those who are poor in this world, to be encouraged to look unto the Lord,
and to seek His favor and direction by a life of faith,
rather than to repine at the situation or circumstances in which they are placed:
knowing that no human reasonings or contrivings, without His blessing, will avail us:
but that "`godliness with contentment,`" is the great gain.

Christopher Healy had been speaking of a Friend, poor as to this world,
in whom he felt much interested, and who had lately, in the usual course,
been acknowledged a minister in our Society; when he thus continues:--

"`As poor as +++_______+++ may be, if he will but keep his place, keep low,
and look to the Master, I have no fear for him.
The good Master will make a way for him.
Haven`'t I abundant cause to bless his holy name? Was there ever a poorer
Quaker than I was? And hasn`'t the Lord cared for me through many long years,
and hasn`'t He now fixed me in my old age in as
comfortable a situation as my heart can wish? Why,
yes!
I have a comfortable home at which I can welcome and entertain all my friends.
Ah! this was the height of my worldly ambition,
that I should be able to accommodate my friends;
and the Lord has fulfilled the desire of my heart.
In my first wife`'s time I had hard work to keep my head above water;
but the Lord strengthened me.
My wife was very weakly, and at least half her time so sick she couldn`'t help:
so that with doctor`'s bills and other expenses, I had to struggle with many difficulties,
having no other way to earn a living but by going out at day`'s works.
Many a time after working hard all day at hoeing corn, or other farm labor,
I have received my half bushel of corn for my day`'s
work (for the farmers didn`'t pay us in money),
and then after sundown had to carry it on my
back a mile or more to mill to get it ground.
So I couldn`'t get it home until long after I ought to have been in bed and asleep,
to prepare me for another day`'s hard work.`"

"`I remember that at one time my doctor`'s bill was so large,
that I had to hire myself out for eighteen months to get money enough to pay it.
This reminds me of a circumstance which shows how poor and weak I was,
and how easily I was discouraged.
I was indeed both outside and in, one of the poorest Quakers that ever was:
at least I thought so.
My eighteen months were out at Quarterly Meeting time,
and my father-in-law brought my wife and two of my
children down to the Quarterly Meeting to meet me.
When we were going home, father took my wife behind him on horseback,
and carried one of my children in his arms, while my wife carried the other in her lap.
Of course I had to go afoot, and I had to carry my clothes and some other little matters.
We were thirty miles from home.
Still I didn`'t mind the distance,
but there was one of the bundles which I couldn`'t contrive to carry on my back;
it wouldn`'t stay fixed: so I spoke to a Friend in company,
who was one of the overseers of our meeting,
and who had a good strong horse under him and no baggage,
to know if he wouldn`'t let me tie that little bundle behind his saddle,
telling him I did not like to be a trouble or burden to my friends,
but I did not see how I could get it along myself.
He looked anything but encouraging and said,
'`If this was all the trouble and burden you was giving Friends,
we could more easily put up with it.`' Well, I was poor enough in spirit before,
but this overset me.
I had been bleating out a few words in meeting for some time,
and now I thought surely it is all over with me.
But the Lord who knew the sincerity of my heart did not allow me to perish,
but has preserved me, and blessed me even unto this day.
That rich overseer came to poverty, and made a bad end;
but the Lord has watched over me for good, given me my life for a prey, and bid me live.
It is wonderful how little money we can get along with.
When I had concluded to move into New York State,
we gathered together all the little property we had in the world, and started.
We had a wagon and that was paid for, and in it there was my wife and six children,
and all the rest of our worldly goods.
We had a horse but it wasn`'t paid for,
and when we landed on the west side of the North River,
I had just one piece of money left, and that was a half dollar.
But I soon got into a school and began to earn something;
and am preserved unto this day to praise the Lord, and to tell of his wondrous works,
and of his goodness to the children of men.`"

These remarks of Christopher, writes the Friend who heard and who penned this account,
are very striking in themselves,
but they had an additional force to those who heard them, from the animation of manner,
and lively energy in the delivery.
He sat and rocked on his chair as he spoke,
and at times his voice would mellow away to a solemn melody,
especially when he was speaking of the Lord`'s mercies to him.
A feeling of thankfulness seemed very much the constant clothing of his mind,
and he loved to tell others of the riches of the
mercy and providential care of the Lord Jesus,
towards and over his dependent little ones.
A very short time before he was taken sick with his last illness, coming to his home,
perhaps after a chilly ride,
and finding everything comfortably prepared for him in his little sitting room,
and a good fire blazing on the hearth,
he sat down and seemed overcome by the thankful emotions of his heart.
He could not forbear to speak of the Lord`'s mercies to him,
of the promise made him in early life of future earthly blessings,
if he would be faithful, and of the sweet fulfillment he then experienced.

The anecdotes that follow are instructive.
Christopher said:--

"`I remember when I was in England,
I had one day eaten something which gave me severe pain;
and while I was suffering therefrom I was betrayed into irritability of temper,
by not keeping so close a watch over my spirit as I ought to have done;
and in consequence I said two or three words, for which my conscience smote me.
I do not remember what I said,
but I recollect very well that I soon found the sting
in my conscience harder to bear than my bodily pain.
I think there were twenty or more Friends in the room, eating dinner;
but as I could not eat, I sat in my rocking-chair, rocking backwards and forwards,
as long as I could; and then I spoke right out and said: Friends,
I cannot bear this any longer,
for I feel that I did very wrong in saying those few words just now;
but I hope I shall be forgiven for it, for I am truly sorry for having said them;
and I cannot hope to have my peace of mind restored,
until I acknowledge my fault and express my sorrow for it,
which I now do in the presence of all of you who
heard me.`' One of the company immediately said,
he did not see that I had said anything out of the way,
that I need express or feel any sorrow for; and so several others expressed themselves.
But there was a plain and simple-looking woman Friend present,
who I think was a minister, who said, '`I am truly glad that our dear friend,
Christopher Healy, has been made willing to own his fault thus publicly,
and that he has been strengthened to condemn it at once, in so decided a manner.
I, like other Friends, did not at the time perceive any evil in the words he uttered,
but I now see that he has taught us a lesson, and given us an example,
which I hope we shall all try to profit by:
for I see we are not so watchful over our spirits, and over our words, as we ought to be;
and I hope we will all endeavor to get low and humble
enough to imitate our tender-spirited friend,
in acknowledging and condemning our faults,
whenever we are betrayed through unwatchfulness, into the commission of them.
It has been, I must say, a very instructive lesson to me,
and I hope it will be so to all of us.`'`"

Christopher said:
"`The Friend`'s remarks had a very reaching effect upon the whole company,
and I felt myself healed at once:
so that I was enabled to go that afternoon to an appointed meeting,
which proved indeed a very satisfactory one, and the gospel message flowed through me,
as I scarcely remember it to have done before.
And, (he added) I do believe that I should not have been able to
have opened my mouth that day in the way of the ministry,
if I had not been faithful in condemning my fault before all the company,
who had heard me commit it.
I know that I lost nothing in the estimation of these Friends by doing so,
but on the contrary, I am fully persuaded that they thought all the better of me.
And my heavenly Father was also well pleased with the sacrifice which
I made of self on the altar of humility and truth.
Indeed there is no other way to true honor but
by the road of humility and self-abasement.`"

"`I once had an appointed meeting at +++_______+++, in the State of New York,
in which I was led to speak of the pernicious doctrine of election and reprobation,
as many persons believe in it, and are thereby led to take up a false rest,
very far from the true rest which remains for the people of God;
and which has a tendency to foster in them that pharisaical spirit
which can thank God that they are not like other men are,
and make them look down upon those whom they in their spiritual pride,
call publicans and sinners.

"`There was one of the great men of this world at meeting that day, who was a judge, and,
as I understood a brigadier-general also.
This mail did not relish the doctrine I had to deliver;
and at last he stood up and interrupted me in my discourse; and I, in my freedom,
answered him as well as I was able.
After meeting, he kindly invited me--indeed he did more than that,
for he pressed me very earnestly--to go home with him to dine.
I felt something more than a mere willingness to go with the man,
and told my companion that if he was free to go along,
that I thought it might be right for me to go.
As my companion was willing to bear me company, I went,
and was kindly treated and hospitably entertained.
After dinner, he said, I desire to have some conversation with you, sir,
in relation to the doctrine you preached this morning.
I told him that I was at present not very well in health,
and that I was at best but a poor weak man, and no great hand at an argument,
as I could not say anything of myself, and if Master would not help me,
I could do nothing.

"`But as he insisted that I should defend the doctrine I had delivered,
I consented to hear him, but told him that there were a few preliminaries,
which I would like to have settled before he began his
argument.--As I cannot give flattering titles to men,
+++[+++see Job 32:21-22],
I want to know your name and to have full liberty to call you by it,
desiring that you will take no offence by my so doing, for it is not out of disrespect,
but as a matter of conscience that I so speak.
My name is Christopher Healy, and I would much prefer you would call me by my name.
And my name, said he, is Paul Todd, and I have no objection to be called by my name.

"`There is another proposition (said Christopher) which I wish to make, and that is,
if I should say anything, which you should think to be too hard,
about principles and doctrines, I hope you will not take it to yourself,
so as to make a personal matter of it, and get offended with me;
for it is principles and not persons, I trust, that we are going to discourse about.
And I consent to let you say as hard things about my doctrines and principles,
as you may see fit, promising you not to be offended thereat.
To all which he gave his assent,
saying it would be very weak in either of us to get affronted.`"

After the Judge had stated a few of his objections against Friends`' doctrines,
Christopher said:--

"`Now, Paul Todd, from what you said in meeting this morning, and from what you say now,
I think I understand precisely where you are; I presume that you are a Presbyterian.`"
To this he assented.
"`I suppose, too, that you have '`got religion,`' as your people express it.`"
"`Yes,`" he said, "`I got religion thirty years ago; and when our minister is absent,
I sometimes exhort the brethren myself.`"
"`No doubt, then,
you are fully persuaded in your own mind that everything which happens, past,
present and to come, does so in accordance with, and in conformity to,
the fixed and unalterable decree of God; and that nothing ever did,
or ever can come to pass,
but in exact conformity with His will--fore-ordained and
determined before the foundations of the world were laid.`"
"`Yes,`" he said, "`these are my views and belief, and they are, in my apprehension,
in strict accordance with the Bible.`"
"`Now,`" continued Christopher, "`let me put one simple case to you.
You are a judge, and as such, you have, no doubt, tried many criminals.
We will suppose that some wicked man--and the wickeder he is,
the better for my purpose--comes, and, in the secrecy and darkness of midnight,
murders your innocent neighbor, or your dearest friend; and he is tried before you,
and his guilt proved in the most positive and unquestionable manner:
what would you do with him?`" "`Condemn him to be hanged, most certainly.`"
"`But you have said that there is no act done,
but in strict conformity with the will of God.
Therefore, if God foreordained this man to commit this very murder, who are you,
that dare to punish him for doing the will of
his great Creator? According to your belief,
he could not in any way, or by any possible means,
escape from the necessity of killing this man; and must he be punished for it? Why,
this horrible doctrine makes God himself the author of
all the wickedness that is in the world!
Is it not blasphemy? Now, Paul Todd, I want you seriously to consider this matter,
and decide what you ought to do with criminals,
if the truth be as you have believed it to be.`"

The Judge said, "`this subject has been placed before my mind in a new light.
I never so contemplated it before.
I do not know what I ought to do,`" "`But I,`" said Christopher,
"`do know what you ought to do; and that is, give up, renounce, and utterly forsake,
all such false doctrines, which are derogatory to the character of our heavenly Father,
who wills all men to be saved, and to come to the knowledge of the truth.
But they limit the offices of Christ,
and detract from the merits of that most holy sacrifice,
which the dear Son of God made of himself,
when He shed his blood on the cross for all men;
and they quench the Holy Spirit in the hearts of many;
for a manifestation thereof is given to every man to profit withal.
Our heavenly Father long ago declared,
'`For I have no pleasure in the death of him that dies, says the Lord God,
wherefore turn yourselves and live,`' And shall we, worms of the dust,
limit the Holy One of Israel, either in his power or his mercy,
or his loving kindness to the children of men;
who sent not his Son into the world to condemn the world, but that the world,
through Him, might be saved? And my advice to you, Paul Todd, is,
that you should not trust to anything which you may have received thirty years ago;
for unless you receive a renewal of the Holy Spirit from day to day,
and have fresh and heavenly nourishment ministered more often than the returning morning,
to enable you to resist temptations, you will die in your sins,
notwithstanding all the experiences in which you have entrenched yourself Yes,
destruction shall suddenly come upon you, and you shall be cut asunder,
and have your portion in that eternal misery into which, as a judge,
you would send the poor wretches who have committed what are called capital crimes.`"

"`The judge received my close dealing without offence.
He appeared somewhat affected, and we parted friendly.
But before my return home from that journey, Paul Todd was no more.
Whilst walking in his garden one day, he fell down and expired.`"
