== Chapter XV.

[.chapter-synopsis]
* Visits Friends and Others in the Limits of Indiana Yearly Meeting; and Some of the Indian Tribes in Wisconsin Territory
* Letter to His Wife
* Remarkable Religious Opportunities with Indians of the Brothertown and Stockbridge Tribes
* Letter of Joseph Gibbons
* Letter of Cutting Marsh
* Visits Meetings in Iowa
* Extracts from Letters to His Wife
* Attends Meetings in Indiana
* Letter of Sarah Keese
* Notice of Religious Engagements in Pennsylvania, New Jersey, and New York

+++[+++Though Christopher Healy, subsequent to the period now reached,
was engaged in several more religious visits abroad,
the one we are about to record is the last, so far as his memoranda show,
of which he himself has left us any account.
He was now nearing that point of life--his three score and ten years--
when the shadows of the evening were being fast lengthened out,
and the time not very distant when this dedicated servant was
to rest from his labors in the church militant,
and to join the church triumphant,
in the ceaseless anthem of glory and praise to the Lord God, and the Lamb that was slain,
forever and ever.
In reference to this visit he writes:--]

[.small-break]
'''

I felt my mind drawn in gospel love,
to visit Friends and others within the limits of Indiana Yearly Meeting;
and some of the Indian tribes in Wisconsin territory.
Obtaining the unity of Friends, I took an affectionate leave of my dear wife and family,
and on the 6th day of Fifth Month, 1842,
left home in company with my friend John S. Comfort.
On the 17th of the same month we got to Benjamin Ladd`'s, in Smithfield, Ohio.

[.small-break]
'''

+++[+++Christopher Healy and companion, proceeded to Canada,
and visited the settlements of Friends there.
Of a meeting at Norwich he says: "`Next day, which was First-day attended meeting there;
others being informed, it was a very large meeting, and to good satisfaction;
many were comforted, and my own soul rejoiced,`" The diary adds:
"`On First-day we had an appointed meeting at Adrian, Michigan, in a Baptist meetinghouse.
Many people attended, and a number of Friends came also.
A precious meeting it proved, and some expressed their comfort with thankfulness of heart.
May the praise be given to Him to whom it is due.`"

At Adrian they were joined by their friend Joseph Gibbons,
of whom mention is made in the following letter from Christopher to his wife,
written at this place:--]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Adrian, State of Michigan, 13th of Sixth Month, 1842.

[.salutation]
My very dear Wife,

We left Smithfield after attending their Select Preparative Meeting,
and a public meeting on Fifth-day, which was large and favored.
Sixth-day went to Mount Pleasant, and attended their Select Quarterly Meeting.
On Seventh-day their Quarterly Meeting.
First-day we were at a public meeting, to the comfort of many.
Second-day set out for Alum Creek.
That night lodged at Benjamin Hoyle`'s, where Joseph Edgerton spent the evening with us,
to our comfort.
Next morning Benjamin accompanied us seven miles to the turnpike.
That night got to Zanesville, on the Muskingum river, and were kindly entertained at
J+++.+++ D.`'s. Fourth-day got to Robert Comfort`'s,
distant from Benjamin Hoyle`'s a hundred and four miles.
Fifth-day, rode to Alum Creek Monthly meeting, where we met with Jacob Healy,
brother Joseph`'s son: a kind and religious young man.
He was our guide back to Greenwich, where his father lived.
Robert Comfort went with us to Alum Creek, on horseback,
though in his seventy-ninth or eightieth year; the distance being about eighteen miles.
Sixth-day; returned to Robert Comfort`'s, and had a public meeting at Owl Creek,
at three o`'clock in the afternoon.

Next morning, with Jacob Healy for our guide, we got to my brother Joseph`'s, at Greenwich.
They were exceedingly glad to see us.
First-day, had a large and crowded meeting at that place.
The house could not hold the people, and seats were placed out of doors.
Many minds were witnesses of the presence of our good Master,
to the melting and contriting of our hearts together.
Blessed be His holy name.
Third-day, at Sandusky, at ten o`'clock.
Fourth-day, at Mount Gilead, where was a marriage; and general notice having been spread,
the house could not contain the people by more than three hundred;
but convenient seats being put up at the door,
the meeting was a remarkably quiet and instructive season to many minds.
Many came from the village of Mount Gilead.

--

+++[+++After stopping at a few more places, and visiting some meetings,
they at length reached Adrian; and were kindly received by Joseph Gibbons.
The letter continues:--]

[.embedded-content-document.letter]
--

Since we have got to Adrian, our dear friend Joseph Gibbons, who was once at our house,
has concluded to go with us among the Indians.
This arrangement suits me well, he having already been through that country.
Moreover, many Friends of Adrian Monthly Meeting, which was held yesterday,
having felt and expressed a very near and dear unity
and sympathy with us in our arduous undertaking,
drew together after meeting, and encouraged and assisted Joseph Gibbons to accompany us,
and I think he will be likely to go on, after leaving the Indians, to Iowa.
This makes the way seem much more pleasant.

I write this account that you, my dear wife, may be comforted in my journey,
and with your husband bless that good Hand and holy unslumbering Shepherd of Israel,
who has thus far been my blessed Helper in temporals and spirituals:
being also mouth and wisdom.
Blessed be his glorious Name forever.
We expect to leave Adrian tomorrow morning for the Indian settlement.
We are in good faith,
humbly desiring our blessed Shepherd and heavenly Guide may be pleased to go before us,
and keep us in the right way;
and give us to "`drink of the brook in the way,`" so that we
may be enabled to do whatsoever He requires at our hands.

And now may we both thank our dear Master, and take fresh courage.
I am more and more confirmed that this great undertaking is required at my hands.
Dear John is exceedingly kind and travels very cheerfully we
have been remarkably favored with our health.
It is thought to be about five hundred miles to the Indian settlement.

Taking my leave, I bid you farewell in the truth; and remain your loving husband,

[.signed-section-signature]
Christopher Healy

--

+++[+++He attended and appointed a number of meetings on the way, till they came to Chicago,
the 22nd of Sixth Month.
Pursuing a northwesterly course from here,
they at length got to their friend Andrew Schofield`'s, ninety miles from Chicago.
They left their horses at this Friend`'s, he kindly joining them and taking his.
The journal proceeds:--]

[.small-break]
'''

We are now four in company--cheerful travellers in this good cause.
Arriving at Brothertown, the first Indian settlement, on Fourth-day the 29th,
we were received by the natives, it might be said, with open arms.
We put up with one of the Indians belonging to this tribe,
where we were kindly and very comfortably cared for.
The next day had a meeting for these poor children of the wilderness,
which was crowned with the living presence of our holy Redeemer,
to the tendering of many of their minds.
Sixth-day went see the Stockbridge tribe, six miles distant.
Here we had a meeting on Seventh-day.
Nearly all the tribe were present; and a tendering time it proved,
to the rejoicing of many of their hearts.`"

[.small-break]
'''

+++[+++The diary of Christopher Healy next gives a short
account of their visit to an old Indian woman,
named Gracey Tocus,
as follows:--"`First-Day had a meeting at an
Indian woman`'s house by the name of Gracey Tocus,
which was a time of favor.
This Indian woman was raised up to speak in this meeting in the life and power of Truth,
to the comfort of many present.
I trust it will not soon be forgotten by us.`"
This religious opportunity is spoken of by Christopher Healy '`s companion,
John S. Comfort, in a journal kept by him, and in a letter of Joseph Gibbons.

[.offset]
The journal of John S. Comfort thus introduces it:--]

[quote]
____
Fifth-day, Sixth Month 30th, 1842.
After a walk of about a mile from our place of tarriance,
upon returning we found a woman seventy-four years of age, whose name was Hannah Dick.
She remembered Christopher when he visited their tribe in New York State,
before they emigrated here.
She appeared like a thoughtful, well-meaning woman.
In allusion to a paralysis which had affected her speech, she said,
placing her hand on her heart, "`I have lost nothing here.
I feel concerned for myself, and my conduct; for my children,
and the whole human family.`"

On our way here Christopher had spoken of an Indian
woman of this tribe that expressed a few words,
lively and pertinent,
at the close of a meeting which he had with them in the State of New York,
before their removal from there; but whose name he could not recollect.
He had frequently wondered whether she was living,
and whether he should ever meet with her again.
Querying of this Hannah Dick in reference to the circumstance,
she could not remember anything about it;
and thought it must be herself. But Christopher did not find in
this woman what he expected in the one alluded to.
Here the matter rested,
till after a meeting held for the Indians wherein our friend
Christopher Healy was much favored in testimony and supplication,
when we were invited to go and see a sick woman.
Upon arriving at her house,
we found her to be the very one after whom Christopher`'s inquiries had been.
Her name was Gracey Tocus.
She knew Christopher, and seemed rejoiced to see him, exclaiming,
"`Is it true that my eyes once more see my old friend? I remember when you told me,
away off yonder at Brothertown, that you thought of coming here;
and I have been looking for you many times: and when I have thought of it,
and you did not come,
I concluded you had been called home.`"

There were some
now with us who had not been at our previous meeting,
and several that had, having borne us company. Christopher`'s certificate being read,
we all dropped into silence; when he had considerable to say very encouragingly.
After which Gracey Tocus stood up, and in a truly feeling manner said:
"`I believe it will be right for me to say a few words, not that I think myself anything;
I am a poor worm of the dust, not worthy to open my mouth before the Lord`'s servants;
and I feel it a great cross to appear in this way, but I feel it my duty to say,
that through the mercy of the Lord,
when I first heard this dear ancient minister and servant of the Most High,
away down in Brothertown, his words sent conviction to my heart,
and it has remained with me ever since; and I can bear my testimony,
that it is the eternal Truth of God that he has told us;
it is that that will do to live by, and that that will do to die by;
and I feel thankful in my heart and bless my Heavenly Father for this opportunity;
and that He has sent his dear servant into this far country,
that I might hear him once more before I die.
I have but a little longer to stay, and this dear ancient servant of the Lord,
and minister of the Gospel, is also nearly done his work;
and I feel glad to see all these dear friends here,
and pray that the Lord may bless His work in your hands,
and that you will remember me in times of favor,
when the Lord permits you to approach near unto him.
And although I am a poor unworthy creature,
and it is a great cross for me to speak before the Lord`'s servants,
and before the others that are present;
yet my heart rejoices with joy unspeakable and full of glory,
and I feel to encourage all, and bless the Lord for this opportunity.`"
____

[.offset]
+++[+++Christopher, in a letter to his wife, describes this opportunity:--]

[.embedded-content-document.letter]
--

We arrived among the Indians on Fourth-day afternoon; went first to an Indian`'s house,
who kept a tavern, and put up with him.
On Fifth-day, had a meeting at 4 o`'clock in the afternoon,
a meeting to be remembered by all present who had come to religious sensibility.
Some of the tribe not being present, they were desirous of another meeting.
This tribe is called the Brothertown tribe.
After meeting some of these dear Indians wishing us to make a visit to an Indian woman,
who was not able to get out, at about half a mile from the meeting place,
we went with them, and in an opportunity in her family (her husband being blind),
it was an unusual time of Divine favor.
After I expressed what was on my mind the dear
old woman spoke in a most remarkable manner,
which made deep impressions on us all not soon to be forgotten:
this opportunity closed under a precious covering of the Blessed Truth.

Seventh-day.--Had a meeting among the Stockbridge tribe, about six miles distant.
They are not so much civilized, but a large and favored meeting it proved,
both to us and them.
Two of their chiefs being present, were very much tendered.
We parted from them in gospel love which had spread over us in the meeting.

After this meeting we returned to the missionary home,
where we had some satisfactory conversation with a
young man who made great profession of religion.
He pleaded that Christians might defend themselves by the sword,
but the missionary did not join him, but seemed to favor our views,
and related some remarkable instances of the protecting hand
of Providence in saving those who had not resisted evil,
but had put their whole confidence and trust in the Lord.
Our conversation seemed to silence the young man, and from the respect he showed,
and the missionary also, to us, we believed our labor was not in vain with them.
First-day morning we had a tendering opportunity in this family,
and left them in a tender frame of mind.
This afternoon went to the house where the blind Indian
lived whose wife had spoken so remarkably before.
They, with some other Indians, had been in the practice of sitting down together, and,
as they said, if they felt anything on their minds,
to speak as the Spirit gave them utterance.
We sat down with them, and a favored opportunity it proved:
most of them were much tendered.

In the afternoon attended the meeting at their meeting-place,
appointed for us at five o`'clock.
The house could not contain them by many.
A remarkable season it proved;
my poor soul was humbled under the flowings of gospel love,
and the plain doctrines thereof, which was acknowledged by their ministers,
and joyfully received by many of these dear children of the wilderness.
Oh may it be as the dew that lies long on the tender grass,
causing the plant of the Father`'s right hand planting to grow
and bring forth fruit to his own glory and praise.

--

[.offset]
+++[+++The following are extracts from the letter of Joseph Gibbons to Sarah Healy,
to which allusion has been made:--]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Stockbridge, Wisconsin Territory,

[.signed-section-context-open]
Seventh Month, 2nd, 1842.

[.salutation]
Dear Friend Sarah Healy,

Not only at the request of your dear husband,
but from feelings that accompany my own mind (for I remember
with great satisfaction the very pleasant visit I had at your
house a little more than a year since),
I am willing to try to give you a little information in
relation to the visit so long in prospect,
and so much dreaded, not only by Christopher himself,
but by many of his friends on his account.
But we read in the Good Book that "`hard things shall be made
easy;`" and truly we have to a great degree experienced this
to be the case in our journey to this far-off land.
We have been agreeably disappointed in several respects: in the first place,
we have all enjoyed the great favor of pretty good health;
and Christopher has for the most part seemed to feel very comfortable,
and to press forward with good courage, believing himself to be in his proper allotment.
In the second place, we have found the roads altogether better than we expected;
so that we could come comfortably all the way in a carriage;
while even the distance was not quite so great as was anticipated. Now, also,
that we are really among the Indians, we find them living very much like ourselves;
dressing like ourselves; speaking like ourselves; and almost looking like ourselves;
and we have hardly found more comfortable fare as to eating, drinking,
and lodging anywhere on our journey, than since we have been among the Indians.
And last of all, though not least, we find an open door to receive us and our doctrines;
and Christopher has seemed much exercised, and unusually favored with '`mouth and wisdom,
tongue and utterance,`' since we have been among them.
For although he has only as yet had one public meeting,
yet in several family opportunities we have been made truly glad;
so that we might perhaps adopt the language,
repeated by a poor Indian woman in a family sitting the day before yesterday, viz:
"`My heart rejoices with joy unspeakable and full of glory.`"

But before I say much more in relation to our visit here,
let me return a little and trace our progress since the date of
Christopher`'s letter to you at Andrew Schofield`'s. A meeting was
appointed there at nine o`'clock on First-day morning last,
which was well attended by persons of different persuasions; and,
to our surprise by (as we were told after meeting) twenty-two
members of our Society (including ourselves). The meeting was
so greatly favored that I told Christopher,
after it was over, that it seemed almost worth our while to have come all the way here,
if it was but to attend this one meeting.

In the afternoon we had another meeting at Mequanego, about six miles distant.
But there seemed to be something present that obstructed a full,
free flow of gospel ministry.
After meeting, we thought we could discover, in part, what it was.
There were two or three dark spirits present, who professed to be Mormon preachers,
and had made some converts to their faith in that place.
They fell into an argument with Christopher after meeting,
but we did not think gained much credit by it.
Next morning, Second-day,
Andrew Schofield harnessed two of his horses and came on with us;
leaving ours to rest until we return.
We found a very good road through an open prairie country,
with the exception of perhaps about twenty miles,
so that in a little less than three days we reached the Brothertown Indians,
and put up at a very comfortable place among them.

The next day we had a good open time in a meeting
appointed at four o`'clock in the afternoon.
After meeting, went to see Grace Tocus, an Indian woman who had seen Christopher before,
and well remembered him, but was not able on account of ill-health,
to attend the meeting.
Christopher had a sweet flow of tender counsel and encouragement for them,
and after he closed, and we had sat some time in silence, Grace rose,
and in a very weighty, solemn manner, spoke nearly as follows:
+++[+++His version of the communication is omitted, being very similar to that already given.]

I do not remember ever to have felt more sympathy, or nearer unity of feeling,
or evidence of divine favor, towards any collection of Friends or others in my life,
than in this poor Indian`'s family.
I do not think there was a dry eye present after this opportunity.
Christopher and myself went home with an Indian, William Dick, and his wife,
who seemed very glad to see us.
She said travelling Friends had often put up at their
house when they lived in the State of New York.
They treated us with great kindness, even putting us into large separate beds,
with clean sheets and pillow-cases: saying they wished us to rest well,
while they had a bed on the floor for themselves to sleep on.
In the morning we had a remarkably favored opportunity with this family.
Christopher spoke until he seemed almost exhausted with
the length and intensity of his exercise.
We had one or more favored opportunities yesterday, and then came to this place,
which is among the Stockbridge Indians,
where a meeting is appointed for them at two o`'clock this afternoon.

Evening.--The meeting this afternoon was large.
Most of the tribe were present,
and a more favored meeting I think I never was in anywhere in my life.
I never heard Christopher when I thought him more, if as much favored, in a full, free,
and lucid manner of explaining and laying home gospel truths.
He seemed anointed to lay open and impress upon the minds of these poor Indians the
doctrines and principles of the religion of our Lord and Savior Jesus Christ,
in all their simplicity and purity; and with such divine authority attending,
that I could see the tears rolling down the swarthy cheeks before me.
I am very much of the mind that many of them will never forget the opportunity.
Some of them could scarcely bid us farewell for their emotion.

Thus, my dear friend,
I have attempted to give you a very little and
imperfect sketch of this part of our journey.
Please remember me affectionately to B. Cadwallader`'s family,
and to all other friends there who enquire for me;
and also accept my kind remembrance for yourself and family.

[.signed-section-signature]
Joseph Gibbons

--

[.offset]
+++[+++We now return to the diary of Christopher Healy:]

Had another meeting at their (Indians`') usual place of holding them.
The house was full, and all could not get in.
A very solid and blessed season it proved to us altogether.
May He who is glorious in holiness, fearful in praises, doing wonders,
have all the honor; to whom it does belong forever.
We had also many precious family visits,
wherein the principles and doctrines of the blessed gospel were opened to this poor,
afflicted, and despised part of the human family; yet for whom Christ died,
as well as for us.
These favored seasons caused their hearts to rejoice;
and many of them expressed it in great thankfulness of soul.

[.small-break]
'''

+++[+++While among the Stockbridge Indians they frequently met, it seems,
with a minister or missionary named Cutting Marsh, who resided there.
He was by profession a Presbyterian.
The following letter from him to Sarah Healy, is not without interest,
as confirming the acceptableness of our dear friend`'s labors among these far
distant and sadly oppressed and persecuted children of our western wilds:--]

[.embedded-content-document.letter]
--

[.letter-heading]
To Mrs. Sarah Healy

[.signed-section-context-open]
Stockbridge, near Green Bay, Wisconsin Territory, July 5th, 1842

[.salutation]
Madam,

Your dear aged husband, with three other Friends, came here on the 1st instant,
and paid us a Christian visit.
On the 2nd he preached to the Stockbridge Indians,
among whom I am laboring as a missionary.
Be assured, Madam, that his visit, together with his company,
was very acceptable both to myself and family, and to the Indians also.
Some of them feel under great obligations to the Friends,
as they have kindly educated some of their children.

Although I am a Presbyterian by profession,
yet I can cheerfully extend the hand of Christian fellowship to other denominations also,
where I perceive the image of the Savior.
Yes, all who have been born of the Spirit, have a common Lord,
and it is their delightful privilege to love one another with a pure heart fervently,
and greet them wherever they meet them, as fellow travellers to the same heavenly rest.

I love to dwell upon those pure principles of the holy religion of
Jesus Christ which the Friends are so zealously disseminating:
and my ardent desire and prayer is, that these may continue to extend wider and wider,
until the song which the shepherds on the plains
of Bethlehem heard the heavenly host sing,
shall be the song of every people and nation upon the habitable earth.

I hope your dear husband may still be spared to
accomplish great good in the Masters blessed cause.
I know you will be glad to hear from a stranger
that his health and spirits at his advanced age,
appeared to be as good and buoyant as my own, although I am but little turned of forty.

He made lively mention of your cheerfully consenting to tarry at home,
and guide your numerous family, and bear all alone the heavy burden of it,
so that he might travel, and teach the unsearchable riches of the gospel.
This excited in my own mind a lively and tender interest in your welfare,
and that of your dear family.
May you also be sustained in your numerous trials and cares in so important, laborious,
and responsible duties as you must meet with and perform.
So that when he mentioned about writing you,
I felt that I could do it with great cheerfulness, for I know it will encourage,
and do you and your family good to hear from him by strangers,
and to know that his religious visits are kindly and affectionately received.
I saw that my Indians were deeply interested in his preaching,
and would have been highly gratified if he had felt it his duty to preach again.
But at the close of his discourse he said that he felt satisfied,
and should then take his leave of them.
One of the old men inquired of me, with tears in his eyes,
if your husband was not going to preach again.
But I told him, no.
These poor Indians seem at once to love those who take a deep interest in them;
and the counsel of your husband, in his discourse to them,
was exceedingly kind and affectionate; this pleased them,
and they therefore listened with deep interest; and I have no doubt with profit also.

These Indians are the remnant of a once powerful and warlike tribe.
But long since they have given up this savage practice,
and many of them give evidence of being true Christians; but they are very poor,
in consequence of having to remove so often, as they have in time past,
but especially on account of their former intemperate habits.
For a number of years past,
great efforts have been made to promote the cause of temperance among them,
and with happy success; so that few drink at the present time.
In proportion as they become temperate, they become industrious;
and manifest a desire to take care of themselves, and provide for their families.

I have forgotten to mention that your husband left here on the third instant,
to go to a settlement, a few miles south of the Brothertown Indians,
where he expected to hold a meeting on that evening.
May the Lord guide and support you, and bless your family also abundantly,
and make them all children of his grace.

With great regard for yourself and yours, I subscribe myself your Christian friend,

[.signed-section-signature]
Cutting Marsh

--

+++[+++From the journal of Christopher Healy,
it appears that they left the Indian settlements on Second-day,
the fourth of Seventh Month;
and on the following Fourth-day got to Andrew Schofield`'s again,
where they were kindly received.
The next Sixth-day, taking their departure from there,
and holding some meetings on their way, they arrived at Salem, Iowa,
distant about two hundred and fifty miles, the 16th of the same month.
They were hospitably entertained by their friend Jacob Pickering and his family.
From here Christopher addressed a letter to his wife; in which he says,
in allusion to these religious opportunities with the Indians,
"`these meetings bring my concern fresh to my mind; and while standing exercised in them,
it fastens on me and on them as a nail in a sure place;
and my soul is rewarded a hundred fold for yielding up to perform this journey.
May your heart also be made joyful with that of your husband.`"

From the diary of John S. Comfort the following is selected,
referring to the subject of a part of Christopher Healy`'s more condensed letters:--]

[quote]
____
Learning there were some Indians that met at Gracey Tocus`' twice a week,
to hold meetings somewhat after the manner of the Society of Friends,
we made enquiry concerning them;
and whether they had anyone to act as a regular officiating preacher.
The answer was, they had not.
But if any believe themselves called thereto,
they thought it right to speak as the Spirit gave utterance.
We concluded to go and sit with them.
Christopher had a good deal to say; after which, Gracey Tocus arose and again spoke,
to the admiration and edification of all present.
____

+++[+++The first part of this communication, though not so lively,
is somewhat similar to the foregoing one.
We therefore insert only the conclusion of it here,
more particularly because of its having application to every one of
us who profess to be followers of the meek and lowly Jesus,
yet Sovereign and impartial Lord of all.
It is as follows:--]

[quote]
____
I wish to ask one favor of you;
that when you return to your friends and brethren at home,
you would give them my best love,
in the fellowship of this gospel we have had preached this day;
and tell them a poor unworthy Indian sister wishes and
prays for their prosperity and advancement in the Truth,
and that they may be obedient and faithful to their Master,
in whatsoever He makes known to them, and requires at their hands;
and that in their seasons of divine favor,
they would remember this poor despised part of the land.
____

+++[+++Another fact of interest is recorded by John S. Comfort,
which is not mentioned by Christopher Healy:]

[quote]
____
After meeting yesterday, many of the Indians came and shook hands with us;
and among the rest our kind landlord, O. D. Fowler, from Brothertown,
came to bid us farewell, as he said, for the last time; but he could hardly speak,
he was so affected.
He appears to be a sober, thoughtful man.
When we left his house yesterday,
we offered and pressed to pay him for our board and horse feed; but he refused,
and said he knew it cost us a great deal; but we told him we had enough,
and expected and would rather pay than not; but he refused, and said,
in a manner that showed that he looked upon all that he had as a gift of heaven:
"`I know where I get it from,
and I am not willing to take anything.`" I thought it would have been
a lesson to many in more favored circumstances in our Society,
as it was to me, if they could have heard him.
____

[.offset]
+++[+++Christopher Healy, continuing his memoranda, writes:--]

We were at the Preparative meeting of Ministers and Elders (Salem,
Iowa,) to a good degree of satisfaction.
On First-day, general notice being given, the meeting was large,
and owned by the great Shepherd of Israel.
During the same week we attended all the meetings belonging to Salem Monthly Meeting,
except one; and on Seventh-day the Monthly Meeting.
The abundance of business caused them to adjourn to the Second-day following.
First-day we had a very large meeting, and a memorable season it proved.
The house would not hold the people; a shed was fitted up on the north side,
and many sat under it.

[.small-break]
'''

+++[+++This is all that our dear Friend says of the meeting; but his companion, more in detail,
has recorded the subjoined:--]

[quote]
____
Christopher had a good deal to say, and after sitting down, he got up the second time,
and stated to the meeting our belief in the Scriptures of truth.
Although there had been nothing in what he had previously said to call it forth,
or to require any explanation or confirmation of our belief in the Bible; yet it seemed,
the second time he was on his feet,
his whole business was to show the value our Society set upon the Scriptures.
I afterwards learned, that there was a man the day before,
who was pretending to set forth Friends`' principles to a large company; who,
among other things, affirmed that Friends did not believe the Bible.
The man and his hearers were at the meeting.
Christopher, I am persuaded,
knew nothing of the circumstance of the man`'s disparaging story for several days after.

In the afternoon,
Joseph Gibbons left us for his own home.
We have travelled in near unity and fellowship, being of one heart and one mind.
____

[.offset]
+++[+++Christopher`'s memoranda resumed:--]

Second-day, the adjourned Monthly Meeting convened;
and after several hours of solid deliberation, it concluded to the comfort of many minds.
Fifth-day, Eighth Month, 4th, got to Uriah McMullin`'s; he and his wife are choice Friends.
Next morning rode to Hopewell, and had a meeting there under the shade of the trees,
the house not being sufficiently large to contain the gathering.
I scarcely remember a more precious season of Divine favor.
From this place we went to Vermilion,
and attended a preparative meeting of Ministers and Elders.
Seventh-day sat with them in their Monthly Meeting, wherein I had good service.
First-day we were at Elwood, which was a crowded meeting; many could not get in.
The people of the neighborhood were generally gathered together;
they seemed prepared to hear the doctrines of the blessed Truth.
May it fasten as a nail in a sure place.

[.small-break]
'''

+++[+++They then held or attended meetings at Pine Creek, Flint, and Bloomington;
and from there went to the Quarterly Meeting called the Western Branch,
held the 14th of Eighth Month, 1842. On First-day they were at the same place.
The diary records:--]

[.small-break]
'''

Here the blessed effects of the sufferings and death of Christ,
experienced through obedience to His inward appearance in the heart,
with the necessity of our receiving Him, and following Him there,
were dwelt upon as that which brings redemption and salvation to us.
Oh the necessity of receiving with meekness the engrafted Word,
which is able to save the soul.
May this ever be the constant concern of our minds.

[.small-break]
'''

+++[+++They next had meetings at Rocky Run, Rush Creek,
and Poplar Grove "`These,`" Christopher Healy writes,
"`were all largely attended by Friends, and those not of our religious Society;
and blessed be the name of Israel`'s Shepherd,
He was pleased in an eminent manner to be with us.
May all praise be given to His ever glorious and holy Name, forever.`"
He next attended some Quarterly and other meetings,
respecting which he makes but little or no comment.

The following are extracts from a letter to his wife, which was written near this time:--]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Bloomfield, Indiana, 14th of Eighth Month, 1842.

[.salutation]
My very dear Wife,

Yesterday was the Quarterly Meeting at this place, wherein I had good service;
and it ended to the comfort of many.
We are getting along to our satisfaction among Friends,
and the public meetings are remarkably large, and according to Friends`' judgment,
favored seasons.
I have been careful not to have more than one meeting a day,
except sometimes on First-day.
Meetings in this part of the land are near together, and Friends are many.
A goodly number of them appear to be concerned for the good cause.
Today, which is First-day, general notice for a meeting is given at this place.

We seem now to be turning our faces homeward,
though I expect we shall not get home until after the Yearly
Meeting (Indiana). Our Divine Master has abundantly made way
for us wherever our lot has been cast on this journey,
in a remarkable manner.
May the praise and glory be given to Him, and to Him alone.

I received your second letter, day before yesterday, to my comfort,
having waited long therefor.
I was sorry to hear you had gotten but one from me,
as this is the fifth I have written or sent.
I received one from William and Sarah.
It was truly comforting to find they remembered their dear father.
Give my dear love to them, with all our children, and tell them I love them in the truth.
Read this letter to them.
My time is so much occupied with travelling and meetings,
that my dear children will excuse me, I trust, from writing to them.
It is not because I am unmindful of them, for they are daily in my mind,
even every one of them.
May the Great Shepherd that has been their dear father`'s helper in every time of need,
be their leader and guide; and He will be so to them,
if they receive with meekness his engrafted word.
Give my dear love to all that enquire after me.
Let them know my love was never stronger for the blessed cause of Truth than now;
and this love being shed abroad in my heart, keeps my soul alive in Him that is true,
in Him who was dead and is alive again, and lives forevermore.
Oh, my dear, He is the desire of our souls!
He is the Head of the church; and if we keep our love chaste and pure to Him,
He will be our present helper in every needful time.

Afternoon, we attended the First-day meeting here, which was very large;
and in a remarkable manner owned by the Head of the Church.
May we be humbled in the dust before Him.

I suppose the time may seem long before we may meet again,
but I believe if it is His good pleasure that we enjoy each other again,
the blessed Shepherd will be our consolation.
We know, my dear bosom friend, in whom we do believe;
and as we yield each other up for our Divine Master`'s sake.
He will never leave nor forsake us;
neither withhold any good thing from those that love Him.

Farewell in the blessed Truth.
I remain your dear and tender husband,

[.signed-section-signature]
Christopher Healy

--

+++[+++The annexed letter from Christopher Healy to his wife, or rather extracts from it,
is the last epistolary communication from his own pen, preserved in these memoranda:--]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Henry County, Indiana, 15th of Ninth Month, 1842.

[.salutation]
My very dear Wife,

We have attended five Quarterly Meetings in Indiana, and many other appointed meetings.
With the exception of one of the Quarterly Meetings, which was a trying season,
they were favored times.
At New Garden we saw a colored man, a member of our Society,
one hundred and six years old.
He is nearly blind; but got to the Quarterly Meeting,
and seemed rejoiced to shake hands with me.
Friends are very thickly settled in this part of Indiana,
and the meetings are generally large.
Two weeks from yesterday (Second-day), the Meeting for Sufferings will be held.
Third-day, the Meeting for Ministers and Elders.
Fourth-day, the public meeting.
Fifth-day, which will be the 29th of the month,
the Yearly Meeting for discipline will be opened,
which commonly ends on the Third-day following; which will be the 4th of Tenth Month.
After that we expect to leave for home if we are well;
and hope that by the 25th of Tenth Month, if our Divine Master should prosper our way,
we may be favored to see each other again.
And now, my dear wife, be of good cheer.
The same good Hand that has always been with us is still mindful of us,
and as we keep near to Him, He will be very near to do us good.
I was comforted in hearing you say,
that you were in the good practice of reading a portion of Holy Scripture in our family.
I hope you will continue to do this.
I believe it to be a help to the children, and a satisfaction to yourself,
as it is to your absent husband.

I lately received a precious letter from Samuel B. Morris;
giving an account of a good visit he had with you and our children;
also of our son Mark`'s visit to him,
with the letters you sent him from Joseph Gibbons and the missionary; which were,
as he says, highly interesting.
With regard to this visit I may say, I never had a more encouraging one thus far.
How the remainder may prove we know not,
but hope that He who first put forth, will continue to go before,
and to show forth His praise,
that so fruits may be brought forth by which our Divine Master may be glorified,
who alone is worthy forever.

Friends are exceedingly kind in this land; and very many precious meetings we have had.
Many of those not of our Society, seem much comforted.
Oh! may He who calls for the labor, be sure to fasten it as a nail in a sure place;
that so the praise may be given to Him who is glorious in holiness, fearful in praises,
doing wonders.
I think I never travelled anywhere where the people of other
societies were more attentive to hear the Truth as it is in Christ.
Oh! may they be willing to do it!
Then will they be able to build on that Rock, against which no storms can prevail,
nor anything lay waste.
And Oh! my dear, may we continue to look unto the Rock from which we were hewn,
and the hole of the pit from which we were digged.
And may we remember, too, good old Abraham our father,
who resigned his beloved son Isaac to the Lord.
Upon which, said the Lord: Because you have not withheld your son, your only son,
in blessing I will bless you,
and in multiplying I will multiply your seed as the stars of the Heaven,
and as the sand which is on the sea-shore.
This is the faith, with works, that pleases the living God, who alone is able to save.

Give my dear love to all that enquire after me.
Tell them I love the Truth; and that it never was more precious to me than at this time,
and sweet is the fellowship I have with them that walk therein.
In that love that many waters cannot quench, nor floods drown, farewell,
says your husband,

[.signed-section-signature]
Christopher Healy

--

+++[+++After this Christopher Healy attended meetings at Elm Grove, Carthage, Blue River,
Walnut Ridge, Knightstown and a few other places.
About this time the following epistle from Sarah Keese to Christopher Healy was received.
It alludes to one she had gotten from him,
wherein he seemed to have been instrumental in stirring up the pure mind in her; and,
obeying the injunction to "`comfort them that mourn,`"
to have soothed and refreshed her drooping spirit.
The letter is as follows:--]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Weston, Ninth Month 10th, 1842.

[.salutation]
Dear and valued Friend,

It is under a deep sense of obligation that I
acknowledge the reception of your favor of Eighth Month,
17th. It did, indeed,
afford us great satisfaction to find that we were still remembered by you;
and we were much interested also in hearing through
your own pen of your welfare and preservation every way.
Tender solicitude on your account has been felt,
in your very arduous and important engagement--
still bearing the burden and heat of the day,
under the infirmities of advanced age.
But I doubt not that amidst all,
Divine support has been abundantly experienced to be near,
producing the acknowledgement that '`hitherto You have
helped me.`' Oh! what an attainment and a favor,
that the poor mind thus knows its own home, the place of its rest.
That after it has been called forth into deep and laborious exercises,
even when this too may seem to be almost labor in vain, or as bread upon the waters,
that it can breathe the grateful language, Return, then, Oh my soul,
to the place of your rest, for the Lord has dealt bountifully with you.`'

I hope when Friends return from the Yearly Meeting,
we shall receive further accounts from you.
It would be a gratification to learn more of your future prospects!
Where next? and whether you have any view of our Quarterly at your return? In these
inquiries I would not burden you with the task of communicating particulars.

My health has improved considerably,
so that I have walked to our little meeting several times.
And since receiving your letter,
I have visited my friends in the neighborhood of Alum Creek.
As you desired your remembrance to Friends, I took it with me,
and quite a number shared in the satisfaction.

Your visit to us, and particularly to me in my then weak state of health,
is remembered with gratitude; the savor of which at times rests sweetly upon our spirits.

I feel interested in the proceedings of the ensuing Yearly Meeting,
and according to my measure, feel with the true burden-bearers.
Oh that wisdom may be dwelt in; remembering that help is laid upon One that is mighty.
I am aware to whom I am writing, and would not exceed my bounds,
feeling myself as a child, and you a father.

Should I fail in writing to your dear wife before your return,
please present her with my sympathetic and affectionate regards,
with the hope that when you return from your present field of labor,
laden with sheaves of peace, she too may be entitled to share with you.
I cannot fail to be interested with any account from you at any time;
and when you return to your far distant home,
and should be writing to your friends at Greenwich, a remembrance in that way,
if it is not asking too much,
would be grateful to one who feels that she has the
constant need of the help and prayers of the faithful.
My husband unites in the expression of love and sympathy to you.
Affectionately your friend,

[.signed-section-signature]
Sarah Keese

--

[.offset]
+++[+++The diary resumed:--]

Fourth-day, Ninth Month, 21st, we got to the house of our friend John Poole, at Richmond.
Here we rested till First-day, when we attended their usual meeting.
Second-day met with the Meeting for Sufferings of Indiana Yearly Meeting.
Third-day went to the Yearly Meeting of Ministers and Elders.
Fifth-day the Yearly Meeting commenced, which continued by adjournments until Third-day,
4th of Tenth Month.
Though some trying circumstances took place,
yet the Yearly Meeting was owned by the Divine presence, whereby the church was edified.
The next day we set out for home, by the way of Springborough, Zanesville,
Mount Pleasant, Sewickly, etc.
The following Fourth-day week we got to Isaac
Evans`'. Fifth-day to our friend William Rhoads`';
and the next day, at evening, Tenth Month, 21st, I was favored to reach home,
and was gladly received by my dear wife and family; and felt a thankful heart to Him,
who had called me forth, and brought again in peace.
May He have all the honor.
Blessed forever be His holy Name.

[.small-break]
'''

+++[+++This closes Christopher Healy`'s diary of his various labors in the love of the Gospel,
prolonged beyond the time allotted to most.

He returned his certificate in the same month,
with the information that the visit had been greatly to the peace of his mind.
He brought with him also several testimonials of
unity with his company and religious services,
from Monthly and Quarterly Meetings which he had attended,
and also from Indiana Yearly Meeting.

After his last-mentioned visit to Indiana,
and to some of the Indian tribes in Wisconsin Territory, in 1842, Christopher Healy,
as appears by the minutes of his Monthly Meeting, paid religious visits,
but without leaving any record of them, to the meetings composing Abington Quarter,
with liberty also to appoint some meetings with those thereabouts,
not in religious profession with us.
This certificate he returned in the Fourth Month of 1843. The
Seventh Month of the same year he procured a minute to attend
some of the meetings of Friends in New Jersey,
and to appoint some in places where none of our members reside.
And in the Eighth Month, one to attend Shrewsbury and Rahway Quarterly Meeting,
and to appoint a few meetings within its limits.

In the First Month of 1844,
he obtained a minute to appoint a few public meetings within
the compass of Bucks and Abington Quarterly Meetings.
In the Eighth Month of the same,
he procured a minute to hold public meetings within the limits of Concord, Western,
Salem and Shrewsbury and Rahway Quarterly Meetings.

In the Fourth Month of 1845,
he obtained the approbation of his Monthly Meeting to pay a religious visit
to Friends and others within the limits of New York Yearly Meeting.
In the First Month, 1846,
he visited some of the meetings constituting Salem and Concord Quarterly Meetings,
and appointed some meetings within their limits.
In the Sixth Month of the same year,
he paid family visits to the Friends composing Abington Quarter,
liberty also being granted to appoint meetings, if way should open for it,
in some of the towns within the border of the same.
In the Sixth Month of 1847, a minute was granted him to visit Friends,
with those not in connection with us, in Salem, Haddonfield,
Shrewsbury and Rahway Quarters; and if way should open, to the same class in Concord,
Cain, and the Western Quarterly Meetings;
with a few meetings east of the Susquehanna River, belonging to Baltimore Yearly Meeting.
In the Sixth Month, 1849,
he asked and obtained liberty to visit Friends of Haddonfield Quarterly Meeting,
and to appoint some public meetings in that and Salem Quarter.
In Ninth Month, 1849, a minute was granted him to visit Friends,
and those not of our religious profession, in Concord, Cain,
and Western Quarterly Meetings;
likewise the meetings composing Nottingham and Little Britain Monthly Meetings.]
