== Chapter XVIII.

[.chapter-synopsis]
* Last Illness and Death

The following account is extracted from memoranda kept of his last illness and death:--

"`The 8th of Fourth Month, 1851,
our dear friend Christopher Healy was taken alarmingly ill;
upon which he intimated that it might be his last sickness;
and wished it understood that he felt no condemnation,
but experienced that scripture verified: '`There is, therefore,
now no condemnation to them that are in Christ Jesus, who walk not after the flesh,
but after the Spirit.`'

"`11th.--He said, '`I feel very poorly; but tell all my friends that if I go now,
I go well.
I feel nothing but peace.
All is peace!`'

"`He manifested solicitude on account of a Friend who called to see him;
and exhorted him to be careful that he did not get into the spirit of the world,
to the neglect of his religious duties; as some had sorrowfully done.

"`A thankful spirit was eminently his;
and he appreciated the outward comforts with which he was surrounded;
and contrasted them with the destitution of many of his fellow-creatures:
repeating the little verse,

__While some poor creatures scarce can tell,__ etc.

He said that the accumulation of wealth might have been a snare to him;
but that he never sought after great things;
and what he had asked for had been abundantly granted.
His mind seemed clothed with contentment and gratitude.

"`19th.--In the afternoon his articulation became much obstructed,
so that but little could be clearly gathered;
but the following expressions were distinctly understood: '`Our poor shattered Society!
But I have done what I could.`' '`AH is peace! all is peace!`' '`The
righteous shall have living comfort.`' '`The living praise the Lord;
the dead cannot praise Him.
They may praise him in the letter;
but they cannot praise Him in the Spirit.`' '`They that live in the Spirit,
must walk in the Spirit.`' '`I have a hope,
an everlasting hope of being gathered "`where the wicked cease from troubling,
and the weary are at rest.`"
My secret help, my hope, and my salvation is Christ.`'

"`20th.--To his wife he said,
'`We have lived together many years in great harmony and unity.
I believe that the time is drawing near when we shall have to part;
and I hope that we shall be favored to meet in a better country.
I trust that if I have missed it, it is forgiven me.
I feel no condemnation.
I have sometimes felt a desire to live to see
our Society in a better state than it now is;
but I still believe that there will be a remnant preserved,
that will uphold our ancient doctrines, and that without equivocation.
There is a disposition in many who profess our ancient doctrines, to equivocate;
and wherever there is equivocation there will be a going off.
I think the number will be small that will stand;
but after that there will be a gathering.`'

"`To a Friend who called to see him, he said in substance, '`I am glad you have come;
and I hope you will be careful to do what you find it your duty to do.
I have labored a long time in our poor Society, but my labor has nearly come to a close,
and I can say as the apostle said:
'`My speech and my preaching were not in the enticing words of man`'s wisdom,
but in demonstration of the Spirit and of power.`' The Friend, being about to leave,
inquiring what he should tell his friends, he replied, '`Tell them,
I love all that love the Truth, and walk in it;
but I cannot have fellowship with those who forsake it.`'

"`22nd.--'`I do not think that I see anything in my way.
All seems well.
What a favor to be an inhabitant of that city that needs not the light of the sun,
nor the moon to shine in it, for the glory of the Lord does lighten it,
and the Lamb is the light thereof!
Oh! if I could quietly pass away to that blessed inheritance, how glad I should be!
I hope there is nothing in the way! "`My soul thirsts for God, for the living God;
when shall I come and appear before him!`" "`As the hart pants after the water-brooks,
so pants my soul after you, O God.`"`'

"`About noon today the accumulation of phlegm in the
throat seemed as though it must produce strangulation;
and his friends were apprehensive that the period of his release had nearly come.
In his struggles for life he said: '`I cannot stand it.
I must go!
Oh be honest!
Oh be faithful!
Joy forevermore appears great!`'

"`24th.--Today he remarked: "`Christ knows his own sheep, and his sheep hear his voice,
and he leads them out, and goes before them; and a stranger they will not follow,
but will flee from him, for they know not the voice of strangers.`"
Poor and unworthy as I am, I see nothing in my way;
and I hope I shall be patient until it shall please my Divine Master to cut
short the thread of my life--to cut short the work in righteousness.`'

"`A beloved friend sitting by his bedside, he said, '`We love each other in the Lord;
we have both known the Truth, and the Truth has made us free;
and if Christ has made us free,
then are we free indeed!`' He spoke much of the
necessity of standing firm in the day of trial;
of standing upon both feet +++[+++being firmly planted]
and of the danger of falling if standing but upon one foot, and said,
'`I have borne my testimony faithfully against unsoundness and innovation,
and have never turned my back in the day of battle.`'

"`25th.--One of his daughters coming to see him,
he expressed his hope that his children would tread in the footsteps of their father;
who had been made willing to take up the cross in early life,
which had preserved him from many snares and temptations.
'`Oh!
Truth is Truth; it cannot be divided!
As regards our poor Society, I believe there will be a suffering time for the true seed,
before it can reign.
Then it may be said: "`Therefore I will allure her, and bring her into the wilderness,
and speak comfortably unto her.
And I will give her her vineyards from there, and the valley of Achor for a door of hope;
and she shall sing there,
as in the days of her youth and as in the day
when she came up out of the land of Egypt.`"
'`He also quoted as the fruit of this: "`Look upon Zion, the city of our solemnities:
your eyes shall see Jerusalem a quiet habitation,
a tabernacle that shall not be taken down;
not one of the stakes thereof shall ever be removed,
neither shall any of the cords thereof be broken.
But there the glorious Lord will be unto us a place of broad rivers and streams;
wherein shall go no galley with oars, neither shall gallant ship pass thereby.
For the Lord is our judge, the Lord is our Lawgiver, the Lord is our king:
he will save us.`"`'

"`'`Oh! if I could now settle away, and go to sleep in the arms of my beloved Savior,
how glad I should be!
But it is not time yet.
His time is the best time, and the right time.
He has brought me through all my trials and temptations,
and landed me safe in a well-grounded hope of a happy eternity!
What a consolation it is to me; and how glad I am, that I can say at such a time as this,
that I feel no condemnation.
Everything looks pleasant.
Yes, as clear and bright as the light.
I have that hope which is as an anchor to the soul both sure and steadfast;
and enters into that within the veil, where our Forerunner has gone.`'

"`'`I have no wish to survive the morning.
I am ready to leave this troublesome world,
to pass through the valley and shadow of death to that
city whose inhabitants "`shall hunger no more,
neither thirst any more,
for the Lamb which is in the midst of the throne shall feed them,
and lead them unto living fountains of waters,
and God shall wipe away all tears from their eyes.`"
As said the apostle, "`We have not followed cunningly devised fables,
when we made known unto you the coming of our Lord Jesus Christ.`"
I have this to comfort me, that I have always believed the truths of the gospel:
that the true gospel is the power of God unto salvation to all them that believe.
The angel flew through the midst of heaven having the everlasting gospel to preach.
That everlasting gospel was not a book; it was the power of God unto salvation.
The angel had no book, but he said with a loud voice, "`Fear God, and give glory to Him,
and worship Him who made heaven and earth, the sea, and the fountains of waters.`"
The outward account of the gospel is not the gospel.`'

"`'`I now say as I have often said.
Friends speak often one to another; and if we speak right, the Lord will hearken and hear.
I don`'t mean that we should speak often one to another in common conversation,
or about the things of the world, but about heavenly tilings; and encourage one another;
and endeavor to get into that state in which we will say no evil;
and the Lord will hearken and hear;
and a book of remembrance will be written for those that fear Him,
and that think upon his great and glorious Name.`'

"`28th.--His outward sight was very much gone, but in allusion to his inward feelings,
he said, '`What a pleasant morning!
It is a morning without clouds!
Is it so out of doors?`' Being answered that it was a bright morning, he responded,
'`All seems bright and pleasant with me;
and if I could now pass away to the realms of bliss, how glad I should be!`'

"`Upon taking some water, he remarked,
'`It will be but little more water that I shall need here;
but I believe that I shall shortly partake freely of the
waters of life:`" "`He makes me to lie down in green pastures;
He leads me beside the still waters.`"
"`Though I walk through the valley of the shadow of death, I will fear no evil:
for You are with me: your rod and your staff they comfort me.
You prepare a table before me in the presence of my enemies; you anoint my head with oil;
my cup runs over.`"`'

"`He placed a high value upon that unity which subsists between true brethren,
baptized by the one Spirit into the one body; and in reference to such unity,
repeated the 133rd Psalm:
'`Behold how good and how pleasant it is for brethren to dwell together in unity;
it is like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard; that went down to the skirts of his garments; as the dew of Hermon,
and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing, even life forevermore.`'

"`To a friend who visited him, he said, '`I am glad you have come to see me.
We are poor things of ourselves;
but what an unspeakable mercy if we can only feel that we have no
condemnation--that we are in Christ Jesus--the only safe abiding place.
The old enemy is a deceiver and murderer;
and would discourage us and try to make us believe that there is no such thing as
perfection.`' '`Oh that our Divine Master would bow the heavens and come down,
and put darkness under our feet, and make a way for his travailing seed.`'

"`Fifth Month, 2nd.--He said:
'`I feel the guardian angel of His holy presence to be round about me,
to guard and comfort me through the valley and shadow of death.
I have done my day`'s work;
and would be glad if I could now pass quietly away to
my everlasting inheritance--to the realms of peace,
'`where the weary are at rest.`'`"

"`When under great bodily suffering he exclaimed,
'`O Lord! be pleased to give me patience to endure unto the end.
My pain is very great; and may you be pleased to bless my dear wife,
and dear children.`' Then addressing these he said:
'`But your loss will be my eternal gain; and I hope you will feel it so.
My Lord endured great sufferings.
He was a man of sorrows and acquainted with grief You will have to
pass through this last dispensation--and oh! be prepared!`'

"`3rd.--Some Friends from a distance calling to see him, he said,
he had been much comforted,
and had sweet peace of mind in visiting their part of the vineyard;
believing that there were many there that preferred Jerusalem to their chiefest joy;
adding, '`and may their number increase!
Oh, dear Friends, speak often one to another of the good things of the world to come!
Keep in the unity! and a blessing will attend you.
Give my love to all Friends in that part of the land.`'

"`'`I have been led much among those not of our Society,
and the language has often been sounded in my ear:
'`Other sheep I have which are not of this fold; them also I must bring,
and they shall hear my voice; and there shall be one fold, and one Shepherd.`'`"

"`4th.--After having been in much bodily distress, he uttered the encouraging language:
'`The Lord will bless Zion.
He will sanctify Jerusalem.
He will make her walls salvation, and her gates praise.
The Lord will bless Zion.
When he pleases, he will fortify her walls, he will set up her gates!
O Lord I the mighty One of Israel!
I feel your comfort, and I rejoice,
and sing your name and your praises in the land
of the living!`' '`Unto you that fear my name,
shall the Sun of righteousness arise with healing in
his wings.`' '`This is a great and blessed Supper.`'

"`Alluding to some who seemed to be departing from our ancient faith, he said:
'`I have no unity with those who go in this way.
I can only unite with those, and walk with those,
that go in the way that the Lord opens and preserves in.`' Being
dipped into sympathy with the oppressed and struggling seed,
he said: What will become of the poor little precious flock and family!
May their heads be a little anointed with oil.
He will anoint their heads with oil!`' '`Inquire after the good old ways,
and the ancient paths, and shun the paths that lead to evil.`"

5th.--Being in great pain, he passed a suffering night,
and obtained but little alleviation this morning.
But through his protracted sufferings, his soul seemed to be centered on heavenly things,
and clothed with devotion,
spending much of the night in earnest intercession at the Throne of Grace.
His mind was unusually exercised.
He prayed fervently for the best interests of his wife, his children, his friends,
and all the church of Christ; and, notwithstanding the decay of nature, was, at times,
remarkably strengthened with might in the inner man;
manifesting abundant evidence that they who have fixed
their habitations on the unchangeable Truth,
are not forsaken in the time of need,
but are supported and sustained in the hour of sore trial and deep distress,
when vain is the help of man; and are even enabled to rejoice in tribulation,
and sing praises unto their Creator; and that while they are thus established,
no divination or enchantment will be allowed to prevail against them,
to destroy their holy confidence and well-grounded hope
of the attainment of an inheritance,
incorruptible, that fades not away.
The faith of these is no cunningly devised fable, but a sustaining and substantial truth,
that is as an anchor to the soul both sure and steadfast;
and their light shines more and more unto the perfect day,
until the purified soul is swallowed up in immortality!

"`Towards noon his mind seemed to be carried back to the days of his youth,
and he expressed his gladness that he had come out from
the forms and ceremonies of a lifeless profession,
and had been brought into a more spiritual way.
He spoke of the great importance of bearing a faithful testimony to the faith once
delivered to the saints--to the faith once delivered to our forefathers:
of the necessity of great watchfulness, lest hurtful things should take root amongst us,
and weaken our faith in the precious doctrines and
testimonies that had been given us as a people to bear:
'`for,`' said he '`it was while men slept that the enemy sowed tares.
The good wheat had been sown amongst us,
but the enemy also had sowed tares.`' He seemed to be much impressed
with the great importance of preserving the clean seed unmixed;
and rejoiced in the belief, that there were those preserved amongst us,
who do bear a faithful testimony against those things which may be compared to the tares.

"`He travailed greatly in spirit for the prosperity of Zion.
The welfare of our Society seemed almost constantly to be mingled with his best feelings;
and his fervent intercessions often arose to the Father of mercies,
that it might be preserved upon its ancient foundation;
and that He would spare His people, and give not his heritage to reproach.

"`Though abundantly favored with an evidence that the Divine Presence is round about him,
to sustain and comfort this soul,
and with a holy assurance that as he puts off the tabernacle of clay,
there will be prepared for him a building of God, a house not made with hands,
eternal in the heavens,
yet (writes the author of these notes) it has
been with him as with most Zionward travellers,
some seasons of poverty of soul have been his allotted portion,
doubtless for the further trial of his faith,
but not sufficient to shake his confidence in that never-
failing Arm of Power that has hitherto sustained him;
and which he believed would continue to support him through all his remaining trials,
yet sufficient at times to afflict his spirit;
and expressions of this kind occasionally were heard:
'`My soul is exceeding sorrowful.`' '`They have taken away my Lord,
and I know not where they have laid him.`' Pray for me.`' But it has seldom
been that these feelings have been permitted to cloud his triumphant spirit,
and they have soon passed away,
and left his mind calm and peaceful in the enjoyment of
renewed faith and holy hope and confidence,
even as a morning without clouds.

"`6th.--He said that his day`'s work was done, and his peace made;
and without manifesting any impatience on account of
the protracted period of his earthly pilgrimage,
he queried why it was that he was kept here so long,
evincing a longing desire to depart when it should
please his Divine Master to take him hence;
evidently waiting, with holy confidence, for the gracious invitation,
'`Enter into the joy of your Lord.`'

"`He exclaimed: '`O Lord, you are good and kind to your truly exercised children!
You have been my stay and my staff through my pilgrimage.
Be pleased to continue to be to the latest period of my life.`' Again: '`O Lord,
be pleased to remember your disobedient and gainsaying children.
Make them to know that you are God;
and that they must appear before your judgment seat to receive the reward of their deeds,
let them be good or evil.
Every one that will not bow in mercy, must in judgment.
Dear friends, fear God and keep his commandments, for this is the whole duty of man.
For God shall bring every work into judgment, with every secret thing,
whether it be good or whether it be evil.`'

"`He was often much exercised on account of the low state of our once favored Society;
and said it was his unshaken belief,
that the testimonies that were given our forefathers to bear,
would not be allowed to fall to the ground:
but that there would be standard bearers raised up,
and watchmen to proclaim the day of the Lord: as said the Prophet formerly,
'`I will turn my hand upon you, and purge away your dross;
and I will restore your judges as at the first, and your counsellors as at the beginning:
'`afterwards, '`You shall be called the City of Righteousness.`' Then the song will be, '`Lo,
the winter is past, the rain is over and gone, the flowers appear on the earth,
the time of the singing of birds is come,
and the voice of the turtle is heard in our land.`'

"`11th.--A disinterested love and living desire for salvation of all souls,
it is believed has seldom been more prominent in
the experience of any of Zion`'s children,
than in that of our departed Friend.
When health and liberty permitted,
his labors in the line of religious duty were abundant, beyond the pale of our Society;
and as the energies of the outward man became prostrated,
and the termination of his earthly existence apparently drew near,
still that universal love of souls came up before him,
and he supplicated fervently for this generation--for this untoward generation.

"`12th.--To a friend who called to see him, he said, '`I love to meet my friends;
it generally brings tenderness with it.`'

"`He spent much of the night in supplication and exercise of soul,
but owing to great exhaustion and feebleness of articulation,
but little could be gathered, except the frequent naming of his Maker,
and a few detached sentences, such as,
'`How good'`--'`how comfortable'`--'`how sweet '`--`'
His glorious presence '`--`' I love my friends.`'

"`16th.--This day about eleven o`'clock, our dear friend departed this life.
An easy passage was mercifully granted him, his close being calm and peaceful;
and his last words, '`Peace, peace!`'`"

He was in the seventy-eighth year of his age, having been a minister about fifty years.

A concern had long rested on the mind of our beloved friend to have
his remains enclosed in a coffin of very plain and simple appearance;
and as his illness progressed,
and the solemn period of his departure appeared to be drawing near,
the subject revived with increasing weight;
and he solemnly enjoined upon his friends the faithful
performance of his wishes in this respect:
which request was strictly complied with: "`Have my coffin made of white pine boards,
without stain or color, brass hinges or lining; and have it flat on the top;
and let it be laid in the earth without any outside coffin or box.`"
Though the fulfillment of this concern might present to
some minds the aspect of needless singularity,
yet it evidently felt to our dear friend to be a testimony of very grave importance,
which he was conscientiously bound to sustain.
He had long mourned over a growing propensity among
Friends to exhibit a vain display at funerals;
which he believed was gradually leading us away
from the becoming simplicity of our forefathers,
and introducing us more and more into conformity to the world and its spirit;
and he felt religiously engaged that neither his example nor
precepts should tend to the promotion of such ends.
He also believed that it was not consistent with the will of an all-wise Creator,
that there should be any decoration or adorning about the corruptible part, which,
in the return of "`dust to dust`" was to lose all its comeliness;
but that strict simplicity was far more becoming the solemn occasion.
Considerations such as these, we believe, under the influence of heavenly light,
operated upon his mind, and produced a powerful conviction,
that there was a necessity laid upon him to bear a faithful
testimony against all appearance of pride or ostentation in
the preparation of the poor body for the grave.

On the 19th, his remains were interred in Friends`' burying ground at Fallsington,
Bucks County, Pennsylvania, attended by a very large collection of Friends and others:
after which a solemn meeting was held,
and many public testimonies borne to the Christian virtues of the deceased;
and to the undoubted assurance that his spirit had been
gathered into the fold of everlasting rest.

"`Mark the perfect man, and behold the upright, for the end of that man is peace.`"
